BC-5685 Получение достижения "Организатор"
CorporationX/project_service pull request #234
Opened 2023-08-29 12:34 UTC by czar777

2023-09-05 11:17 UTC, Monono7 commented
good job

2023-09-05 17:20 UTC, Monono7 commented on src/main/java/faang/school/projectservice/dto/StageInvitationDto.java
> +}
а что ты тут слелал? почему пусто?.. или так и было задумано?)

2023-09-05 17:20 UTC, Monono7 commented on src/main/java/faang/school/projectservice/config/RedisConfig.java
> +public class RedisConfig {
напиши полное название, RedisConfiguration)

2023-09-06 12:15 UTC, InnMish requested changes

2023-09-06 12:15 UTC, InnMish commented on src/main/java/faang/school/projectservice/publisher/AbstractEvent.java
> +public class AbstractEvent<T> {
Наверное, AbstractPublisher

2023-09-06 12:15 UTC, InnMish commented on src/main/java/faang/school/projectservice/publisher/InviteSentEvent.java
> +public class InviteSentEvent extends AbstractEvent<InviteSentEventDto> {
Тоже в названия давай  паблишеры добавим, чтобы было понятно, что это они

2023-09-06 12:15 UTC, InnMish commented on src/main/java/faang/school/projectservice/service/StageInvitationService.java
> +        inviteSentEvent.publish(stageInvitation);
а не можем ли мы здесь... обратиться сразу к методу абстрактного класса? То есть внутри конкретного паблишира абстрактный метод не переопределять? По сути-то все, что мы делаем в том переопределенном методе - маппим класс и вызываем другой метод
И тогда... можно будет топик не бином передавать, а прям строчкой из конфига
Так у нас в конфиге и бинов в будущем поменьше будет

2023-09-06 12:15 UTC, InnMish commented on src/main/java/faang/school/projectservice/config/RedisConfiguration.java
> +    private String invitationChannelName;
Вот получается вот этот поле можно будет передавать в паблишер, а тут не создавать бин.
По сути в бине этом все, что нам нужно - это channelName из конфига 
А если мы его в конструктор положим в паблишере сразу, то нам ни бин, ни метода-посредник, будут не нужны))

2023-09-06 12:15 UTC, InnMish commented on src/main/java/faang/school/projectservice/publisher/AbstractEvent.java
> +        redisTemplate.convertAndSend(topic.getTopic(), json);
Так, вот тут будет просто строчка, которая потом прилетит из конструктора наследника
мне кажется неплохой план

2023-09-07 12:20 UTC, InnMish approved these changes

2023-09-07 12:20 UTC, merged