Werewolf master bc 3914 all branch
CorporationX/project_service pull request #237
Opened 2023-09-02 20:19 UTC by M437A

2023-09-03 13:49 UTC, M437A commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectService.java
> +            momentService.createMoment(momentMapper.toMomentDto(project));
а у нас проект закрывается только в случае, когда закрыты все подзадачи

2023-09-04 03:21 UTC, M437A commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectService.java
> +        }
Если мы хотим сделать приватный проект, то мы попадаем в валидатор
Валидатор выдает ошибку только в случае, когда хотим создать публичный проект в приватном проекте, все остальное работает
Если валидатор ошибку не выкинет, то у нас такая видимость сохранится в дто и отправится в базу данных

2023-09-04 03:44 UTC, M437A commented on src/test/java/faang/school/projectservice/service/subproject/SubProjectServiceTest.java
> +        assertTrue(project.getUpdatedAt().isBefore(LocalDateTime.now()));
Так они же все проверяют одно условие и если какой-то тест сломается, то он подчеркнется (мне не сложно скопировать и вставить одно и тоже, просто как будто будет награмождение кода)

2023-09-04 10:56 UTC, InnMish requested changes

2023-09-04 10:56 UTC, InnMish commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectService.java
> +        return subprojectFilters.stream()
Это работает через постман? У тебя фильтры - не компоненты 
Как у нас заполняется private final List<SubprojectFilter> subprojectFilters?

2023-09-12 12:30 UTC, InnMish requested changes

2023-09-12 12:30 UTC, InnMish commented on src/main/java/faang/school/projectservice/validator/subproject/SubProjectValidator.java
> +            }
Сейчас работает так: 
мы из базы достаем проект, у которого хотим поменять статус (в вызывающем методе). Затем заходим сюда, и у полученного проекта получаем статус. Если этот статус Completed, то зачем-то идем проверять children-проекты. Но если проект уже Completed, то зачем это делать? Тут по идее надо было бы валидировать именно статус тот, который приходит извне (из дто), тогда такая проверка имела бы смысл. А сейчас непонятно, зачем это действие нужно

2023-09-12 12:30 UTC, InnMish commented on src/main/java/faang/school/projectservice/validator/subproject/SubProjectValidator.java
> +            }
Здесь же статус еще старый, до изменения. Поэтому если сабпроект уже Completed, то мы с ним больше ничего не может сделать. Это как бы финальный статус

2023-09-12 12:30 UTC, InnMish commented on src/main/java/faang/school/projectservice/validator/subproject/SubProjectValidator.java
> +            }
Соответственно, в методе updateStatusSubproject мы сейчас вообще не гарантируем, что момент будет создан вовремя. Потому что мы подпроекты не проверим в том случае, если статус проекта, который нашли по id отличен от Completed

2023-09-14 06:19 UTC, InnMish approved these changes

2023-09-14 06:19 UTC, merged