Сделал задачу по мягкому удалению
CorporationX/project_service pull request #241
Opened 2023-09-04 19:59 UTC by ringoway

2023-09-05 11:26 UTC, Dlakares approved these changes
Душную кнопку не жму, но хотелось бы удалить закоменченные участки + одну микроправку внести

2023-09-05 11:26 UTC, Dlakares commented on src/main/java/faang/school/projectservice/dto/campaign/CampaignDto.java
> +//    @NotNull
Что за комент? Или удали или раскоменти. Сейчас не сделаем, так и останется в проде лежать до конца времен)

2023-09-05 11:26 UTC, Dlakares commented on src/main/java/faang/school/projectservice/service/CampaignService.java
> +        Campaign campaign = campaignById.get();
Эти две строчки вроде можно объеденить. orElseThrow возрващает объект "или иначе кидает" ошибку

2023-09-05 11:26 UTC, Dlakares commented on src/main/java/faang/school/projectservice/service/CampaignService.java
> +
Добавить бы лог еще

2023-09-05 11:26 UTC, Dlakares commented on src/test/java/faang/school/projectservice/service/ProjectServiceTest.java
> +//    }
То же самое что и выше про комент. Старайся в прод привозить код без закоменченного кода. Чаще всего такой код остается до конца времен, т.к. всем на него всё равно, каждый подумает что оставит т.к. вдруг пригодиться в будущем

2023-09-05 11:26 UTC, Dlakares commented on src/test/java/faang/school/projectservice/service/ProjectServiceTest.java
> +//    }
И в принципе, старайся делать как можно меньше комментов в коде. В идеале код должен за тебя говорить что ты тут делаешь. Исключения - это какие нибудь сложные конструкции или неочевидные алгоритмы. Почитай "Чистый код", там под коменты целая глава есть

2023-09-05 11:27 UTC, Dlakares commented on src/test/java/faang/school/projectservice/service/ProjectServiceTest.java
> +//    }
Вот еще закоменченный код

2023-09-05 12:42 UTC, kkkooolllyyyaaa requested changes
Согласен с ревьювером + обрати внимание на мой один коммент

2023-09-05 12:42 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/project_V008__alter_campaign.sql
> +ALTER TABLE campaign ADD COLUMN flag bool NOT NULL DEFAULT false;
Почему flag? Не понятно что за флаг, давай так и назовём, is_deleted, или deleted

2023-09-07 15:20 UTC, kkkooolllyyyaaa approved these changes
👍

2023-09-07 15:20 UTC, merged