Feature bc 4516
CorporationX/project_service pull request #253
Opened 2023-09-13 11:22 UTC by Hanibalai

Наверяка, это не идеальная реализация, особенно с клиентом, но ничего лучше не смог придумать.
Также если через файл делать, то не сможем всю это логику на другом Jira проекте использовать, потому у каждого проекта свой url.
В общем, жду замечания)

2023-09-16 15:48 UTC, ipavelbel approved these changes

2023-09-16 15:48 UTC, ipavelbel commented on src/main/java/faang/school/projectservice/client/JiraClient.java
> +    private final RestTemplate restTemplate;
Возможно если использовать FeignClient, то было бы попроще.

2023-09-16 15:48 UTC, ipavelbel commented on src/main/java/faang/school/projectservice/dto/jira/IssueReadOnlyDto.java
> +    public static class IssueFields {
Получается матрешка из классов, тут вопрос больше к Инне, по другому можно было сделать ?

2023-09-16 16:39 UTC, Hanibalai commented on src/main/java/faang/school/projectservice/client/JiraClient.java
> +    private final RestTemplate restTemplate;
Тоже хотел, но тут либо FeignClient получается, либо использовать с разными проектами в jira всю логику, так как у каждого проекта свой url)

2023-09-18 08:27 UTC, InnMish commented on src/main/java/faang/school/projectservice/client/JiraClient.java
> +    private final RestTemplate restTemplate;
Что-то не поняла здесь немножко 
У нас же один проект..)

2023-09-18 08:35 UTC, Hanibalai commented on src/main/java/faang/school/projectservice/client/JiraClient.java
> +    private final RestTemplate restTemplate;
Ну я подумал так, что проектов может быть много в Jira, так как у нас может быть много проектов в базе и для каждого такого отдельного проекта, мы можем использовать данный функционал по работе с тасками)
На это расчет был)

2023-09-18 08:42 UTC, InnMish requested changes

2023-09-18 08:42 UTC, InnMish commented on src/main/java/faang/school/projectservice/dto/jira/IssueFilterDto.java
> +    @Pattern(regexp = "^(?i)(to do|in progress|done)$",
Какой-то синьорский приемчик :D

2023-09-18 08:42 UTC, InnMish commented on src/main/java/faang/school/projectservice/dto/jira/IssueReadOnlyDto.java
> +public class IssueReadOnlyDto {
Единственное, что я могу предложить - написать json-схему, по которой сгенерятся нужные классы, и будут лежать не в рабочих директориях, в .build  
Я не увидела, где этот класс используется по @Data, но если где-то используется, то так не получится сделать) 
Вообще, можно, наверное, хотя бы на часть классов json написать, наверное...

2023-09-18 08:42 UTC, InnMish commented on src/main/java/faang/school/projectservice/service/JiraService.java
> +    }
можно метод-обертку написать для ошибок, чтобы не повторять одно и то же

2023-09-19 15:37 UTC, Hanibalai commented on src/main/java/faang/school/projectservice/service/JiraService.java
> +    }
Не очень понял, как это можно сделать..)
Обобщил через один метод для read)

2023-09-19 15:45 UTC, Hanibalai commented on src/main/java/faang/school/projectservice/dto/jira/IssueReadOnlyDto.java
> +public class IssueReadOnlyDto {
@Data используется в маппере и в тестах)
Вот как это сделать у меня вызвало трудности)

2023-09-21 17:49 UTC, merged