Feature bc 3903
CorporationX/project_service pull request #254
Opened 2023-09-13 18:05 UTC by AntonRudnikovskiy

2023-09-15 12:49 UTC, Dlakares approved these changes
Всё крута, я чуть подушнил)

2023-09-15 12:49 UTC, Dlakares commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    }
Почему юрлы просто черточка? Думаю стоит добавить осмысленные имена

2023-09-15 12:49 UTC, Dlakares commented on src/main/java/faang/school/projectservice/filters/VacancyFilterByName.java
> +    }
стоит добавить проверку на пустую стрингу

2023-09-15 12:49 UTC, Dlakares commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
Небольшое микро замечание, больше душу конечно.
В этих двух методах ты сохраняя сущность пишешь два раза одну и ту же строчку. Мне нравится такие вещи выносить в отдельные методы. Сокращается вроде не очень сильно. но если тут в будушем будет много таких вызовов, то сократить количество кода. Плюсом, можно предположить что что нибудь измениться. Например репа станет возвращать не опшинал, и придётся везде переписывать реализацию. Вот. Но в целом, этовсё норм, просто я душню)

2023-09-16 15:08 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    }
Не, по REST'у так норм, сверху есть префикс "/vacancy"

2023-09-16 15:12 UTC, kkkooolllyyyaaa requested changes
Всё круто, но нужно поправить конфликты)

2023-09-18 20:03 UTC, AntonRudnikovskiy commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    }
❤️

2023-09-18 20:04 UTC, merged