Создать стажировку
CorporationX/project_service pull request #391
Opened 2024-05-06 15:58 UTC by NadirCianid

2024-05-06 16:32 UTC, nn1ck0 commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +        validationDto(internshipDto);
Лучшше вынести валидацию в отдельный класс, а то контроллер уже странно смотрится

2024-05-06 16:32 UTC, nn1ck0 commented on src/main/java/faang/school/projectservice/validation/InternshipValidation.java
> +public class InternshipValidation {
Я думаю лучше сделать методы, которые будут бросать исключения, заинжектить этот класс в сервис и уже использовать его методы и передавать нужные параметры, чем инжектить все зависимости в валидацию и использовать приватные методы

2024-05-06 17:42 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/validation/InternshipValidation.java
> +public class InternshipValidation {
Пока не вижу причин это делать

2024-05-08 07:29 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/controller/internship/InternshipControllerValidation.java
> +        if (internshipDto.getInternsIds() == null || internshipDto.getInternsIds().size() == 0) {
Рекоммендую использовать метод от спринга для проверки коллекции CollectionUtils.isEmpty(internshipDto.getInternsIds()). Делает всё то же самое, но код чуть короче)

2024-05-08 07:37 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +                .filter(intern -> {
Я бы вынес эту большую логику в отдельный метод, который возвращает предикат

2024-05-08 07:39 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +            if (internRoles.size() == 1) {
А если несколько ролей будет?

2024-05-08 09:15 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/controller/internship/InternshipControllerValidation.java
> +        if (internshipDto.getInternsIds() == null || internshipDto.getInternsIds().size() == 0) {
Спасибо!

2024-05-08 09:20 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +                .filter(intern -> {
Тоже об этом подумал

2024-05-08 09:30 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +            if (internRoles.size() == 1) {
Согласен, не в том месте удалял роль стажера

2024-05-08 16:21 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/internship/filter/InternshipEndDateFilter.java
> +                    LocalDateTime endDatePattern = filters.getEndDatePattern();
По сути , endDatePattern можно её один раз достать и использовать. Мне кажется,лучше вынести из стрима

2024-05-08 16:23 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/internship/filter/InternshipStartDateFilter.java
> +                    LocalDateTime startDatePattern = filters.getStartDatePattern();
То же самое,как в endDatePattern

2024-05-08 16:25 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    public InternshipDto getInternshipById(long internshipId) {
Лучше принимать Long в качестве параметра, т.к если просто дернуть эндпоинт без передачи id, у тебя будет по дефолту 0L, а не null, и в метод что-то передастся

2024-05-08 16:28 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +                .orElseThrow(() -> new DataValidationException(NON_EXISTING_INTERNSHIP_EXCEPTION.getMessage()));
Насчет переносов не уверен, будет ли так лучше обрывать
Лучше спросить у Сабины. Возможно, можно ввести на проекте код стайл

2024-05-08 16:36 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceUtility.java
> +    private Predicate<TeamMember> checkCompletionOfTasks() {
Из видосов Влада помню, что лучше соблюдать очередность полей и методов по модификатору доступа
Так что лучше сделать public методы выше private и других

2024-05-08 16:37 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceUtility.java
> +class InternshipServiceUtility {
Не уверен, что стоит разделять сервис на сервис и утилиты
Надо у Сабины уточнить. А то как будто один класс на 2 растащили

2024-05-08 16:57 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +                .orElseThrow(() -> new DataValidationException(NON_EXISTING_INTERNSHIP_EXCEPTION.getMessage()));
@Sabina-Vishnya, как в данном случае быть с переносом? Норм или нет?

2024-05-08 16:59 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceUtility.java
> +class InternshipServiceUtility {
Растащили, чтобы нормально протестировать код в приватных методах. + так сервис лучше читается, как мне кажется

2024-05-11 17:08 UTC, Sabina-Vishnya requested changes

2024-05-11 17:08 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +        if (internshipDto.getId() == null) {
эта проверка и ниже идентичны почти, там лонги в обоих случаях, а сообщение аргументом можно передать и более того, в твоем валидаторе InternshipControllerValidation есть также такие проверки, которые проверяют лонг на null. Не привязывайся к объекту там, где проверяешь только поля, вот в данном случае у тебя много частей с повторением на проверки полей конкретного типа, хоть это и может показаться неочевидным, но тут явно можно валидацию уменьшить и переиспользовать

2024-05-11 17:08 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/controller/internship/InternshipControllerValidation.java
> +        if (startDate.isBefore(endDate.minus(3, ChronoUnit.MONTHS))) {
что за 3 неизвестное никому?) это в константу стоит вынести

2024-05-11 17:08 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceValidation.java
> +class InternshipServiceValidation {
VacancyRepository нигде не используется тут

2024-05-11 17:08 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +                .orElseThrow(() -> new DataValidationException(NON_EXISTING_INTERNSHIP_EXCEPTION.getMessage()));
Я за то, чтобы код помещался в окно идеи, в данном случае перенос к месту. 
Еще видела, что некоторые прям по точкам просто переносят, но мне такой вариант вполне понятен тоже. 
В идеи рамка есть и выходя за рамки сложнее воспринимать уже остальное, ты как бы фокусируешься, когда код у тебя попадает в одно поле видимости. 
Есть даже некий стандарт https://www.oracle.com/java/technologies/javase/codeconventions-indentation.html
не только у джавы такое, но вот исторически сложилась так, что настроены идеи на 80 символов обычно. Кажется это из-за того, что печатали исходники и удобнее было. Щас уже некоторым всё равно и это не требуется строго соблюдать прям, изменились времена, но по холивару на эту тему на работе есть мнение, что многим всё же такой вариант понятнее по сей день) Можно конечно растянуть всё, но в большинстве случаев удобнее не растягивать при чтении. Так что, я за такую, если можно назвать, компактность)
Радмир, про код стайл хорошо подсветил, была мысль такое предложить, возможно надо бы, только кто готов себе туду завести?) Можем на дейли обсудить еще, у нас там есть разные задачки, эту мб тоже добавим

2024-05-11 17:08 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceUtility.java
> +class InternshipServiceUtility {
"нормально протестировать код в приватных методах" - не очень поняла про что это?
Учитывая, что не все тесты есть - это скорее всего доделаешь после основных правок? 

Сложно понять, что происходит, поскольку глобально разницы сервиса, валидатора и утилиты нету. Сервис лучше читается тебе, потому что ты больше остальных погружен в происходящее и бизнес-логику текущую. Спустя время наверняка тебе захочется этот код переделать.
Метод toEntity в утилитах, который и мапит еще другой toEntity, и в репозитории идет. Суть метода в чем? Название явно ничего не говорит, а лишь вводит в заблуждение. 
Вадлидатор и сервис используют одни и те же методы для работы с бд. Класс утилит также проверки имеет. В чем смысл такого растаскивания, когда тут не прослеживается разделение ответственности?

2024-05-11 17:08 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +    Internship toEntity(InternshipDto dto);
норм ли нам игнорить поля эти? а то что-то не первый раз вижу игнор полей, не нахватаем ли мы багов и кривую логику из-за этого?

2024-05-11 17:08 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceUtility.java
> +                //TODO: нормально ли делать по умолчанию бывших стажеров разработчиками, если до этого у них не было другой роли?
Если требуется доп. разграничение ролей и прав доступа, то присвоение роли разработчика по дефолту может не подойти. У нас вроде такого пока нет, поэтому кажется норм, но непонятно у стажеров роль интерна была или нет? у бывших стажеров должна быть удалена роль интерна и присвоена какая-то другая ведь, т.е. стажер-разработчик после удачной стажировки будет с ролью разработчика, а роль интерна у него удалена, как это "не было другой роли"?

2024-05-11 21:22 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +    Internship toEntity(InternshipDto dto);
Мы из игнорируем, потому что не можем в мапере обратиться в репозиторий, чтобы их установить

2024-05-11 21:23 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceUtility.java
> +                //TODO: нормально ли делать по умолчанию бывших стажеров разработчиками, если до этого у них не было другой роли?
У стажеров роль интерна должна быть в любом случае
Также у них в теории должна быть и вторая роль, указывающая их специальность

2024-05-11 21:24 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceUtility.java
> +                //TODO: нормально ли делать по умолчанию бывших стажеров разработчиками, если до этого у них не было другой роли?
"не было другой роли", кроме стажера

2024-05-14 21:23 UTC, Sabina-Vishnya requested changes

2024-05-14 21:23 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/internship/InternshipFiller.java
> +    private final InternshipMapper internshipMapper;
не вижу тут использования маппера этого

2024-05-14 21:23 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/internship/InternshipFiller.java
> +public class InternshipFiller {
~public~

2024-05-14 21:23 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/internship/InternshipFiller.java
> +        var interns = internIds.stream()
у jpa репозитория кажется есть метод findAllById
посмотри, вдруг, он подойдет сюда и тогда оптимальнее и красивее выйдет код

2024-05-14 21:23 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +        verifyMentorsProject(internshipDto);
подумай над рефакторингом, у тебя сейчас снова дублирование по сути, например:
1 метод верификации, внутри вызывает getProjectById
2 метод getTeamMembersProject фактически тоже, тк внутри вызывает findById
эти же методы у тебя повторно вызываются для энтити в InternshipFiller

Аналогично и для update метода

Попробуй оптимизировать, код у тебя вероятнее всего упростится

2024-05-16 19:52 UTC, Sabina-Vishnya requested changes

2024-05-16 19:52 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +        verifyMentorsProject(internshipDto.getProjectId(), internshipDto.getMentorId());
дублируешь логику в валидаторах и методах, вызовы те же
и у тебя сервис энтити возвращает, какой тогда смысл в вызовах таких сервисов?
почему нельзя тогда сделать проще, например, вызов трех репозиториев,
типа:
```
Project project = projectRepository.getProjectById(internshipDto.getProjectId());
TeamMember teamMember = teamMemberRepository.findById(internshipDto.getMentorId());
List<TeamMember> teamMemberList = teamMemberRepository.findAllByIds(internshipDto.getInternsIds());
```
В каждом есть проверка, кроме последнего вызова, где список. Эти же данные потом сетятся в филлере. Суть та же, те же энтити и другие репозитории, почему не упростить тогда до похожего примитивного вызова с проверкой? 

подумай о подобном, чтобы не дублироваться
и у тебя какие-то сервисы возвращают дто, а какие-то энтити, например TeamMemberService, почему так - непонятно,. Тут бы тоже привести в порядок.

Это, если что, лишь часть метода для примера, который можно было бы поправить. Тебе стоит начать с того, чтобы просмотреть подобные вещи в других частях кода, а они есть и поправить их. Ты ведь таким образом и код впоследствии можешь упрощать, а сейчас усложняешь, накручивая проверки, которые у тебя в вызовах и так есть.

2024-05-19 01:52 UTC, Sabina-Vishnya requested changes

2024-05-19 01:52 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/internship/InternshipFiller.java
> +class InternshipFiller {
Бины тут не используются + от этого класса можно отказаться в виде филлера и сетить в сервисе тогда уже, а этот класс лучше сделать валидатором. Просто
все свои методы verify перетащить сюда и переименовать класс - всё. 
Больше здесь ничего не будет, кроме твоих приватных методов верифаев из сервиса, которым ты модификатор доступа только поправишь.

2024-05-19 01:52 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +        internshipFiller.fillEntity(internship, project, mentor, interns);
- Про филлер тебе написала, сеттеры сюда притаскивай, а три метода verify утаскивай

- А вот эта часть
```
Project project = projectRepository.getProjectById(internshipDto.getProjectId());
TeamMember mentor = teamMemberRepository.findById(internshipDto.getMentorId());
List<TeamMember> interns = teamMemberRepository.findAllByIds(internshipDto.getInternsIds());

verifyMentorsProject(project, mentor);
verifyExistenceOfAllInterns(interns, internshipDto.getInternsIds().size());
```
дублируется в create и update методах. Можно попробовать выделить в общий метод. 
Например, с помощью приватного класса хранить `Project, TeamMember, List<TeamMember>`. А часть повторяющегося кода вынести в метод и возвращать объект с нужными данными.

2024-05-19 01:52 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +    void update(InternshipDto dto, @MappingTarget Internship entity);
Лучше переименовать, иначе будет сбивать столку, что это часть маппинга.
Можно fillEntityForUpdate или что-то в этом духе, просто название понятнее метода

2024-05-19 08:35 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +    void update(InternshipDto dto, @MappingTarget Internship entity);
Это же буквально часть маппинга. Просто в этом методе не создается новая сущность, а обновляется существующая.

2024-05-19 13:14 UTC, Sabina-Vishnya approved these changes

2024-05-22 19:46 UTC, Sabina-Vishnya approved these changes

2024-05-22 19:53 UTC, merged