BJS2-6398 : Создание вакансии
CorporationX/project_service pull request #392
Opened 2024-05-06 16:15 UTC by nn1ck0

2024-05-07 16:48 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/dto/vacancy/VacancyDto.java
> +}
Мне кажется в дто не хватает поля статуса вакансии

2024-05-07 16:50 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/dto/vacancy/VacancyDto.java
> +}
а вот createdBy и updatedBy лично я бы не добавлял пока

2024-05-07 16:51 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/dto/vacancy/VacancyDto.java
> +}
И хорошо бы иметь возможность добавлять кандидатов через dto

2024-05-07 16:53 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/validation/ValidationVacancy.java
> +        if (vacancyDto.getName().isBlank()) {
А если поле name будет null?

2024-05-07 16:54 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +        vacancyService.createVacancy(creatorId, vacancyDto);
А если creatorId будет null ?  Может тогда сделать его примитивом, чтобы не проверять?

2024-05-07 16:55 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +        vacancyService.createVacancy(creatorId, vacancyDto);
И может стоит проверять также наличие  requiredSkills?

2024-05-07 17:00 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/validation/ValidationTeamMember.java
> +    public void checkMemberRole(TeamMemberDto member) {
по названию не понятно, что за проверка именно происходит

2024-05-07 17:04 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/vacancy/VacancyService.java
> +        vacancyEntity.setUpdatedAt(LocalDateTime.now());
Разве эти поля не  в бд автоматически заполняются ?

2024-05-07 17:06 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/vacancy/VacancyService.java
> +        vacancyEntity.setUpdatedAt(LocalDateTime.now());
Если нет, тогда здесь также надо и установить поле updatedBy

2024-05-07 17:07 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/vacancy/VacancyService.java
> +    public void createVacancy(Long creatorId, VacancyDto vacancyDto) {
Метод должен возвращать созданную сущность (в виде dto)

2024-05-10 11:22 UTC, nn1ck0 commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +        vacancyService.createVacancy(creatorId, vacancyDto);
> И может стоит проверять также наличие requiredSkills?
Можно же у вакансий указывать скиллы, а можно и не указывать

2024-05-10 13:50 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +        validationVacancy.checkProjectId(vacancyDto);
Не  вижу смысла разделять проверку на null и isBlank на два метода. 

есть аннотация @NonNull, которую в данном случае можно повесить на поле метода, чтобы ломбок автоматически реализовал проверку на null

2024-05-10 13:51 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +        validationVacancy.checkProjectId(vacancyDto);
И проверять checkVacancyNameForNull  после checkVacancyName нелогично

2024-05-10 13:52 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    private final ValidationCreator validationCreator;
немного бесполезный класс, особенно учитывая возможность использовать аннотацию @NonNull  (см. следующий комментарий)

2024-05-10 13:58 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/validation/ValidationCreator.java
> +public class ValidationCreator {
нет смысла делать валидаторы публичными

2024-05-10 14:03 UTC, NadirCianid requested changes
Поправь хотя бы момент с проверкой на null после проверки isBlank

2024-05-10 14:03 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/validation/ValidationCreator.java
> +public class ValidationCreator {
Но тогда возможно придется поменять их расположение

2024-05-11 17:48 UTC, Sabina-Vishnya requested changes

2024-05-11 17:48 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    private VacancyDto createVacancy(@NonNull Long creatorId, VacancyDto vacancyDto) {
почему приватный? у тебя позже тест будет на контроллер, а в последствии это будет еще и рест

2024-05-11 17:48 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    private VacancyDto createVacancy(@NonNull Long creatorId, VacancyDto vacancyDto) {
раз про аннотацию @NonNull тебе известно, почему бы не добавить к дто ее тоже, а проверку checkVacancy на null из валидатора убрать?

2024-05-11 17:48 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/vacancy/VacancyService.java
> +        validationTeamMember.checkThatTheUserCanCreateAVacancy(teamService.findMemberById(creatorId));
имя checkThatTheUserCanCreateAVacancy лучше изменить на то, что проверяет метод на самом деле

2024-05-11 17:48 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +        validationVacancy.checkProjectId(vacancyDto);
а почему часть заполнения энтити в VacancyMapper а часть в сервисе?
это логика маппера должна быть в маппере, а тут выходит разброс

2024-05-14 22:22 UTC, Sabina-Vishnya requested changes

2024-05-14 22:22 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public Project getProjectById(Long id) {
почему не дто, а энтити? у тебя причем в других сервисах дто, посмотри видео от Влада про дто, если не видел https://faang-school.com/courses/mbvd6kz9/9ndwp46z

если ссылка не сработает, то ищи в теме под номером 5 (пункт 5.3 Spring core: IoC, Beans, Dependency Injection, Configuration)

2024-05-14 22:22 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/vacancy/VacancyService.java
> +        vacancyEntity.setCandidates(new ArrayList<>());
непонятна строка 31, почему кандидаты сетятся так?
кажется, что этот метод весь как-то перемудрил, попробуй подрефачить после того, как все сервисы будут возвращать дто или возможно ты не сервисы захочешь использовать

2024-05-14 22:22 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/vacancy/ValidationTeamMember.java
> +        if (!member.getRoles().contains(TeamRole.MANAGER.toString())
не нужно два раза вызывать member.getRoles(), достаточно один и вопрос, у нас роли уникальны или могут дублироваться? мы кажется сет тут можем использовать вообще тогда

2024-12-22 19:28 UTC, closed without merging