Phoenix bc4 feature bjs2 6401
CorporationX/project_service pull request #414
Opened 2024-05-18 19:28 UTC by Murzin34

2024-06-20 07:03 UTC, p1maf requested changes

2024-06-20 07:03 UTC, p1maf commented on src/main/java/faang/school/projectservice/controller/moment/MomentController.java
> +    }
Если передать пустую дтошку, то вылетит NPE, можешь добавить валидацию через джакарту довольно таки компактно и красиво

2024-06-20 07:03 UTC, p1maf commented on src/main/java/faang/school/projectservice/controller/moment/MomentController.java
> +    }
Так же вижу, что есть валидация в MomentDto, но нет аннотации @Valid чтобы он провалидировал перед заходом в контроллер

2024-06-20 07:03 UTC, p1maf commented on src/main/java/faang/school/projectservice/dto/moment/MomentDto.java
> +    private List<@NotNull Long> userIds;
Если передать [] то с ошибкой упадет, добавь @NotEmpty

2024-06-20 07:03 UTC, p1maf commented on src/main/java/faang/school/projectservice/service/moment/MomentService.java
> +
нигде не используешь

2024-06-20 07:03 UTC, p1maf commented on src/main/java/faang/school/projectservice/controller/moment/MomentController.java
> +    }
Get не может иметь тела

2024-06-20 07:03 UTC, p1maf commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +
не нашел где использовал бы

2024-06-20 07:03 UTC, p1maf commented on src/main/java/faang/school/projectservice/service/moment/MomentService.java
> +    }
у тебя есть метод findMomentById, который просто возвращает найденный момент и тут ты превращаешь его в DTO, предполагаю что ты вынес из-за длинной строчки которая получилась, но ты же можешь как с стримами перенести на новую и не нужен будет доп.метод который не выполняет никакого доп.функционала

2024-06-20 07:03 UTC, p1maf commented on src/main/java/faang/school/projectservice/dto/moment/MomentDto.java
> +    private LocalDateTime date;
добавь формат для даты к примеру @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")

2024-06-20 07:22 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/controller/moment/MomentController.java
> +    }
Поменял на `@PostMapping`

2024-06-20 07:25 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/service/moment/MomentService.java
> +
Этот код уже есть в мастере, написан Денисом. Добавил eго чтобы избежать конфликта в git'e, но наверно стоит иначе решить этот конфликт.

2024-06-20 07:33 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +
Да, не использую. Возможно стоит оставить только `toDto` и `toEntity` переписав свой код, я подумаю.

2024-06-20 08:04 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/service/moment/MomentService.java
> +    }
Да, метод `findMomentById` вывел только чтобы код в паблик методах был почище. В целом, ок, давай сделаю как ты предлагаешь.

2024-06-20 08:07 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/dto/moment/MomentDto.java
> +    private LocalDateTime date;
Спасибо за наводку.

2024-06-20 08:12 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/dto/moment/MomentDto.java
> +    private List<@NotNull Long> userIds;
Спасибо за наводку.

2024-06-21 07:21 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/controller/moment/MomentController.java
> +    }
Поправил

2024-06-24 20:29 UTC, Sabina-Vishnya reviewed
в целом хорошо, поправить несколько замечаний нужно и можешь уже тесты писать оставшиеся

2024-06-24 20:29 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/controller/moment/MomentRestController.java
> +public class MomentRestController {
у нас по влитым пр-ам большинство контроллеров вроде без Rest в названии, лучше единообразно тогда уж сделать и убрать тоже (либо можно переименовать все на ресты, это понятнее будет, но это не прям замечание, можно в целом и оставить так)

2024-06-24 20:29 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/dto/moment/filter/MomentFilterDto.java
> +    private LocalDateTime endDate;
десериализуются?

2024-06-24 20:29 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/moment/filter/MomentDateFilter.java
> +public class MomentDateFilter implements MomentFilter {
ну вот, снова паблик эти фильтры начали все делать, а я ведь с самого начала пропагандировала не делать пабликами, но видимо только несколько ребят это сделали (тк это не во всех сервисах и в текущем все фильтры паблик), а я  пропустила =( 
так то вообще хорошо бы не публичными делать эти реализации фильтров, тк они пока только в одном месте используются и работают через интерфейс только в MomentRestService

2024-06-24 20:29 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/validation/moment/MomentRestValidator.java
> +    //Todo Перенести в ProjectValidator
свой ник к тудухе, чтобы всем понятно было, кто сделает

2024-06-24 20:29 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/validation/moment/MomentRestValidator.java
> +    public void projectsUpdateValidator(Moment oldMoment, MomentRestDto newMomentDto) {
кажется упростить можно или декомпозировать

2024-06-29 00:58 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/controller/moment/MomentRestController.java
> +public class MomentRestController {
Изменил название с MomentController на MomentRestController чтобы избежать конфликта в мастере.

2024-06-29 01:14 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/service/moment/filter/MomentDateFilter.java
> +public class MomentDateFilter implements MomentFilter {
Поменял на модификатор доступа по умолчанию.

2024-06-29 01:15 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/validation/moment/MomentRestValidator.java
> +    //Todo Перенести в ProjectValidator
Добавил никнейм

2024-06-29 03:11 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/validation/moment/MomentRestValidator.java
> +    public void projectsUpdateValidator(Moment oldMoment, MomentRestDto newMomentDto) {
Попробовал декомпозировать

2024-07-03 22:42 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/controller/moment/MomentRestController.java
> +public class MomentRestController {
так у нас с мапперами также, будет теперь в мастере всегда для моментов несколько мапперов/контроллеров итд? это рефачится будет или так и останется?

2024-07-03 22:49 UTC, Sabina-Vishnya approved these changes

2024-07-05 06:24 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/controller/moment/MomentRestController.java
> +public class MomentRestController {
Думал, через сабтаску это поправить

2024-12-22 19:28 UTC, closed without merging