BJS2-6404: Этапы проекта
CorporationX/project_service pull request #437
Opened 2024-06-01 10:17 UTC by p1maf

2024-06-01 11:02 UTC, RickHammerson commented
Нужно влить все изменения мержем с ветки phoenix-master-bc4, чтобы у тебя были актуальные данные для последующего мержа и появления новых файлов, которые ты можешь использовать

2024-06-01 11:05 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +    public List<StageDto> getFilterStageByStatus(@PathVariable("projectId") long projectId, @RequestParam("status") TaskStatus status) {
Не совсем ясное ,что делает метод по названию
Получить фильтер этапа по статусу
При чем тут фильтр и где он, если всё, что ты передаешь это Id проекта и статус?

2024-06-01 11:07 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +public class StageController {
В название можно добавить, к какой сущности это относится
Сейчас же это просто этап, но этап чего?
Лучше переименовать в ProjectStageController

2024-06-01 11:08 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +public class StageController {
И ещё лучше класть в отдельные пакеты, чтобы разделить, к чему это относится
Сейчас controller лежит просто в пакете контроллеров. Для проектов у нас будет несколько контроллеров, так что лучше их объединить в один пакет

2024-06-01 11:09 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +@RequestMapping("stages")
Если этапы относятся к проектам, можно изменить путь на project/stages

2024-06-01 11:10 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +    public void deleteStage(@PathVariable("stageId") Long stageId) {
Где-то переменные @PathVariable Long stageId у тебя примитивного типа, а где-то ссылочного. Попробуй использовать что-то одно

2024-06-01 11:35 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +    public List<StageDto> getFilterStageByStatus(@PathVariable("projectId") long projectId, @RequestParam("status") TaskStatus status) {
В @RequestParam("status") необязательно указывать как называется поле, если оно совпадает с названием параметра в методе
То есть можно оставить @RequestParam TaskStatus status,а он уже по названию переменной метода поймет, что название параметра - status

2024-06-01 11:36 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/dto/stage/StageDto.java
> +    @NotNull
Вместо двух аннотаций можно использовать @NotBlank
Она идеально подходить под String
@NotEmpty можно использовать с коллекциями

2024-06-01 11:38 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/exceptions/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
В этом классе не хватает обработки ошибок, если будет ошибка валидации через аннотации @NotEmpty и другие
Попробуй локально через постман отправить неправильную DTO, которая вызовет ошибку

2024-06-01 11:39 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/StageService.java
> +public class StageService {
Опять же указать, что это этап относится к проекту

2024-06-01 11:40 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/StageService.java
> +    public List<StageDto> getAllStages(Long projectId) {
Компонуй методы по модификатору доступа
public
protected
default
private

То есть сейчас все паблик методы должны быть выше private

2024-06-01 11:41 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        return stageMapper.toDto(stageRepository.save(stage));
Нужно пробелами чуть разделить логику метода, чтобы глазам легче было

Валидация

какая-то обработка сущности

return что-то

2024-06-01 11:42 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/StageService.java
> +                .filter(stage -> stage.getProject().getId() == projectId)
Почему бы не добавить .filter(stage -> stage.getProject().getId() == projectId) в нижний стрим?

2024-06-01 11:43 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/StageService.java
> +                .filter(stage -> !stage.getTasks().stream()
Если есть сложные предикаты, можно вынести в отдельный маленький метод с хорошим названием

2024-06-01 11:44 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        for (Task task : tasks) {
Можно заменить на стрим, а можно и нет. Как удобнее)

2024-06-01 11:47 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/validation/StageValidation.java
> +public class StageValidation {
Лучше называть классы по тому, что он делает, а методы - его поведение
Например, сейчас он называется Проверка Стадий

Но можно Проверяльщик Стадий (StageValidator). Потом он будет делать какую-то проверку

2024-06-01 11:49 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/validation/StageValidation.java
> +    public void projectValidate(Long id) {
В продолжение верхнего коммента - это действие, которое будет совершать твой Валидатор
Сейчас он называется Проверка проекта

Проверка на что? На создание, на апдейт, на удаление?
 Переименуй метод на то, к какому действию он относится

2024-06-01 11:50 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/validation/StageValidation.java
> +        if (projectRepository.getProjectById(id).getStatus().equals(ProjectStatus.CANCELLED) ||
Не обязательно 2 раза запрашивать проект по ID. Можно выделить его в переменную перед ifом и у неё уже опросить статус
Так ты уменьшишь количество кода и не будешь делать 2 вызова к БД

2024-06-02 10:18 UTC, p1maf commented on src/main/java/faang/school/projectservice/validation/StageValidation.java
> +public class StageValidation {
Тут согласен, просто в пакете уже был класс которые так назывался и поэтому подумал, что не стоит портить стилистику

2024-06-03 18:23 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/dto/stage/StageDto.java
> +    private Long projectId;
Ещё можно повесить @PozitiveOrZero,а то пришлют минусовое значение

2024-06-03 18:26 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/projectStage/ProjectStageService.java
> +        tasks.forEach(task -> {
А какой смысл делать эти действия, если ты потом на 62 строчке удаляешь сущность?
Возможно, я по логике не прав, отпиши потом

2024-06-04 07:54 UTC, p1maf commented on src/main/java/faang/school/projectservice/service/projectStage/ProjectStageService.java
> +        tasks.forEach(task -> {
Там нужно сделать удаление этапа, а так же закрыть задачи связанные с ними, поэтому я в цикле прохожу и закрываю задачи которые не выполнены

2024-06-11 19:00 UTC, RickHammerson commented
Йес йес, можно кидать на ревью

2024-06-13 19:21 UTC, Sabina-Vishnya requested changes

2024-06-13 19:21 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/dto/stage/StageDto.java
> +    private List<StageRolesDto> stageRolesDto;
список может содержать и null значения?

2024-06-13 19:21 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/projectStage/ProjectStageService.java
> +                .filter(stage -> stage.getProject().getId() == projectId)
рискуешь с **==**
если выйдешь за границы кэшированного диапазона, то некорректно сравнишь, а тут как раз такое может быть.
Оболочки рекомендуется сравнивать через **equals**
Посмотри исходники кода и поищи про кеш, также в доке частично упоминается это в методе valueOf https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Long.html#valueOf(long)

2024-06-13 19:21 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/projectStage/ProjectStageService.java
> +        List<TeamMember> members = teamsProject.stream()
можно без переменной teamsProject, а сразу project.getTeams() сюда

2024-06-18 20:20 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/dto/stage/StageDto.java
> +    private List<StageRolesDto> stageRolesDto;
Проверяй запросами, если не очевидно так (позитивные и негативные).
1. имя атрибута будет в запросе, как `stageRolesDto` - лучше stageRoles, никому неинтересно и это неправильно знать, что это дто.
2. `List<StageRolesDto>` у тебя не может быть пустым, при этом в `StageRolesDto` ни одно поле не помечено обязательным. Но сам список то должен быть обязательным судя по твои аннотациям (типа, но это не будет работать). Выходит, что можно отправить пустой список? Подсказка - не хватает аннотации.
3. Проверь ответ, после того как поправишь валидацию, у тебя в ответе у постмана не будет кода ошибки.

Любой код перед пушем проверяй и постманом в том числе, ты себе время сэкономишь в первую очередь.
Сейчас я не поднимаю контейнер и твой код не проверяю кидая запросы, но по коду вижу, что ты не проверял (либо не всё учел при проверке, а нужно проверять и всякие ошибки, которые ты ожидаешь и в коде обрабатываешь)

2024-06-18 20:56 UTC, Sabina-Vishnya commented
если эти правки займут больше часа-двух, кидай на ревью мне обратно, но с комментом о том, что нужно больше времени (просто подробнее напиши причину), мы тогда заведем таску с рефакторингом (или баг на фикс), для этих правок и сделаешь в ней

2024-06-21 07:23 UTC, Sabina-Vishnya approved these changes

2024-07-06 15:57 UTC, merged