Решение задачи BJS2-6775 Добавление обложки к проекту
CorporationX/project_service pull request #448
Opened 2024-06-11 18:52 UTC by RickHammerson

https://faang-school.atlassian.net/browse/BJS2-6775

2024-06-11 20:34 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/controller/project/ProjectImageController.java
> +    @PostMapping("/{projectId}/thumbnail")
Почему не "cover", как в задании и в модели?

2024-06-11 20:47 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/controller/project/ProjectImageController.java
> +        @NotNull(message = "Uploading team member Id Id can't be null") @PositiveOrZero(message = "Uploading team member Id can't be negative") Long teamMemberId,
Я считаю, что аннотацию @RequestParam добавить не повредит

2024-06-11 20:50 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/controller/project/ProjectImageController.java
> +        return projectService.uploadThumbnail(projectId,teamMemberId, file);
Возможно ты это сделал где-то на глобальном уровне, но я не вижу проверку на макс. размер файла в общем. В задании указано, что файл обложки  не может быть больше 5 мб.

2024-06-11 20:53 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +    public BufferedImage convertImageToThumbnail(Supplier<ImageResource> imageSupplier) {
Какой смысл делать этот метод через ФИ, если ты используешь только одну реализацию? 

Да и название метода немного не отражает истины. 

+ Я считаю, что выносить логику конвертации в основной сервис не логично. Логичнее было бы написать интерфейс специальный и несколько реализаций. Если хочешь использовать полиморфизм

2024-06-11 20:54 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +            String error = "IO exception while converting image to input stream";
Почему здесь не используешь текст ошибки из enum ?

2024-06-11 20:56 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +            String error = "IO exception while converting image to input stream";
Здесь и в других местах

2024-06-11 20:57 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +    }
А здесь сразу метод с реализацией. И без Функциональных интерфейсов...

2024-06-11 20:57 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +    }
Как ниже*

2024-06-11 21:01 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/dto/image/ImageResource.java
> +        this.orientation = calculateOrientation(height, width);
Зачем здесь "this" ?

2024-06-11 21:02 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/dto/image/ImageResource.java
> +    protected Integer targetWidth;
Почему не примитивами ?

2024-06-11 21:14 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/model/Project.java
> +
Нет проверки на null в поле storageSize (оно nullable)

2024-06-11 21:25 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/s3/requests/S3Request.java
> +public interface S3Request<T> {
generic не используется никак

2024-06-11 21:26 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/config/properties/S3Properties.java
> +    private String isMocked;
Зачем это поле?

2024-06-11 21:27 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/s3/requests/S3Request.java
> +public interface S3Request<T> {
Для чего создаешь интерфейс?

2024-06-11 21:29 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/exception/aws/s3/S3ExceptionMessages.java
> +    BUCKET_NOT_FOUND_EXCEPTION("Бакет, указанный в настройках не найден");
Почему на русском?

2024-06-11 21:30 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/exception/aws/s3/S3ExceptionMessages.java
> +    }
Можно заменить на аннотацию

2024-06-11 21:31 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    private final S3Properties properties;
неиспользуемое поле(

2024-06-11 21:32 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    }
Где логи?

2024-06-11 21:35 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/model/Resource.java
> +//    private List<TeamRole> allowedRoles;
Что это такое?

2024-06-11 21:39 UTC, NadirCianid reviewed
На мой взгляд, ты перемудрил с разбиением  логики. Может это и улучшит масштабируемость (хотя я сомневаюсь, что для этого необходимо так сильно дробить логику). Но разбираться в этом всем довольно сложно. Большинство методов вызываются единожды и могут быть объединены даже логически. Но это не критично. 

Больше смущает то, то ты используешь термин "thumbnail", хотя в проекте уже есть термин "cover" (в моделе). 

И ответь на вопрос про проверку размера файла до попадания в сервис.

2024-06-11 22:12 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/controller/project/ProjectImageController.java
> +    @PostMapping("/{projectId}/thumbnail")
Хз, моча в голову ударила. Переделаю

2024-06-11 22:13 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/controller/project/ProjectImageController.java
> +        @NotNull(message = "Uploading team member Id Id can't be null") @PositiveOrZero(message = "Uploading team member Id can't be negative") Long teamMemberId,
Да, верно

2024-06-11 22:23 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/controller/project/ProjectImageController.java
> +        return projectService.uploadThumbnail(projectId,teamMemberId, file);
Да, сделал это на уровне бин конфига
![image](https://github.com/CorporationX/project_service/assets/42961541/2e7e61d1-5df6-4ee2-bc24-a430c9db5fff)
Где-то уже видел вопрос в help канале, что людям может помешать ограничение на весь микросервис в 5мб, но Влад сказал .что мы тренируемся и так можно делать

2024-06-11 22:25 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +    public BufferedImage convertImageToThumbnail(Supplier<ImageResource> imageSupplier) {
Может быть много наследников от ImageResource. Я ж не только для обложки сделал
В проект можно будет запихнуть какие-то ресурсы,в том числе и картинки, которые будут таким же образом скейлиться через этот интерфейс, но по другому алгоритму, в отличие от обложек проектов

2024-06-11 22:28 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/dto/image/ImageResource.java
> +        this.orientation = calculateOrientation(height, width);
Привык так писать, чтобы явно указать, что переменные относятся к данному классу
Чисто визуально так легче воспринять

2024-06-11 22:29 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/dto/image/ImageResource.java
> +    protected Integer targetWidth;
Не хочу, чтобы инициализировались 0-ми
Да и прост привык оболочки юзать
Примитивы нужны только для быстрых вычислений. Решил, что тут они не нужны

2024-06-11 22:35 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/model/Project.java
> +
Размер для проекта задается при создании. Если оно не заполнено, кинет ошибку. Измениться может только при апдейте
Добавил на это проверки аннотациями

2024-06-11 22:35 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/s3/requests/S3Request.java
> +public interface S3Request<T> {
Да, это осталось от предыдущей попытки реализации. Там в тупик всё пришло
Уберу

2024-06-11 22:37 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/config/properties/S3Properties.java
> +    private String isMocked;
Тож не понял, но в application.yaml оно есть. Оставил на всякий случай

2024-06-11 22:37 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/exception/aws/s3/S3ExceptionMessages.java
> +    BUCKET_NOT_FOUND_EXCEPTION("Бакет, указанный в настройках не найден");
Параллельно работал, там ошибки на русском пишем. Исправлю

2024-06-11 22:38 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/exception/aws/s3/S3ExceptionMessages.java
> +    }
Какую аннотацию?

2024-06-11 22:38 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    private final S3Properties properties;
Да,ты прав

2024-06-11 22:40 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    }
На работе привык, что логи только в сложных местах или ошибках. Надо спросить у Сабины, надо ли логгировать успешность

2024-06-11 22:42 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/model/Resource.java
> +//    private List<TeamRole> allowedRoles;
Поле, для которого не нашел миграцию. Оставил тудушку спросить у Сабины

2024-06-11 22:44 UTC, RickHammerson commented
Согласен, что разбил достаточно подробно
Но это всё во имя масштабирования в будущем, даже если его не будет. Сейчас тренируюсь, чтобы понять, правильно ли делаю всё или есть что-то попроще для реализации

Изменил все названия на cover

Оставил коммент по размеру файла

2024-06-11 22:49 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +            String error = "IO exception while converting image to input stream";
Переделал

2024-06-12 06:32 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +    public BufferedImage convertImageToThumbnail(Supplier<ImageResource> imageSupplier) {
А, что здесь, кроме картинки может превратиться в BufferdImage? 

Я имел в виду, что метод в одну строку, да еще и с supplier'ом, который здесь ни к селу ни к городу, выглядит пустовато. Ты же по сути вызываешь метод ImageResource для конвертации, получив из suplier'а сам ресурс. Так для чего здесь целый метод?

2024-06-12 06:33 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/dto/image/ImageResource.java
> +        this.orientation = calculateOrientation(height, width);
Это не ошибка. Просто мне до этого Инна такой же вопрос задавала. Вкусовщина больше

2024-06-12 06:36 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/model/Project.java
> +
![image](https://github.com/CorporationX/project_service/assets/101037555/31b6b2da-0dd6-470e-8fba-75b1022c35ec)
До коммита было так

2024-06-12 06:36 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/model/Project.java
> +
А все эти аннотации пропускают null

2024-06-12 06:37 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/model/Project.java
> +
Кстати, а 1000 байт не маловато?

2024-06-12 06:38 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/config/properties/S3Properties.java
> +    private String isMocked;
) 
Лучше разберись, если оставляешь, заодно мне расскажешь

2024-06-12 06:38 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/exception/aws/s3/S3ExceptionMessages.java
> +    }
@AllArgsConstructor
@RequiredArgsConstructor

2024-06-12 06:40 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/exception/aws/s3/S3ExceptionMessages.java
> +    }
>@RequiredArgsConstructor

Ну ты понял...

2024-06-12 06:42 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    }
Было бы хорошо видеть путь выполнения метода. Тем более при запуске сервиса в логах не только ошибки выводятся. Но и сообщения об успешных подключениях. 

Но ты спроси на дейлике

2024-06-12 06:45 UTC, NadirCianid commented on src/main/resources/db/changelog/changeset/project_V004__alter_resource.sql
> +alter table resource
Почему переименовал?

2024-06-12 06:47 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        project.setCoverImageId(key);
Я все еще считаю, что здесь слишком много кода. Это должно выглядеть, как вызов сервиса в одну-две строки.

2024-06-12 06:47 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        project.setCoverImageId(key);
Сервиса по работе с S3

2024-06-12 06:50 UTC, NadirCianid commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
>          Project project = projectRepository.getProjectById(projectId);
Метод неиспользуемый. Знаю, что это я его создал, но рас уже ты работаешь в сервисе, то надо бы с ним разобраться, если он в таком виде (с таким названием) не нужен уже

2024-06-12 06:51 UTC, NadirCianid approved these changes

2024-06-13 23:05 UTC, Sabina-Vishnya requested changes
также к замечаниям вопрос, почему модификаторы протектет? разве не достаточно геттеров/сеттеров или ты что-то хотел сделать таким образом? мб я не поняла, будет круто, если расскажешь)

2024-06-13 23:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/config/WebConfig.java
> +        factory.setMaxFileSize(DataSize.of(5, DataUnit.MEGABYTES));
есть DataSize.ofMegabytes + в констану, но еще лучше вообще это настроить в конфигурации

2024-06-13 23:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/dto/image/ProjectImage.java
> +    class VerticalImageBorders {
почему не приватные статики эти классы?

2024-06-13 23:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/dto/image/ImageResource.java
> +        if (width > height) {
давай этот if-else в тернарку, чуть меньше кода сделаем

2024-06-13 23:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/dto/image/ProjectImage.java
> +                .outputQuality(1)
константа

2024-06-13 23:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/dto/image/ProjectImage.java
> +                .size(this.targetHeight, this.targetWidth)
наоборот, ширина и высота
посмотри в метод size

2024-06-13 23:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/dto/image/ProjectImage.java
> +                if (isImageHeightGreater(VerticalImageBorders.HEIGHT_BORDER)) {
Можно эти ифчики и ниже, вынести в приватный метод, с параметрами, который будет содержать два ифа, например.

2024-06-13 23:06 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/dto/project/ProjectFileUploadDto.java
> +public class ProjectFileUploadDto {
а для чего этот класс?

2024-06-14 13:52 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/model/Project.java
> +
Поправил

2024-06-14 14:00 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        project.setCoverImageId(key);
Я даж не знаю, как это сократить. И так уже сделал билдер. Ну и в с3 кладётся буквально 2 строками

2024-06-15 21:43 UTC, Sabina-Vishnya requested changes

2024-06-15 21:43 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    private static String defaultFolderResourceDelimiter = "_";
константа аппер кейс и final добавь

2024-06-15 21:43 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/dto/image/ProjectImage.java
> +                resize(VerticalImageBorders.HEIGHT_TARGET_BORDER, VerticalImageBorders.WIDTH_TARGET_BORDER);
чуть удобнее читать (лично мне)
```
case VERTICAL -> resize(
                VerticalImageBorders.HEIGHT_TARGET_BORDER,
                VerticalImageBorders.WIDTH_TARGET_BORDER);
case SQUARE -> resize(
                SquareImageBorders.HEIGHT_TARGET_BORDER,
                SquareImageBorders.WIDTH_TARGET_BORDER);
```
поэтому не обяз.править, это мелочь

2024-06-15 21:43 UTC, Sabina-Vishnya commented on src/main/resources/application.yaml
>      bucketName: projectbucket
ты проверял написанный код и смог добавить файлик?
бакета такого у нас нет, куда они сохраняются, где найти файлы?

2024-06-15 21:43 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/s3/requests/S3Request.java
> +public interface S3Request {
Зачем делать это запросом, почему не назвать бы S3Service, а реализацию назвать S3ServiceImpl и расположить их в папке service/s3.
Или просто сервис, интерфейс по желанию, но сервис у тебя может содержать уже логику загрузки и удаления файла

2024-06-15 21:43 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        //TODO: Спросить как избавиться от этих проверяемых ошибок? SneakyThrows? Из-за этого метод разросся
у тебя размазана логика, поэтому и метод большой, и класс 

тебе работу с ресурсом можно вынести в отдельный сервис, какой-нибудь ресурс сервис, который и будет содержать логику по работе с файлом.
твой сервис ресурса обращается в сервис с3, сервис 3 загружает файл и возвращает его в сервис ресурс, зачем сервис ресурс отдает ответ в контроллер, который лучше назвать ресурс контроллер и эндпоинты соответствующие сделать(переименовать)

Советую тебе пересмотреть еще раз урок по minio, Инна прям разжевывает там все и демонстрирует даже части кода, которые ты как раз таки можешь подглядеть для более удачного расположения логики всей. Разделяй код прям по зонам ответственности.

2024-06-15 21:43 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/model/Resource.java
> +    //TODO: Спросить у Сабины, почему нет миграции на эту таблицу
пиши лучше такие вопросы в дескрипшн к задаче, можешь забыть удалить, а я не заметить и тогда это вообще никому непонятно будет + такие вопросы надо спрашивать в чатах наших и общих, точно не в коде

про этот момент уточню или ты все таки уточнил уже сам?)

2024-06-16 21:58 UTC, RickHammerson commented
> также к замечаниям вопрос, почему модификаторы протектет? разве не достаточно геттеров/сеттеров или ты что-то хотел сделать таким образом? мб я не поняла, будет круто, если расскажешь)

Потому что в наследнике хочу использовать эти поля
![image](https://github.com/CorporationX/project_service/assets/42961541/4e83d6d9-e8a2-461f-aadf-50e92e30518c)

2024-06-16 22:01 UTC, RickHammerson commented on src/main/resources/application.yaml
>      bucketName: projectbucket
Да,код проверял, лично ручками добавлял бакет в s3. Также в коде сделал проверку на наличие такого бакета 
Тоже смутило название бакета, но оно изначально было в apllication.yaml такое. Так что решил сделать проверку и кидать исключение
![image](https://github.com/CorporationX/project_service/assets/42961541/9ac599d1-6448-4d8c-a0ff-d987872dd96b)

2024-06-16 22:08 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/s3/requests/S3Request.java
> +public interface S3Request {
Решил разделить логику создания запросов на вставку вещей в S3
Для каждого ресурса будет своя логика, как они будут обрабатываться
То есть как называется папка, какой ключ будет к ресурсу, какая метадата будет присутствовать

А уже в S3Service классе я кладу вообще любой запрос, созданный на этапе ранее для любого ресурса

![image](https://github.com/CorporationX/project_service/assets/42961541/bb424038-0055-42ff-9e91-1490c8357a34)

![image](https://github.com/CorporationX/project_service/assets/42961541/be12748e-627a-4c39-8e36-d340e963b4fe)

2024-06-16 22:09 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/model/Resource.java
> +    //TODO: Спросить у Сабины, почему нет миграции на эту таблицу
Не, насчет этого я вообще не нашел ничего

2024-06-16 22:44 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        //TODO: Спросить как избавиться от этих проверяемых ошибок? SneakyThrows? Из-за этого метод разросся
Прикол в том, что у неё получился компактный метод, потому что нет доп проверок, заполнения сущности данными, сжатия обложки до размера и т.д
Попробовал сократить

2024-06-17 21:14 UTC, Sabina-Vishnya commented on src/main/resources/application.yaml
>      bucketName: projectbucket
Вероятно кто-то грохнул файл или случайно указал такой бакет, а может специально, кто знает -_-
Нам главное, чтобы работало всё. То что добавил бакет ручками, проверил - отлично, а как остальным проверять то? Догадаться о том, что надо руками тоже добавить, ведь в данной реализации бакет не создается автоматом и вылезет та самая ошибка твоя, которая такой бакет не найдет. 
Мы то предполагаем, что всё работает, но придется в итоге разбираться с тем, что бакет нужный надо создать, да и еще руками. Либо поднять другой сервис помимо инфры? Ты кстати как-то в личку про это писал, не совсем понятно было, о чем речь. 

В общем, варианты:  
1). писать о том, что надо создать руками итд (типа НФТ некое настроить перед поднятием контейнеров) - это лучше, чем ничего, но фиговый, в данном случае, вариант, ведь ты сдаешь готовую задачу и предполагается, что влитый код/настройки и тд, работают и это может любой проверить, в том числе и кто-то из собесов. 
2). создавать бакет при поднятии контейнера, аналогично как это делает инфра или юзер сервис сейчас - это предпочтительнее, так как мы хотим делать минимум усилий и с помощью одной кнопочки, чтобы всё работало. Поставь себя на место коллеги и представь, как он должен был догадаться об этом и сколько времени потратил бы на такую мелочь.
3). использовать бакет, который уже есть, тоже рабочий вариант.
4). уточнять в общих чатах, вероятно это бага, которая влетела ко всем, а может и нет, но если сомнения у тебя уже сразу появились и тебе пришлось руками создавать бакет, очевидно, что-то пошло не так, ты это увидел и мог бы попробовать уточнить.

2024-06-18 20:28 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/model/Resource.java
> +    //TODO: Спросить у Сабины, почему нет миграции на эту таблицу
Так а чего не удалил в итоге? акое стоит озвучивать, не ждать, пока код глянут, где это супер не ожидается. Чаты/личка/дейлики. По похожей проблемы ты писал, но сам в итоге разобрался. Не скажу щас точно, к текущей ли таске относилась проблема или нет, но тут ты почему-о  закомментил и не удалил).
Важно, что код на ревью +- неделя с лишним, все это время ты ждешь, когда увидит комменты, но проблема еще в том, что будь это более жирные изменения, это бы затронуло возможно твой текущий код с логикой всей, и выходит всю прошедшую неделю с готовым кодом, прождал бы, чтобы переделать.  Плюс я только сейчас увидела, случайно, еще один коммент о том, что надо уточнить у меня. Таким комментам не место в коде. Удаляй. По миграции чекну. Пока давай с этим решением разберемся.

2024-06-18 20:35 UTC, Sabina-Vishnya commented
такс, много вопросов
часть замечаний не поправил
рефачить начни с проджект сервиса, как минимум выносить логику начни оттуда, у тебя ведь проджект сервис сейчас с ресурсами частично работает, обращается к бинам, которые для ресурса, где-то возвращает ресурс и тд
в итоге, слишком большой сервис получается, тестами покрывать сложно будет и разобраться в последствии тоже, причем и тебе самому. А если для проекта добавится еще логика с какими-то интеграциями, класс еще жирнее будет. Не усложняй ты сразу логику, пытаясь паттерны применить, упрости сначала самый напичканный логикой класс

2024-06-18 20:40 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/s3/requests/S3Request.java
> +public interface S3Request {
хорошо, что подумал про это!
getDefaultFolderDelimiter не используется кажется нигде
а если дто на входе другая нужна будет для другой реализации или не нужно удаление...
"а если" может быть много
сейчас тут немного кода, но есть проджект сервис, которому как раз таки требуется рефакторинг, в отличии от этой одной реализации

2024-06-19 00:17 UTC, RickHammerson commented on src/main/resources/application.yaml
>      bucketName: projectbucket
Там для каждого проекта свой бакет, оказывается. И это было давно установлено. Скинул в found_bugs
https://discord.com/channels/1102662981743030334/1113762895323467816/1252778793165131898

Исправил на corpbucket в Project Service

2024-06-19 01:00 UTC, RickHammerson commented
Исправил недочеты
Сделал рефактор кода в ProjectService
Сменил в application.yaml бакет на созданный в инфре
Удалил ненужное поле в resource Jpa

2024-06-20 00:18 UTC, Sabina-Vishnya requested changes
немного ещеееее) и пройдись плз по замечаниям, либо не заметил все, либо не стал править просто и не забудь про обновление ветки
чуть-чуть осталось

2024-06-20 00:18 UTC, Sabina-Vishnya commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +#     TODO: Уточнить у Сабины, может сломать миграции у остальных
тут не удалил, уже писала про комменты такие, их озвучивать нужно, не держать в коде)
настроил на папку, видимо сделал, чтобы каждый раз руками не добавлять или для чего, если сомневаешься?
если не нужно особо контроля, тут пойдет (по идее не должно сломаться, но стоит отладить), поскольку не все файлы были включены, а по отдельности ты можешь явнее управлять и порядком, так что это надо проверять, тк сейчас ты все включаешь и порядок (вроде по алфавиту будет), а возможно что-то надо исключать и порядок гарантировать другой, поэтому подход стоит выбирать исходя из того, что нужно и проверять такие изменения. Вообще у includeAll могут быть приколы, советую чуть подробнее почитать об этом, тк такое казалось бы небольшое изменение иногда может привнести проблем. Ну и в доку заглянуть полезно:
https://docs.liquibase.com/change-types/includeall.html#:~:text=Use%20the%20includeAll%20tag%20to,SQL%20files%20as%20individual%20changes.

2024-06-20 00:18 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/model/Resource.java
> -    @ElementCollection(targetClass = TeamRole.class)
вот я бы не удаляла все же поле, а пока туду вписала бы, а то совсем потеряем. Ты закомментил с туду и это норм, просто коммент твой был не в тему в плане описания. Такие штуки если и есть в коде, то конкретную проблему описывают и могут ссылку на задачу содержать даже, а коммент из серии "уточнить у кого-то, почему так, почему не работает", не подходит - более четкое описание просто лучше. Типа не работает с этим полем, потому что...итд, и требуется доработка - что-то наподобие этого. У тебя же ошибка по идее возникает еще, и вот можно написать проблему на которую ты нарвался, чтобы другой увидев коммент понял, что тут не так. Вдруг кто-то это починил/починит и так хотя бы будет видно баг

2024-06-20 00:18 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public ResourceDto uploadCover(Long projectId, Long teamMemberId, MultipartFile file){
предлагала тебе разрефачить с выносом методов (писала про бины которые относятся к ресурсу)

2024-06-24 18:56 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/service/s3/requests/S3Request.java
> +public interface S3Request {
Отрефакторил

2024-06-24 19:08 UTC, RickHammerson commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +#     TODO: Уточнить у Сабины, может сломать миграции у остальных
Убрал

2024-06-24 21:03 UTC, RickHammerson commented
Исправил замечания. Вынес работу с ресурсами в Resource Service

2024-06-24 21:26 UTC, Sabina-Vishnya reviewed
лучше уже, только мелкие замечания поправь (внимательнее плз, я уже несколько раз одно и тоже пишу про проджект сервис!) и го писать тесты уже, след. коммит вместе с тестами по идее уже последний должен быть

2024-06-24 21:26 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/model/Resource.java
>      @ElementCollection(targetClass = TeamRole.class)
до этого ты вроде закомментил вместе с атрибутом (видимо, чтобы работало всё?), щас значит без коммента не будет работать или будет? зачем тогда только туду, если до этого поле было закомменчено? я теперь не понимаю)
замечание лишь было к тексту в туду ведь)

2024-06-24 21:26 UTC, Sabina-Vishnya commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public ResourceDto uploadCover(Long projectId, Long teamMemberId, MultipartFile file){
так методы ты в итоге не вынес все, которые с ресурсу относятся....

2024-06-26 12:38 UTC, RickHammerson commented on src/main/java/faang/school/projectservice/model/Resource.java
>      @ElementCollection(targetClass = TeamRole.class)
Сейчас почему-то сохраняется

2024-06-26 12:38 UTC, RickHammerson commented
Исправил замечания, как понял их
Пока тесты не делаю, т.к много задач в работе, отстаю от графика

2024-06-27 07:40 UTC, Sabina-Vishnya reviewed
Лучше! Ты молодец, есть еще что править, ну можно будет задачу завести (или в этом продолжать)

Непонятно, почему еще классов создавать решил, достаточно было унести все что к ресурсу, в ресурс сервис для начала, а там уже и дальше порефачить. Ну то что захотел разбить логику, это здорово, только ты названия осмысленнее давай классам и методам (в целом, не только к новым классам отновится). И ты сделал абстракцию, хорошо, а классы у тебя в итоге почти идентичные для ProjectCoverResource и ProjectFileResource, да они друг за другом идут, идея понятна, но дублирования привнес, а это не очень хорошо

почему-то только переименование на S3RequestService, при это названия можно было бы точнее и для методов

в общем, тесты тебе тут в любом случае нужны
много логики накручено везде и... названия, думай прям лучше над неймингом, смотри в джава классы и спринговые, чтобы +- прикидывать, как можно назвать тот или иной класс, чтобы было очевиднее, что в коде делается
в новых классах ты наследуешь от конвертора абстрактного, классы, а эти классы какие делают операции? За что отвечают, мапят, экстрактят, билдят, как ты понимаешь смысл этих классов и методов-суть? -  поточнее просто формулировки, это сильно упрощает чтение кода 
и, там где много классов и логики, можно джава доки влепить, несмотря на то, что в идеале код должен быть понятен и без доков (к такому коду все стремимся=)), но джава доки иногда нам упрощают жизнь, особенно коллегам твоим и тебе потом)

2024-06-27 21:04 UTC, RickHammerson commented
> И ты сделал абстракцию, хорошо, а классы у тебя в итоге почти идентичные для ProjectCoverResource и ProjectFileResource, да они друг за другом идут, идея понятна, но дублирования привнес, а это не очень хорошо
Угу, но я чет не могу представить, как это убрать
Там, по сути, главный метод билдера, который строит ответ, но никак не могу придумать, как вставить туда поля из того, что будет обрабатывать до него. Допустим, для обложки мне надо сначала её создать, а потом её данными наполнить ответ
Думал насчет функциональных интерфейсов, но чёт ничего годного в голову не пришло. Можешь дать подсказку?

2024-06-27 21:13 UTC, RickHammerson commented
Переименовал классы и методы, добавил JavaDocи

Можно, всё таки, не писать тесты? Ещё 3 задачки в работе

2024-06-28 12:42 UTC, Sabina-Vishnya commented
@RickHammerson понимаю, но без тестов плохо сдавать) тестами надо покрывать, особенно достаточно сложную логику, как тут, с множеством операций, где потенциально багов словить очень просто. Давай повесишь туду тут и заведешь себе на тесты задачу, а эту ветку вольешь без тестов тогда? Мы тесты все равно пишем и просто скипнуть их из-за того, что есть еще задачи, такое себе, во многих проектах это может сыграть злую шутку, так что не стоит тестами пренебрегать и привыкать к тому, что их писать не стоит. 
Лайк влеплю, задачу заводи, ставь туду (если нету, для тестов) и вливай

2024-06-28 12:42 UTC, Sabina-Vishnya approved these changes

2024-06-29 03:47 UTC, merged