BJS2-15587 - CI pipeline для project_service
CorporationX/project_service pull request #466
Opened 2024-07-08 23:02 UTC by ravshanbekn

+ added ci.yml file

2024-07-17 13:12 UTC, pablo023 requested changes
Ты запускаешь только тесты, при этом сам проект может не собраться из-за какой-то ошибки. Более типичным шагом в CI для проверки корректности всего, является gradle build. Он включает в себя тесты, и общую проверку сборки проекта.

2024-07-18 17:08 UTC, ravshanbekn commented
Исправил

2024-07-20 04:10 UTC, pablo023 approved these changes
lgtm

2024-07-20 04:10 UTC, pablo023 commented on .github/workflows/ci.yml
> +        run: ./gradlew test --no-daemon
Вот эта работа содержится в gradle build. Но лан.

2024-07-20 04:10 UTC, merged