Моменты
CorporationX/project_service pull request #468
Opened 2024-07-10 17:55 UTC by kpzxpf

2024-07-10 18:43 UTC, Caveri95 commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +    public void updateMoment(@NotNull MomentDto momentDto) {
Здесь тоже желательно повесить Valid, тогда NotNull можно убрать и все ограничения в классе ДТО прописать

2024-07-10 20:00 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +    public void updateMoment(@NotNull MomentDto momentDto) {
Хорошо, спасибо

2024-07-11 15:46 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                .flatMap(filter -> filter.apply(moments, momentFilterDto))
Эта часть работает? Мне кажется, ты для каждого пункта берешь подходящие моменты и засовываешь их в результативный List, а надо чтобы в результативном List были моменты удовлетворяющие всем пунктам  MomentFiilterDto

2024-07-11 16:09 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        if (!differentElements.isEmpty()) {
А если тут убрать if , что-то поменяется?

2024-07-11 16:15 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/filter/MomentAfterDateFilter.java
> +                .filter(moment -> moment.getDate().isAfter(momentFilterDto.getAfterDateFilter()));
Мне кажется лучше тут брать stream в параметрах.
Тебе же нужно фильтровать поэтапно, то есть сначала оставить все подходящие на первой фильтрации, затем на второй фильтрации делать filter из оставшихся от первого фильтра, а не от изначального.
Если не понятно можем в ПП сходить

2024-07-11 16:18 UTC, ravshanbekn reviewed
В целом, хорошо написано

2024-07-11 17:12 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                .flatMap(filter -> filter.apply(moments, momentFilterDto))
Ты прав, изменил

2024-07-11 17:16 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        if (!differentElements.isEmpty()) {
Нет, просто мне кажется, что лучше обработать такой случай, чтобы не вызывался другой метод

2024-07-11 17:16 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/filter/MomentAfterDateFilter.java
> +                .filter(moment -> moment.getDate().isAfter(momentFilterDto.getAfterDateFilter()));
Я понял, спасибо

2024-07-11 17:32 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        if (!differentElements.isEmpty()) {
Мне кажется, если там пусто, то forEach нечего отрабатывать

2024-07-20 04:09 UTC, pablo023 requested changes
Есть что исправить

2024-07-20 04:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/validator/MomentServiceValidator.java
> +        }
validateMomentDoesExist. В ином случае, название метода говорит будто бы о том, что ты валидируешь создание момента.

2024-07-20 04:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    private void addMembersIDsToTheMoment(MomentDto momentDto, List<Project> projects) {
ToAMoment тогда уж. Но вообще по стилю обычно артикли эти отрбасываются, поэтому скорее будешь видеть addMembersIDsToMoment

2024-07-20 04:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/dto/moment/MomentDto.java
Я бы сюда поимо имени, добавил бы строчку описание. У тебя ведь момент сущность содержит её

2024-07-20 04:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                                        tempMembers.add(teamMember.getId());
Чтобы не писать это, ты мог бы tempMembers сделать сетом. Быстрее, чище, без этой проверки получилось бы.

2024-07-20 04:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    private void addMembersIDsToTheMoment(MomentDto momentDto, List<Project> projects) {
В целом грязненький метод, и не особо нужный. У нас есть TeamMemberRepository, который по айдишнику команды может вытащить всех участников, и это будет одной строчкой. Давай переделаем.

2024-07-20 04:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    private void checkAndAddProjectsByNewMember(Moment moment, MomentDto momentDto) {
Ты нарушаешь Single responsibility принцип из солида этим методом. Вообще, каждый раз, когда пишешь And в названии метода - это уже сигнал, что ты нарушаешь этот принцип. Надо переделать.

2024-07-20 04:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    private void checkAndAddProjectsByNewMember(Moment moment, MomentDto momentDto) {
Этот метод не должен быть войдом. Пусть принимает момент и дто, и возврашает новый момент, который не перетрет предыдущий.

2024-07-20 04:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    }
Аналогично, это не по SOLID. Вот так я это вижу:

    public List<Long> findDifferentProjectIds(Moment moment, List<Long> newProjectIds) {
        List<Long> existingProjectIds = moment.getProjects().stream()
            .map(Project::getId)
            .toList();
        newProjectIds.removeAll(existingProjectIds);
        return newProjectIds;
    }

    public List<Long> getProjectMemberIds(List<Long> projectIds) {
        return projectIds.stream()
            .map(projectRepository::getProjectById)
            .toList();
    }
}

2024-07-20 04:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/validator/MomentServiceValidator.java
> +    }
В отдельный метод.

2024-07-20 10:31 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/validator/MomentServiceValidator.java
> +        }
понял

2024-07-20 10:31 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    private void addMembersIDsToTheMoment(MomentDto momentDto, List<Project> projects) {
хорошо

2024-07-20 10:32 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/dto/moment/MomentDto.java
добавил

2024-07-20 10:32 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                                        tempMembers.add(teamMember.getId());
ок

2024-07-20 10:41 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    private void addMembersIDsToTheMoment(MomentDto momentDto, List<Project> projects) {
Не понимаю, зачем использовать репозиторий TeamMemberRepository, если я также могу получить всех участников из команды
private List<Long> getNewMemberIds(List<Project> projects) {
        Set<Long> memberIds = new HashSet<>();
        projects.forEach(project -> project.getTeams()
                .forEach(team -> team.getTeamMembers()
                        .forEach(member -> memberIds.add(member.getId()))));

        return new ArrayList<>(memberIds);
    }
private List<Long> getNewMemberIds(List<Project> projects) {
        Set<Long> memberIds = new HashSet<>();
        projects.forEach(project -> project.getTeams()
                .forEach(team -> teamMemberRepository.findByTeamId(team.getId())
                        .forEach(member -> memberIds.add(member.getId()))));

        return new ArrayList<>(memberIds);
    }

2024-07-20 10:42 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    private void checkAndAddProjectsByNewMember(Moment moment, MomentDto momentDto) {
понял

2024-07-20 10:42 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    private void checkAndAddProjectsByNewMember(Moment moment, MomentDto momentDto) {
ок

2024-07-20 10:42 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    }
понял

2024-07-20 10:42 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/validator/MomentServiceValidator.java
> +    }
ок

2024-07-25 02:28 UTC, pablo023 requested changes

2024-07-25 02:28 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                .map(projectRepository::getProjectById)
У тебя вот тут вот в цикле будет дергаться projectRepository столько раз, сколько у тебя проектов в моменте. В целом по бизнес-логике вряд-ли предусмотрено такое, что он может дернуться тысячи раз, но тем не менее, я хочу тебе объяснить, что так делать не стоит. Если ты пишешь операцию таким образом, то у тебя подразумевается, что на каждой for each итерации, ты что-то тянуть будешь из базы. В контексте высоконагруженного приложения, которым пользуются сотни тысяч, миллионы, десятки миллионы пользователей - такая операция недопустима, т.к. ты будешь просаживать производительность базы, дергая вот так вот её по разочку для каждой сущности. У тебя есть метод  
в репозитории findAll() - он позволяет один раз сходить, и вытащить всё, что нужно, и для этого он как раз и есть - чтобы не дёргать базу постоянно кучу раз.

2024-07-25 02:28 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        momentDto.setUserIds(getNewMemberIds(projects));
Нам вот это точно надо вообще? По-моему, нет.

2024-07-25 02:28 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        updateUserIdsInMoment(moment, momentDto);
Это - антипаттерн. Ты никогда не должен писать код таким образом, чтобы у тебя терялось исходное состояние. Вот эти два метода навсегда изменят в рамках метода оригинальный момент, который ты на 45 строке вытащил из репозитория. Ты всегда должен писать код таким образом, чтобы оригинальные данные не затирались в памяти. Эти два метода, если они тебе реально нужны (я в этом не уверен), должны возвращать какое-то значение, например - момент, с обновленными проектами, или айдишниками. Должно быть возвращаемое значение.

2024-07-25 02:28 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    public List<MomentDto> getAllMoments(MomentFilterDto momentFilterDto) {
getFilteredMoments*

2024-07-25 02:30 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    private void addMembersIDsToTheMoment(MomentDto momentDto, List<Project> projects) {
Чтобы лишний код не писать, и на вход список проектов не передавать. Из момента вытащил айдишники проектов, из TeamMemberRepository по ним вытащил участников и все. Попроще выглядит.

2024-07-25 10:38 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    public List<MomentDto> getAllMoments(MomentFilterDto momentFilterDto) {
поправил

2024-07-25 10:42 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                .map(projectRepository::getProjectById)
понял

2024-07-25 10:46 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        momentDto.setUserIds(getNewMemberIds(projects));
Посмотрел по заданию, не нужно в этом методе ничего изменять, убрал

2024-07-25 11:20 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        updateUserIdsInMoment(moment, momentDto);
Я правильно понял, что если я изменяю что-то в моменте, который достал из репозитория, я должен делать это в этом же методе?

2024-08-02 21:49 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        updateUserIdsInMoment(moment, momentDto);
Да, но они должны иметь возвращаемое значение

2024-08-02 21:57 UTC, pablo023 requested changes

2024-08-02 21:57 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        return momentMapper.toDto(moment);
Так нельзя писать код, Никит. Куча ответветсвености в одном методе, и нечитаемо. Я это вижу так:

    public MomentDto updateMoment(MomentDto momentDto) {
        Moment moment = findMomentById(momentDto.getId());
        Moment updatedMomentWithProjects = updateProjects(moment, momentDto.getProjectsIds());
        Moment updatedMomentWithUsers = updateUserIds(updatedMomentWithProjects, momentDto.getUserIds());
        Moment finalUpdatedMoment = updateDescription(updatedMomentWithUsers, momentDto.getDescription());
        momentRepository.save(finalUpdatedMoment);
        return momentMapper.toDto(finalUpdatedMoment);
    }

    private Moment findMomentById(Long id) {
        return momentRepository.findById(id)
                .orElseThrow(() -> new DataValidationException("Moment not found"));
    }

    private Moment updateProjects(Moment moment, List<Long> newProjectIds) {
        List<Project> differentProjects = projectService.findDifferentProjects(moment.getProjects(), newProjectIds);
        List<Long> updatedUserIds = new ArrayList<>(moment.getUserIds());
        if (!differentProjects.isEmpty()) {
            updatedUserIds.addAll(userService.getNewMemberIds(differentProjects));
        }
        return new Moment(moment.getId(), moment.getDescription(), moment.getProjects(), updatedUserIds);
    }

    private Moment updateUserIds(Moment moment, List<Long> newUserIds) {
        List<Long> differentMemberIds = userService.findDifferentMemberIds(moment.getUserIds(), newUserIds);
        List<Project> updatedProjects = new ArrayList<>(moment.getProjects());
        if (!differentMemberIds.isEmpty()) {
            updatedProjects.addAll(projectService.getNewProjects(differentMemberIds));
        }
        return new Moment(moment.getId(), moment.getDescription(), updatedProjects, moment.getUserIds());
    }

    private Moment updateDescription(Moment moment, String newDescription) {
        if (!moment.getDescription().equals(newDescription)) {
            return new Moment(moment.getId(), newDescription, moment.getProjects(), moment.getUserIds());
        }
        return moment;
    }

Это легко читать, понимать, что тут происходит, и расширять. На данный момент, тяжео читать это и разбираться. Я декомпозировал этот метод по первому принципу SOLID. Посмотри, и переделай, пожалуйста.

2024-08-02 21:57 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        return momentMapper.toDto(moment);
И также не забудь, что мы лезем в базу, и что-то там меняем. Это должно происходить в рамках транзакции.

2024-08-03 19:48 UTC, kpzxpf commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        return momentMapper.toDto(moment);
понял

2024-08-03 22:31 UTC, pablo023 approved these changes

2024-08-03 22:32 UTC, merged