Feature bjs2 15580
CorporationX/project_service pull request #491
Opened 2024-07-14 17:33 UTC by GevorgSogomonian

Created StageController
Created StageDto and StageFilterDto
Created StageFilter interface and implementation StageStatusFilter
Created StageService
Created StageDtoValidator and StageIdValidator

Created unit tests on StageDtoValidator, StageIdValidator and StageService

2024-08-03 23:18 UTC, pablo023 requested changes
Там с апдейтом прям чет совсем не то у тебя. Нет даже данных, которые приходят от клиента, которыми что-то обновляется.

2024-08-03 23:18 UTC, pablo023 commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +    public List<StageDto> getStages(@PathVariable Long projectId, @RequestBody StageFilterDto filter) {
getStagesByFilter

2024-08-03 23:18 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +            tasks.forEach(task -> taskRepository.deleteById(task.getId()));
Не нужно в цикле никогда обращаться к базе. Если тебе нужно выполнить операцию над множеством записей в бд - сделай это разом.

2024-08-03 23:18 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    }
Это то ли ремув, то ли апдейт, то ли реплейс. Я не понимаю, почему так. Логика метода на удаление не предполагает замену какую-то.

2024-08-03 23:18 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    private void searchAndSend(int rolesDeficit, Set<Long> gotStageInvitation, Stage stage, TeamRole teamRole) {
Что ищется и что отправляется?

2024-08-03 23:18 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +        int sended = 0;
sent*

2024-08-03 23:18 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +                .build());
Почему бы нам просто не создать дефолтный конструктор StageInvitation для такого вот приглашения? Тут же куча кода бесполезного, а можно было бы одной строчкой всё сделать.

2024-08-03 23:18 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    public void updateStage(Long stageId) {
А где обновление происходит? У нас через дто должно прийти то, что нам надо обновить, а тут нет никакого обновления - извне ничего не приходит даже.

2024-08-03 23:18 UTC, pablo023 commented on src/test/java/faang/school/projectservice/service/stage/StageServiceTest.java
Тесты красиво пишешь, очень гуд

2024-08-04 07:53 UTC, GevorgSogomonian commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +    public List<StageDto> getStages(@PathVariable Long projectId, @RequestBody StageFilterDto filter) {
Исправил

2024-08-04 08:04 UTC, GevorgSogomonian commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    }
<img width="681" alt="Снимок экрана 2024-08-04 в 10 54 16" src="https://github.com/user-attachments/assets/bf71a358-fa20-4e03-8c7c-95df9e4df174">
Я сделал два перегруженных метода удаления: 

1. если пользователь хочет удаляя этап удалить или закрыть все задачи связанные с данным этапом, то он присылает нам id необходимого этапа и действие, которое хочет, чтобы мы сделали с его тасками

2. если пользователь хочет удаляя этап перенести все его таски в другой этап, то он присылает нам id своего этапа и id этапа куда мы переносим все его таски(replaceStageId)

Поэтому во втором методе мы обновляем этап, в который пользователь хочет перекинуть таски(сначала считываем этап из бд, добавляем таски а потом сохраняем изменённую версию в бд)

2024-08-04 08:16 UTC, GevorgSogomonian commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    private void searchAndSend(int rolesDeficit, Set<Long> gotStageInvitation, Stage stage, TeamRole teamRole) {
это приватный метод, сделал его чтобы не писать огромный updateStage, он ищет всех пользователей в рамках данного проекта, у которых есть нужная роль и отправляет им приглашения к нашему этапу

2024-08-04 08:17 UTC, GevorgSogomonian commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +        int sended = 0;
Исправил

2024-08-04 08:24 UTC, GevorgSogomonian commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    public void updateStage(Long stageId) {
<img width="723" alt="Снимок экрана 2024-08-04 в 11 18 09" src="https://github.com/user-attachments/assets/db4f8f31-41c2-4b0c-8f2a-bfc2de7f2fa4">
Этот метод обновляет этап учитывая роли которые прописаны в требованиях к данному этапу. Мы проверяем что все необходимые для данного этапа роли присутствуют в нужном количестве (в избытке тоже хорошо, главное чтобы не меньше необходимого), и если какой-то роли не хватает - ищем обладателей такой роли по всему проекту и создаём соответстующий stageInvitation

2024-08-04 08:40 UTC, GevorgSogomonian commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +                .build());
Исправил

2024-08-04 08:50 UTC, GevorgSogomonian commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +            tasks.forEach(task -> taskRepository.deleteById(task.getId()));
Исправил

2024-08-07 13:14 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    private void searchAndSend(int rolesDeficit, Set<Long> gotStageInvitation, Stage stage, TeamRole teamRole) {
Почему название метода никаким образом не указывает на это?

2024-08-07 13:19 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    public void updateStage(Long stageId) {
Хорошо, а если на этапе потребовалась новая роль, как мы об этом сообщим? У нас есть этап, на который нам нужен один разработчик, и один тестироващик. Завтра выясняем, что нужен еще и дизайнер. И как мы произведем обновление это, как мы обозначим, что в проекте нужен дизайнер?

2024-08-07 13:22 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    }
Эта логика понятна только тебе, на это нужно указывать через соотвествующие нейминги. removeStageAndReplaceTasks снимает все вопросы.

2024-08-14 04:30 UTC, GevorgSogomonian commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    }
Исправил

2024-08-14 04:39 UTC, GevorgSogomonian commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    private void searchAndSend(int rolesDeficit, Set<Long> gotStageInvitation, Stage stage, TeamRole teamRole) {
Исправил

2024-08-31 10:43 UTC, GevorgSogomonian commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    public void updateStage(Long stageId) {
Добавил StageRolesService, который отвечает за изменение требуемых ролей на stage. Таким образом если произойдет изменение требуемого состава, система автоматически вызовет метод updateStage() и разошлет все необходимые инвайты. Так же в StageRolesService есть метод getAllRolesDeficit с помощью которого пользователь может получить список всех недостающих исполнителей по всем ролям сразу.

2024-08-31 11:13 UTC, merged