BJS2-15577: Вакансии
CorporationX/project_service pull request #498
Opened 2024-07-15 09:46 UTC by YPG0

1. Метод для создания вакансии.
2. Метод для обновления вакансии.
3. Метод для удаления вакансии.
4. Метод для получения всех вакансий с фильтрами по позиции и названию.
5. Метод для получения конкретную вакансию по id.
6. Тесты

2024-07-25 03:11 UTC, pablo023 commented
Тут потно. Завтра дам ревью тут

2024-08-02 23:39 UTC, pablo023 requested changes

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +    }
Это не совсем правильно. Если у тебя речь идет о кандидатах, это значит - мы говорим о каких-то пользователях. Если есть пользователи, значит они есть в базе. Если они есть в базе - значит это сущности какие-то, в которых есть много всякой инфы, в духе имя / email, и тд. А тут мы просто создаём объекты, которым айдишник сеттим. Это же неправильно. Нам нужны именно пользователи из базы, которым эти айдишники принадлежат, т.е. тащить из базы пользователей по айди, а не просто создавать какие-то объекты. 

Почему это вообще плохо - потому что например придет список айдишников 1 2 3 4 5. Мы создадим вот тут мапом список из них кандидатов, а потом где-то его по логике будем использовать, что-то например обновлять - роль кандидатов, или что-то в таком духе. А потом сохранять в базу. И получается при таком подходе, мы пользователя с айди 1, у которого есть в базе имя, фамилия, мейл, телефон, и тд - просто перетрем вот таким объектом, в котором кроме айди - ничего нет от оригинального.

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/repository/TeamMemberRepository.java
> +    }
так и что тут?

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    public void createVacancy(@Valid Vacancy vacancy,@NonNull Integer count) {
Почему у нас тут приходит сущность, а не дто?

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        }
В отдельный класс валидатор.

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        vacancy.setCount(count);
У тебя в дто есть count, его тут и надо использовать.

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        vacancyRepository.save(vacancy);
Уверен, что нам тут не нужна транзакционность?

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    private final VacancyServiceValidator validator;
какой валидатор? У нас валидаторов в проекте может быть много. Не validator, а vacanyServiceValidator.

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/validator/VacancyServiceValidator.java
> +    public void createVacancyValidator(List<TeamRole> teamRoleOwner) {
Этот метод валидирует наличие роли OWNER, и называться он должен в соответствии с этим.

ensureOwnerRolePresent / validateOwnerRolePresent

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        validator.createVacancyValidator(teamRoleOwner);
В этом не так чтобы прям много смысла, т.к. ты по ownerId формируешь этот список TeamRole на 38 строке. Если у тебя есть ownerId, не подразумевает ли это само собой наличие кого-то с ролью Owner?

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
Не то чтобы много смысла в том, чтобы одну строку завернуть в абстракцию так. Но если и делать - с понятным именем метода. Вот это getVacancy - это как геттер какой-то, и сбивает с толку.

findVacancyByIdOrThrow

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/validator/VacancyServiceValidator.java
> +    }
Название этого метода ну вот никак не отображает суть. Что там валиируется? Я не понимаю, мне нужно сюда будет идти и смотреть, а так быть не должно.

validateCandidateCountForVacancy

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        validator.updateVacancyValidator(vacancy);
Вот эта штука кинет эксепшен, если прямо сейчас кандидатов недостаточно. И зачем нам это? Мы хотим допустим поменять название вакансии, или описание. Мы через эту строчку не пройдем никогда, т.к. у нас либо не хватает, либо слишком много кандидатов. А как обновлять то в таком случае какие-то данные о вакансии?

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        vacancyRepository.save(vacancy);
Эта логика предназначена для закрытия вакансии. А мы может не хотим её закрывать, а просто обновить?

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        validator.createVacancyValidator(teamRoleOwner);
Метод лезет в базу, и что-то делает там. Транзакционность нам тут не нужна?

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +                .forEach(teamMemberRepository::deleteTeamMember);
Вот тут будет 100 кандидатов, и что мы 100 раз установим подключение к базе, и удалять по одному человеку будем? Нам нужно минимизировать подключения к базе данных, чтобы не нагружать её лишний раз

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        Stream<Vacancy> vacancies = vacancyRepository.findAll().stream();
То есть у нас может быть в репозитории несколько миллионов вакансий, и мы вот это всё раз - и вытащим вот этой строкой в память? И несколько тысяч пользователей если захотят посмотреть вакансии по названию, они вот это вот все разом сделают, и наше приложение не рассыпется?)

2024-08-02 23:39 UTC, pablo023 commented on src/main/java/faang/school/projectservice/validator/VacancyControllerValidator.java
> +        }
Это можно сделать аннотацией Positive над полем id. Не то чтобы вот это вот - плохо, но имей ввиду.

2024-08-02 23:39 UTC, pablo023 commented on src/test/java/faang/school/projectservice/vacancy/ControllerTest.java
> +    @DisplayName("В метод получения вакансии передан id 0 или меньше")
У тебя на 67 строчке точно такой же метод, судя по DisplayName

2024-08-27 04:37 UTC, YPG0 commented on src/main/java/faang/school/projectservice/repository/TeamMemberRepository.java
> +    }
Поправил

2024-08-27 04:37 UTC, YPG0 commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    public void createVacancy(@Valid Vacancy vacancy,@NonNull Integer count) {
+

2024-08-27 04:37 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        }
+

2024-08-27 04:37 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        vacancy.setCount(count);
+

2024-08-27 04:37 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        vacancyRepository.save(vacancy);
Тогда еще не знал о ней

2024-08-27 04:37 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    private final VacancyServiceValidator validator;
+

2024-08-27 04:37 UTC, YPG0 commented on src/main/java/faang/school/projectservice/validator/VacancyServiceValidator.java
> +    public void createVacancyValidator(List<TeamRole> teamRoleOwner) {
+

2024-08-27 04:37 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        validator.createVacancyValidator(teamRoleOwner);
+

2024-08-27 04:38 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
+

2024-08-27 04:38 UTC, YPG0 commented on src/main/java/faang/school/projectservice/validator/VacancyServiceValidator.java
> +    }
+

2024-08-27 04:38 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        validator.updateVacancyValidator(vacancy);
+

2024-08-27 04:38 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        vacancyRepository.save(vacancy);
Тут просто описание задачи сбило. Там идет "Обновить вакансию. Закрыть вакансию можно только в случае..." и дальше про закрытие я и подумал что нужно именно ее закрыть.

2024-08-27 04:38 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        validator.createVacancyValidator(teamRoleOwner);
+

2024-08-27 04:38 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +                .forEach(teamMemberRepository::deleteTeamMember);
Собираю Id в лист и сразу передаю пачку на удаления

2024-08-27 04:38 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        Stream<Vacancy> vacancies = vacancyRepository.findAll().stream();
Передаю на сторону базы данные по которым будет фильтрация и получаю уже готовый отфильтрованный список.

2024-08-27 04:38 UTC, YPG0 commented on src/main/java/faang/school/projectservice/validator/VacancyControllerValidator.java
> +        }
+

2024-08-27 04:38 UTC, YPG0 commented on src/test/java/faang/school/projectservice/vacancy/ControllerTest.java
> +    @DisplayName("В метод получения вакансии передан id 0 или меньше")
+

2024-08-28 03:37 UTC, merged