Feature bjs2 15764
CorporationX/project_service pull request #522
Opened 2024-07-19 17:54 UTC by raukaztaev

2024-07-19 17:57 UTC, raukaztaev commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +//         stageInvitationService.send(stageInvitation);
Тут нужно отправить приглашение, переделаю как станет доступен StageInvitationService.

2024-07-20 07:05 UTC, cancion2able requested changes

2024-07-20 07:05 UTC, itstnslv commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +@RequestMapping("/stage")
Если придерживаться RESTFul спецификации, то можно заметно упростить восприятие API и синтаксис запросов. 
Мы обращаемся к коллекции под названием stages.
Далее все стандартные действия выполняют не определенные нами слова, а HTTP глаголы.

POST stages
GET stages
PUT stages/id
GET stages/id
DELETE stages/id
DELETE stages/id/close-tasks
(https://restapitutorial.ru/lessons/restfulresourcenaming/)

2024-07-20 07:05 UTC, itstnslv commented on src/main/java/faang/school/projectservice/dto/stage/StageDto.java
> +    @Positive
Классно придумал, я такую не нашел. Единственное, что добавлю: стоит учитывать, что дефолтное сообщение не всегда может давать исчерпывающую информацию для пользователя

2024-07-20 07:05 UTC, itstnslv commented on src/main/java/faang/school/projectservice/jpa/StageJpaRepository.java
> +    List<Stage> findByStatus(ProjectStatus status);
Посмотри, что такое JPA Query Methods. Когда в запросе нет какой-то сложной логики, можно не утруждать себя написанием SQL.

2024-07-20 07:05 UTC, itstnslv commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +        return stageMapper.toStageDto(stageRepository.save(stage));
Возможно, нам стоит подумать здесь об обработке ошибок от БД, поскольку это достаточно частая операция, которая может происходить под нагрузкой (аналог перетаскивания тасок в джире, то есть присваивание таске разных статусов)

2024-07-20 07:05 UTC, itstnslv commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    public StageDto deleteStageById(Long stageId) {
Нам стоит здесь задуматься о @Transactional при запросах к разным данным, чтобы не растерять консистентность

2024-07-20 07:05 UTC, itstnslv commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +        tasksToClose.forEach(task -> task.setStatus(TaskStatus.DONE));
Возможно, нам стоит здесь подумать о различении в логике статусов задач между DONE и CANCELLED (или, может, добавить новый статус CLOSED). Если мы удаляем этап со всеми задачами, возможно, их не стоит считать сделанными?

2024-07-20 07:05 UTC, itstnslv commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +public class StageService {
Нам стоит заложить основу иерархии в виде интерфейса для этого сервиса

2024-07-20 07:05 UTC, cancion2able commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +        List<TeamMember> currentExecutors = currentStage.getExecutors();
Можно было бы немного сократить код через forEach() и заворачивание дальнейших операций внутрь него

2024-07-20 07:05 UTC, cancion2able commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +//         stageInvitationService.send(stageInvitation);
Вот как раз сюда можно было бы применить гибкость, которую дают интерфейсы (которой мы данный момент себя лишаем и в этом сервисе). Описать интерфейс под этот сервис, замокать его поведение в тестах и в соответствии с этим написать свое решение.

2024-07-20 07:13 UTC, cancion2able commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +@RequestMapping("/stage")
Либо со вторым DELETE можно еще один вариант: DELETE stages/id?close-tasks=TRUE

Этот @RequstParam будет опциональным с значением по умолчанию false. Таким образом, мы ограничиваемся одним методом в контроллере и сервисе, а логика удаления тасок опирается на логический параметр.

2024-07-20 07:48 UTC, raukaztaev commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +@RequestMapping("/stage")
хороший вариант с @RequestParam, не приходило в голову

2024-07-20 07:57 UTC, raukaztaev commented on src/main/java/faang/school/projectservice/jpa/StageJpaRepository.java
> +    List<Stage> findByStatus(ProjectStatus status);
да, я позже увидел что уже есть готовый метод в интерфейсе, надо разобраться теперь как с ним работать

2024-07-27 19:10 UTC, egorbarzenkov commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +        Project project = projectRepository.getProjectById(stageDto.getProjectId());
обрати внимание на то, что StageService по какой то причине выполняет валидацию объекта Project, работу с объектом Project должен выполнять ProjectService, вынеси туда получение объекта и его проверку на валидность
это уберет ненужную логику из StageService и облегчит код, так же сохраниться принцип единства ответственности, состояние объекта Project будет контролировать сервис "специально обученный" для этих целей
так же обрати внимание на остальные репозитории, которые выполняют какую то работу с базой данных, их по хорошему здесь тоже быть не должно

2024-07-27 19:10 UTC, egorbarzenkov commented on src/main/java/faang/school/projectservice/mapper/stage/StageMapper.java
> +    StageDto toStageDto(Stage stage);
можно просто называть toDto и toEntity

2024-07-27 19:10 UTC, egorbarzenkov commented on src/main/java/faang/school/projectservice/mapper/stage/StageRolesMapper.java
> +    StageRoles toStageRoles(StageRolesDto stageRolesDto);
аналогично toEntity и toDto

2024-07-27 19:10 UTC, egorbarzenkov commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +        List<TeamMember> allMembers = project.getTeams().stream()
надо перепроверить, не происходит ли дополнительного подтягивания сущностей из БД при работе этого стрима, если происходит то переписать стараясь минимизировать количество запросов к БД

2024-07-27 19:10 UTC, egorbarzenkov commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +            throw new ProjectStatusException("You can't create stage for cancelled project");
персонализируй сообщение об ошибке, при разборе логов будет гораздо проще понимать из-за каких данных что то пошло не так

2024-08-08 17:03 UTC, merged