BJS2-15617
CorporationX/project_service pull request #558
Opened 2024-07-28 10:22 UTC by YPG0

1) Возможность добавление файлов
2) Возможность удалять файлы
3) Тесты

2024-08-08 22:17 UTC, pablo023 requested changes

2024-08-08 22:17 UTC, pablo023 commented on src/main/java/faang/school/projectservice/amazon/S3ClientProvider.java
По сути, у тебя здесь конфигурация бина. Такие классы обычно помещаются в пакет config, называются как-то по типу AmazonS3Config, а метод помечается аннотацией Bean, и всё - у нас в спринге есть вот этот бин, один на весь контекст, и всё окей.

2024-08-08 22:17 UTC, pablo023 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +        }
Вот это вот можно вынести в отдельный метод, который будет называться что-то в духе uploadFileToS3

2024-08-08 22:17 UTC, pablo023 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +            throw new IllegalStateException("Failed to upload file to S3");
В этот эксепшен лучше добавить деталей о том, что случилось, и где. Добавить сервис, и какую-то информацию из файла. Обычно это айдишники, но если нет айдишника, то какую-то другую инфу, чтобы было проще понять - что сломалось.

2024-08-08 22:17 UTC, pablo023 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +        String key = nameFolder + "/" + file.getName() + file.getSize() + file.getContentType();
Вот это можно в отдельный приватный метод createMetaData()

2024-08-08 22:17 UTC, pablo023 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +        resource.setName(file.getOriginalFilename());
А вот это - в приватный метод buildResource() / createResourceForFileUploading

2024-08-08 22:17 UTC, pablo023 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +        resource.setName(file.getOriginalFilename());
Кстати, проверь - не нужно ли тут сохранять этот ресурс в базу?

2024-08-08 22:17 UTC, pablo023 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +            throw new IllegalStateException("Failed to delete file from S3");
Добавь инфы - какой файл, и тд.

2024-08-08 22:17 UTC, pablo023 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +        resource.setSize(new BigInteger("0"));
А зачем это делается? Этот ресурс в памяти модифицируется (кстати, какими-то странными данными), и никуда не сохраняется. Это точно так не должно быть.

2024-08-08 22:17 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/FileServiceUpload.java
> +        resource.setUpdatedBy(teamMember);
Вот это вот можно было бы в приватный метод вынести

2024-08-08 22:17 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/FileServiceUpload.java
> +        }
Это можно вынести в отдельный класс-валидатор.

2024-08-08 22:17 UTC, pablo023 commented on src/main/java/faang/school/projectservice/validator/FileServiceValidator.java
> +    private final BigInteger PREMIUM_STORAGE_SIZE = new BigInteger("4294967296");
Вынеси это в проперти, и вытягивай аннотацией Value

2024-08-27 10:01 UTC, YPG0 commented on src/main/java/faang/school/projectservice/amazon/S3ClientProvider.java
+

2024-08-27 10:01 UTC, YPG0 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +        }
+

2024-08-27 10:01 UTC, YPG0 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +            throw new IllegalStateException("Failed to upload file to S3");
+

2024-08-27 10:01 UTC, YPG0 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +        String key = nameFolder + "/" + file.getName() + file.getSize() + file.getContentType();
+

2024-08-27 10:01 UTC, YPG0 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +        resource.setName(file.getOriginalFilename());
В приватный перенес. В базу сохранение идет этот метод создает ресурс и возвращает его в FileUploadService который сохраняет в БД

2024-08-27 10:01 UTC, YPG0 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +            throw new IllegalStateException("Failed to delete file from S3");
+

2024-08-27 10:01 UTC, YPG0 commented on src/main/java/faang/school/projectservice/amazon/AmazonS3Service.java
> +        resource.setSize(new BigInteger("0"));
По задаче нужно было "в Resource обнулять key и size, изменять status на DELETED", а сохранения происходят в основном методе. FileUploadService берет ресурс из БД потом передает уже в AmazonS3Service и в FileUploadService идет сохранения изменённого ресурса.

2024-08-27 10:01 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/FileServiceUpload.java
> +        resource.setUpdatedBy(teamMember);
+

2024-08-27 10:01 UTC, YPG0 commented on src/main/java/faang/school/projectservice/service/FileServiceUpload.java
> +        }
+

2024-08-27 10:01 UTC, YPG0 commented on src/main/java/faang/school/projectservice/validator/FileServiceValidator.java
> +    private final BigInteger PREMIUM_STORAGE_SIZE = new BigInteger("4294967296");
+

2024-08-28 03:37 UTC, pablo023 commented
У тебя билд ломается на CI, поправь, и давай ещё раз

2024-08-28 18:57 UTC, YPG0 commented
Пытался убрать лишние коммиты в которых искал что сломалось, как-то не вышло. Просто были тесты на старую логику которые пропустил когда все поменял. Видел файл в деталях проверки, а в проекте найти его не мог мимо глаз попадал

2024-08-29 09:50 UTC, merged