BJS2-15623 - Управление календарем
CorporationX/project_service pull request #567
Opened 2024-08-01 11:36 UTC by ravshanbekn

BJS2-15623 - Управление календарем

+ Created:
- Entities:      Meet, MeetStatus, MeetDto
- Controller:  MeetController for CRUD endpoints over Meet Entity
- Service:       MeetService for logic execution, interaction with repository and controller
- Filters:         Start, End and Title filters
- Validator:    MeetValidator, TeamValidator
- Exception :  DeniedInAccessException
- Tests:           MeetController, MeetService, MeetEndFilter, MeetStartFilter, MeetTitleFilter, TeamValidator, MeatValidator
- Interfaces:   UpdateMeet, CreateMeet, MeetMapper, MeetJpaRepository, MeetFilter

+ Updates:
- ExceptionHandler
- changeLog
- Project and Team entities

2024-08-09 00:09 UTC, pablo023 requested changes
Приятно было это ревьюить.

2024-08-09 00:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Может быть сюда лучше HttpStatus.NOT_FOUND?

2024-08-09 00:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
А почему бэд реквест, если у нас отказ в доступе? Может 403 или 401 подойдут лучше?

2024-08-09 00:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/mapper/MeetMapper.java
> +}
На мой взгляд, это не очень. У тебя будут добавляться поля, тебе сюда придется ходить, добавлять их. Было бы лучше сделать какой-то метод, который фетчит поля все неулевые поля из дто, и обновляет ими сущность.

2024-08-09 00:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/model/Team.java
> +    private List<Meet> meets = new ArrayList<>();
Вот этого лучше не делать. Давай разберем этот момент: когда ты работаешь с Hibernate, все коллекции в сущностях должны быть правильно связаны с Hibernate session. Это значит, что если у тебя есть список встреч List<Meet> meets в твоей сущности Team, этот список уже управляется Hibernate. Когда ты делаешь что-то вроде meets = new ArrayList, ты фактически создаешь новый список, который никак не связан с текущей сессией Hibernate. Это может привести к тому, что изменения в этом списке не будут отслеживаться и, следовательно, не сохранятся в базу данных, когда ты делаешь commit транзакции.

2024-08-09 00:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/model/meet/MeetStatus.java
ACTIVE?

2024-08-09 00:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/MeetService.java
> +        Meet meet = meetValidator.verifyMeetExistence(meetId);
Валидатор не должен возвращать ничего, писал об этом в прежних ПР

2024-08-09 00:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/validator/TeamValidator.java
Поправь на войды

2024-08-09 00:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/validator/meet/CreateMeet.java
Маркировочный?

2024-08-09 00:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/validator/meet/CreateMeet.java
Судя из названия - нет. Что это?

2024-08-09 00:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/validator/meet/MeetValidator.java
> +    public Meet verifyMeetExistence(long meetId) {
войд

2024-08-09 00:09 UTC, pablo023 commented on src/main/java/faang/school/projectservice/validator/meet/UpdateMeet.java
Что это?

2024-08-12 12:36 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Да, точно

2024-08-12 13:10 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Да, обратил внимание, спасибо

2024-08-12 13:46 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/mapper/MeetMapper.java
> +}
Не совсем понял тебя, можешь поподробнее расписать пожалуйста

2024-08-12 13:48 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/model/meet/MeetStatus.java
Хорошо

2024-08-12 14:09 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/validator/TeamValidator.java
Хорошо

2024-08-13 08:33 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/model/Team.java
> +    private List<Meet> meets = new ArrayList<>();
Хорошо

2024-08-13 08:34 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/service/MeetService.java
> +        Meet meet = meetValidator.verifyMeetExistence(meetId);
Хорошо

2024-08-13 08:35 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/validator/meet/MeetValidator.java
> +    public Meet verifyMeetExistence(long meetId) {
Хорошо

2024-08-13 08:41 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/validator/meet/CreateMeet.java
Забыл поставить аннотацию @ Validated в контроллере. Группирую валидацию по этим интерфейсам

2024-08-13 08:42 UTC, ravshanbekn commented on src/main/java/faang/school/projectservice/validator/meet/UpdateMeet.java
Группирую валидацию по этим интерфейсам

2024-08-15 22:15 UTC, pablo023 commented on src/main/java/faang/school/projectservice/mapper/MeetMapper.java
> +}
Объяснил в личке

2024-08-15 22:21 UTC, merged