BJS2-15628
CorporationX/project_service pull request #568
Opened 2024-08-01 18:45 UTC by Caveri95

- Добавлена возможность создавать компании для сбора бюджета к проектам
- Редактировать/создавать компании может только владелей или менеджер
- Написаны тесты к сервисам

2024-08-08 23:06 UTC, pablo023 requested changes
Вообще, очень даже хорошо, но чуть чуть исправь по замечаниям

2024-08-08 23:06 UTC, pablo023 commented on src/main/java/faang/school/projectservice/controller/CampaignController.java
Респонс статусы не проставил.

2024-08-08 23:06 UTC, pablo023 commented on src/main/java/faang/school/projectservice/dto/campaign/CampaignUpdateDto.java
> +    private BigDecimal goal;
Почему это бигдецимал?

2024-08-08 23:06 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/CampaignService.java
> +        checkUserPermission(campaignDto.getProjectId(), userId);
Я бы это в валидатор вынес.

2024-08-08 23:06 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/CampaignService.java
> +        }
Не особо имеет смысл. Если campaigns будет пустым, мы его вернем пустым, зачем нам отдельный List.of() для этого?

2024-08-08 23:06 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +    }
Не надо добавлять проверку на то, существует ли он?

2024-08-11 09:00 UTC, Caveri95 commented on src/main/java/faang/school/projectservice/controller/CampaignController.java
Да, окей, добавлю

2024-08-11 09:04 UTC, Caveri95 commented on src/main/java/faang/school/projectservice/controller/CampaignController.java
по дефолту и так контроллер 200 вернет, если ошибок не было. Лучше тогда статусы проставлять на ответы, отличные от 200?

2024-08-11 09:11 UTC, Caveri95 commented on src/main/java/faang/school/projectservice/dto/campaign/CampaignUpdateDto.java
> +    private BigDecimal goal;
Посмотрел какой тип используется при создании в БД, там DECIMAL. Поэтому выбрал аналогичный тут.
Можно конечно и Double использовать

2024-08-11 09:13 UTC, Caveri95 commented on src/main/java/faang/school/projectservice/service/CampaignService.java
> +        checkUserPermission(campaignDto.getProjectId(), userId);
Согласен

2024-08-11 09:23 UTC, Caveri95 commented on src/main/java/faang/school/projectservice/service/CampaignService.java
> +        }
Ага, что то намудрил

2024-08-11 09:24 UTC, Caveri95 commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +    }
внутри этого метода есть проверка уже 
![image](https://github.com/user-attachments/assets/0fe1682a-7197-45c0-a9ba-02c13d8e6bb6)

2024-08-12 22:11 UTC, pablo023 approved these changes

2024-08-12 22:11 UTC, pablo023 commented
Пофикси конфликты, и можем мерджить!

2024-08-13 04:50 UTC, merged