BJS2-16424
CorporationX/project_service pull request #591
Opened 2024-08-28 09:56 UTC by fraifree

2024-08-29 14:44 UTC, pablo023 requested changes
Есть баг в getAllTeamMember

2024-08-29 14:44 UTC, pablo023 commented on src/main/java/faang/school/projectservice/dto/team/TeamDto.java
> +@Builder
Про это уже писал. Не критично, но имей ввиду

2024-08-29 14:44 UTC, pablo023 commented on src/main/java/faang/school/projectservice/publisher/GenericMessagePublisher.java
> +public abstract class GenericMessagePublisher<T> implements MessagePublisher<T> {
Немножко по неймингу - абстарктные классы принято называть Abstract.... а не Generic

2024-08-29 14:44 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/TeamService.java
> +    }
А что у нас за гет такой, который ничего не возвращает, а просто assert выполняет?

2024-08-29 14:44 UTC, pablo023 commented on src/main/java/faang/school/projectservice/service/TeamService.java
> +        return team;
Я не думаю, что нам это нужно. Если ты что-то создаешь, максимум, что должно возвращаться - это дто. И то, не факт. Зачем нам это из create возвращать? Тут войд по моему вообще уместнее.

2024-09-01 17:42 UTC, fraifree commented on src/main/java/faang/school/projectservice/service/TeamService.java
> +        return team;
Бывает такое, что сущность нужна в живом виде, для создания другой сущности, которая может создаваться в другой задаче, сталкивался с этим, по этому и пишу наперед, а контроллер связываю с доп методом, возвращающим дто

2024-09-03 10:05 UTC, fraifree commented on src/main/java/faang/school/projectservice/service/TeamService.java
> +    }
убрал этот бесполезный метод

2024-09-03 10:09 UTC, merged