BJS2-27399 : Проекты
CorporationX/project_service pull request #600
Opened 2024-09-10 11:27 UTC by soulasphyxia

2024-09-11 01:22 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/dto/project/CreateProjectDto.java
> +    @NotBlank(message = "field \"name\" must not be blank")
Может еще @NotEmpty добавить?

2024-09-11 01:23 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/dto/project/CreateProjectDto.java
> +    @Positive(message = "field \"ownerId\" must be positive")
Кстати, для Number @Positive не проверяет на null, не знаю важно это здесь или нет

2024-09-11 01:24 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/dto/project/CreateProjectDto.java
> +    @Positive(message = "field \"ownerId\" must be positive")
А ну ниже у тебя есть

2024-09-11 01:26 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/filter/project/ProjectStatusFilter.java
> +    @Override
Пустую строчку забыл

2024-09-11 01:31 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +            throw new DataValidationException("Project with id %d cannot be negative".formatted(projectId));
Project id cannot be negative мб лучше? А еще почему < 0? Разве не с 1 начинаются?

2024-09-11 01:32 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    }
Тут не надо никакой проверки если этого проекта не существует?

2024-09-11 01:33 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +            throw new DataValidationException("Project with name \"%s\" by user with id %d is already exists"
Ну еще придерусь, может текст ошибок в константы вынести?

2024-09-11 01:35 UTC, SharkB38 requested changes

2024-09-11 01:35 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/filter/project/ProjectStatusFilter.java
> +    @Override
Забыл пустую строчку

2024-09-11 01:37 UTC, SharkB38 commented
Мегахарош

2024-09-11 05:26 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    }
тут необычный Project Repository, там отдельный класс в котором расписано много методов и там уже используют  JPA repository, крч там для findById уже проверка есть, можешь посмотреть(https://github.com/CorporationX/project_service/blob/feature-BJS2-27399/src/main/java/faang/school/projectservice/repository/ProjectRepository.java)

2024-09-11 05:28 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +            throw new DataValidationException("Project with id %d cannot be negative".formatted(projectId));
да, название поменяю, а вот условие для проверки на отрицательность мне кажется намного более понятное именно < 0 (читаем как книгу), < 1 как будто надо дополнительно мозг напрягать

2024-09-11 05:30 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/dto/project/CreateProjectDto.java
> +    @NotBlank(message = "field \"name\" must not be blank")
разве @notblank не будет лучше тут, тк еще trim() делает перед проверкой на пустоту

2024-09-11 09:14 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +            throw new DataValidationException("Project with name \"%s\" by user with id %d is already exists"
не знаю, мне кажется, что если строка в коде используется 1 раз, то вынесение ее в константу лишь ухудшит читаемость(если читаешь сверху вниз, то надо запомнить, что в какой константе записано, или постоянно туда сюда скроллить). поэтому давай оставим это пока так, если Маша поддержит эту идею, то вынесу

2024-09-11 12:50 UTC, SharkB38 approved these changes

2024-09-11 15:09 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/controller/project/ProjectController.java
> +    }
наверно лучше будет просто @PostMapping
оно уже подразумевает create

2024-09-11 15:09 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/controller/project/ProjectController.java
> +    @PutMapping("/update")
а тут только {id} передать вместо update

2024-09-11 15:09 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/dto/project/CreateProjectDto.java
> +    private ProjectStatus status = ProjectStatus.CREATED;
мне кажется ты уже сделал по дефолту сет статус CREATED и NOTNULL кажется лишним)

2024-09-11 15:09 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    @Override
сюда бы транзакцию)

2024-09-11 16:05 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +            throw new DataValidationException("Project with name \"%s\" by user with id %d is already exists"
Я тоже поддерживаю вынос в константы. Это, как мне кажется, больше на упрощение модификации кода в будущем. И хорошо было бы самого себя приучать писать подобное таким образом, чтобы потом это было на автомате)

2024-09-11 16:24 UTC, wmwmaks approved these changes
Выглядит хорошо, я ничего не нашел 😢

2024-09-11 19:15 UTC, mysosnovskaya requested changes
Хорошая работа 👍 Жду тестов на следующую итерацию!)

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectController.java
> +    }
Да, по правилам проектирования api Post - это уже и есть create, поэтому ничего дополнительно в урл дописывать не нужно. Для update аналогично

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectController.java
> +    @PutMapping("/update")
И опять соглашусь, по правилам проектирования api сюда нужно передавать id проекта, который нужно обновить

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/CreateProjectDto.java
> +    private ProjectStatus status = ProjectStatus.CREATED;
Интересно, что ответит Виталий)

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +    public ValidationErrorResponse handleValidationExceptions(MethodArgumentNotValidException ex) {
Возможно, лучше подошла бы структура List<ValidationError>, где в ValidationError два поля - fieldName и errorMessage (или error или errorDescription)

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectController.java
> +    public ProjectDto createProject(@RequestBody @Valid CreateProjectDto projectDto) {
Круто, что уже используешь продвинутую валидацию 👍

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    ProjectDto createProject(CreateProjectDto projectDto);
Чаще всего между методами оставляют пустые строки. Но это не строгое правило, даже вообще не правило) Встречается и такой вариант. Мне больше нравится, когда пустые строки есть, но ты можешь оставить так

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    ProjectDto updateProject(UpdateProjectDto projectDto);
Сейчас у тебя в названии каждого метода присутствует "Project". Если метод находится в классе ProjectService, то как будто бы и так понятно, что create/update/findAll/findById здесь могут быть только про Project. Это опять не правило, и часто пишут так, но просто напишу о том, что можно Project в названия не добавлять) Тоже решать тебе, меня оба варианта устраивают

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    public ProjectDto createProject(@Valid CreateProjectDto projectDto) {
Здесь тоже @Valid? Достаточно в одном месте оставить валидацию

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +            throw new DataValidationException("Project with name \"%s\" by user with id %d is already exists"
Тут неоднозначно. С одной стороны, если вынести ошибки в константы, то код это облегчит (нам не особо важно само сообщение, мы же понимаем, что там какое-то понятное описание ошибки), но обычно так не делают, т.к. в коде может быть очень много разных ситуаций, где генерируются исключения, и у каждого индивидуальное сообщение об ошибке. Тогда констант станет слишком много, а их роль непонятна: как будто бы не столько упростили код, сколько усложнили обязанностью каждое сообщение выносить в константы) Так что я бы не выносила, но если очень хочется, то можно: читаемость слегка повысится, а потомкам оставите немного головной боли =)

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    @Override
Можешь аргументировать?)

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +        List<Project> filteredProjects = projectFilters
Просто напомню, что в контроллере у тебя стоит `@RequestBody(required = false)`, т.е. projectFilters может быть null. Либо здесь нужно обработать эту ситуацию, либо сделать реквест обязательным в контроллере (все его поля могут быть null, но объект обязательно должен прийти)

2024-09-11 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +        //TODO: У проекта также должен быть признак приватности. Если проект приватный, то по поиску он должен быть видим только своим участникам.
Ты сейчас не сделал это из-за того, что у тебя нет id пользователя? Добавь в метод контроллера int userId и передай его сюда - это будет айди пользователя, который делает запрос. Если хочется правдоподобности, то в контроллере для этого параметра используй `@RequestHeader("X-User-Id")` и можешь подробнее почитать про http хэдеры. 
Но раз по условию такой фильтр должен быть, то давай его сделаем

2024-09-12 11:37 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +            throw new DataValidationException("Project with name \"%s\" by user with id %d is already exists"
Ну все теперь я не настолько поддерживаю этот вынос. Меня убедили, что это не обязательно

2024-09-12 14:10 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/dto/project/CreateProjectDto.java
> +    private ProjectStatus status = ProjectStatus.CREATED;
согласен, не заметил!

2024-09-12 14:17 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    @Override
насколько я понял из лекций, транзакцию мы применяем, когда у нас происходит несколько действий в рамках одной(или нескольких) таблиц и мы хотим сделать эту операцию атомарной, чтобы во время того как мы соверашем эти запросы ничто не могло нарушить консистентность данных. я не думаю, что здесь она так сильно нужна, единственную логику, которую я вижу это то, что мы сначала вызываем метод existsByOwnerUserIdAndName() и пока он вызывается, кто то может вызвать идентичный запрос на создание проекта и тогда метод отработает некорректно. не знаю, насколько это критично и как вообще себя поведет БД в таком случае

2024-09-12 14:18 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    @Override
я всегда думал что эта аннотация нужна чтобы не потерять деньги во время перевода...

2024-09-12 14:20 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +        //TODO: У проекта также должен быть признак приватности. Если проект приватный, то по поиску он должен быть видим только своим участникам.
сделаю, пока не решил как это реализовать, хотел поскорее запушить на кросс-ревью, чтобы исправить все недочеты а потом уже на вторую итерацию допилить этот метод. это нормальная практика или лучше потратить больше времени, но сделать сразу?

2024-09-12 14:23 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +        List<Project> filteredProjects = projectFilters
второе решение отличное, спасибо!

2024-09-12 17:39 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +    public ValidationErrorResponse handleValidationExceptions(MethodArgumentNotValidException ex) {
сделал оба варианта, мне визуально больше нравится, когда это в мапе лежит, но с точки зрения добавления каких-то дополнительных полей с информацией для конкретного филда, наверное ваш вариант лучше, оставлю его

2024-09-13 05:44 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    @Override
> Можешь аргументировать?)

я всегда думал что по дефолту транзакции должны быть при create, update, delete =)

2024-09-16 11:06 UTC, soulasphyxia commented on src/test/java/faang/school/projectservice/service/project/ProjectServiceTest.java
> +    public void testFindAllProjectsWithoutFiltersByTeamMember() {
насколько я понял, мне не нужно тестировать фильтрацию в этих тестах, т.к я написал тесты для фильтров и могу быть уверен, что они работают, и здесь мне нужно проверить только логику показа приватных проектов для участников команды, просто я не совсем понял как это все грамотно сделать(я не знаю как получить все компоненты ProjectFilter списком как в реальном классе), поэтому, я могу создать их только вручную, но что если у нас добавится еще фильтр и нужно будет тоже сюда это добавлять, что не очень удобно и как будто неправильно

2024-09-16 17:38 UTC, mysosnovskaya requested changes

2024-09-16 17:38 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectController.java
> +                                     @RequestHeader("x-user-id") Long userId) {
С хэдерем круто 👍

2024-09-16 17:38 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/ProjectDto.java
> +    @Positive(message = "id must be positive")
Я бы пустых строчек оставила между полями) Когда есть аннотации, то это становится актуальным, чтобы не сливалась всё в одно целое

2024-09-16 17:38 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/ForbiddenAccessException.java
> +public class ForbiddenAccessException extends RuntimeException {
Хорошее название 👍 Поддерживаю добавление этого исключения

2024-09-16 17:38 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +        return new ErrorResponse(ex.getMessage());
А логировать исключение будем?)

2024-09-16 17:38 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/Project.java
> +import org.hibernate.annotations.Cascade;
Зачем?)

2024-09-16 17:38 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    @Override
Обсудили на встрече) Не нужна, если в методе делается всего один модифицирующий запрос в бд

2024-09-16 17:38 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +                .sorted(Comparator.comparing(Project::getVisibility).reversed()) //отсортировал, чтобы сначала шли Private проекты, думаю так логичнее :)
В требованиях такого нет, а мы как разработчики не имеем права такое решать) Это нужно спрашивать у аналитика или автора задачи. Самопроизвольно вносить подобные бизнесовые правила нельзя. В данной ситуации это, конечно, не критично, но лучше сразу привыкать, что мы как разработчики отвечаем только за техническую реализацию бизнес требований, а также задаем вопросы по тому, что и как должно работать. Но сами не решаем ничего в этом плане)

2024-09-16 17:38 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/validation/ProjectDtoValidator.java
> +public class ProjectDtoValidator {
Правильно понимаю, что он понадобился из-за общего dto? Вообще эти проверки делаются аннотациями с помощью групп
https://struchkov.dev/blog/ru/spring-boot-validation/#%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D1%8B-%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D0%B9

2024-09-16 17:38 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/filter/project/ProjectNameFilterTest.java
> +    private ProjectFilterDto nullProjectFilterDto;
Лучше emptyProjectFilterDto, а то null это как будто nullProjectFilterDto == null

2024-09-16 17:38 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/filter/project/ProjectNameFilterTest.java
> +        assertEquals(0, result.size());
Можно было на разные тесты разбить) Я такой подход предпочитаю. Но можно так оставить, так тоже делают

2024-09-16 17:38 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/project/ProjectServiceTest.java
> +    public void testFindAllProjectsWithoutFiltersByTeamMember() {
Тебе нужно тестировать не сами фильтры, а их применение (правильно ли интерпретируются результаты isApplicable и apply методов). Для этого достаточно два каких-то фильтра добавить, неважно каких. Мы предполагаем, что сами фильтры все работают корректно (мы их уже протестировали). Можно даже два мокнутых фильтра сделать) Два - потому что 0 или 1 - это краевые случаи (их тоже надо протестировать отдельным тестом).

2024-09-17 04:16 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/model/Project.java
> +import org.hibernate.annotations.Cascade;
мы с Валерой проверяли как добиться нужного нам поведения у сущностей, эксперементировали с  каскадностью, а потом  я забыл это убрать...

2024-09-17 04:18 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/validation/ProjectDtoValidator.java
> +public class ProjectDtoValidator {
да, я увидел их, когда вы включали код Арстана на планировании, на самом деле это как раз то, что я искал и думал что мне именно это скинут, когда писал вопрос Владу :) спасибо!!

2024-09-18 19:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +        //TODO: У проекта также должен быть признак приватности. Если проект приватный, то по поиску он должен быть видим только своим участникам.
Разные ситуации бывают, так тоже можно, но тогда лучше явно обозначить свой вопрос. Либо комментарием в коде, либо комментарием в гитхабе

2024-09-18 19:49 UTC, mysosnovskaya approved these changes

2024-09-18 19:49 UTC, merged