Проекты
CorporationX/project_service pull request #602
Opened 2024-09-10 19:40 UTC by RuslanIovlev

тесты не создавал, постарался быстро сделать задание, жду комментов что доработать

2024-09-12 15:22 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +    }
а нельзя сразу вернуть ProjectDTO?

2024-09-12 15:53 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +                })
лучше в отдельный метод, выглядит как валидация

2024-09-12 15:55 UTC, DankeVilletti reviewed
коменты оставил)

2024-09-12 15:57 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +    }
а здесь вместо set set set нельзя в dto преобразовать
вопрос ко всем

2024-09-13 18:23 UTC, mysosnovskaya requested changes
На следующее ревью жду тестов!)

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +    public ResponseEntity<ProjectDto> createProject(ProjectDto projectDto) {
Зачем нам здесь ResponseEntity?) Считаю, что это лишнее усложнение кода. Без него тоже будет прекрасно работать:
```
public ProjectDto createProject(ProjectDto projectDto) {
        return projectService.createProject(projectDto);
    }
```

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/ProjectDto.java
> +    private long projectOwnerId;
Из названия поля не понимаю, что это. Может быть parentProjectId?

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/ProjectDto.java
> +    private List<Team> teams;
Для Team тоже dto класс нужен

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/ProjectFilterDto.java
> +    private TeamMember teamMember;
Зачем нам весь teamMember? Его id недостаточно?

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/ProjectMapper.java
> +    ProjectDto toDto(Project project);
Название метода лучше уточнить: toProjectDto, а то мало ли в какое dto ты можешь Project преобразовать)

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/ProjectMapper.java
> +    Project toEntity(ProjectDto projectDto);
Тут тоже лучше toProject, добавим конкретики

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/ProjectMapper.java
> +    List<ProjectDto> toDtoList(List<Project> projects);
toProjectDtos

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/ProjectMapper.java
> +    ProjectMapper INSTANCE = Mappers.getMapper(ProjectMapper.class);
А это для чего?) Нигде не используется

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +    private final List<ProjectFilter> projectsFilter;
Т.к. фильтров много, то поле лучше назвать projectsFilters

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +        project.setStatus(ProjectStatus.CREATED);
А также необходимо проставить поля createdAt и updatedAt. Мы не можем полагаться на то, что пришлет фронтенд. Вся логика происходит на бэке и проставление этих полей - это часть логики

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/ProjectDto.java
> +
Не хватает id проекта. Когда сохраним объект в базу данных, то как-то нужно будет сказать фронтенду, с каким id этот проект создан. Иначе фронт никогда об этом не узнает и далее не сможет подставлять верный id в методы обновления и поиска

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +            throw new IllegalArgumentException("Project with this name already exists for the owner");
Лучше своё собственное исключение (ValidationException, например). Потому что IllegalArgumentException это немного о другом (когда в метод пришли значения из некорректного диапазона, например, параметр метода - объект, который должен быть not null, но пришел null, или параметр - неотрицательное число, а пришло -2). В данном случае переданные данные корректные с точки зрения диапазона, а проблема в том, что такая запись уже есть в бд. Вот это уже не про IllegalArgumentException. Рекомендую в любых проверках на валидацию использовать ValidationException

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +            throw new IllegalArgumentException("Project with this name already exists for the owner");
В сообщение об ошибке нужно добавить идентифицирующую информацию (имя и owner id)

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +            throw new IllegalArgumentException("This project doesn't exist");
Здесь должна быть другая ошибка, EntityNotFoundException, например. 
И в сообщение об ошибке нужно добавить идентификатор

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +                .forEach(projectFilter -> projectFilter.apply(projects, filterDto));
Метод нужно протестировать, так это работать не будет. Писала тебе такой же комментарий к задаче с 5 спринта, про UserFilter

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +                    if (project.getVisibility() == ProjectVisibility.PRIVATE) {
А эту логику нельзя реализовать через отдельный ProjectFilter? Почему это отдельно здесь написано?

2024-09-13 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/ProjectMapper.java
> +public interface ProjectMapper {
Маппер необходимо протестировать. В таком виде он работать не будет)

2024-09-15 10:55 UTC, ChibixAnastasia approved these changes

2024-09-19 17:16 UTC, mysosnovskaya requested changes

2024-09-19 17:16 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/ProjectDto.java
> +    private long ProjectId;
С маленькой буквы

2024-09-19 17:16 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/team/TeamDto.java
> +public class TeamDto {
А этот класс для чего?)

2024-09-19 17:16 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/filter/ProjectFilter.java
> +    boolean filterByVisibility(Project project, ProjectFilterDto filterDto);
Вот это не поняла. У тебя в каждой имплементации этого метода будет одна и та же реализация? А зачем? Почему вообще все фильтры должны иметь такой метод?
Можно создать ещё одну реализацию интерфейса ProjectFilter - например, ProjectVisibilityFilter. Там в isApplicable можно всегда возвращать true, а в apply - реализовать соответствующую логику. Всё должно быть едино. Сейчас этот метод сильно выбивается из общей логики

2024-09-19 17:16 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +        project.setDescription(projectDto.getProjectDescription());
А description в projectDto может быть null? Я думаю, да. В случае, если я не хочу обновлять описание, хочу только статус обновить. Тогда в ProjectDto только поле status будет не равно null

2024-09-19 17:16 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/ProjectDto.java
> +public class ProjectDto {
Куда-то поле teams пропало) Почему?

2024-09-19 17:16 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +public class ProjectService {
Нужны логи

2024-09-19 17:16 UTC, mysosnovskaya commented on src/test/java/faang/school/service/ProjectServiceTest.java
> +        when(projectDto.getProjectDescription()).thenReturn(description);
А зачем projectDto мокать? Можно настоящий объект создать

2024-09-19 17:16 UTC, mysosnovskaya commented on src/test/java/faang/school/service/ProjectServiceTest.java
> +    @Mock
Используй аннотацию Spy, чтобы не мокать маппер

2024-09-19 17:16 UTC, mysosnovskaya commented on src/test/java/faang/school/service/ProjectServiceTest.java
> +    void testGetAllProjectsByFilterWhenFiltersAreApplied() {
На фильтры надо побольше тестов: если ни одного фильтра нет, если есть только один, если ни один из проектов не был отфильтрован, если были отфильтрованы все

2024-09-19 17:16 UTC, mysosnovskaya commented on src/test/java/faang/school/service/ProjectServiceTest.java
> +        assertNotNull(updatedProject);
Я бы ещё проверила, что updatedTime обновилось и что поля какие-то обновились (в твоем случае описание)

2024-09-19 17:16 UTC, mysosnovskaya commented on src/test/java/faang/school/service/ProjectServiceTest.java
> +    void testUpdateProjectWhenValidInput() {
Нет теста на обновление, где бы обновлялся статус

2024-09-19 17:16 UTC, mysosnovskaya commented on src/test/java/faang/school/service/ProjectServiceTest.java
> +        assertNotNull(savedProject);
Нужно проверить поля createdAt и updatedAt

2024-09-20 18:37 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/dto/project/ProjectDto.java
> +public class ProjectDto {
убрал так как нигде не использовался

2024-09-21 16:46 UTC, mysosnovskaya requested changes
Одна маленькая правочка в тестах и точно будет аппрув) Жду скорее)

2024-09-21 16:46 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/filter/ProjectVisibilityFilter.java
> +public class ProjectVisibilityFilter implements ProjectFilter {
Вот теперь отлично получилось 👍

2024-09-21 16:46 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/ProjectDto.java
> +    private List<TeamDto> teamDtos;
Вижу, вернул поле)

2024-09-21 16:46 UTC, mysosnovskaya commented on src/test/java/faang/school/service/ProjectServiceTest.java
> +        verify(projectDto, times(1)).getProjectUpdatedAt();
Почему в projectDto обязательно должен быть вызывать этот метод? Нам важно проверить, что у project поле updatedAt изменилось на актуальное. Вот такой проверки не хватает)

2024-09-21 16:46 UTC, mysosnovskaya commented on src/test/java/faang/school/service/ProjectServiceTest.java
> +        projectDto = Mockito.mock(ProjectDto.class);
По-прежнему думаю, что это лишнее) Ну ладно

2024-09-21 19:09 UTC, RuslanIovlev commented on src/test/java/faang/school/service/ProjectServiceTest.java
> +        verify(projectDto, times(1)).getProjectUpdatedAt();
правильно ли проверил?

2024-09-22 16:01 UTC, mysosnovskaya approved these changes

2024-09-22 16:01 UTC, merged