BJS2-27585 добавлено решение задачи без тестов
CorporationX/project_service pull request #607
Opened 2024-09-12 18:46 UTC by KarabbasBarabas

2024-09-15 10:53 UTC, ChibixAnastasia approved these changes

2024-09-16 16:10 UTC, DankeVilletti reviewed
Вооот

2024-09-16 16:10 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +        return service.getMoments(filterDto);
FilterDTO я бы расположил туда где директория с dto

2024-09-16 16:10 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +            throw new RuntimeException("Наименование момента не может быть пустым");
is blank добавь

2024-09-16 16:10 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +            throw new RuntimeException("Момент должен относиться к какому-нибудь проекту");
Validate exception наверное лучше

2024-09-16 16:10 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/dto/MomentDto.java
> +    private String imageId;
String... imageId...
Странновато

2024-09-16 16:10 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        }
интересеный момент по созданию если нет момента.
я его понимаю, но что лучше, может ошибку все таки?
это вопрос ко всем

2024-09-16 16:10 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    }
слишком много всего в одном методе
я бы разбил
валидацию отдельно
фильтры отдельно

2024-09-16 17:36 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    }
Не увидел проверки, что имя момента не пустое

2024-09-16 17:41 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        }
Мне кажется лучше исключение выкинуть, во избежании дальнейших ошибок

2024-09-16 17:48 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +        }
Мне кажется RuntimeException не совсем сюда подходит. Я у себя свой собственный создавал, я бы тебе советовал также

2024-09-16 17:49 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +        }
И валидацию как я понял, лучше полностью на сервис возложить

2024-09-16 17:59 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    }
Согласен, тяжело так воспринимать

2024-09-16 18:00 UTC, RuslanIovlev approved these changes

2024-09-17 19:55 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +        return service.getMoments(filterDto);
согласен

2024-09-17 19:55 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +        }
согласен с RuntimeException
логическая валидация как я понял проходится в контроллере

2024-09-17 19:55 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +            throw new RuntimeException("Наименование момента не может быть пустым");
согласен

2024-09-17 19:55 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +            throw new RuntimeException("Момент должен относиться к какому-нибудь проекту");
согласен

2024-09-17 19:55 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/dto/MomentDto.java
> +    private String imageId;
вполне себе, когда id формате guid

2024-09-17 19:55 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    }
есть в контроллере

2024-09-17 19:55 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        }
я думаю, что исключение выкинуть
хотя тут есть контраргумент, что "не стоит ограничивать  пользователя", если ему хочется создать момент через update - че бы нет, или всё таки нет...

2024-09-17 19:55 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    }
согласен

2024-09-18 17:55 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +        }
Логическая как раз в сервисе, в контроллере только очень простые (типа какое-то поле не null или непустое, или вот как у тебя id)

2024-09-18 19:18 UTC, mysosnovskaya requested changes

2024-09-18 19:18 UTC, mysosnovskaya commented on build.gradle.kts
> +    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2")
В данной задаче это изменение не требовалось, оно должно быть в ПРе для другой задачи. Кстати, тоже твоей) Поэтому отсюда его нужно убрать. Один ПР относится только к одной задаче, никаких других изменений в нем быть не должно

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +    @PostMapping("/create")
По правилам проектирования api глаголы (действия) в урле прописывать не нужно. Post - это уже создание, Put - это уже обновление. Понимаю, что этого ещё не проходили, но важно говорить об этом уже на этом этапе

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +    @PutMapping("/get/moments")
GetMapping для методов получения

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/filter/moment/MomentFilter.java
> +
Лишние пустые строчки)

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/filter/moment/MomentFilterMonth.java
> +public class MomentFilterMonth implements MomentFilter {
`MomentMonthFilter `- название класса в первую очередь должно отвечать на вопрос "что", у нас этот класс в первую очередь - фильтр. А потом уже - какой фильтр? Фильтр месяцев для моментов. По правилам английского - сначала дополнения, потом существительное

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/filter/moment/MomentFilterProjects.java
> +                            .toList();
Можно сразу в Set собрать: `.collect(Collectors.toSet())`

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +    MomentDto toDto(Moment moment);
Лучше toMomentDto, т.к. в будущем могут появиться и другие dto классы. Ну и в целом так код будет чуть понятнее)

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +    List<MomentDto> toDto(List<Moment> moments);
`toMomentDtos `(обязательно s в конце, чтобы подчеркнуть множественность)

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +    Moment toEntity(MomentDto momentDto);
`toMoment` лучше, т.к. Entity - это слишком абстрактно

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                throw new DataValidationException("Момент можно создать только для незакрытого проекта");
Хорошо было бы в описание ошибки ещё добавить информацию, какой именно проект из переданных сейчас незакрыт.

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        log.info("Create moment with id = " + returnMomentDto.id());
В логи ещё можно добавить id проектов, для которых этот момент создан

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +            throw new DataValidationException("Переданного момента не существует в бд");
Нужно добавить id момента в описание ошибки

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        }
Исключение будет лучше. Т.к. если вызывается метод update, то ожидается именно обновление. Если обновление невозможно, то об этом нужно сообщить, т.к. скорее всего какая-то ошибка в переданных данных. Представьте себя на месте пользователя: вы хотите что-то обновить и ожидаете именно такое поведение, а система вам молча вместо обновления делает создание и говорит, что всё хорошо. А я может быть всего лишь цифрой ошиблась)

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +            log.info("Returning empty moment");
Должна быть ошибка, EntityNotFound

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        if (momentDto == null) {
Раз findById возвращает Optional, то нужно этим пользоваться. `MomentDto momentDto =  optional.map(moment -> mapper.toDto(moment)).orElseThrow(...);` Потом лог, потом return

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                .filter(projectId -> momentOld.getProjects().stream()
Предлагаю вынести в отдельную переменную List<Integer> projectIds. чтобы не создавать новый список на каждой итерации filter

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                        .contains(projectId)
Кажется, ошибка? Если мы оставить только те projectId, которые будут новыми, то значит они НЕ должны были содержаться в momentOld.getProjects(). А у тебя наоборот содержатся

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                .filter(userId -> momentOld.getUserIds().contains(userId))
Тут тоже фильтр оставляет только тех, кто уже был в momentOld.getUserIds()

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +            return null;
А зачем возвращать null, а затем проверять на null? Не проще ли вернуть пустой список? Похоже, ничего и не сломается. Тут даже отдельная проверка на пустоту не нужна, если список пустой, то стрим (который ниже) ничего не сломает, просто дальше тоже вернется пустой список

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +            return null;
Аналогично предыдущему, я бы эту проверку не делала. Ничего не вижу страшного в том, чтобы вернуть пустой список. Наоборот, избежим потенциальных Null Pointer Exception

2024-09-18 19:18 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +    path: /swag
Лучше полностью - swagger

2024-09-18 19:18 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/controller/MomentControllerTest.java
> +    public void testCreate_captor() {
После нижнего подчеркивания пишется, какое поведение проверяется тестом, а здесь - особенность реализации. Можно назвать testCreate_Success - проверяется успешное создание

2024-09-18 19:18 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        momentDto = new MomentDto(
Можно создание объектов вынести в отдельный приватный метод. В этом случае - createMomentDto.

2024-09-18 19:18 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +                momentDto.createdAt(),
Создание этого объекта очень похоже на создание предыдущего за исключением этих двух полей. В такой ситуации в метод createMomentDto в параметры нужно вынести различающиеся части. В данном случае нужно будет добавить параметры createdAt и updatedAt

2024-09-18 19:18 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        momentDtoToReturn = new MomentDto(
А создание этого объекта аналогично предыдущему

2024-09-18 19:18 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        momentToReturn = new Moment();
Для создания momentToReturn и expectedMoment тоже отлично подойдет отдельный метод

2024-09-18 19:18 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +                        Project.builder()
Страшно =) Попробуй эту вложенность упростить. Часть можно вынести в локальные переменные или в приватные методы

2024-09-19 17:27 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +    @PostMapping("/create")
поправил

2024-09-19 17:27 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +    @PutMapping("/get/moments")
поправил

2024-09-19 17:28 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/filter/moment/MomentFilter.java
> +
поправил

2024-09-19 17:29 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/filter/moment/MomentFilterMonth.java
> +public class MomentFilterMonth implements MomentFilter {
это критично?
мне больше так нравится, потому что есть интерфейс "MomentFilter", а классы, которые его реализуют называются "MomentFilter" + что фильтруется

2024-09-19 17:31 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/filter/moment/MomentFilterProjects.java
> +                            .toList();
поправил

2024-09-19 17:32 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +    MomentDto toDto(Moment moment);
у других классов дто же будет другой маппер

2024-09-19 17:34 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +    List<MomentDto> toDto(List<Moment> moments);
поправил

2024-09-19 17:35 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +    Moment toEntity(MomentDto momentDto);
маппер он относится к Moment,
маппится дто в сущность
это критично?

2024-09-19 17:36 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                throw new DataValidationException("Момент можно создать только для незакрытого проекта");
поправил

2024-09-19 17:37 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        log.info("Create moment with id = " + returnMomentDto.id());
поправил

2024-09-19 17:37 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +            throw new DataValidationException("Переданного момента не существует в бд");
поправил

2024-09-19 17:45 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +            log.info("Returning empty moment");
поправил

2024-09-19 17:57 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        if (momentDto == null) {
поправил

2024-09-19 17:59 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                .filter(projectId -> momentOld.getProjects().stream()
поправил

2024-09-19 17:59 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                .filter(projectId -> momentOld.getProjects().stream()
при каждом вызове momentOld.getProjects()
создаётся новый список?
не ссылка возвращается на уже созданный объект?

2024-09-19 18:02 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                        .contains(projectId)
cогласен, поправил

2024-09-19 18:03 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                .filter(userId -> momentOld.getUserIds().contains(userId))
согласен, поправил

2024-09-19 18:08 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +            return null;
согласен, поправил

2024-09-19 18:08 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +            return null;
согласен, поправил

2024-09-19 18:10 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/controller/MomentControllerTest.java
> +    public void testCreate_captor() {
поправил

2024-09-19 18:11 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        momentDto = new MomentDto(
метод setup только подготавливает объекты для теста, его тогда переименовать?

2024-09-20 15:54 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        momentToReturn = new Moment();
поправил

2024-09-20 15:54 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        momentDtoToReturn = new MomentDto(
поправил

2024-09-20 15:54 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +                momentDto.createdAt(),
поправил

2024-09-20 16:06 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +                        Project.builder()
поправил

2024-09-20 18:11 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +    @PutMapping("/update")
Действия (глаголы) в урле прописывать не нужно (также, как я писала про create). Аналогично здесь, аналогично для get

2024-09-20 18:11 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +    @PutMapping("/get/id")
Тут тоже должен быть GetMapping

2024-09-20 18:11 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/filter/moment/MomentFilterMonth.java
> +public class MomentFilterMonth implements MomentFilter {
Да, критично. Ты правильно рассуждаешь, просто по правилам английского языка сначала "что фильтруется", а потом что это за класс. Можно назвать MonthMomentFilter

2024-09-20 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +    MomentDto toDto(Moment moment);
Для Moment может быть больше одного dto. Возможно, тебе в каком-то из методов контроллера нужно будет вернуть другую информацию и MomentDto не подойдет. Тогда придется создать новый dto класс, а маппинг будет в этом классе, т.к. это тоже относится к моментам

2024-09-20 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +    List<MomentDto> toDtos(List<Moment> moments);
toMomentDtos будет лучше по той же причине, которую написала выше (могут быть и другие dto классы)

2024-09-20 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +    Moment toEntity(MomentDto momentDto);
Здесь не критично, но я бы предпочла дать методу максимально конкретное название. От этого код станет более понятным и читаемым. Так что рекомендую переименовать.

2024-09-20 18:20 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +                .filter(projectId -> momentOld.getProjects().stream()
Я про  .toList() ниже. В momentOld.getProjects(), конечно, возвращается одна и та же ссылка, но по итогу работы стрима создается новый список

2024-09-20 18:20 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/controller/MomentControllerTest.java
> +    public void testUpdate_captor() {
Здесь аналогично тому, что я писала про название для теста на создание. И для других тестов ниже тоже аналогично

2024-09-20 18:20 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        momentDto = new MomentDto(
Пусть остается) Стандартно так называют

2024-09-20 18:35 UTC, mysosnovskaya requested changes

2024-09-20 18:35 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +    MomentDto createMomentDto(LocalDateTime createdAt, LocalDateTime updatedAt) {
Эти методы лучше сделать приватными и переместить в самый низ класса (обычно в классе сначала идут все публичные методы, а потом все приватные)

2024-09-20 18:35 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        expectedMomentDto = new MomentDto(
А здесь метод createMomentDto не подойдет?

2024-09-20 18:35 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        expectedMomentDto = new MomentDto(
И здесь

2024-09-20 18:35 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +                        Project.builder()
Не вижу изменений, вложенность по-прежнему страшная =)

2024-09-20 18:35 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        expectedMomentDto = new MomentDto(
createMomentDto?

2024-09-20 18:35 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        MomentDto expectedMomentDto = new MomentDto(
Для создания такого объекта тоже можно сделать отдельный приватный метод, т.к. ниже у тебя есть необходимость создавать почти такие же объекты. Значения полей можно вынести в параметры этого приватного метода (имею в виду id, projectIds и userIds)

2024-09-20 18:35 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +                        Project.builder().id(1L).build(),
Может быть добавим метод для создания проекта? Ты очень часто используешь этот код с билдером, выглядит так, как будто это можно вынести в отдельный метод с параметром id. Тогда здесь можно было бы в одну строчку записать: 
`List.of(createProject(1L), createProject(2L), createProject(3L))`
И везде ниже тоже. А то с этими билдерами код выглядит очень массивно.

2024-09-21 08:14 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/filter/moment/MomentFilterMonth.java
> +public class MomentFilterMonth implements MomentFilter {
поправил

2024-09-21 08:20 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +    MomentDto toDto(Moment moment);
поправил

2024-09-21 08:26 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +                        Project.builder()
поправил,
сначала не понял где вложенность - исправлял код в testUpdate_NewUsers

2024-09-21 08:27 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +    @PutMapping("/update")
поправил

2024-09-21 08:27 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/controller/MomentController.java
> +    @PutMapping("/get/id")
поправил

2024-09-21 08:30 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/mapper/MomentMapper.java
> +    List<MomentDto> toDtos(List<Moment> moments);
поправил

2024-09-21 08:33 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/controller/MomentControllerTest.java
> +    public void testUpdate_captor() {
поправил
после "_" слово с большой буквы или с маленькой?

2024-09-21 08:34 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +    MomentDto createMomentDto(LocalDateTime createdAt, LocalDateTime updatedAt) {
поправил

2024-09-21 08:36 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        expectedMomentDto = new MomentDto(
поправил

2024-09-21 08:48 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        expectedMomentDto = new MomentDto(
поправил

2024-09-21 08:51 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        expectedMomentDto = new MomentDto(
поправил

2024-09-21 08:53 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        MomentDto expectedMomentDto = new MomentDto(
ну там из постоянных значений только LocalDateTime.of(2024, 8, 1, 1, 1, 1)
останется, конструктор на метод поменяется

2024-09-21 08:57 UTC, KarabbasBarabas commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +                        Project.builder().id(1L).build(),
поправил

2024-09-21 16:49 UTC, mysosnovskaya approved these changes
Разреши конфликт и можешь самостоятельно смержить и закрыть задачу)

2024-09-21 16:49 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/MomentServiceTest.java
> +        MomentDto expectedMomentDto = new MomentDto(
Куча null уйдут, они тоже постоянные значения)

2024-09-22 17:50 UTC, merged