first solution to the task BJS2-27397
CorporationX/project_service pull request #615
Opened 2024-09-13 22:13 UTC by wmwmaks

https://faang-school.atlassian.net/jira/software/c/projects/BJS2/boards/63?selectedIssue=BJS2-27397

2024-09-14 07:07 UTC, wmwmaks commented
Не понимаю, почему в моделях импорты на другие строки перешли. Я ничего в них не делал. Верну, как было

2024-09-14 07:26 UTC, SharkB38 requested changes

2024-09-14 07:26 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    public void updateInternship(@PathVariable @Positive Long internshipId, TeamRoleDto teamRole) {
@requestbody для teamRole, а то как мы ее получим?

2024-09-14 07:26 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    public List<InternshipDto> getAllInternships(InternshipFilterDto filters) {
И тут тоже

2024-09-14 07:26 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    @Size(min = 1, message = "At least one intern is required")
Блин клевая аннотация не знал про нее

2024-09-14 07:26 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/dto/internship/InternshipFilterDto.java
> +@Getter
Ну тут конструктор надо

2024-09-14 07:26 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/filter/InternshipStatusFilter.java
> +    @Override
Забыл пустую строчку)

2024-09-14 07:28 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    public void updateInternship(@PathVariable @Positive Long internshipId, TeamRoleDto teamRole) {
Ага, тоже это заметил, как отправил. Сделаю

2024-09-14 07:29 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    @Size(min = 1, message = "At least one intern is required")
Я подсмотрел у Витали 😅

2024-09-14 07:29 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +            }
Мое увожение

2024-09-14 07:37 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PostMapping("")
Думаю, пустые кавычки тут не нужны)

2024-09-14 07:39 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PutMapping("{internshipId}")
Без / работает? Если да, думаю, стоит всё равно придерживаться единой структуры. А то слэша у тебя тут нет, а внизу есть)

2024-09-14 07:40 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private Long projectId;
Думаю @Positive тоже стоит добавить)

2024-09-14 07:51 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private TeamMember mentorId;
Тут как я понял ты передаёшь только mentorId? Одно поле типа Long? А то сейчас в mentorId у тебя лежит сущность TeamMember, со всеми полями) Или я не так понял)

2024-09-14 07:53 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PutMapping("{internshipId}")
согласен с Арстаном

2024-09-14 07:59 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private TeamMember mentorId;
там просто в самой сущности Intership само поле так называется, мне кажется просто чтобы лишнее в маппере не писать) странное название, соглашусь, но это не к Максу вопросы

2024-09-14 08:02 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private List<TeamMember> interns;
помню, Влад в лекции говорил, что ДТО нужны, чтобы отдавать только нужную информацию пользователю, т.е если мы отдадим List<TeamMember>, то отдадим всю сущность TeamMember, а это может привести к отдачи какой-то информации, которую мы бы не хотели отдавать. Не уверен, что тут это прям критично, но, вроде как надо создать тогда отдельные DTO для сущностей (типа TeamMemberDto), либо передавать List<Long> internsIds. Это, конечно все надо тоже решать и думать, прошу Машу свое мнение по этому поводу написать

2024-09-14 08:02 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +            throw new EntityNotFoundException("No interns");
В сообщение думаю стоит передать и id проекта, где не оказалось старжеров

2024-09-14 08:05 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PutMapping("{internshipId}")
Согласен, добавлю

2024-09-14 08:11 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +            throw new EntityNotFoundException("No interns");
Да, согласен, добавлю

2024-09-14 08:13 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private List<TeamMember> interns;
Точно, я об этом помню, но тут пропустил. Сделаю, чтобы id этих тиммемберов передавались

2024-09-14 08:14 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private TeamMember mentorId;
Нет, тут у меня вопрос не к названию, а к сущности TeamMember, как ты и писал ниже, в нём есть много и своих данных, например  List<TeamRole> и List<Stage>. И чтобы создать стажировку, пришлось бы в json передавать все эти данные. Поэтому тут скорее всего стоит передать лишь Id c типом Long)

2024-09-14 13:10 UTC, SharkB38 approved these changes

2024-09-14 13:13 UTC, ArstanSubanov approved these changes

2024-09-14 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private List<TeamMember> interns;
Всё верно

2024-09-14 20:48 UTC, mysosnovskaya requested changes

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PostMapping()
Скобочки тоже можно удалить)

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private String internshipName;
А разве не name должно быть?  В модели Internship просто name. Сейчас видимо маппинг этого поля не работает?

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private final LocalDateTime startDate = LocalDateTime.now();
Я бы не стала ставить значение по умолчанию. На мой взгляд, с фронта должна прийти дата начала стажировки. Мы на бэке за пользователя это решить не можем

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    @Future(message = "End date must be in the future")
Хорошая аннотация)

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +@NoArgsConstructor
Зачем нужен конструктор без параметров? Разве не должны быть все поля финальными?

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/internship/InternshipFilterDto.java
> +public class InternshipFilterDto {
Можно сделать record. В сервисе распишу подробнее

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +    List<InternshipDto> getAllInternshipsOnProject(Long projectId);
getAllInternshipsByProjectId

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +    private final static int maxInternshipDurationMonth = 3;
ИМЯ_КОНСТАНТЫ_ПИШЕТСЯ_ТАК

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +                    intern.setTeam(null);
Из interns его тоже нужно удалить

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +                boolean passed = intern.getStages().stream()
Эту проверку можно в отдельный метод вынести

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +        internshipRepository.save(internshipForUpdate);
Эту строчку имеет смысл выполнять внутри if только. А вообще если в будущем добавятся ещё статусы в InternshipStatus, то эта строчка будет выполняться для всех, кроме IN_PROGRESS, хотя смысла в этом не будет. Я бы самый первый if сделала таким: если статус не равен COMPLETED, то исключение. А дальше выполняем эту логику по завершению стажировки.

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +        if (filters == null) {
Можно так, чтобы не костылить с созданием пустого InternshipFilterDto:
```
        List<Internship> internships = internshipRepository.findAll();
        if (filters == null) {
            return mapper.internshipsToInternshipDtos(internships);
        }
```

А ещё можно так: 
```
    public List<InternshipDto> getAllInternships(InternshipFilterDto filters) {
        List<Internship> internships = internshipRepository.findAll();
        if (internships.isEmpty()) {
            throw new EntityNotFoundException("No internships");
        }
        if (filters != null) {
            Stream<Internship> filteredInternships = internships.stream();
            for (InternshipFilter filter : internshipFilters) {
                if (filter.isApplicable(filters)) {
                    filteredInternships = filter.apply(filteredInternships, filters);
                }
            }
            internships = filteredInternships.toList();
        }
        List<InternshipDto> result = internshipMapper.internshipsToInternshipDtos(internships);
        log.info("Returned {} filtered internships", result.size());
        return result;
    }
```
А ещё можно логику по фильтрации вынести в отдельный приватный метод, тогда здесь останется, например, так:
```
        if (filters != null) {
            internships = filterInternships(internships);
        }
```

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +            log.info("Returned {} filtered internships", result.size());
Хорошо, что size добавил. Отмечу только, что как правило get-запросы делаются очень часто, поэтому логов от них будет очень много. Рекомендую использовать уровень логгирования debug для таких get запросов

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +        } else {
else не нужно, незачем повышать уровень вложенности кода) Актуально для всех методов

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +                    .filter(teamMember -> !teamMember.getRoles().contains(TeamRole.INTERN))
А этот фильтр зачем? Вряд ли у нас будет teamMember с ролью INTERN и айди = mentorId. Или думаешь, может такое быть?

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +public class InternshipServiceImpl implements InternshipService {
Очень симпатичный сервис у тебя получился. Логики много, но написана аккуратно и понятно. Отличное разбиение на методы, согласна с каждым приватным методом - супер! 👍

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/internship/InternshipFilter.java
> +public interface InternshipFilter {
А почему этот интерфейс в пакете с dto оказался?)

2024-09-14 20:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/filter/InternshipRoleFilter.java
> +    Пока не понял, что за фильтр по роли...
Да, непонятная задачка. А давай сделаем по роли ментора? Вроде бы логично получается: если ментор - разработчик, то значит стажировка для разработчиков =)

2024-09-14 20:55 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private final LocalDateTime startDate = LocalDateTime.now();
Я сделал так, потому что в статусе стажировке есть 2 варианта: В процессе, завершена. Нет такого статуса, чтобы она и не завершена и не начата была. От этого отталкивался. Убрать?

2024-09-14 21:03 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private String internshipName;
Насчет работает ли маппинг не могу сказать, я не до конца понимаю, как это работает. Если есть на примете статьи насчет этого, я бы почитал)
Но, действительно, в модели просто name, исправлю.

2024-09-14 21:05 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +@NoArgsConstructor
В 6.1 модуле есть Воркшоп от Влада. И там у Дто все эти аннотации были, я повторил🙄
Оставить лучше только Data или Data + AllArgsConstructor?

2024-09-14 21:09 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +                    .filter(teamMember -> !teamMember.getRoles().contains(TeamRole.INTERN))
Может не может мы не знаем, а так точно не будет) 
Лучше убрать?

2024-09-14 21:58 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private String internshipName;
Посмотри вот здесь
https://rukovodstvo.net/posts/id_799/
А ещё в папке build можно посмотреть, что именно там сгенерировалось) Это если собрать проект командой build
![image](https://github.com/user-attachments/assets/94c62143-a484-4265-b345-2078e741b6f0)

2024-09-14 21:59 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +    private final LocalDateTime startDate = LocalDateTime.now();
Логику поняла! Тогда молодец, в данной ситуации это выглядит подходящим решением) Давай так оставим

2024-09-14 22:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/internship/CreateInternshipDto.java
> +@NoArgsConstructor
Оставить нужно только то, что нужно) Если по какой-то причине конструктор без параметров нужен, тогда оставляй его. Если нет и нет идей, зачем он может понадобиться, тогда удаляй. Аналогично со всем остальным) 
Меня скорее даже не наличие этих аннотаций смущает (сами по себе они ок, ничего страшного в них нет), а финальность полей)

2024-09-14 22:03 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +                    .filter(teamMember -> !teamMember.getRoles().contains(TeamRole.INTERN))
Такого рода валидации должны быть при сохранении объектов, а не в каждом гет-запросе) А то так можно вообще всему project не доверять и заново его провалидировать. Такая проверка имеет смысл только если такая ситуация возможна

2024-09-15 15:04 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +package faang.school.projectservice.service;
я видел что многие пишут в package service только интерфейс, а impl в package service.impl =)

2024-09-15 15:04 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +@Slf4j
не вижу логи, может надо убрать?

2024-09-15 15:06 UTC, aassylkhan commented
все классно написано =)

2024-09-15 15:10 UTC, aassylkhan approved these changes

2024-09-15 18:19 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +                    .filter(teamMember -> !teamMember.getRoles().contains(TeamRole.INTERN))
Я вспомнил для чего это сделано. mentorId в модели стажировки просто TeamMember. И чисто теоретически при создании стажировки человек может указать в это поле айдишник кого-то из стажеров. И чтобы такое не получилось, я проверяю, что указанный id точно не интерн.

2024-09-15 18:20 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +@Slf4j
Они есть) На 54 строке, например)

2024-09-15 18:32 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +package faang.school.projectservice.service;
Насчет этого не знаю) Я в пакеты не лезу, как получил проект, такой и отдаю😅

2024-09-18 20:18 UTC, mysosnovskaya approved these changes
Поправь две мелочи и можешь сам мержить и закрывать задачу. Аппрув ставлю.

2024-09-18 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +        } else {
else не нужно

2024-09-18 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +        } else {
else не нужно

2024-09-18 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +        } else {
else не нужно

2024-09-18 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +                    .filter(teamMember -> !teamMember.getRoles().contains(TeamRole.INTERN))
Я про это и говорю, что такие ситуации должны валидироваться при создании стажировки. Т.е. такое должно быть невозможно создать

2024-09-18 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +@Slf4j
Их нельзя убирать, наоборот нужно добавлять, тем более в сервисе)

2024-09-18 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +package faang.school.projectservice.service;
Строго правила нет, часто даже в одном пакете service находятся и интерфейсы, и реализации, а когда классов в пакете становится много, то выделяют подпакеты по логике классов. Но встречаются и такие варианты, когда интерфейсы или реализации в отдельном пакете

2024-09-18 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +        interns.addAll(passedInterns);
Наверное, ты хотел сделать retainAll?
https://docs.oracle.com/javase/8/docs/api/java/util/List.html#retainAll-java.util.Collection-

2024-09-18 22:02 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/InternshipServiceImpl.java
> +package faang.school.projectservice.service;
Я только сейчас понял о чем вообще был комментарий. Я ответил не на то 😅 Отвечу сейчас. Мне такое не попадалось. Пока не вижу смысла разделять. Надо посмотреть, как общий проект выглядеть будет, если будет "грязно", выделим, а пока так оставлю)

2024-09-18 22:11 UTC, merged