Features/stages of project bjs2 27589
CorporationX/project_service pull request #616
Opened 2024-09-14 06:35 UTC by DankeVilletti

2024-09-15 10:36 UTC, ChibixAnastasia approved these changes

2024-09-15 10:37 UTC, ChibixAnastasia approved these changes

2024-09-15 10:37 UTC, ChibixAnastasia approved these changes

2024-09-15 10:40 UTC, ChibixAnastasia approved these changes

2024-09-15 10:41 UTC, ChibixAnastasia approved these changes

2024-09-15 10:50 UTC, ChibixAnastasia approved these changes

2024-09-15 10:51 UTC, ChibixAnastasia approved these changes

2024-09-15 10:57 UTC, ChibixAnastasia approved these changes

2024-09-15 10:58 UTC, ChibixAnastasia approved these changes

2024-09-15 10:58 UTC, ChibixAnastasia approved these changes

2024-09-16 18:31 UTC, mysosnovskaya requested changes

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/validation/TaskStatusValidator.java
> +        if(!TaskStatus.getAll().contains(taskStatus)){
А как такое может быть, что одно из значений перечисления не найдется в среди всех возможных значений этого перечисления? Аналогичный вопрос в других аналогичных проверках

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +    private final EntityValidator entityValidator;
Я тебе очень рекомендую познакомиться с валидацией с помощью аннотаций 
https://struchkov.dev/blog/ru/spring-boot-validation/
Сейчас эти валидаторы выглядят страшно, тем более это костыли, т.к. есть уже готовые решения =)

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/validation/StageRolesValidator.java
> +        rolesWithAmount.entrySet()
Если (а я надеюсь когда) будешь делать валидацию с помощью аннотаций, то чтобы заменить эту валидацию рекомендую сделать так: создать отдельный dto класс с полями TeamRole и Integer, и вместо Map использовать List этих объектов. Или Set, чтобы гарантировать уникальность, но в этом случае внимательно поработай с методами equals и hashcode

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/jpa/StageJpaRepository.java
> +    @Modifying
Зачем здесь Modifying? Запрос же ничего не изменяет в базе данных

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/jpa/StageJpaRepository.java
> +    List<Stage> findStagesByProjectAndFilters(
Тебе похоже понравилось писать свои запросы к базе?) Вообще спринг позволяет делать это проще, используя запросные методы. Но т.к. базы данных это тема будущих спринтов, то исправлений здесь не жду (только если тебе захочется изучить тему заранее)
https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/jpa/TeamMemberJpaRepository.java
> +    TeamMember findByUserIdAndProjectId(@Param("userId") long userId, @Param("projectId") long projectId);
А без Param не работает?

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +        return null;
Это корректно? Почему?

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +        return null;
И это тоже корректно?

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +public interface StageMapper {
Отличная работа с маппером, много возможностей используешь)

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/taskActionAfterDeletingStage/TaskActionAfterDeletingStage.java
> +public enum TaskActionAfterDeletingStage {
Пустая строчка нужна

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/taskActionAfterDeletingStage/TaskActionAfterDeletingStage.java
> +public enum TaskActionAfterDeletingStage {
Страшненькое название) Может быть это какая-то стратегия? DeleteStageStrategy может?

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/taskActionAfterDeletingStage/TaskActionAfterDeletingStage.java
> +package faang.school.projectservice.model.taskActionAfterDeletingStage;
Пакеты называют только через точку или слитно, camelCase для пакетов не используется. И это слишком длинное имя для пакета)

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/taskActionAfterDeletingStage/TaskActionAfterDeletingStageAbstract.java
> +
Слишком много пустых строчек)

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/taskActionAfterDeletingStage/TaskActionReassign.java
> +        };
Стиль поплыл

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/taskActionAfterDeletingStage/TaskActionAfterDeletingStageAbstract.java
> +public abstract class TaskActionAfterDeletingStageAbstract {
Круто, что ты заметил общность и выделил такую абстракцию 👍 Я бы только над названием поработала)

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/repository/ProjectRepository.java
> +import faang.school.projectservice.model.stage.Stage;
Это зачем?)

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/repository/ProjectRepository.java
> +
И это не нужно

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/repository/TaskRepository.java
> +    List<Task> findAllById(List<Long> taskIds);
Такой метод уже есть в JpaRepository

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/repository/TaskRepository.java
> +public interface TaskRepository extends JpaRepository {
У JpaRepository обязательно нужно прописать типы в <>

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageRolesService.java
> +public class StageRolesService {
Логирование нужно добавить

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageRolesService.java
> +        stageInvitationRepository.save(invitation);
Может быть собрать все приглашения и затем сделать saveAll?

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageService.java
> +    private final TaskActionClose taskActionClose;
TaskActionClose, TaskActionDelete и TaskActionReassign можно собрать в одно целое: с помощью спринга собрать здесь List<TaskActionAfterDeletingStageAbstract>, а затем этот список преобразовать в Map<TaskActionAfterDeletingStage, TaskActionAfterDeletingStageAbstract>. Затем из этой мапы можно будет брать сразу нужный обработчик по значению перечисления, без switch. Это сложная, но красивая идея. Рекомендую сделать так, а если не получится - приходи, обсудим)

2024-09-16 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageService.java
> +    public StageDto updateStage(StageDto stageDto) {
Метод получился довольно объемным. Попробуй вынести какую-то его часть (или части) в приватный метод

2024-09-17 07:22 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/controller/validation/TaskStatusValidator.java
> +        if(!TaskStatus.getAll().contains(taskStatus)){
не знаю
я думал фронт передает по сути просто строку или это не так?

2024-09-17 17:20 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +        return stageRoles.stream()
нужно учесть случай, когда stageRoles is null
иначе stageRoles.stream() может вылететь с ошибкой.
Можно это сделать так:
``` 
if (stageRoles == null) {
return null;
}
```

2024-09-17 17:20 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +        return tasks.stream().map(Task::getId).toList();
аналогично выше нужно учесть ситуацию с null

2024-09-17 17:20 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +        return executors.stream().map(TeamMember::getUserId).toList();
аналогично выше нужно учесть ситуацию с null

2024-09-17 17:20 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        switch (taskAction) {
можно через мапу ещё сделать - ключ taskAction - значение объект,который реализует интерфейс, от которого наследуются классы TaskActionClose, TaskActionDelete, TaskActionReassign.
если не удалось получить значение по ключу, то вызывается то, что в блоке default, иначе вызывается метод execute у полученного объекта

Только я хз насколько в такое нужно упарываться

2024-09-18 19:41 UTC, mysosnovskaya requested changes

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/client/TeamRoleDto.java
> +public record TeamRoleDto () {
Пробел лишний)

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/client/TeamRoleDto.java
> +@Component
Аннотация не нужна

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/stage/StageRolesDto.java
> +public record StageRolesDto(@EqualsAndHashCode.Include TeamRole teamRole,
Отлично, что использовал @EqualsAndHashCode.Include 👍 Убедись только, что всё это корректно работает с record. Тесты помогут)

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +    StageDto toDto(Stage stage);
Лучше toStageDto, а то мало ли какие ещё dto потом могут появиться) Да и конкретики больше, читаемость повышается

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +    List<StageDto> toDtos(List<Stage> stages);
toStageDtos

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +    Stage toEntity(StageDto stageDto);
toStage, т.к. Entity - слишком абстрактно

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +    List<Stage> toEntities(List<StageDto> stageDtos);
toStages

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +        return stageRoles.stream()
Почему этот комментарий помечен как resolved, но ни исправления, ни ответа нет?)

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +        // Загружаем задачи по ID (пример с подгрузкой задач)
Комментарий лишний

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/StageMapper.java
> +                    Task task = new Task();
Может быть будет проще добавить в Task конструктор с одним параметром id?

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/DeleteStageStrategy.java
> +public enum DeleteStageStrategy {
Пустой строчки не хватает) По названию ещё идея пришла DeleteStageTaskStrategy, чтобы подчеркнуть, что именно делать с задачами. Хотя уже длинно получается, не очень красиво. Можно ещё DeleteTaskStrategy

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/DeleteStageStrategyAbstract.java
> +
Лишние пустые строчки

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/DeleteStageStrategyAbstract.java
> +    public abstract DeleteStageStrategy getMethod();
А между методами пустых строчек не хватает

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/TaskActionProcessor.java
> +                        throw new IllegalArgumentException("Task action method is null");
Вообще говоря такого не должно быть, это значит разработчик накосячил и такую обработку не нужно в код закладывать) Это должно быть отловлено на этапе тестов и ревью

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/DeleteStageStrategyAbstract.java
> +public abstract class DeleteStageStrategyAbstract {
DeleteStageStrategyExecutor может быть? В названии класса обязательно должно быть существительное, которое отвечает на вопрос "что это за класс". В моем варианте ответом будет - это класс executor. А в твоем текущем такого конкретного ответа нет

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/taskactions/TaskActionClose.java
> +public class TaskActionClose extends DeleteStageStrategyAbstract {
Класс нужно переименовать в соответствии с родительским классом. Здесь это может быть CloseTaskStrategy(Executor). Вообще в коде не должно ничего остаться про task action, т.к. это уже осталось от старой логики. Теперь у нас стратегии

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageRolesService.java
> +            @Min(1) Long stageId,
А эта аннотация Min точно работает?)

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        updateStageName(stage, stageDto.stageName());
В этом случае выносить одну строчку в отдельный метод не стоит, т.к. это никак не упрощает метод

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        updateStageTasks(stage, tasks);
В этом методе тоже необходимости нет

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        sendRoleInvitations(stageDto, stage, currentRoleCountMap);
А вот это хорошо

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        updateStageExecutors(stage, executors);
Тоже не стала бы так делать

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        Map<TeamRole, Long> currentRoleCountMap = getCurrentRoleCountMap(stage);
Это тоже хорошо

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/TaskActionProcessor.java
> +public class TaskActionProcessor {
Круто с мапой получилось, молодец, что реализовал эту идею 👍 Я только сомневаюсь по поводу отдельного класса TaskActionProcessor. Почему решил вынести? Разве сервис сильно перегружался от этой логики?

2024-09-18 19:41 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/StageServiceTest.java
> +public class StageServiceTest {
Тесты ещё планируешь дописать, я верно понимаю? Если нет, то запланируй) Т.к. сейчас их всего два

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/validation/TaskStatusValidator.java
> +        if(!TaskStatus.getAll().contains(taskStatus)){
Фронт да, но ты в методе принимаешь TaskStatus - это уже не просто строка, а строка, преобразованная в одно из значений TaskStatus. Не получится сделать преобразование в несуществующее значение) Об этом спринг позаботится

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/jpa/TeamMemberJpaRepository.java
> +    TeamMember findByUserIdAndProjectId(@Param("userId") long userId, @Param("projectId") long projectId);
Вопрос остается

2024-09-18 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageRolesService.java
> +public class StageRolesService {
Всё ещё не хватает логгирования, хотя комментарий помечен как resolved

2024-09-19 16:57 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/jpa/TeamMemberJpaRepository.java
> +    TeamMember findByUserIdAndProjectId(@Param("userId") long userId, @Param("projectId") long projectId);
findByUserIdAndProjectId из-за согласованности имени в запросе и видимо понимает имена переменных

2024-09-20 18:45 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageRolesService.java
> +public class StageRolesService {
Ещё актуально

2024-09-20 18:45 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageRolesService.java
> +            @Min(1) Long stageId,
Ещё актуально

2024-09-20 18:45 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/TaskActionProcessor.java
> +public class TaskActionProcessor {
Интересно было бы почитать здесь твой ответ)

2024-09-20 18:54 UTC, mysosnovskaya requested changes
Осталось совсем чуть-чуть и будем мержить)

2024-09-20 18:54 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/taskactions/CloseTaskStrategy.java
> +public class CloseTaskStrategy extends DeleteStageStrategyExecutor {
CloseTaskStrategyExecutor

2024-09-20 18:54 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/taskactions/DeleteTaskStrategy.java
> +public class DeleteTaskStrategy extends DeleteStageStrategyExecutor {
DeleteTaskStrategyExecutor

2024-09-20 18:54 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/taskactions/ReassignTaskStrategy.java
> +public class ReassignTaskStrategy extends DeleteStageStrategyExecutor {
ReassignTaskStrategyExecutor

2024-09-20 18:54 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/DeleteStageProcessor.java
> +package faang.school.projectservice.model.stage.strategy.delete;
Нужно поработать с пакетами. Классы DeleteStageProcessor  и DeleteStageStrategyExecutor не относятся к моделям, они должны быть в сервисном слое, также как и реализации для DeleteStageStrategyExecutor. И пакет taskaction нужно либо переименовать, либо вообще не выделять) Пусть всё в одном будет. Думаю, в данной ситуации это нормально)

2024-09-20 18:54 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/StageRolesService.java
> +    public void sendInvitationsForRole(Stage stage, TeamRole role, long invitationsToSend) {
На этот метод нужны тесты

2024-09-20 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/StageServiceTest.java
> +    void testSuccess_deleteStage() {
Нужен ещё неуспешный тест)

2024-09-20 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/StageServiceTest.java
> +}
Не хватает тестов на updateStage метод, хотя там куча логики

2024-09-21 06:19 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/model/stage/strategy/delete/TaskActionProcessor.java
> +public class TaskActionProcessor {
Мне кажется, что при добавлении каких-то новых вещей, которые будут дополнительно происходить с удалением этапа их было бы удобно в отдельном классе добавлять, чтобы не смешивать с логикой в сервисе которая содержать может прочие несвязанные методы

2024-09-21 16:34 UTC, mysosnovskaya approved these changes

2024-09-21 16:34 UTC, merged