Подпроекты
CorporationX/project_service pull request #619
Opened 2024-09-14 19:29 UTC by ArstanSubanov

2024-09-14 19:49 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +            throw new IllegalArgumentException("You cannot update a project, because the subprojects statuses are not suitable. ID: " + subProjectDto.getId());
думаю, лучше сделать перенос трой строки, а то очень длинная выходит
визуально выделяется на фоне остальных)

2024-09-14 19:52 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/dto/responses/ErrorResponse.java
> +public record ErrorResponse(String message) {
Прикольно, про рекорд в ошибках я не додумался 😅

2024-09-14 20:04 UTC, wmwmaks approved these changes
Я ничего критичного не увидел. По логике мне оценить сложно, потому что плохо знаю, что должен делать код и как. Нужно будет изучить. Думаю, парни получше изучат)

2024-09-14 20:32 UTC, SharkB38 approved these changes

2024-09-14 20:32 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        if (parentProject.getVisibility() == ProjectVisibility.PUBLIC && subProjectDto.getVisibility() == ProjectVisibility.PRIVATE) {
А наоборот разрешается?

2024-09-15 07:35 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +            throw new IllegalArgumentException("You cannot update a project, because the subprojects statuses are not suitable. ID: " + subProjectDto.getId());
Хорошо, в следующем коммите перенесу, спасибо)

2024-09-15 07:39 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        if (parentProject.getVisibility() == ProjectVisibility.PUBLIC && subProjectDto.getVisibility() == ProjectVisibility.PRIVATE) {
В условии было сказано только про то, что публичному проекту нельзя создать приватный подпроект. А значит наоборот должно быть возможно, если я правильно понял задачу)

2024-09-15 15:22 UTC, aassylkhan reviewed
Хорошо написано =)

2024-09-15 15:22 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +package faang.school.projectservice.controller;
кажется нужен package подпроекты

2024-09-15 15:22 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    @PutMapping
тут нужен айди {subProjectId}

2024-09-15 15:22 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/dto/subproject/SubProjectDto.java
> +    private LocalDateTime createdAt;
кажется нужен по дефолту LocalDateTime.now() и не получать их от фронта

2024-09-15 15:22 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectService.java
> +    SubProjectDto create(SubProjectDto subProjectDto);
createSubProject? @wmwmaks

2024-09-15 15:22 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        if (subProjectDto.getStatus() == null) {
а почему сразу статус CREATED не сделать? даже не проверяя. Потому что у тебя метод create =)

2024-09-15 15:22 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        Stream<Project> subProjects = projectRepository.getProjectById(parentId).getChildren().stream()
мне Маша говорила что не надо обращаться к бд каждый раз и получить разом через findAllById. Тут кажется такая же ситуация =)

2024-09-15 16:33 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +package faang.school.projectservice.controller;
Хорошо, добавлю в след PR)

2024-09-15 16:34 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    @PutMapping
Я в DTO передаю Id, поэтому не видел смысла тут)

2024-09-15 16:36 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/dto/subproject/SubProjectDto.java
> +    private LocalDateTime createdAt;
LocalDateTime можно проигнорировать и не задавать, благодаря аннотации @JsonInclude

2024-09-15 16:38 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectService.java
> +    SubProjectDto create(SubProjectDto subProjectDto);
Подумал что раз сервис называется SubProjectService и других сущностей не создаётся, то нет необходимости везде писать SubProject)

2024-09-15 16:40 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        if (subProjectDto.getStatus() == null) {
Я предполагал, что могут создать проект с любым статусом и если он не задан создать по дефолту. Я ещё подумаю об этом перед след PR, спасибо)

2024-09-15 16:50 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        Stream<Project> subProjects = projectRepository.getProjectById(parentId).getChildren().stream()
Да, соглашусь, тут можно было сразу получать список подпроектов по id родительского проекта, спасибо)

2024-09-15 17:03 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectService.java
> +    SubProjectDto create(SubProjectDto subProjectDto);
@aassylkhan Маша писала, что это некритично и каких-то правил касаемо этих названий нет) Поэтому теперь я такое не отмечаю, как кому удобно)

2024-09-16 09:49 UTC, mysosnovskaya requested changes

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +package faang.school.projectservice.controller;
Необязательно выделять подпакеты на этом этапе. Вот если в пакете controller соберется классов 8, то тогда можно будет подумать, как их разбить на подпакеты. А может быть этот микросервис вообще не будет развиваться и там останется всего 5 контроллеров, тогда смысла в подпакетах нет

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    @Operation(summary = "New Sub Project Creation")
Сваггер подвезли, это хорошо 👍

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    @PutMapping
По правилам проектирования апи корректно будет передавать id именно в пути, поэтому с комментарием согласна, но он из будущего (седьмого) спринта)

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    public SubProjectDto updateSubProject(@Validated(UpdateGroup.class) @RequestBody SubProjectDto subProjectDto) {
Валидация по группам, круто 👍

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    @PostMapping("/sub-projects-by-filter/{parentId}")
Это должен быть get  маппинг, судя по смыслу метода

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +    public ConstraintErrorResponse onConstraintValidationException(ConstraintViolationException e) {
Метод тоже можно назвать handle...

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        if (parentProject.getVisibility() == ProjectVisibility.PUBLIC && subProjectDto.getVisibility() == ProjectVisibility.PRIVATE) {
Хороший вопрос и хороший ответ) Молодцы! В идеале на реальном проекте этот вопрос лучше было бы уточнить у аналитика (или у автора задачи)

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        subProject = projectRepository.save(subProject);
Обрати внимание: у тебя в subProjectDto может прийти id, тогда логика создания поломается

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        if (subProjectDto.getStatus() == null) {
Согласна, я бы не разрешала создавать проекты в других статусах. Выглядит логичным всегда ставить статус CREATED при создании

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        subProject = projectRepository.save(subProject);
А имя и описание нельзя обновить?

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        Stream<Project> subProjects = projectRepository.getProjectById(parentId).getChildren().stream()
Верно, давайте исправим

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +    private boolean checkIfAllSubProjectsOfCurrentProjectHaveSameStatus(Project subProject) {
` private boolean checkIfAllSubProjectsHaveSameStatus(Project project) {`

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +    private boolean checkIfAllSubProjectsAreClosed(Project subProject) {
Параметр можно переименовать в project, здесь нет никакой разницы, является ли он чьим-то подпроектом

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/subproject/SubProjectDto.java
> +    @NotNull(groups = UpdateGroup.class, message = "Visibility can't be null when updating")
Почему? А если я просто статус проекта хочу изменить, а visibility не хочу менять?

2024-09-16 09:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/subproject/SubProjectDto.java
> +    private LocalDateTime createdAt;
JsonInclude это про сериализацию. Если в объекта этого класса поле createdAt будет равно null, то в json этого поля не будет вообще. 
![image](https://github.com/user-attachments/assets/df808bd4-7cec-4cee-8976-e7da6312b5d2)

2024-09-17 16:28 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    @PostMapping("/sub-projects-by-filter/{parentId}")
В @GetMapping не работал @RequestBody, SubProjectFilterDto выходил пустым и возвращал ошибку что фильтр не найден, поэтому вернул обратно @PostMapping

2024-09-17 19:02 UTC, mysosnovskaya requested changes

2024-09-17 19:02 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    @PostMapping("/sub-projects-by-filter/{parentId}")
Вообще это возможно, просто не нужна аннотация RequestBody. И из постмана это будет выглядеть не как json, а как параметры запроса (?param1=value1&param2=value2) - вот так и будет правильнее такие эндпоинты реализовывать)
https://medium.com/@pandaniel/spring-boot-controllers-getmapping-and-complex-objects-bd182ec99f54

2024-09-17 19:02 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        if (!checkIfAllSubProjectsHaveSameStatus(subProject)) {
Мне кажется, можно проще:
приватный метод `Set<ProjectStatus> getStatusesOfSubProjects(Project project)`;
далее, если этот Set имеет размер 1, то значит у всех статус одинаковый, иначе исключение;
далее, если этот Set содержит статус COMPLETED и у subProject тоже этот статус, то создаем момент.

На мой взгляд, так будет понятнее, чем методы checkIfAllSubProjectsHaveSameStatus и checkIfAllSubProjectsAreClosed. Что думаешь?

2024-09-17 19:02 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +            subProject.setChildren(subProjects);
Эта строчка не нужна, список subProjects находится в памяти, поэтому делая setVisibility изменения происходят и в поле children

2024-09-17 19:02 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/subproject/request/UpdatingRequest.java
> +    @NotBlank(message = "Project name can't be null or empty")
Вообще теоретически это и другие поля могут быть null. Например, если нужно обновить только имя, то другие три поля будут null. Обновлять нужно только not null поля

2024-09-17 19:02 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/subproject/request/UpdatingRequest.java
> +public class UpdatingRequest {
По условию задачи обновить можно только статус и видимость. Я в прошлый раз задавала вопрос, это было уточнение, а не призыв к исправлению)

2024-09-17 19:02 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +            throw new IllegalArgumentException("You cannot update a project, " +
Мне кажется, нужно ещё подумать над логикой. Я не понимаю, почему я не могу обновить проект, например, в статус CANCELLED, если у него часть подпроектов в статусе CREATED, а часть - в IN_PROGRESS. Как будто бы это условие вообще касается только перевода проекта в статус COMPLETED. Если так, то мой комментарий с предыдущей строки уже не имеет смысла)

2024-09-17 19:02 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +            throw new IllegalArgumentException("You cannot update a project, " +
Если это так, то метод update я бы переработала так:
```
               Project subProject = projectRepository.getProjectById(projectId);
              // проверка, если updatingRequest.status == COMPLETED, то все подпроекты должны иметь такой же статус. Если это так, то создать момент, иначе сгенерировать исключение
        subProject.setStatus(updatingRequest.getStatus());

       // делаем обновление видимости. это даже можно вынести в приватный метод updateVisability, т.к. код метода update уже довольно объемный, хотя в целом всё ещё вполне читаемый, поэтому выносить необязательно
        subProject.setVisibility(updatingRequest.getVisibility());
        if (subProject.getVisibility() == ProjectVisibility.PRIVATE) {
            List<Project> subProjects = subProject.getChildren();
            subProjects.forEach(p -> p.setVisibility(ProjectVisibility.PRIVATE));
            subProject.setChildren(subProjects);
        }

        subProject.setUpdatedAt(LocalDateTime.now());
        subProject = projectRepository.save(subProject);
        log.info("Updated sub-project with id {}", subProject.getId());
        return subProjectMapper.toSubProjectDto(subProject);
```

2024-09-17 19:02 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +    private Moment createMomentIfSubProjectClosed(Project project) {
А зачем в названии этот `IfSubProjectClosed`? В методе же нет этой проверки

2024-09-18 07:24 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    @PostMapping("/sub-projects-by-filter/{parentId}")
Хорошо, спасибо)

2024-09-18 07:24 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/dto/subproject/request/UpdatingRequest.java
> +    @NotBlank(message = "Project name can't be null or empty")
Хорошо, исправлю)

2024-09-18 07:30 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +            throw new IllegalArgumentException("You cannot update a project, " +
Я по условию "При этом проверить, все подпроекты текущего подпроекта имеют тот же статус.", подумал что если родительский проект хотят обновить, то сначала нужно обновить подпроекты. Например, что родительский проект будет в процессе, только если все его подпроекты будут в процессе. Так получается что родительский проект сильно зависит от подпроектов. Если это условие можно пересмотреть, то согласен, что логичнее просто проверять на завершение подпроектов перед закрытием родительского проекта)

2024-09-18 07:33 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        if (!checkIfAllSubProjectsHaveSameStatus(subProject)) {
Да, такой способ выглядит в разы лучше, но я хочу ещё подумать над реализацией этих методов, так как хочу проверять статус не только на COMPLETED, но и на CANCELLED, так как вроде тоже проект будет закрыт при таком статусе)

2024-09-18 07:34 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +            subProject.setChildren(subProjects);
Хорошо, уберу, спасибо)

2024-09-18 07:34 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +    private Moment createMomentIfSubProjectClosed(Project project) {
Понял, уберу)

2024-09-18 20:00 UTC, mysosnovskaya reviewed
Хорошо получилось) Я почти готова ставить аппрув и мержить, не забудь только разрешить конфликт. С ним смержить не получится

2024-09-18 20:00 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/subproject/request/UpdatingRequest.java
> +    private String name;
Решил оставить возможно обновлять имя и описание? Хорошо, пусть остается, я не против)

2024-09-18 20:00 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        boolean childrenEndedStatus = subProject.getChildren().stream()
allChildrenAreFinished (глагол end немного про другое). В названии метода checkIfProjectEnded аналогично. Можно переименовать в isProjectFinished

2024-09-18 20:00 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/subproject/impl/SubProjectServiceImpl.java
> +        if (checkIfProjectEnded(subProject) && childrenEndedStatus) {
Предложу чуть по-другому написать, хотя твой вариант тоже хороший. Мне не нравится только два раза вызывать `checkIfProjectEnded(subProject)`
```
        if (checkIfProjectEnded(subProject)) {
            if (!childrenEndedStatus) {
                throw new IllegalArgumentException("You cannot update a project, " +
                        "because the subprojects statuses are not suitable. ID: " + projectId);
            }
            Moment moment = createMoment(subProject);
            subProject.getMoments().add(moment);
        }
```

2024-09-19 18:28 UTC, mysosnovskaya approved these changes

2024-09-19 18:29 UTC, merged