stage invitation
CorporationX/project_service pull request #625
Opened 2024-09-16 09:24 UTC by aassylkhan

2024-09-16 11:06 UTC, SharkB38 requested changes

2024-09-16 11:06 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/mapper/StageInvitationMapper.java
> +@Mapper(componentModel = "spring")
unmappedTargetPolicy не добавил, или так и задумано?

2024-09-16 11:06 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/stage_invitation/StageInvitationService.java
> +    @Validated(CreateGroup.class)
Как-будто бы было лучше провалидировать в контроллере

2024-09-16 11:06 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/stage_invitation/impl/StageInvitationServiceImpl.java
> +        if (filters.containsKey("invitedId")) {
Не уверен насчет такой реализации фильтров. Можешь в лекции Влада глянуть как там предлагается или у остальных ребят посмотреть

2024-09-16 11:06 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/stage_invitation/impl/StageInvitationServiceImpl.java
> +        invitation.setStatus(StageInvitationStatus.PENDING);
Тут можно было бы через маппер сразу сделать

2024-09-16 11:06 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/repository/StageRepository.java
> +    }
Не совсем понял зачем этот метод, getById аналогично методам findById работает, например в TeamMemberRepository

2024-09-16 11:06 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/mapper/StageInvitationMapper.java
> +    }
Тут по сути можно было указать в @Mapping(target = "stage.stageId", source = "stageId") без этого доп. метода. Маппер в своей реализации буквально тоже самое что и этот метод делает.

2024-09-16 11:07 UTC, SharkB38 commented
У нас получается с тобой друг от друга задачи зависят

2024-09-16 12:26 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/repository/StageRepository.java
> +    }
В самом проекте через него написано. Не хотел менять и соответствовать стилю

2024-09-17 03:20 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +            @PathVariable @Positive Long id, @Valid @RequestBody Map<String, String> payload) {
У тебя же есть дто DeclineInvitationDto с валидацией, думаю тут стоит заменить Map на этот дто, а то получается аннотация @Valid не используется)

2024-09-17 03:29 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/repository/StageRepository.java
> +    }
findById и getById делают почти тоже самое, не лучше ли использовать getById?)

2024-09-17 03:33 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/stage_invitation/impl/StageInvitationServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Stage not found with id: " + invitationDto.stageId()));
Если использовать getById, то можно тут не выбрасывать exception)

2024-09-19 16:22 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/stage_invitation/impl/StageInvitationServiceImpl.java
> +    private List<StageInvitationFilter> createFilters(StageInvitationFilterDto filterDto) {
мне кажется, вариант, который нам предложили на лекциях для фильтров лучше, тк дает больше гибкости, объясню: если ты повесишь над всеми имплементациями фильтров аннотацию @Component, и в сервисе заинджектишь List<StageInvitationFilter>, то у тебя спринг сам заполнит лист всеми реализациями этого интерфейса. вдруг тебя попросят добавить новый фильтр, ты будешь писать сюда эту проверку на null? не лучше тогда ее вынести в метод интерфейс фильтра, и там уже сравнивать нужное поле, а уже когда приходит объект фильтров, то брать уже фильтры, которым есть что фильтровать. посоветовал бы лекцию Влада, но там ошибка крупная(код не рабочий), можешь у ребят в проектах глянуть, у нас вроде у всех одинаково,а так молодец что сам придумал как все это делать у меня так не вышло :(

2024-09-19 16:35 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +            @Validated(CreateGroup.class) @RequestBody StageInvitationDto invitationDto) {
Мне кажется лучше убрать валидацию по группам, так как у тебя по сути только один дто для создания приглашения. Для фильтров и отказа у тебя используется другие дто и смысл группировки теряется))

2024-09-19 16:37 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +    @PostMapping("/{id}/decline")
Порекомендовал бы здесь и в acceptInvitation использовать @PutMapping, так идёт обновление уже существующих данных)

2024-09-19 16:41 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/dto/stage_invitation/StageInvitationDto.java
> +            createdAt = LocalDateTime.now();
Нужно ли поле createdAt? Просто в сущности StageInvitation я не увидел поля createdAt, и получается это поле не сохраняется никуда) Или я не заметил)

2024-09-19 16:47 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/mapper/StageInvitationMapper.java
> +    default TeamMember teamMemberFromId(Long id) {
Я думаю Валера имел ввиду, что можно убрать методы teamMemberFromId и stageFromId, и в методе toStageInvitation сделать так же, как в методе toStageInvitationDto, только поменять source и target)

2024-09-19 16:49 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/validation/UpdateGroup.java
> +public interface UpdateGroup {
Вроде бы UpdateGroup нигде не используется?)

2024-09-19 16:58 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/stage_invitation/impl/StageInvitationServiceImpl.java
> +        StageInvitation updatedInvitation = stageInvitationRepository.save(invitation);
Порекомендовал бы ещё переиспользовать переменную invitation и не создавать updatedInvitation, также и в других методах)

2024-09-19 16:59 UTC, ArstanSubanov approved these changes
Я внёс несколько предложений, можешь рассмотреть их в следующем коммите после ревью от Маши)) Если конечно, она сразу не смержит)

2024-09-20 03:22 UTC, SharkB38 approved these changes

2024-09-25 19:12 UTC, mysosnovskaya requested changes

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +            @Validated(CreateGroup.class) @RequestBody StageInvitationDto invitationDto) {
Согласна

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +            @PathVariable @Positive Long id, @Valid @RequestBody DeclineInvitationDto declineInvitationDto) {
Чтобы Positive заработала, нужна ещё одна аннотация над классом - Validated

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/stage_invitation/DeclineInvitationDto.java
> +    private String reason;
final? И почему здесь не используешь record?

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/stage_invitation/StageInvitationFilterDto.java
> +public class StageInvitationFilterDto {
record не подойдет?

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +        return ex.getMessage();
Мы не возвращаем просто строчки, т.к. их нельзя представить в формате json. Только отдельный dto-класс и обязательно логгирование. 
У нас уже есть такой хэндлер в мастер-ветки, поэтому тебе нужно подтянуть изменения)
https://github.com/CorporationX/project_service/blob/hydra-master-stream6/src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/repository/StageRepository.java
> +    }
Не понимаю, почему этот диалог закрыт без ответа? С комментариями согласна

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/stage_invitation/StageInvitationService.java
> +    StageInvitationDto acceptInvitation(@Positive Long id);
А зачем здесь Positive?)

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/stage_invitation/impl/StageInvitationServiceImpl.java
> +public class StageInvitationServiceImpl implements StageInvitationService {
Нужны логи

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/stage_invitation/impl/StageInvitationServiceImpl.java
> +            throw new IllegalArgumentException("Invitation already exists.");
В описании ошибки нужна идентифицирующая информация

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/stage_invitation/impl/StageInvitationServiceImpl.java
> +            throw new IllegalStateException("Invitation cannot be accepted in its current status.");
В описании ошибки нужна идентифицирующая информация

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/stage_invitation/impl/StageInvitationServiceImpl.java
> +            throw new IllegalStateException("Invitation cannot be declined in its current status.");
В описании ошибки нужна идентифицирующая информация

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/stage_invitation/impl/StageInvitationServiceImpl.java
> +    private List<StageInvitationFilter> createFilters(StageInvitationFilterDto filterDto) {
Согласна

2024-09-25 19:12 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/validation/UpdateGroup.java
> +public interface UpdateGroup {
Согласна

2024-09-25 19:12 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/stage_invitation/StageInvitationServiceImplTest.java
> +public class StageInvitationServiceImplTest {
Маловато тестов как-то =) Нужны ещё тесты на негативные сценарии

2024-09-26 10:13 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/repository/StageRepository.java
> +    }
Не совсем понимаю зачем мне менять код который есть в самом проекте? Я думал надо использовать готовые методы которые уже написаны

2024-09-26 19:41 UTC, mysosnovskaya requested changes

2024-09-26 19:41 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/repository/StageRepository.java
> +    }
Выше в коде в этом же классе есть getById, ничего менять не нужно. Как раз и этот метод добавлять не нужно было, достаточно было пользоваться тем, что уже есть в этом классе

2024-09-26 19:41 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/stage_invitation/StageInvitationServiceImplTest.java
> +public class StageInvitationServiceImplTest {
Тестов на негативные сценарии всё ещё не хватает)

2024-09-27 15:09 UTC, mysosnovskaya approved these changes

2024-09-27 15:09 UTC, merged