Cerberus master stream6 bjs2 26642 подпроекты
CorporationX/project_service pull request #630
Opened 2024-09-16 18:28 UTC by NurseyitTursunkulov

2024-09-16 19:30 UTC, ostermal7 reviewed
У тебя полностью отсутствует пакетирование твоих классов, это надо исправлять. Например, не controller/Subprojectcontroller, а controller/subproject/SubprojectController. И так везде, где создаешь классы.

Инфа, связанная с ошибками, должна быть в папке exception, а не util

Также считаю ошибкой создавать так много эксепшенов. Почему бы просто не передать текстом контекст ошибки, а не плодить классы?

Также не увидел где ты закрываешь подпроекты (п.2  пп.1)

Также мне показалось, что ты немного злоупотребляешь прям функциями, но тут может с непривычки.

Третий пункт я не смотрел с тестами.

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +        }
Это выглядит не очень. Ты пробрасываешь ошибки наверх что ли?

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    public CreateSubProjectDto createSubProject(CreateSubProjectDto subProjectDto){
У тебя в условии задачи сказано, что принимается в метод id, а не дто

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/dto/CreateSubProjectDto.java
> +public class CreateSubProjectDto {
Названия классов не должны начинаться с глагола, это не метод

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/dto/CreateSubProjectDto.java
> +    private String coverImageId;
Тебе в дто нужны прям все переменные?

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +            return subProjectService.createSubProject(projectMapper.toEntity(subProjectDto));
конвертацией дто в энтити должен заниматься сервис, а не контроллер

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectService.java
> +    public CreateSubProjectDto createSubProject(Project subProjectDto) throws RootProjectsParentMustNotBeNull, CannotCreatePrivateProjectForPublicParent, ParentProjectMusNotBeNull;
обрабатывай ошибки там, где ты их получаешь, зачем их выкидывать до контроллера?

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        }
Это должно быть в отдельно классе-валидаторе

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        }
разве тут должна быть ошибка? Зачем родительскому проекту родитель?

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +public class SubProjectServiceImpl implements SubProjectService {
По какому принципу у тебя нун инжектятся классы? Ты запускал в спринге это все дело? У тебя никогда репозитории не заинжектятся

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +            return subProjectService.refreshSubProject(projectMapper.toEntity(subProjectDto));
маппер в сервис

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +    public CreateSubProjectDto refreshSubProject(Project subProject) throws ChildrenNotFinishedException {
refresh имеет другой логический контекст, правильно update

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        var subproject = repository.getProjectById(subProject.getId());
а если проект не найден?

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        var result = repository.findAllByIds(project.getChildren()).stream().filter(child -> Objects.equals(nameFilter, child.getName())
Это нечитаемо в одну строчку, разбивай на строки

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        ).toList();
Зачем тебе такая запутанная логика да еще и с рекурсией в таком просто методе(функции)? Мне кажется, что это переделать

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        project.setStatus(project.getStatus());
???? Ты же не менял статус, что это за логика

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +
лишний пробел

2024-09-16 19:30 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +            project.setVisibility(project.getVisibility());
Это зачем

2024-09-17 07:28 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +            project.setVisibility(project.getVisibility());
не заметил

2024-09-17 07:55 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        ).toList();
нужно проверить все подпроекты, а подпроект внутри себя может иметь еще подпроект. Поэтому нужна рекурсия которая всех собирает.

2024-09-17 07:56 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        var subproject = repository.getProjectById(subProject.getId());
вылетит EntityNotFoundException

2024-09-17 07:57 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        var subproject = repository.getProjectById(subProject.getId());
Влад сказал что мы должны тупо выбрасывать исключение.

2024-09-17 08:04 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +public class SubProjectServiceImpl implements SubProjectService {
почему? работает вроде все.

2024-09-17 08:06 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        }
условие такое:
Создать подпроект. Принимаем идентификатор родительского проекта. При этом:

Корневой проект не имеет родительского проекта.

Подпроект ВСЕГДА имеет родительский проект.

2024-09-17 08:54 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        }
И как это противоречит моему комментарию? Ты же сам скопировал условие, которому противоречие есть) у корневого проекта не должно быть родителя. Корневой проект это project.getproject. Его корневой это project.getproject.getproject. Там должен быть нулл

2024-09-17 09:04 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +public class SubProjectServiceImpl implements SubProjectService {
Работает где? Я не вижу внедрения зависимостей, ты с дебагом запускал?

2024-09-17 09:05 UTC, ostermal7 commented
Также где тесты твоим компонентов? Как минимум не вижу сервиса

2024-09-17 10:49 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/dto/CreateSubProjectDto.java
> +public class CreateSubProjectDto {
![Screenshot 2024-09-17 at 12 49 48](https://github.com/user-attachments/assets/861d5f4d-f804-4f04-aaec-9ba275813411)

2024-09-17 10:51 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/dto/CreateSubProjectDto.java
> +public class CreateSubProjectDto {
![Screenshot 2024-09-17 at 12 51 08](https://github.com/user-attachments/assets/27df40e4-4f02-48f0-a305-a21642440006)

2024-09-17 11:50 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +        }
а что с ними делать то?

2024-09-17 11:52 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +        }
Удалить это все? Зачем тебе это

2024-09-17 12:02 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        var subproject = repository.getProjectById(subProject.getId());
Я имею ввиду, что у тебя есть ряд действий в функцияз над null обхектом. У тебя там дальше ничег оне отвалится? Ты проверял такой вариант тестами?

2024-09-17 12:35 UTC, NurseyitTursunkulov commented
> Member
пакетирование исправил

на мой взгляд создание ексепшенов оправдано, на фронте будет легче разобрать что делать.

"Также не увидел где ты закрываешь подпроекты (п.2 пп.1)" это реализовано в функции ifStatusIsComletedCheckThatChildrensAreCompleted

"Также мне показалось, что ты немного злоупотребляешь прям функциями, но тут может с непривычки." -  мне кажется функциональный подход он намного лучше

"Третий пункт я не смотрел с тестами." он есть просто не был добавлен в котролер (уже добавил)

2024-09-17 13:55 UTC, 108ardev reviewed
По хорошему тебе надо весь проект протестировать в Postman
Посмотри лекции с последнего спринта про RestController, ResponseBody и тд
Тебе нужно использовать все эти аннотации

2024-09-17 13:55 UTC, 108ardev commented on src/main/java/faang/school/projectservice/controller/subproject/SubProjectController.java
> +    SubProjectService subProjectService;
нужно поставить модификаторы доступа
private final
+ ты не инжектишь поле, тебе нужно либо создать конструктор с этим полем в аргументе, либо поставить аннотацию RequiredArgsConstructor над классом

2024-09-17 13:55 UTC, 108ardev commented on src/main/java/faang/school/projectservice/controller/subproject/SubProjectController.java
> +        }
всю валидацию выноси в отдельный класс

2024-09-17 13:55 UTC, 108ardev commented on src/main/java/faang/school/projectservice/controller/subproject/SubProjectController.java
> +    public SubProjectDto createSubProject(Long projectId){
Тебе в аргументы нужно передавать SubProjectDto

2024-09-17 13:55 UTC, 108ardev commented on src/main/java/faang/school/projectservice/controller/subproject/SubProjectController.java
> +    }
Посмотри воркшоп про фильтры, как правильно их делать с точки зрения SOLID
В аргументе метода должно быть DTO с полями по которым фильтруешь а не сами поля

2024-09-17 13:55 UTC, 108ardev commented on src/main/java/faang/school/projectservice/dto/subproject/SubProjectDto.java
> +}
1) Для всех DTO можешь теперь использовать record
Это специальный класс в java который является не изменяемым и прекрасно подходит для dto
Также можешь использовать здесь валидацию полей в виде аннотаций и тогда не придется многое валидировать вручную в контроллере, достаточно будет поставить аннотацию Valid или Validated в аргументе контроллера

2024-09-17 13:55 UTC, 108ardev commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectService.java
> +    public SubProjectDto updateSubProject(SubProjectDto subProjectDto) throws ChildrenNotFinishedException;
ты можешь сделать так, чтобы все эти эксепшены которые у тебя находятся в сигнатуре наследовались от рантайма, тогда тебе не придется пробрасывать их наверх

2024-09-17 13:55 UTC, 108ardev commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectServiceImpl.java
> +    private SubProjectValidator validator;
Ты должен сделать эти поля final и заинжектить их либо через конструктор либо через аннотацию RequiredArgsConstructor

2024-09-17 15:49 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/controller/subproject/SubProjectController.java
> +    public SubProjectDto createSubProject(Long projectId){
изначально было дто, но там в коменте выше сказали только айди отправлять. Поэтому исправил

2024-09-17 16:41 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/service/SubProjectServiceImpl.java
> +        var subproject = repository.getProjectById(subProject.getId());
не покрывал тестами, но репозиторий выкидывает ексепщн.

2024-09-17 18:13 UTC, mikhailov26 requested changes

2024-09-17 18:13 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/exception/ThrowingConsumer.java
> +
Никаких лишних комментариев в коде, убери пожалуйста

2024-09-17 18:13 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectServiceImpl.java
> +import static faang.school.projectservice.model.ProjectStatus.COMPLETED;
статические импорты всегда до обычных

2024-09-17 18:13 UTC, mikhailov26 commented on src/test/java/faang/school/projectservice/validator/SubProjectValidatorImplTest.java
> +
Дублирование кода

2024-09-17 18:13 UTC, mikhailov26 commented on src/test/java/faang/school/projectservice/validator/SubProjectValidatorImplTest.java
> +                .build();
Вынеси создание проектов в отдельный метод(ы), так чтобы это было гибко. Например чтобы ты смог задавать видимость проекта в параметрах метода

2024-09-17 18:13 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/dto/subproject/SubProjectDto.java
> +}
В целом совет дельный, не жёсткая рекомендация конечно, но это довольно упростит жизнь

2024-09-17 18:13 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/controller/subproject/SubProjectController.java
> +    public SubProjectDto updateSubProject(SubProjectDto subProjectDto) {
Проверка на прилетающий дто, что он не пустой, как каз подойдёт совет Андрея про рекорд

2024-09-18 18:10 UTC, ostermal7 reviewed
Уже, вроде писал, что тебе надо раскидать свои новые классы по пакетам. Например фильтры в filter/project, validator/subproject.

Насчет фильтров - почему ты решил делать не как у остальных? Онон не сработает у тебя через reduce? просто не оч нравится, что ты в apply используешь isapplicable.

И не увидел теста контроллера

2024-09-18 18:10 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/controller/subproject/SubProjectController.java
> +    @ResponseStatus(HttpStatus.CREATED)
если я правильно помню, что по дефолту идет подобный ответ

2024-09-18 18:10 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/controller/subproject/SubProjectController.java
> +    public ProjectDto updateSubProject(@PathVariable @NotNull Long projectId, @RequestBody SubProjectDto subProjectDto) {
на этом уровне должна валидироваться дто через @Valid

2024-09-18 18:10 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/controller/subproject/SubProjectController.java
> +    public List<ProjectDto> getAllSubProjectsWithFiltr(@PathVariable @NotNull Long projectId, @RequestBody ProjectFilterDto filtrDto) {
same

2024-09-18 18:10 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/exception/ChildrenNotFinishedException.java
> +    }
Здесь разве не прокатит просто супер конструктор без лишнего файнал поля?

2024-09-18 18:10 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/exception/ChildrenNotFinishedException.java
> +public class ChildrenNotFinishedException extends RuntimeException{
Странное имя для экспешн класса, если честно. Оно ни о чем не говорит пользователю

2024-09-18 18:10 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/mapper/ProjectMapper.java
> +        unmappedTargetPolicy = ReportingPolicy.IGNORE)
уверен, что оба нужны?

2024-09-18 18:10 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectService.java
> +    public List<ProjectDto> getAllSubProjectsWithFiltr(Long projectId, ProjectFilterDto filtrDto);
зачем интерфейсу паблик доступ

2024-09-18 18:10 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectServiceImpl.java
> +@Getter
зачем тут геттер?

2024-09-18 18:10 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectServiceImpl.java
> +        }
projectfilters.foreach?

2024-09-18 18:10 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/validator/SubProjectValidator.java
> +}
интерфейс с какой целью создан?

2024-09-18 20:20 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/validator/SubProjectValidator.java
> +}
так ведь до этого говорили пол SOLID последняя D. только из за этого добавил

2024-09-18 20:23 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectServiceImpl.java
> +        }
там  final variable нужен, поэтому не могу так.

2024-09-18 20:23 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/validator/SubProjectValidator.java
> +}
На валидатор-то зачем?) У валидатора не нужна абстракция, он создается под конкретный класс

2024-09-18 20:38 UTC, NurseyitTursunkulov commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectServiceImpl.java
> +@Getter
нужен для тестов

2024-09-18 20:50 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/subproject/SubProjectServiceImpl.java
> +@Getter
А почему ты так тестируешь функции? Они должны быть в рамках сервис метода же

2024-09-18 21:24 UTC, NurseyitTursunkulov commented
> Рекорд класы заменил на обычные, потомучто выходят проблемы на тестах контроллера. Ибо нужно кучу настроек делать.
> 
> Насчет фильтров - тупо скопировал у другой команды , моя релиазация была вообще по другому. 
> 
> тесты контроллера добавил.

2024-09-19 08:57 UTC, merged