Feature bjs2 26077
CorporationX/project_service pull request #634
Opened 2024-09-16 22:42 UTC by Silencemess1ah

Создание стажировок

2024-09-17 05:35 UTC, Killhimka commented on src/main/java/faang/school/projectservice/validator/intership/InternshipValidator.java
> +        teamMemberRepository.findById(internshipDto.getMentorId().getId());
А тут что происходит? Зашли в базу вытащили по ид, а дальше?

2024-09-17 05:35 UTC, Killhimka commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +    public InternshipDto create(InternshipDto internshipDto) {
А если налл прилетит?

2024-09-17 05:35 UTC, Killhimka commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        internshipValidator.validateInternshipDuration(internshipDto);
Если попросят добавить еще 3 валидации, то это уже не метод создания, а метод валидации получится

2024-09-17 06:28 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/validator/intership/InternshipValidator.java
> +        teamMemberRepository.findById(internshipDto.getMentorId().getId());
finyById в тим мембер репо написан до меня, он кидает эксепшн если не найден, мне же от него это и надо если все ок, ниче не делаем

2024-09-17 06:37 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +    public InternshipDto create(InternshipDto internshipDto) {
То всё упадет, повесил аннотацию в дто и в контроллере

2024-09-17 06:37 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        internshipValidator.validateInternshipDuration(internshipDto);
Справедливо, предложения?)

2024-09-17 07:08 UTC, Killhimka commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        internshipValidator.validateInternshipDuration(internshipDto);
Вынеси в приват

2024-09-19 14:08 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
А Rest аннотации ?

2024-09-19 14:08 UTC, segaTk commented on src/main/java/faang/school/projectservice/dto/internship/InternshipDto.java
>  public class InternshipDto {
@Not null над полями в классе

2024-09-19 14:08 UTC, segaTk commented on src/main/java/faang/school/projectservice/validator/intership/InternshipValidator.java
вчера договорились разделить логику по отдельным репозиториям

2024-09-19 14:16 UTC, segaTk commented on src/main/java/faang/school/projectservice/validator/intership/InternshipValidator.java
> +    public void validateInternshipHaveProjectAndInterns(InternshipDto internshipDto) {
Как по мне длинноватое название, можно сократить

2024-09-19 14:16 UTC, segaTk commented on src/main/java/faang/school/projectservice/validator/intership/InternshipValidator.java
> +        teamMemberRepository.findById(internshipDto.getMentorId().getId());
Получается что там уже валидация на уровне репозитория, может тогда здесь она не нужна?

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    @PostMapping("/create")
Глаголы мы не добавляем в REST урлы
Поэтому если сверху есть путь /internships, а здесь есть метод POST, то уже понятно, что сейчас будет создание стажировки
Поэтому делаем просто пустой PostMapping

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    @ResponseBody
Поскольку у тебя на классе висит аннотация @RestController, то @ResponseBody автоматически добавляется ко ВСЕМ эндпоинтам в этом классе, а значит ты везде ее можешь удалить

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    @PostMapping("/update")
То же самое. Никаких глаголов. Поменяй аннотацию на @PutMapping, и всем будет понятно, что это обновление стажировки, т.к. PUT - это метод для обновления

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/dto/internship/InternshipDto.java
> +    private ProjectDto project;
А зачем нам тут целый проект? По-моему, можно просто id возвращать, а не всю гору данных тащить за стажкой. Нужен будет проект - получим отдельным запросом по его id.
Иначе мы по интернету таскаем огромную (проект все же) сущность, а она может и не нужна юзеру вообще - он стажировку только хотел получить

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/exception/internship/InternshipValidationException.java
> +    public InternshipValidationException(String message) {
Не, DataValidationException. Не создаем исключение для каждой отдельной сущности. Используем общее для всех ошибок валидации

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/filter/internship/InternshipFilter.java
> +public interface InternshipFilter {
У нас таких интерфейсов уже целая куча на разные фильтры для разных сущностей. Все они одинаковые, только типа параметров и возвращаемых значений разные. Можем ли мы сделать единый интерфейс, который сможет быть использован ЛЮБЫМ классом-фильтром вне зависимости от конкретных типов? Как сделать так, чтобы конкретный класс-фильтр сам определял, с какими типами данных будут его методы?

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/filter/internship/InternshipFilter.java
> +@Component
Это же не бин, просто интерфейс

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +        internshipValidator.validateInternshipExists(internshipDto.getId());
Так там же пустой id передается в метод создания. Мы можем просто проверить, что id никакого не передается, и тогда мы по идее можем просто создавать. Что именно мы тут валидируем?

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +        teamMemberService.getTeamMemberById(internshipDto.getMentorId().getId());
Почему мы вызываем этот метод, но никак не используем его результат?

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +            internship.setInterns(membersPassed);
А это зачем? Они ведь и так уже внутри internship, мы этот список как раз и получили из interniship
Когда мы обновляем элементы этого списка, то мы ведь по ссылке их обновляем. А значит они уже обновлены внутри internship

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +        return internshipMapper.toDto(internshipValidator.validateInternshipExists(id));
Не, валидатор не может ничего возвращать. Получать из БД должен сервис, а не валидатор. Соответственно тут нечего валидировать. Переносим этот метод в сервис и говорим: нашли что-то - вернем. Не нашли - кидаем EntityNotFoundException. Но поиск такой сущности делает сервис, а не валидатор

2024-09-22 14:00 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/validator/intership/InternshipValidator.java
> +    public Internship validateInternshipExists(Long id) {
Этот метод лучше вообще убрать. Мы в сервисе просто напишем метод getInternshipById()
Он будет возвращать нам сущность, если она есть, а если ее нет - кидать EntityNotFoundException()
Тогда нам и валидировать ничего не придется, если мы и так получаем исключение, если не смогли найти нужную сущность в бд

2024-09-23 22:57 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +        internshipValidator.validateInternshipExists(internshipDto.getId());
Глупость сделал каюсь

2024-09-23 22:57 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +        teamMemberService.getTeamMemberById(internshipDto.getMentorId().getId());
Обработал результат и еще допом проверил по проекту так же

2024-09-23 22:58 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +            internship.setInterns(membersPassed);
Блин тут пришлось попотеть) тесты не заводились долго доходило что Arrays.asList и List.of не позволяют меня и удалять из существующего списка, по мне так было конечно явней и понятней, выдернули бывший список с ним провели манипуляции подсохранили, и перезаписали

2024-09-23 22:59 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/validator/intership/InternshipValidator.java
> +    public Internship validateInternshipExists(Long id) {
Убрал

2024-09-23 22:59 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/filter/internship/InternshipFilter.java
> +public interface InternshipFilter {
Тут заморочился конкретно, залип на долго и потно, но кайфанул, написал фильтр общий на дженериках! хоть их вспомнил даже все работает!

2024-09-23 23:01 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/dto/internship/InternshipDto.java
> +    private ProjectDto project;
Переписал на Long projectId

2024-09-24 18:17 UTC, mysosnovskaya requested changes

2024-09-24 18:17 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/internship/InternshipServiceTest.java
> +        public void whenValidFilterDtoPassedThenReturnFilteredDtoList() {
Нужен тест, где больше одного фильтра) Текущая реализация метода getFilteredInternship некорректна.

2024-09-24 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/filter/internship/Filter.java
> +public interface Filter<T extends FilterDto, R> {
А вот это классно получилось 👍

2024-09-24 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/validator/intership/InternshipValidator.java
> +    private void validateInternshipHaveProjectAndInterns(InternshipDto internshipDto) {
Обычно в классе сначала идут все публичные методы, а потом все приватные. Так принято :)

2024-09-24 18:17 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/controller/internship/InternshipControllerTest.java
> +    class ControllerCallsTests {
А зачем нужен этот класс? Почему бы просто сразу не писать тесты? По-моему в данной ситуации он избыточен

2024-09-24 18:17 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/filter/internship/InternshipRoleFilterTest.java
> +        public void whenInternshipFilterDtoRoleIsNullTheReturnFalse() {
Это не негативный тест. Это ожидаемое корректное поведение метода. Негативные тесты это когда в метод передают не то, что он ожидает (неверные данные), и мы проверяем, что он умеет такие данные обрабатывать. Например, передали null, а метод должен вернуть исключение. Или передали id несуществующего пользователя. В обеих ситуациях это некорректные данные и метод не может выполнять свою работу. А в твоей ситуации всё корректно, суть метода и заключается в том, чтобы вернуть true или false в зависимости от того, что ему передали.

2024-09-25 21:14 UTC, Silencemess1ah commented on src/test/java/faang/school/projectservice/service/internship/InternshipServiceTest.java
> +        public void whenValidFilterDtoPassedThenReturnFilteredDtoList() {
еще один фильтр добавил, но не понимаю что не так с реализацией? Либо мы друг друга не поняли, либо нужно больше деталей...

2024-09-26 18:47 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/internship/InternshipServiceTest.java
> +        public void whenValidFilterDtoPassedThenReturnFilteredDtoList() {
У тебя оба фильтра оставляют одни и те же два объекта из трех, поэтому тест некорректен. Попробуй в internshipFilterDto поставить статус не COMPLETED, а IN_PROGRESS. Остальное оставь как есть и посмотри, что будет)

2024-09-26 18:47 UTC, mysosnovskaya requested changes
Про тест на фильтры написала. Также необходимо разрешить конфликт)

2024-09-26 21:40 UTC, Silencemess1ah commented on src/test/java/faang/school/projectservice/service/internship/InternshipServiceTest.java
> +        public void whenValidFilterDtoPassedThenReturnFilteredDtoList() {
Сделал через reduce теперь вроде все корректно

2024-09-26 21:41 UTC, Silencemess1ah commented
> Про тест на фильтры написала. Также необходимо разрешить конфликт)

Конфликты разрешил, отрефачил все по папкам все работает красоту навел в общем

2024-09-27 20:22 UTC, mysosnovskaya approved these changes

2024-09-27 20:22 UTC, merged