Feature bjs2 27207
CorporationX/project_service pull request #635
Opened 2024-09-17 10:56 UTC by Rashit86

2024-09-23 20:53 UTC, mikhailov26 requested changes

2024-09-23 20:53 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/model/Project.java
Почему выбрал именно такие каскады?

2024-09-23 20:53 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/model/Team.java
Почему не каскадный тип не ALL?

2024-09-23 20:53 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/repository/InternshipRepository.java
> +            "AND i.status <> faang.school.projectservice.model.InternshipStatus.COMPLETED")
Почему не используешь параметр nativeQuery? И будет ли корректно работать запрос если мы не будем помечать параметры аннотацией @Param ? ( Комментарий актуален для всех репозиториев )

2024-09-23 20:53 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +                .build();
Я бы посоветовал билд вынести в отдельный метод, очень много кода

2024-09-23 20:53 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/validator/InternshipValidator.java
> +    @Transactional
Точно ли тут нужна аннотация?

2024-09-23 20:53 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/validator/InternshipValidator.java
> +    @Transactional
Аналогичный вопрос

2024-09-23 21:39 UTC, Rashit86 commented on src/main/java/faang/school/projectservice/model/Project.java
Когда создается стажировка на проект, 
1) я беру:
- этот проект project, 
- teamMember-а (ментора), который уже работает на проекте в команде team (это команда новая, это одна из команд работающих над проектом project, и в ней пока есть только ментор) 
- стажеров user-ов (нигде пока не задействованы)

2) Беру команду, где пока только teamMember ментор 
- создаю teamMember-ов из стажеров, ставлю им роль INTERN
- добавляю teamMember-ов в team к ментору
3) Сохраняю проект. При этом
- сохраняется team, так как в Project над полем List<Team> teams стоит каскадирование PERSIST и MERGE (т.к проект уже существует мне бы, наверное хватило MERGE, но где обычно PERSIST и MERGE идут вместе)**Другие каскады не поставил, потому что мне по задаче нужно только создавать и обновлять. Кому надо будет удалять или еще что, добавят еще каскады. Вдруг проект удалят, а команды захотят оставить, т.к они уже сработались. Вдруг бизнес-логика в будущем будет предусматривать команды без проекта, которые ждут проект**
- сохраняются teamMember-ы (стажеры), потому что в Team над полем List<TeamMember> teamMembers тоже стоит каскадирование  PERSIST и MERGE. 

Также в Team над полем List<TeamMember> teamMembers стоит каскадирование REMOVE, потому что если удалить команду, то и членов команды тоже удаляем. Т.е user-ы остаются, но они уже не участники этой команды, потому что команды нет. 
Также в Team над полем List<TeamMember> teamMembers стоит orphanRemoval=true. Это на всякий случай, если вдруг team удалят, например, вручную sql запросом, тогда и teamMember-ы как сироты удалятся.

4) сохраненный обновленный проект делаю set в internship и сохраняю internship

2024-09-23 21:48 UTC, Rashit86 commented on src/main/java/faang/school/projectservice/model/Team.java
Потому что мне нужно только эти типа каскадирования. Я честно говоря не очень понимаю как работает DETACH, но по крайней мере REFRESH мне точно не нужен, т.к мне не нужно лишний раз обращаться к БД и обновлять контекс хибернейт. Т.е не нужно тратить лишние ресурсы, в этом нет смысла

2024-09-23 22:02 UTC, Rashit86 commented on src/main/java/faang/school/projectservice/repository/InternshipRepository.java
> +            "AND i.status <> faang.school.projectservice.model.InternshipStatus.COMPLETED")
HQL позволяет работать с ентити, хибернейт сам преобразует такой запрос в запрос для БД. HQL с любой БД будет работать, вне зависимости от диалекта. Если вдруг будем менять название поля в БД, то тут ничего не сломается. Если будет менять название поля в entity, то тут idea подсветит красным. C чистым sql если поменять название поля и забыть поправить sql запросы, то будут баги

2024-09-23 22:21 UTC, Rashit86 commented on src/main/java/faang/school/projectservice/repository/InternshipRepository.java
> +            "AND i.status <> faang.school.projectservice.model.InternshipStatus.COMPLETED")
Без @param будет работать, если название переменной совпадает с тем что написано в JPQL запросе. Это работает начиная со SpringDataJpa 2.0. А вот с NativeQuery, т.е чистым SQL это не работает, там обязательно нужно использовать @param. Я когда добавлял, не знал это всё, просто думал оно должно быть. Но оно точно не лишнее. Может даже так лучше. У нас на проекте есть и JPQL и NativeQuery, можно везде писать @param и не думать. Или давай уберу, где не надо, и где я сам добавил

2024-09-24 12:47 UTC, Rashit86 commented on src/main/java/faang/school/projectservice/validator/InternshipValidator.java
> +    @Transactional
Согласен, не нужна, т.к мы тут не меняем ничего в БД

2024-09-24 12:48 UTC, Rashit86 commented on src/main/java/faang/school/projectservice/validator/InternshipValidator.java
> +    @Transactional
Согласен, не нужна

2024-09-24 14:56 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/repository/InternshipRepository.java
> +            "AND i.status <> faang.school.projectservice.model.InternshipStatus.COMPLETED")
Факт в том, что мы как разработчики, которые занимаются построением архитектуры не должны задумываться о дальнейшем изменении кода, т.к. должны руководствоваться SOLID, в частности принципом О, в данном случае.

2024-09-24 14:58 UTC, mikhailov26 commented
Предлагаю вариант решения: убрать транзакционные аннотации, добавить метод для сборки  объекта Internship, ну и пройтись по репозиториям с учётом моего последнего комментария

2024-09-25 15:24 UTC, mikhailov26 approved these changes

2024-09-25 15:25 UTC, merged