Стадии проекта
CorporationX/project_service pull request #637
Opened 2024-09-18 04:57 UTC by SharkB38

2024-09-18 07:41 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/contoller/project/stage/StageController.java
> +                                    @RequestBody StageFilterDto stageFilterDto) {
У тебя @RequestBody с @GetMapping работает? У меня из-за того что @GetMapping передаётся в теле запроса, FilterDto получалось null и выскакивал exception. Если работает, то ок, если нет, то Маша мне скинула ссылку на статью https://medium.com/@pandaniel/spring-boot-controllers-getmapping-and-complex-objects-bd182ec99f54.

2024-09-18 07:52 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/mapper/project/stage/StageMapper.java
> +
Не уверен, но может разделить StageRoles в другой класс StageRolesMapper? Просто в своей задаче, я думал над тем, стоит ли добавлять CreateDto в мой маппер SubProjectMapper, так как может нарушаться принцип единой ответственности, но в моей задаче всё в итоге работало с сущностью Project, а у тут вроде StageRoles это другая сущность. Или я не прав))

2024-09-18 07:57 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +        }
Посоветовал бы тут использовать новую версию свитч выражения) https://www.baeldung.com/java-switch

2024-09-18 08:00 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/serivce/project/stage/filters/TaskStatusFilter.java
> +            case CANCELLED -> filterByAllMatchWithStatus(stages, TaskStatus.CANCELLED);
ааа, тут ты её уже используешь))

2024-09-18 08:04 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/contoller/project/stage/StageController.java
> +                                    @RequestBody StageFilterDto stageFilterDto) {
У меня работает, передаю json в теле запроса

2024-09-18 08:05 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/mapper/project/stage/StageMapper.java
> +
Может и надо по хорошему, засунул в один потому, что маппер сам использует методы для StageRole, когда работает с StageDto

2024-09-18 08:06 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +        }
Блин, да. В фильтрах то я ее сделал, а тут забыл.

2024-09-18 11:09 UTC, aassylkhan approved these changes
Классно написано =)

2024-09-18 11:09 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/contoller/project/stage/StageController.java
> +@RequestMapping("/projects/{projectId}")
почему не /projects? передать бы айди в контроллере

2024-09-18 11:46 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/contoller/project/stage/StageController.java
> +@RequestMapping("/projects/{projectId}")
Ну кстати надо поменять, да

2024-09-18 13:13 UTC, ArstanSubanov approved these changes

2024-09-18 19:57 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/dto/project/stage/StageRoleDto.java
> +
Аннотации нет, лишний отступ получается?

2024-09-18 20:07 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/serivce/project/stage/filters/TaskStatusFilter.java
> +            case TODO -> filterByAnyMatchWithStatus(stages, TaskStatus.TODO);
В чем выгода использовать switch? Почему не фильтровать по таскам, у которых получать get`ом ТаскСтатус?

2024-09-19 09:19 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +        }
Решил так оставить, там функции с void. Можно вот так вроде сделать:
```
Void nullNoop = switch (event.getType()) {
            case ORDER -> switchExpressionDelegate(event);
            case INVOICE -> switchExpressionDelegate(event);
            case PARCELDELIVERY -> switchExpressionDelegate(event);
        };
```
Но я пока оставлю как есть

2024-09-19 19:24 UTC, mysosnovskaya reviewed
Молодец, хорошая работа. И задача интересная, т.к. есть место для красивых решений) О них рассказала в комментариях. Также жду тестов на следующую итерацию)

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/contoller/project/stage/StageController.java
> +    @PostMapping("/stages")
update это Put, и stageId должен быть в урле

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/stage/StageDto.java
> +        List<Long> executorIds) {}
Стиль рекордов не единообразный получился) А вообще круто, что ты их используешь 👍

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/stage/StageRoleDto.java
> +        Long stageId) {
А здесь NotNull не нужен?

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/repository/TeamMemberRepository.java
> +    public List<TeamMember> findAllByIds(List<Long> ids) {
Отличное решение найти всех через findAllById и потом выдать одну общую ошибку на всех не найденных 👍

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +        List<Stage> stages = stageRepository.findAll().stream()
Что-то мне этот findAll не нравится) Почему нельзя через projectRepository найти нужный проект и взять у него stages?

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +        for (TeamMember executor : executors) {
Может быть вместо этого цикла добавить переменную List<TeamRole> neededRoles и потом просто через containsAll сделать? Просто на каждой итерации цикла делать executor.getRoles().stream() выглядит не самым оптимальным решением

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +            long executorWithNeededRoleCount = executors.stream().
Может быть заранее сделать Map<TeamRole, Integer>?

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +            if (neededCount > 0) {
А если neededCount будет отрицательным? Это в случае, если требуется больше, чем есть

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +        stageRepository.save(stage);
Не поняла, почему сначала save, а потом delete. Это из-за задач? Тогда лучше их в явном виде через taskRepository.saveAll сохранить, а то в таком виде слишком много вопросов возникает)

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +        switch (removeTypeDto.removeAction()) {
Такого вида switch часто реализуют более гибко. Т.к. у нас уже есть три варианта, что делать с задачами, то мы уже можем предположить, что могут появиться и другие, поэтому есть смысл сделать более общее решение. Рассказываю:
Создается абстрактный класс (или интерфейс, но обычно класс), например RemoveActionExecutor (мне кстати больше нравится Strategy вместо Action, но тут тебе решать) с методами execute и getType. У этого класса создаются наследники: CascadeDeleteActionExecutor, CloseActionExecutor, MigrateActionExecutor. Методы execute делают именно тот код, который сейчас делается у тебя, а getType возвращает RemoveAction, который обрабатывает данный класс. Все эти классы помечаются как Component
Далее здесь, в сервисе, через спринг в список List<RemoveActionExecutor> собираются все эти классы, ты список переделываешь в Map<RemoveAction, RemoveActionExecutor> и в этом методе по removeAction достаешь нужный обработчик из мапы и вызываешь у него execute. Решение получится красивым, удобным и гибким)
Уверена, что ты спросишь, что делать с removeStageWithMigrateTasks, ведь ему нужно два параметра. Можно у execute сделать два параметра: Stage stage, RemoveTypeDto removeTypeDto, предполагая, что во втором ещё может появляться какая-то дополнительная информация для этого или других действий.

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/project/stage/StageMapper.java
> +public interface StageMapper {
Сборка проекта не проходит из-за ошибки в маппере. Не хватает нам ci pipeline для этого сервиса)

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/project/stage/StageMapper.java
> +    StageRoles toStageRoles(StageRoleDto stageRoleDto, @Context StageRepository stageRepository);
А этот метод точно где-то нужен? Некоторые другие тоже не вижу, чтобы использовались

2024-09-19 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/serivce/project/stage/filters/TaskStatusFilter.java
> +    public Stream<Stage> apply(Stream<Stage> stages, StageFilterDto filters) {
Может быть добавим в StageFilterDto ещё одно поле, отвечающее за ANY или ALL и здесь сделаем switch по этим значениям?
```
            case Boolean.ANY -> filterByAnyMatchWithStatus(stages, filters.taskStatusFilter());
            case Boolean.ALL -> filterByAnyMatchWithStatus(stages, filters.taskStatusFilter());
```
Или вообще можно сделать разными классами: TaskStatusAnyFilter и TaskStatusAllFilter. Что думаешь?

2024-09-20 04:14 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/dto/project/stage/StageRoleDto.java
> +        Long stageId) {
Нет, stage еще не создана на этот момент у нее нет id, он туда записывается при сохранении stage в createStage

2024-09-20 04:31 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +        for (TeamMember executor : executors) {
Не понял. У меня neededRoles это roles, containsAll не получится как я понял, потому что TeamMember может содержать роль которая не требуется на этом этапе проекта.

2024-09-20 04:36 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +            if (neededCount > 0) {
Это же наоборот в случае если исполнителей с такой ролью больше чем нужно, в этом проблемы по идее нет

2024-09-20 04:46 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +            long executorWithNeededRoleCount = executors.stream().
Как- то сделал, но я наверное опять не понял.

2024-09-20 04:48 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/serivce/project/stage/filters/TaskStatusFilter.java
> +    public Stream<Stage> apply(Stream<Stage> stages, StageFilterDto filters) {
Да, тоже об этом думал

2024-09-20 06:48 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/serivce/project/stage/filters/TaskStatusFilter.java
> +    public Stream<Stage> apply(Stream<Stage> stages, StageFilterDto filters) {
Решил разные классы не делать, сделал ALL, ANY, NONE по идее других вариантов быть не может.

2024-09-20 09:09 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/mapper/project/stage/StageMapper.java
> +
Короче разделил на два маппера, но в тестах никак не получилось адекватно создать главный маппер, второй никак не подтягивался. Все что нашел перепробовал, в итоге засунул все в один класс

2024-09-21 14:23 UTC, SharkB38 commented
Черт...

2024-09-21 17:28 UTC, mysosnovskaya commented
> Черт...

Я пожалуй подожду) Отправлю на доработку, если будут проблемы - пиши. 
Рекомендую сохранить копию того, что есть сейчас (если нет предыдущей версии). И можно поудалять лишние коммиты из твоей ветки

2024-09-22 17:48 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/serivce/project/stage/StageServiceImpl.java
> +        for (TeamMember executor : executors) {
Хорошо, это я сначала не так логику поняла) Тогда как у тебя ок

2024-09-22 18:17 UTC, mysosnovskaya requested changes

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/stage/StageServiceImpl.java
> +        Map<TeamRole, Long> neededRolesCount = new HashMap<>();
Да, я по-другому имела в виду. В Map<TeamRole, Long> положить данные об executors. Сколько исполнителей с какой ролью. Это на стримы задачка) В целом логика абсолютно такая же, как ты делал, только вместо того, чтобы в for каждый раз проверять, сколько исполнителей с искомой ролью, заранее посчитать это в мапе, а в цикле только пользоваться этой мапой.

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/stage/StageServiceImpl.java
> +    private final List<RemoveStrategyExecutor> removeStrategies;
Чтобы это поле не мешалось, можно создать конструктор, в который принять List<RemoveStrategyExecutor>, а с его помощью внутри конструктора проинициализировать Map<RemoveStrategy, RemoveStrategyExecutor> removeStrategyExecutors. Тогда это поле будет не нужно

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/stage/remove/RemoveStrategyExecutor.java
> +package faang.school.projectservice.service.project.stage.remove;
Может быть пакет назвать removestrategy? Обычно глаголами пакеты не называют)

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/project/stage/StageMapper.java
> +        // как лучше обработать null здесь?
Пустой список подойдет. А эта ситуация точно возможна? Из базы точно null вернется, а не пустой список?

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/stage/filters/TaskStatusFilter.java
> +    private Stream<Stage> filterBuNoneMatchWithStatus(Stream<Stage> stages, TaskStatus status) {
Опечатка в Bu

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/stage/StageController.java
> +                                    @RequestBody StageFilterDto stageFilterDto) {
В ПРе Максима обсуждали этот момент:
https://github.com/CorporationX/user_service/pull/1568#discussion_r1769626760
Рекомендую удалить RequestBody аннотацию, должно всё корректно работать (с query params)

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/stage/StageController.java
> +            @Positive @PathVariable Long stageId,
Чтобы аннотации валидации заработали нужно добавить аннотацию Validated над классом

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/stage/StageFilterDto.java
> +        TaskStatusFilterType taskStatusFilterType) {}
Не единообразное оформление рекордов получилось. Я бы фигурные скобки на разных строчках оставляла

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/stage/StageServiceImpl.java
> +            throw new DataValidationException(
Интересный у тебя стиль) Как-то много переносов строк получается. Стандартно такое оформили бы так:
```
            throw new DataValidationException(
                    WRONG_PROJECT_STATUS.getMessage().formatted(stageCreateDto.projectId())
            );
```
Это не ошибка, такой стиль тоже допустим, но просто подсвечу, что чаще пишут по-другому

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/stage/StageServiceImpl.java
> +        if (stages == null) {
Такое точно возможно? Там точно не пустой список будет?

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/stage/StageServiceImpl.java
> +@Slf4j
Аннотация есть, а логов нет. Давай добавим?

2024-09-22 18:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/stage/remove/RemoveStrategyExecutor.java
> +public abstract class RemoveStrategyExecutor {
Хорошо получилось!) Молодец, что разобрался с этой идеей и реализовал её)

2024-09-22 18:17 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/project/stage/StageServiceImplTest.java
> +        Stage savedStage = Stage.builder()
Может быть вынести этот кусочек кода с созданием стейджа через билдер в отдельный приватный метод? Очень много раз одно и то же повторяется. В метода можно сделать параметры id, name, project

2024-09-22 18:17 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/project/stage/StageServiceImplTest.java
> +        Stage savedStage = Stage.builder()
И для StageDto тоже

2024-09-22 18:17 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/project/stage/StageServiceImplTest.java
> +class StageServiceImplTest {
Огромная и качественная работа с тестами проделана, молодец 👍

2024-09-23 10:18 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/dto/project/stage/StageFilterDto.java
> +        TaskStatusFilterType taskStatusFilterType) {}
Вроде все поправил?

2024-09-23 10:24 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/project/stage/StageServiceImpl.java
> +        if (stages == null) {
Да действительно, что то я перемудрил с этим делом, логично что там будут пустые списки

2024-09-23 16:02 UTC, mysosnovskaya approved these changes

2024-09-23 16:02 UTC, merged