BJS2-26078 Приглашения присоединиться к этапу
CorporationX/project_service pull request #639
Opened 2024-09-19 07:22 UTC by segaTk

2024-09-20 11:56 UTC, badasscoding commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +    @PostMapping("/create")
cогласно REST архитектуре, URI должен идентифицировать ресурсы, а не действия
поэтому использование глагола "create" в URI не соответствует RESTful принципам

в REST создание ресурсов обычно выполняется через POST запрос на сам ресурс, поэтому можно просто /v1/stageInvitations и тут @PostMapping оставить

2024-09-20 12:21 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +    @PostMapping("/create")
Согласен, спасибо

2024-09-20 12:21 UTC, badasscoding commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +    @PatchMapping("/accept/{id}")
1. Почему accept через {id} в URI, а reject через Dto?
2. Так же как и выше: можно избавиться от глагола и в один метод переделать всё -> PATCH /{id} с StageInvitationStatus в body (зачем лишние данные по сети гонять)

2024-09-20 12:21 UTC, badasscoding commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +    @GetMapping("/viewAll")
тут можно просто GET v1/stageInvitations

c фильтром будет GET /v1/stageInvitations?invitedStageName=NAME&invitedId=123&status=PENDING

2024-09-20 12:21 UTC, badasscoding commented on src/main/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationInvitedIdFilter.java
> +public class StageInvitationInvitedIdFilter implements StageInvitationFilter {
фильтры приватными делаем (но методы будут public)

2024-09-20 12:21 UTC, badasscoding commented on src/test/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationStatusFilterTest.java
> +                        .status(null)
а так работает? у тебя же @NotNull private StageInvitationStatus status;

2024-09-20 12:21 UTC, badasscoding commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +    public List<StageInvitationDto> getInvitations(@RequestParam StageInvitationFilterDto filter) {
а так?

@RequestParam обычно используется для передачи одиночных значений, может тут лучше @ModelAttribute? плюс добавить @Valid для проверки @NotNull аннотаций?

2024-09-20 13:38 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +    @PatchMapping("/accept/{id}")
Согласен, переделал)

2024-09-20 13:39 UTC, segaTk commented on src/main/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationInvitedIdFilter.java
> +public class StageInvitationInvitedIdFilter implements StageInvitationFilter {
сделал

2024-09-20 13:39 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +    @GetMapping("/viewAll")
Согласен

2024-09-20 13:43 UTC, segaTk commented on src/test/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationStatusFilterTest.java
> +                        .status(null)
там и return еще != null, а в тесте проверка assertFalse

2024-09-20 13:43 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +    public List<StageInvitationDto> getInvitations(@RequestParam StageInvitationFilterDto filter) {
Насчет @ModelAttribute не знаю, пока поставлю его, почитаю, может кто еще подскажет

2024-09-20 18:32 UTC, badasscoding commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +    @PatchMapping("/{id}")
теперь у тебя два метода PATCH /id

как вариант сделать так:

   ```
 @PatchMapping("/{id}")
    @ResponseStatus(HttpStatus.OK)
    public void rejectInvitation(@Valid @PathVariable long id,  @RequestBody StageInvitationStatus status) {
       if (status.equals(StageInvitationStatus.ACCEPTED) {
                stageInvitationService.acceptInvitation(id);
       } else if (status.equals(StageInvitationStatus.REJECTED) {
               stageInvitationService.rejectInvitation(id);
       } else {
              // исключение кинуть например
       }
    }
```

2024-09-20 18:32 UTC, badasscoding commented on src/main/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationNameFilter.java
> +    @Override
@GusevVrn Паша мне писал делать перенос строки после создания класса, я так понял по код стайлу так

2024-09-20 18:32 UTC, badasscoding commented on src/main/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationStatusFilter.java
> +    @Override
и тут перенос строки

2024-09-20 18:32 UTC, badasscoding commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +        stageInvitationService.createInvitation(stageInvitationDto);
вот тут обсуждали что методы POST, PUT, PATCH, UPDATE должны возвращать результирующуюDto
https://discord.com/channels/1102662981743030334/1113503106404192316/1285941581312032770

если будешь править, то и в других методах в этом контроллере глянь

2024-09-20 18:32 UTC, badasscoding commented on src/test/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationIdFilterTest.java
> +@ExtendWith(MockitoExtension.class)
перед этим не хватает пустой строки

2024-09-20 18:32 UTC, badasscoding commented on src/test/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationNameFilterTest.java
> +@ExtendWith(MockitoExtension.class)
перед этим не хватает пустой строки

2024-09-20 18:33 UTC, badasscoding commented
посмотри еще на формат названия ветки

в readme есть:
`Из данной ветки создаем ветку для вашей конкретной задачи по шаблону: feature-{номер_задачи} или bugfix-{номер_задачи} в зависимости от того, делаете ли вы новую фичу или чините некоторый баг.`

но сейчас уже не меняй, что PR не пересоздавать

2024-09-23 09:08 UTC, segaTk commented on src/main/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationNameFilter.java
> +    @Override
Добро

2024-09-23 09:09 UTC, segaTk commented on src/main/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationStatusFilter.java
> +    @Override
Хорошо

2024-09-23 11:23 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +    @PatchMapping("/{id}")
Хорошая идея, а как же принцип единой ответственности?

2024-09-23 13:13 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public StageInvitationDto acceptInvitation(@Valid @PathVariable long id) {
@Valid лишняя. Тут как бы нечего валидировать

2024-09-23 13:13 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PostMapping()
Пустые скобки можно убрать

2024-09-23 13:13 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public StageInvitationDto rejectInvitation(@Valid @PathVariable long id,
Лишний @Valid

2024-09-23 13:13 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/dto/client/stageInvitation/StageInvitationDto.java
> +    @NotNull
А когда я только создаю приглашение, то разве ему не проставляется статус по умолчанию? Разве должен я ОБЯЗАТЕЛЬНО передавать статус, если мы дефолтный потом выставим?

2024-09-23 13:13 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/dto/client/stageInvitation/StageInvitationFilterDto.java
> +    @NotNull
Почему везде @NotNull?
Что если я передам только часть фильтров, а остальные не передам? Почему я ОБЯЗАН передавать все?
Что если мне, как юзеру, не хочется фильтровать по 3-м параметрам, а только по одному?
А завтра по трем...

У юзера должно быть достаточно свободы в выборе того, как он может формировать запросы. А тут мы ему запрещаем передавать часть данных только - всегда нужно передать ВСЕ

2024-09-23 13:13 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/dto/client/stageInvitation/StageInvitationDto.java
> +    @NotNull
Я тут могу ошибаться, если что
Вероятно, в задаче там любой статус можно передавать. Но я бы ожидал, что по умолчанию приглашение ставится в статус PENDING (ожидание)

2024-09-23 13:13 UTC, mighty-mhsl commented on src/test/java/faang/school/projectservice/service/stageInvitation/StageInvitationServiceTest.java
> +                assertEquals(2L, result.size());
А наполнение списка почему не тестируем?
Если нам вернулось ожидаемое число данных, это еще не значит, что нам вернулись именно сами ожидаемые данные (что внутри они те самые)

2024-09-23 13:13 UTC, mighty-mhsl commented on src/main/java/faang/school/projectservice/service/stageInvitation/StageInvitationService.java
> +        return stageInvitationRepository.findById(stageInvitationId);
По идее мы тут Optional должны получать... А почему сразу StageInvitation возвращается?
Это, наверно, из-за того интерфейса странного в репозитории этом
Должно быть JpaRepository только или CrudRepository

2024-09-23 13:13 UTC, mighty-mhsl commented on src/test/java/faang/school/projectservice/service/stageInvitation/StageInvitationServiceTest.java
> +            assertThrows(NullPointerException.class,
Мы не можем на это тестировать. Такое исключение может вылететь откуда угодно - не только из нашего метода. Никогда нельзя писать тесты на NPE, потому что они могут давать неожиданные результаты

Нужно поправить тот метод, который кидает NPE вместо того, чтобы доставать из репозитория Optional и обрабатывать его через EntityNotFoundException. И вот здесь мы тогда будем ожидать именно это исключение, а не NPE

2024-09-23 13:13 UTC, mighty-mhsl commented on src/test/java/faang/school/projectservice/service/stageInvitation/StageInvitationServiceTest.java
> +            assertEquals(STAGE_INVITATION_STATUS, stageInvitationDto.getStatus());
Так ведь REJECTED должен быть

2024-09-23 13:13 UTC, mighty-mhsl commented on src/test/java/faang/school/projectservice/service/stageInvitation/StageInvitationServiceTest.java
> +            assertEquals(STAGE_INVITATION_STATUS, stageInvitationDto.getStatus());
Мы совсем не то здесь ассертим, что должны. Мы должны ассертить то, что передается внутрь метода save() репозитория. А сейчас мы ассертим наш исходный дто, который мы перед тестом создали. Он вообще не имеет ничего общего с тем, что мы на самом деле будем сохранять ведь

rejectInvitation букваль возвращает то dto, которое мы должны ассертить. А мы его игнорим

2024-09-23 13:13 UTC, mighty-mhsl commented on src/test/java/faang/school/projectservice/service/stageInvitation/StageInvitationServiceTest.java
> +            assertEquals(STAGE_INVITATION_STATUS, stageInvitationDto.getStatus());
Это неправильный ассерт. Нам acceptInvitation вернет то, что мы должны ассертить. А сейчас ассертим просто константы внутри нашего теста. Они тут вообще не меняются.

2024-09-23 13:30 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PostMapping()
Убрал

2024-09-23 13:30 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public StageInvitationDto acceptInvitation(@Valid @PathVariable long id) {
Точно, спасибо

2024-09-23 13:31 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public StageInvitationDto rejectInvitation(@Valid @PathVariable long id,
есть такое

2024-09-23 13:33 UTC, segaTk commented on src/main/java/faang/school/projectservice/dto/client/stageInvitation/StageInvitationFilterDto.java
> +    @NotNull
Да, точно, разогнался с @Notnull, спасибо

2024-09-23 13:35 UTC, segaTk commented on src/main/java/faang/school/projectservice/dto/client/stageInvitation/StageInvitationDto.java
> +    @NotNull
Скорее всего так, исправлю

2024-09-23 13:36 UTC, segaTk commented on src/main/java/faang/school/projectservice/service/stageInvitation/StageInvitationService.java
> +        return stageInvitationRepository.findById(stageInvitationId);
Да, там сразу и проверка на null стоит

2024-09-23 13:42 UTC, segaTk commented on src/main/java/faang/school/projectservice/service/stageInvitation/StageInvitationService.java
> +        return stageInvitationRepository.findById(stageInvitationId);
Согласен, так оставлять?

2024-09-23 13:46 UTC, segaTk commented on src/test/java/faang/school/projectservice/service/stageInvitation/StageInvitationServiceTest.java
> +            assertEquals(STAGE_INVITATION_STATUS, stageInvitationDto.getStatus());
Хорошо, переделаю по-нормальному ; )

2024-09-23 15:30 UTC, segaTk commented on src/test/java/faang/school/projectservice/service/stageInvitation/StageInvitationServiceTest.java
> +            assertThrows(NullPointerException.class,
Тогда, по идее это не здесь тестировать, уберу это

2024-09-23 15:43 UTC, segaTk commented on src/test/java/faang/school/projectservice/service/stageInvitation/StageInvitationServiceTest.java
> +                assertEquals(2L, result.size());
Хорошо

2024-09-23 15:52 UTC, segaTk commented on src/test/java/faang/school/projectservice/service/stageInvitation/StageInvitationServiceTest.java
> +            assertEquals(STAGE_INVITATION_STATUS, stageInvitationDto.getStatus());
Хорошо, спасибо

2024-09-23 15:54 UTC, segaTk commented on src/test/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationNameFilterTest.java
> +@ExtendWith(MockitoExtension.class)
Добавил

2024-09-23 15:54 UTC, segaTk commented on src/test/java/faang/school/projectservice/filter/StageInvitation/filterImpl/StageInvitationIdFilterTest.java
> +@ExtendWith(MockitoExtension.class)
Сделал

2024-09-23 19:10 UTC, mysosnovskaya requested changes

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PatchMapping("/{id}")
У тебя сейчас два одинаковых эндпоинта (этот и выше) PATCH /{id} - так это работать не будет) Запрос PATCH /v1/stageInvitations/15 должен интерпретироваться однозначно (наличие тела не влияет на интерпретацию).

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +                                               @Valid @RequestBody String description) {
Мы используем формат json, поэтому description нужно передавать тоже в формате json. Для этого нужно создать отдельный dto класс (например, RejectInvitationRequest) с полем description.
И ещё аннотация Valid в данный момент тут лишняя, т.к. в строке валидировать нечего)

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @ResponseStatus(HttpStatus.OK)
По умолчанию будет OK, поэтому эта аннотация не несет никакого смысла)

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public List<StageInvitationDto> getInvitations(@Valid @RequestParam(required = false)
Здесь тоже Valid лишняя. А ты проверял это через постман, получилось послать запрос?

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/filter/StageInvitation/StageInvitationStatusFilter.java
> +class StageInvitationStatusFilter implements Filter<StageInvitationFilterDto, StageInvitation> {
Круто, что ты переиспользовал уже имеющийся Filter 👍

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/jpa/StageInvitationJpaRepository.java
> +public interface StageInvitationJpaRepository extends JpaRepository<StageInvitation, Long>,
А это изменение зачем?)

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/stageInvitation/StageInvitationDtoMapper.java
> +    StageInvitationDto toDto(StageInvitation stageInvitation);
Вообще я всегда рекомендую использовать более конкретные названия в мапперах:
toDto -> toStageInvitationDto
toDtos -> toStageInvitationDtos
потому что в теории у нас может быть больше одного dto. Это сейчас их нет, но в будущем могут появиться)
Ну и toEntity -> toStageInvitation для единообразия)
Это необязательно исправлять, если у вас уже командный стиль такой. Просто пишу для информации :)

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/moment/MomentService.java
> +            throw new IllegalArgumentException("Moment Id in uri (" + momentId + ")" +
Зачем это изменение? По-моему и без него всё красиво было)

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/stageInvitation/StageInvitationService.java
> +        stageInvitation.get().setStatus(StageInvitationStatus.ACCEPTED);
А если stageInvitation пустой? То здесь получим ошибку)

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/stageInvitation/StageInvitationService.java
> +                () -> new IllegalArgumentException("something went wrong")));
Не понимаю, что здесь может пойти не так, если мы уже с этим stageInvitation поработали, статус ему проставили, исполнителей назначили?

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/stageInvitation/StageInvitationService.java
> +        stageInvitation.get().setStatus(StageInvitationStatus.REJECTED);
Здесь комментарии аналогично предыдущему методу. Про работу с Optional

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/stageInvitation/StageInvitationService.java
> +                .flatMap(stageInvitationFilter -> stageInvitationFilter.apply(invitationStream, filter))
А так точно работает?) А то мы с другой командой сошлись на том, что flatMap здесь не подходит =) И вроде как в help это обсуждалось

2024-09-23 19:10 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/stageInvitation/StageInvitationServiceTest.java
> +            void whenGetStageInvitationFilterThenSuccess() {
Что проверяет это тест? У тебя репозиторий возвращает два объекта StageInvitation (158 строка) и затем ты мокаешь поведение фильтра (замечу - одного) (замечу ещё - он ничего не меняет, также возвращает те же два объекта). Нужен тест, где фильтры "будут работать". То есть где будет несколько фильтров, один из них будет неприменим, один отфильтрует часть объектов, можно добавить ещё один, который не отфильтрует никого. Вот тогда тест будет показательным) И подозреваю, что найдешь ошибку в методе getInvitations.

2024-09-23 19:10 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/repository/StageInvitationRepository.java
> +        return Optional.ofNullable(repository.findById(stageInvitationId).orElseThrow(
Я видела, что Влад писал комментарий про Optional, но возможно он не увидел реализации в этом репозитории. Тут всё было корректно. `repository.findById(stageInvitationId)` возвращает Optional - это как раз то, о чем писал Влад. А дальше проверяется, что в этом Optional что-то лежит, и если нет, то генерируется EntityNotFoundException. А если да, от можно вернуть уже готовый к использованию объект.
Optional из метода мы возвращаем только в том случае, когда хотим подчеркнуть, что может вернуться как запрашиваемый объект, так и null. А в данном случае (как ты реализовал сейчас) у тебя Optional всегда гарантированно будет непустым и нет смысла сначала его получать из базы данных, потом убеждаться в его непустоте, а потом опять оборачивать всё в Optional. Каша получается :) Поэтому рекомендую вернуть старую реализацию, она корректная. Если ещё осталось непонимание с этой темой - можем на дейлике голосом обсудить, только напомни)

2024-09-23 19:10 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/filter/StageInvitation/StageInvitationIdFilterTest.java
> +@ExtendWith(MockitoExtension.class)
Пустой строчки перед аннотацией не хватает)

2024-09-23 19:10 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/filter/StageInvitation/StageInvitationIdFilterTest.java
> +            void whenStageInvitationFilterDtoStatusIsNullThenReturnFalse() {
Но ведь это не негативный тест? Это одно из ожидаемых поведений. Негативный тест, это когда что-то пошло не по плану и должна вернуться ошибка. А здесь всё по плану) Один из возможных корректных сценариев работы метода

2024-09-23 19:10 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/mapper/stageInvitation/StageInvitationDtoMapperTest.java
> +    class toEntity {
Интересно ты придумал с разделением на классы) Я в жизни такое не особо встречала, но ничего против не имею, оригинально =)

2024-09-23 19:52 UTC, segaTk commented on src/main/java/faang/school/projectservice/filter/StageInvitation/StageInvitationStatusFilter.java
> +class StageInvitationStatusFilter implements Filter<StageInvitationFilterDto, StageInvitation> {
Спасибо

2024-09-23 19:55 UTC, segaTk commented on src/test/java/faang/school/projectservice/filter/StageInvitation/StageInvitationIdFilterTest.java
> +@ExtendWith(MockitoExtension.class)
Не увидел) исправил

2024-09-23 19:59 UTC, segaTk commented on src/test/java/faang/school/projectservice/filter/StageInvitation/StageInvitationIdFilterTest.java
> +            void whenStageInvitationFilterDtoStatusIsNullThenReturnFalse() {
Исправил)

2024-09-23 20:01 UTC, segaTk commented on src/main/java/faang/school/projectservice/jpa/StageInvitationJpaRepository.java
> +public interface StageInvitationJpaRepository extends JpaRepository<StageInvitation, Long>,
Не откатилось до конца) добавлю

2024-09-23 20:07 UTC, segaTk commented on src/main/java/faang/school/projectservice/jpa/StageInvitationJpaRepository.java
> +public interface StageInvitationJpaRepository extends JpaRepository<StageInvitation, Long>,
а, это просто перенёс строку чтобы не вылезало)

2024-09-23 20:09 UTC, segaTk commented on src/main/java/faang/school/projectservice/mapper/stageInvitation/StageInvitationDtoMapper.java
> +    StageInvitationDto toDto(StageInvitation stageInvitation);
Не против придерживаться стиля более опытных : )

2024-09-23 20:15 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @ResponseStatus(HttpStatus.OK)
Хорошо)

2024-09-23 20:16 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public List<StageInvitationDto> getInvitations(@Valid @RequestParam(required = false)
честно - нет

2024-09-23 20:19 UTC, segaTk commented on src/main/java/faang/school/projectservice/service/moment/MomentService.java
> +            throw new IllegalArgumentException("Moment Id in uri (" + momentId + ")" +
То, что красиво сомнений нет, за черту вышло, видимо непроизвольно перенес)

2024-09-24 11:38 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/StageInvitationController.java
> +        stageInvitationService.createInvitation(stageInvitationDto);
Хорошо, спасибо

2024-09-24 11:56 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +                                               @Valid @RequestBody String description) {
Можно пока одно дто использовать не разделяя её на response u request?

2024-09-24 13:14 UTC, segaTk commented on src/main/java/faang/school/projectservice/service/stageInvitation/StageInvitationService.java
> +                () -> new IllegalArgumentException("something went wrong")));
Переделал обратно, не вопрос

2024-09-24 13:48 UTC, segaTk commented on src/main/java/faang/school/projectservice/service/stageInvitation/StageInvitationService.java
> +                .flatMap(stageInvitationFilter -> stageInvitationFilter.apply(invitationStream, filter))
Переделал)

2024-09-24 15:22 UTC, segaTk commented on src/test/java/faang/school/projectservice/service/stageInvitation/StageInvitationServiceTest.java
> +            void whenGetStageInvitationFilterThenSuccess() {
Согласен

2024-09-24 18:39 UTC, mysosnovskaya requested changes
Осталось совсем чуть-чуть и смержим задачу) Жду скорее на следующую (думаю, уже финальную) итерацию

2024-09-24 18:39 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PatchMapping("/a/{id}")
Что такое a?)

2024-09-24 18:39 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @GetMapping("/f/{invitedId}")
Что такое f?)

2024-09-24 18:39 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +public class StageInvitationController {
Если ты ещё не смотрел лекцию Влада про rest (8 спринт), тогда по правильному проектированию урлов можешь тэнгуть меня в чате, я сразу ответ напишу)

2024-09-24 18:39 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PutMapping
Почему accept это Patch, а reject - это Put?

2024-09-24 18:39 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public StageInvitationDto rejectInvitation(@RequestBody StageInvitationDto stageInvitationDto) {
Отвечаю на твой вопрос про один dto: я не рекомендую так делать, т.к. это создает путаницу и для тех, кто будет читать твой код, и для тех, кто будет читать документацию нашего api, сгенерированную с помощью swagger. Может даже тебя запутать, если в коде сервиса забыть, что почти все поля не нужны.

2024-09-24 18:39 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/stageInvitation/StageInvitationService.java
> +                .reduce(stageInvitationRepository.findAll().stream(),
Вот теперь красота =) Как вариант можно ещё через for-each сделать, так может быть более читаемо. Это просто для информации, переделывать не нужно

2024-09-24 19:04 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PatchMapping("/a/{id}")
Это увидел в url у google такой подход в календаре, сокращение чтобы не совпадали пути

2024-09-24 19:05 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @GetMapping("/f/{invitedId}")
f от filter))

2024-09-24 19:07 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +public class StageInvitationController {
посмотрел, но тэнгу)

2024-09-24 19:11 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PutMapping
Здесь нужно к чему-то одинаковому прийти, вот немного не понимаю в данном случае по сути идемпотентный и нужен put

2024-09-24 19:17 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public StageInvitationDto rejectInvitation(@RequestBody StageInvitationDto stageInvitationDto) {
Хорошо, переделаю ; )

2024-09-24 19:26 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PatchMapping("/a/{id}")
Гугл может быть и может себе такое позволить, но мы - нет) Это неверно с точки зрения проектирования rest api

2024-09-24 19:29 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PutMapping
Здесь нужно разобраться с разницей в PATCH и PUT. Patch подразумевает, что в метод приходят только те поля, которые нужно обновить (например, description). А Put говорит о полной замене объекта, т.е. в метод объект, который полностью перезатирает то, что находится в базе данных.

2024-09-24 19:35 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PatchMapping("/a/{id}")
Чем мы хуже них?)

2024-09-25 19:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PatchMapping("/a/{id}")
Мы не хуже, мы учимся писать понятный, удобный, легко поддерживаемый код. Сначала научимся, а потом уже можно будет отступать от правил)

2024-09-25 19:45 UTC, mysosnovskaya requested changes
Одно маленькое исправление и после него точно смержу)

2024-09-25 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +                                                       @Valid @RequestBody String description,
Как это два RequestBody? Тут должен быть один dto-класс с двумя полями: description и status

2024-09-25 19:50 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +                                                       @Valid @RequestBody String description,
Точно

2024-09-25 20:13 UTC, mysosnovskaya requested changes

2024-09-25 20:13 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PatchMapping("/reject")
id нужно было оставить в урле (path variable), чтобы было единообразно с acceptInvitation. В методе можно сделать stageInvDtoRequest.setId(id) или передать его отдельным параметром в сервис - тут уже неважно)

2024-09-25 20:29 UTC, segaTk commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    @PatchMapping("/reject")
Понял, спасибо)

2024-09-25 20:30 UTC, mysosnovskaya approved these changes
Ураа, поздравляю с аппрувом)

2024-09-25 20:30 UTC, merged