BJS2-26081: Вакансии
CorporationX/project_service pull request #654
Opened 2024-09-24 14:02 UTC by lowerKamaCase

2024-09-24 20:23 UTC, Silencemess1ah reviewed
В общем многих пунктов не хватает из описания задачи, маппер настроить логику поправить, удачи!

2024-09-24 20:23 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
Смотри : 
1) пришло дто у тебя в нем есть поле   private Long projectId; , а в сущности лежит на этом месте полноценный объект Project, твой маппер не знает как мапить из Long в Project, т.е. ты получил энтити из дто, дальше тебе нужно сходить в ProjectService, он вызовет свой репозиторий и найдет по Id проекта сущность, которую ты подцепишь к своей вакансии и, после, сохранишь, делаешь обратную операцию и кладешь в дто Id от проекта и возвращаешь в контроллер,
2) в задаче сказано что вакансия обязательно относиться к проекту, как раз как вытащишь из базы проект про который выше написал и проверишь удовлетворяет это условию
3) Проверить, что куратор вакансии имеет нужную роль. (с) и Также на проекте обязательно должен быть человек, ответственный за вакансию. (с)  отсюда можем сделать вывод что в проекте нужно сходить в поле ownerId за айдишником юзера (TeamMember)  сходить в TeamMemberService и через репозиторий подтянуть сущность, залезть в список его ролей и проверить что он есть Owner роль (ну я вижу это так поправь если ошибаюсь) или возможно имеется ввиду обратиться вообще в другой сервис (User_Service) и в базе пробить User-a, надо залезать в сущности смотреть где такую инфу можно вытащить

2024-09-24 20:23 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +    List<VacancyDto> toDtos(List<Vacancy> vacancies);
В сервисе написал про маппинг, тебе нужно аннотациями подсказать мапперу как смапить Long projectId и положить его в пустую сущность Project айдишником , туда и обратно естественно + как листами маппить

2024-09-24 20:23 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
Не понимаю что тут делаем, пришло id( от чего не понятно) + dto дальше ты по айдишнику смотришь существует ли такая вакансия в базе, мапишь дто в энтити зачем не понял(ни куда не сохраняешь результат кстати) , сетишь айдишник по которому ты и нашел эту вакансию в базе (???) дальше заново запаковываешь в дто и отдаешь вообще не понял логики,
Судя из текста описания к задаче, я так подозреваю что обновление подразумевает добавления участников, смены статуса вакансии, смены статуса кандидатов и прочее прочее , т.е. иными словами, передаем в поле Dto с нужными полями,
по его айди проверяем что вакансия существует в базе,  мапим дто в сущность, далее проделываем все манипуляции с полями(выше писал про проект, например) сетим что нужно, записываем в базу обратно в дто отдаем  вроде так

2024-09-24 20:23 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
Если вакансия удаляется, то из TeamMember должны быть удалены все кандидаты, если у них нет “рабочего статуса”, т.е. если они всё ещё кандидаты, а не приняты в команду. (c) Опять же достать проверить статусы отсеять тех кто не подходит под описание

2024-09-24 20:23 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
Тут вроде сказано найти все вакансии по фильтрам, всего 2 вида " Получить все вакансии с фильтрами по позиции и названию. " собственно надо прикрутить

2024-09-24 20:23 UTC, Silencemess1ah commented on src/test/java/faang/school/projectservice/service/VacancyServiceTest.java
> +        .build();
все значения, id, name, description выноси в константы вверх

2024-10-05 18:50 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
честно говоря, не понимаю, как связаны какндидат и тиммембер, ведь это разные сущности и получаем их из разных репозиториев. поправил, как понял

2024-10-05 18:50 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
метод обновлен

2024-10-05 18:51 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +    List<VacancyDto> toDtos(List<Vacancy> vacancies);
маппер поправлен

2024-10-05 18:51 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
метод обновлен

2024-10-06 03:30 UTC, mysosnovskaya requested changes

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    public VacancyDto createVacancy(@RequestBody VacancyDto vacancyDto) {
Договорились делать разные dto на создание/обновление/ответ (response). А то сейчас у тебя в dto на создание есть поле  private Long id; - это неверно, при создании мы не можем указывать id и даже не должны давать возможность это сделать

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    public List<VacancyDto> getAllVacancies() {
По условиям задачи get должен быть по фильтрам

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +@RequestMapping("/api/v1/vacancies")
Хорошо api спроектировал, молодец 👍

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +        return projectRepository.getProjectById(projectId);
Нет, маппер не может ходить в базу данных, это не его ответственность. Он может только один данные (которые получил) преобразовать в другой формат (класс), но ничего нового добавить не может

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +    @Mapping(target = "project", expression = "java(mapProjectById(vacancyDto.getProjectId(), projectRepository))")
Почитай про аннотацию org.mapstruct.Named, она тут лучше подойдет, чем expression

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +    VacancyDto toDto(Vacancy vacancy);
toVacancyDto (т.к. в теории dto может быть много разных и нужно пояснять, в какой именно класс происходит преобразование)

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +    List<VacancyDto> toDtos(List<Vacancy> vacancies);
toVacancyDtos

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +@RequiredArgsConstructor
Нужно добавить логи

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +            throw new IllegalArgumentException("Curator does not have the required OWNER role");
Давай ещё айди куратора в описание ошибки добавим

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        Vacancy savedVacancy = vacancyRepository.save(vacancy);
Из-за того, что у тебя в vacancyDto мог прийти id, здесь будет работать не так, как ты ожидаешь. 
Ознакомься с этим сообщением, пожалуйста:
https://discord.com/channels/1102662981743030334/1113503106404192316/1288944216982032465
В том же ПР (на который ссылка в сообщении) была такая же ошибка. Метод save работает так, что если ему передать объект с проставленным id, то он будет обновлять запись, а не создавать новую. Соответственно, если у тебя в vacancyDto был задан id, то и в vacancy он будет задан, а значит здесь либо получим ошибку (что невозможно обновить объект с таким-то айди, т.к. его нет в базе), либо ошибки не будет, но обновиться существующий объект (перезапишется). Готова обсудить это голосом, если нужно.

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        // Находим существующую вакансию
Все комментарии из кода должны быть удалены. Код должен быть самодокументируемым, т.е. я должна из кода понимать, что происходит. И часто желание написать комментарий может быть поводом для того, чтобы вынести часть кода в отдельный приватный метод с понятным названием. Например, вместо комментария "Обрабатываем каждого кандидата" будет лучше вынести эту часть кода в приватный метод processCandidate(Candidate candidate) и всё станет понятно)

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +                System.out.println(candidate);
Удалить, никаких System.out.println в коде быть не должно. Только логи и только с понятным описанием)

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +                    throw new IllegalStateException("Candidate is not a member of the project");
Нужно добавить идентификаторы кандидата и проекта в сообщение об ошибке

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +                teamMember.getRoles().add(TeamRole.DEVELOPER);
А почему именно девелопер? А как другие роли назначить?

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        vacancyMapper.updateVacancyFromDto(vacancyDto, vacancy, projectRepository);
Повторю то, что уже писала выше: из-за одной dto здесь может обновиться и id вакансии, а это повлечет за собой баги

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +                candidateRepository.delete(candidate);
Лучше собрать все id удаляемых кандидатов вместе и потом вызвать deleteAllById, так будет меньше обращений к базе данных

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    public void deleteVacancy(Long id) {
Надо транзакцию на метод повешать, а то может получиться так, что кандидатов удалили, а вакансию - нет

2024-10-06 03:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
Согласна

2024-10-07 13:02 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +    @Mapping(target = "project", expression = "java(mapProjectById(vacancyDto.getProjectId(), projectRepository))")
по другому решил, а этот метод удалил

2024-10-07 13:02 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        vacancyMapper.updateVacancyFromDto(vacancyDto, vacancy, projectRepository);
updateVacancyFromDto удален

2024-10-07 13:11 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +                teamMember.getRoles().add(TeamRole.DEVELOPER);
честно говоря, не знаю.
вот задание: у выбранных кандидатов должна появиться соответствующая роль на проекте.
что значит "соответствующая" я не знаю

2024-10-07 13:11 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    public void deleteVacancy(Long id) {
мы уже проходили транзакции? ок, погуглю

2024-10-09 03:38 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +                candidateRepository.delete(candidate);
done

2024-10-09 03:40 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    public void deleteVacancy(Long id) {
done

2024-10-09 04:06 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +    }
фильтры добавлены

2024-10-09 20:30 UTC, mysosnovskaya requested changes

2024-10-09 20:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +    VacancyDto toDto(Vacancy vacancy);
Ещё актуально

2024-10-09 20:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +    List<VacancyDto> toDtos(List<Vacancy> vacancies);
Ещё актуально

2024-10-09 20:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +@RequiredArgsConstructor
Ещё актуально

2024-10-09 20:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +            throw new IllegalArgumentException("Curator does not have the required OWNER role");
Ещё актуально

2024-10-09 20:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +                    throw new IllegalStateException("Candidate is not a member of the project");
Ещё актуально

2024-10-09 20:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +                teamMember.getRoles().add(TeamRole.DEVELOPER);
А, вижу, в вакансии нет поля про роли. Ок, пусть останется так

2024-10-09 20:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        return vacancies.stream()
Посмотри, как в проекте делаются фильтры:
https://github.com/CorporationX/project_service/tree/unicorn-master-stream6/src/main/java/faang/school/projectservice/filter
https://github.com/CorporationX/project_service/blob/unicorn-master-stream6/src/main/java/faang/school/projectservice/service/internship/InternshipService.java#L76

2024-10-10 04:01 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +    VacancyDto toDto(Vacancy vacancy);
переименовал

2024-10-10 04:02 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/mapper/VacancyMapper.java
> +    List<VacancyDto> toDtos(List<Vacancy> vacancies);
переименовал

2024-10-10 04:09 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +@RequiredArgsConstructor
добавил логи

2024-10-10 04:11 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +            throw new IllegalArgumentException("Curator does not have the required OWNER role");
добавил айди куратора

2024-10-11 07:28 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +        return vacancies.stream()
спасибо, поправил фильтрацию

2024-10-11 19:51 UTC, mysosnovskaya requested changes
Давай ещё немного над логами поработаем)

2024-10-11 19:51 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +            log.error("Curator " + curator.getId() + " does not have the required OWNER role");
Логгировать не нужно, это будет в global exception handler происходить. Здесь достаточно просто выкинуть исключение) Актуально для всех подобных мест

2024-10-11 19:51 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +@Slf4j
Нужно ещё добавить info-логи о том, что какой-то объект (в нашем случае вакансия) создан, обновлен или удален. На получение логи как правило не пишут.

2024-10-12 03:55 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +            log.error("Curator " + curator.getId() + " does not have the required OWNER role");
поправил

2024-10-12 04:11 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/VacancyService.java
> +@Slf4j
добавил логи

2024-10-12 18:06 UTC, mysosnovskaya approved these changes

2024-10-12 18:06 UTC, merged