BJS2-27063   [Advanced] Интеграция календаря с Google Calendar
CorporationX/project_service pull request #673
Opened 2024-09-28 13:15 UTC by ilu23ilu23

Добавил контроллеры для создания эвентов, календарей и доступа к ним в GoogleCalendar(EventController, CalendarController, AclController), а так жде контроллеры для Oauth аутентификации в гугл для пользования GoogleCalendar(GoogleOAuthController, OAuthCallbackController).
Добавил метод для получения информации из user_service в интерфейсе UserServiceClient. 
Добавил конфигурационный файл GoogleCalendarConfige. 
Добавил класс в пакет dto EventDtoForGoogleCalendar для информации из user_service. 
Добавил EventMapper для преобразования информации из сущности Event из user_service в сущность Event из библиотеки GoogleCalendar. 
Для Acl созданы енумы с описанием в коммантариях в пакете model. 
В пакете model созданы сущности: EventMapping для сопоставления айдишников эвента из юезр сервиса и эвента гугл календаря; и сущность GoogleAuthToken для безопасного хранения данных и токенов для аутентификации в гугл. 
Созданы соответствующие сущностям репозитории EventMappingRepository и TokenRepository. 
Созданы в сервисном слое классы с логикой для эвентов, календарей и доступа к ним в ГуглКалендаре(AclService, CalendarService, EventService), а так же сервис с логикой для создания\получения\удаления сопоставления айдишников EventMappingService, сервис для реализации аутентификации OAuthService, сервис для создания и получения токена и другой нужной информации TokenService. 
Создание тестовых классов на все сервисные классы. Добавил данные в application.yaml.
Добавил ченджсеты в ликвибейз.
Добавил некоторые зависимости в билд грэдл.

2024-09-28 15:09 UTC, amilosh commented on src/main/java/faang/school/projectservice/config/context/GoogleCalendarConfig.java
> +    }
А если во время создания бина будет throw new IllegalStateException(errorMsg);
то он потом второй раз создастся?

2024-09-28 15:11 UTC, amilosh commented on src/main/java/faang/school/projectservice/service/google_calendar/OAuthService.java
> +            token.setExpiresIn(credential.getExpiresInSeconds());
А эти токены могут expired, истечь время жизн?
Можешь глянуть какое время жизни создается, или там безлимит какой-нибудь.

И если время короткое, то какое флоу чтобы обновить?

2024-09-28 15:27 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/config/context/GoogleCalendarConfig.java
> +    }
Если бин синглтон, а он по умолчанию синглтон, то второй раз не создастся, в этом случае его лучше сделать прототайп?

2024-09-28 15:46 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/service/google_calendar/OAuthService.java
> +            token.setExpiresIn(credential.getExpiresInSeconds());
Тут у меня есть токен обновления - он постоянный, и токен доступа - он живет до часу. Когда мы используем приложение, при каждом запросе гугл проверяет токен доступа, если срок вышел, то при помощи токена обновления токен доступа придет новый, но он у меня сохраняется только в памяти, надо сделать, чтобы в базу сохранялся

2024-09-28 16:13 UTC, amilosh commented on src/main/java/faang/school/projectservice/config/context/GoogleCalendarConfig.java
> +    }
Я думал, что если мы пробуем создать бин с каким-то названием и он не создастся, то он не запишется к контейнер (в spring application context). И когда пробуем второй раз создать, то спринг проверяет, ели ли он в контексте, то создает если такого нет.
Но это догадки.
Как там на самом деле надо читать и поэкспериентировать.

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/config/context/GoogleCalendarConfig.java
> +            return null;
мне кажется лучше тут исключение выбрасывать, а выше его перехватить и залогировать и дальше пустить

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/config/context/GoogleCalendarConfig.java
> +        log.info("Создание учетных данных на основе токенов");
лог выглядит как-то бесполезным

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/controller/google_calendar/AclController.java
> +
лишняя строка

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/controller/google_calendar/AclController.java
> +        return ResponseEntity.ok("Право доступа с ID " + ruleId + " удалено");
лучше просто возвращать 204 ответ без тела запроса

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/controller/google_calendar/CalendarController.java
> +
лишняя строка

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/controller/google_calendar/CalendarController.java
> +        return ResponseEntity.ok("Календарь удален");
204 код с пустым телом

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/controller/google_calendar/EventController.java
> +
удали везде пустые строки

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/controller/google_calendar/EventController.java
> +        this.eventService = eventService;
почему не через ломбок?

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/controller/google_calendar/EventController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("Мероприятие создано с ID: " + googleEventId);
обычно с бека просто строку в ответе не передают. или 
`{"message": "success message"}`
или
просто успешный http статус, а фронт по нему уже понимает что пользователю показать

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/controller/google_calendar/oauth/GoogleOAuthController.java
> +        return ResponseEntity.ok(authorizationUrl);
тут скорее всего нужен 3хх код для редиректа передавать
https://www.baeldung.com/cs/redirection-status-codes

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/dto/client/EventDtoForGoogleCalendar.java
> +    private LocalDateTime endDate;
startedAt
endedAt

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/exceptions/google_calendar/GoogleCalendarExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(ex.getMessage());
лучше возвращать json
{"error": "message"}

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/model/CalendarAclScopeType.java
> +
очень много пустых строк

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/service/google_calendar/CalendarService.java
> +            com.google.api.services.calendar.model.Calendar calendar = new com.google.api.services.calendar.model.Calendar();
почему полные пути до класса?

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/service/google_calendar/CalendarService.java
> +    private Calendar calendarClient;
видимо нужно было назвать CalendarClient, чтобы не конфликтовало с  
com.google.api.services.calendar.model.Calendar

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/service/google_calendar/EventMappingService.java
> +            throw new NotFoundException("Маппинг для eventId '" + eventId + "' не найден");
лучше` if (!eventMappingRepository.existsById(eventId)) { throw new NotFoundException("Маппинг для eventId '" + eventId + "' не найден");}`
а дальше всё остальное

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/service/google_calendar/OAuthService.java
> +                    Arrays.asList("https://www.googleapis.com/auth/calendar", "https://www.googleapis.com/auth/calendar.events"))
лучше вынести в константу или конфиг

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/service/google_calendar/OAuthService.java
> +            return "Авторизация успешна. Токены сохранены.";
просто void метод

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/service/google_calendar/TokenService.java
> +        log.info("Получение последнего OAuth токена из базы данных");
как по мне лишние логи

2024-09-28 17:33 UTC, cemeh666 commented on src/main/java/faang/school/projectservice/service/google_calendar/TokenService.java
> +        log.info("Сохранение OAuth токена в базу данных");
как по мне лишние логи

2024-09-28 17:48 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/config/context/GoogleCalendarConfig.java
> +        log.info("Создание учетных данных на основе токенов");
Он показывает, что креденшнл сформировался

2024-09-28 17:49 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/controller/google_calendar/AclController.java
> +        return ResponseEntity.ok("Право доступа с ID " + ruleId + " удалено");
Я тем самым в лог пишу, чтобы понятно было

2024-09-28 17:53 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/controller/google_calendar/oauth/GoogleOAuthController.java
> +        return ResponseEntity.ok(authorizationUrl);
Я сделал так, чтобы в постмане я смог забрать сформированный урл и по нему перейти

2024-09-28 17:57 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/controller/google_calendar/oauth/GoogleOAuthController.java
> +        return ResponseEntity.ok(authorizationUrl);
Добавил и то и то

2024-09-28 17:59 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/model/CalendarAclScopeType.java
> +
специально так сделал, чтобы лучше читалось, когда нет строк, глаза корёбит)

2024-09-28 18:03 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/service/google_calendar/CalendarService.java
> +            com.google.api.services.calendar.model.Calendar calendar = new com.google.api.services.calendar.model.Calendar();
Потому что тут используются одинаковые названия в импортах:
com.google.api.services.calendar.Calendar
com.google.api.services.calendar.model.Calendar

2024-09-28 18:04 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/service/google_calendar/CalendarService.java
> +    private Calendar calendarClient;
Это в библиотеке так уже заведено

2024-09-30 20:50 UTC, 20cognosce requested changes
1. Переделать базу
2. Переделать токены
3. Переделать конфигурацию гугла, по-максимуму вынести в проперти, упростить и сделать понятным процесс взаимодействия между компонентами
4. Подчеркиваю жирным. Написать документацию разработчика в README.md / HELP.md, где по пунктам, структурировано словами описано что с чем связано и как оно всё работает, В ИДЕАЛЕ - пару сиквенс диаграмм

2024-09-30 20:50 UTC, 20cognosce commented on build.gradle.kts
> +    implementation ("org.springframework.boot:spring-boot-starter-thymeleaf")
Зачем тебе okhttp, что не выполняет спринговый rest-клиент?
А шаблонизатор thymeleaf для чего вообще, мы фронт будем пилить?

2024-09-30 20:50 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    secret: тут должен быть секретный код
Не писать символы кириллицы в коде нигде, даже в комментариях не пишите

2024-09-30 20:50 UTC, 20cognosce commented on src/main/resources/db/changelog/db.changelog-master.yaml
> -      file: db/changelog/changeset/project_V016_meet.sql
Не понял, ты удалил старые чейнджсеты?

2024-09-30 20:50 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V015_create_event_mapping.sql
> +                               google_event_id VARCHAR(255) NOT NULL
Что это за айдишники, которые смотрят вникуда
С гугловским я еще пойму, но event_id, он чей? Почему ни чей?

2024-09-30 20:50 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V016_alter_event_mapping.sql
> +    ADD PRIMARY KEY (id);
Не понял, ты только что создал таблицу выше
И другим чейнджсетом её модифицируешь, почему так?

2024-09-30 20:50 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V016_alter_event_mapping.sql
> +    ADD PRIMARY KEY (id);
Нельзя сразу создать какой надо?

2024-09-30 20:50 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V017_alter_event_mapping.sql
> +    ADD PRIMARY KEY (id);
И это еще туда же
Зачем ты сиквенс руками создаешь? SERIAL ключевое слово используй

2024-09-30 20:50 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V018_create_google_auth_token.sql
> +);
Если в проекте настроен Redis, а Султан вроде это делал, лучше в Redis это хранить
Ну если хочешь в БД - пойдет

2024-09-30 20:50 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V019_alter_google_auth_token.sql
> +DROP COLUMN token_type;
Ну и это бред какой-то
Ты создал только что таблицу и тут же из нее колонки выкидываешь

Структура базы в общем - трешачок какой-то, переделать всё, обратись в ПП к кому-нибудь, например к Саше Милошу

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/EventMapping.java
> +    private Long id;
Используй UUID и не парься с сиквенсами

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/EventMapping.java
> +    private Long eventId;
Почему не сущность

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/EventMapping.java
> +    private Long eventId;
Если хочешь сказать, что её нет в этом микросервисе, то
1. Как минимум констрейнт в базе 100% должен быть
2. Можно создать базовую либу со всеми общими сущностями и импортировать её между сервисами, но это отдельная задача на пару дней

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/GoogleAuthToken.java
> +public class GoogleAuthToken {
Для учебного проекта допустим, но вообще в базе никакая инфа по межсервисной авторизации не хранится, только конфиг файлы или рантайм

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/exceptions/google_calendar/GoogleCalendarExceptionHandler.java
> +    }
Это всё дублирование кода на 80%, в каждом методе ты делаешь одно и то же
Обобщи их по статус кодам что ли
Текст лога засунь в саму ошибку и из неё всегда доставай, придумай короче, как красоту навести

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/dto/client/EventDtoForGoogleCalendar.java
> +    private LocalDateTime endDate;
startedAt
endedAt
итак видно, что это дата по типу данных
Ты же переменной списка и мапы не добавляешь List Map (надеюсь нет)

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/dto/client/EventDtoForGoogleCalendar.java
> +    private LocalDateTime endDate;
Ну это вкусовщина конечно

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/oauth/google_oauth/DatabaseCredentialDataStore.java
> +        log.info("Получение фабрики хранилища данных");
Никаких комментариев на кириллице... бан...

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/oauth/google_oauth/DatabaseCredentialDataStore.java
> +        log.info("Проверка, содержит ли хранилище данных ключ: {}", key);
Какой смысл несут эти логи

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/oauth/google_oauth/DatabaseCredentialDataStore.java
> +        }
Вот так null возвращать из метода - это бан

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/oauth/google_oauth/DatabaseCredentialDataStore.java
> +public class DatabaseCredentialDataStore implements DataStore<StoredCredential> {
Зачем ты реализовывал этот интерфейс и написал кучу лишнего
Я не понимаю прикладную необходимость в этом классе, что он делает

Ты тут максимум обновляешь в токене поля, полученные из сервиса
Ну и зачем было целый класс на 200 строк создавать. 
Выпили его, всё что надо - в сервис

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/oauth/google_oauth/TokenService.java
> +        log.info("Удаление последнего OAuth токена из базы данных");
Много бесполезных логов, реально бесполезных
Представь столько такой воды будет в выводе
И если тебе реально надо будет найти какие-то ключевые моменты

Убери пожалуйста всё лишнее

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/oauth/google_oauth/TokenService.java
> +public class TokenService {
Пиши конкретно, ты работаешь с access или refresh в каждом моменте
Плюс, если у тебя refresh статичен, тебе по нему нужно просто в определенный момент access запросить, если прошлый протух

Нафига столько телодвижений в БД?????

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/config/google_calendar_config/GoogleCalendarConfig.java
> +    @Lazy
В чем профит

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/oauth/google_oauth/OAuthService.java
> +
Что тут происходит, что мы получаем, куда сохраняем? 
Тут вообще никакой связи с нашими БД токенами нет, что мы делаем?

Вообще не разобраться в происходящем

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/google_calendar/AclService.java
> +    @Autowired
?)

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/google_calendar/AclService.java
> +            List<AclRule> aclRules = calendarClient.acl().list(calendarId).execute().getItems();
Не в одну строчку

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/google_calendar/AclService.java
> +            throw new GoogleCalendarException("Ошибка удаления права доступа", e);
А можно вынести в один приватный метод все try catch и очистить все эти методы?

2024-09-30 20:50 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/google_calendar/CalendarService.java
> +        }
Аналогично try catch if else log - засирают просто всю бизнес логику, но них уходит 70% наполнения методов

Декомпозируй, вынеси в приватные методы пожалуйста

2024-09-30 20:50 UTC, 20cognosce commented on build.gradle.kts
> +    implementation ("org.springframework.boot:spring-boot-starter-thymeleaf")
Для сваггера thymeleaf?

2024-09-30 20:51 UTC, 20cognosce commented
Ну и 5. Общую чистоту навести

2024-10-01 17:14 UTC, ilu23ilu23 commented on build.gradle.kts
> +    implementation ("org.springframework.boot:spring-boot-starter-thymeleaf")
Удалить забыл, в самом начале пока разбирался какой-то проект нашел, там человек эти зависимости использовал

2024-10-01 17:16 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/db.changelog-master.yaml
> -      file: db/changelog/changeset/project_V016_meet.sql
Нет, это кто-то с другой группы запушил в общую проектовскую ветку, я только добавлял, если бы удалил, у меня ничего бы не запускалось)

2024-10-01 17:46 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/project_V015_create_event_mapping.sql
> +                               google_event_id VARCHAR(255) NOT NULL
Он от сущности из юзер сервиса

2024-10-01 17:47 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/project_V015_create_event_mapping.sql
> +                               google_event_id VARCHAR(255) NOT NULL
Тут я сопоставляю айди эвента из юзер сервиса и айди эвента из гугл календаря

2024-10-01 17:48 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/project_V016_alter_event_mapping.sql
> +    ADD PRIMARY KEY (id);
Когда первый раз создал, я думал, что всё ок, но запустил и понял в чем ошибся, исправить в текущем ченжсете нельзя, только создавать новый

2024-10-01 17:52 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/project_V017_alter_event_mapping.sql
> +    ADD PRIMARY KEY (id);
Я на uuid переделаю

2024-10-01 17:52 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/project_V018_create_google_auth_token.sql
> +);
Влад сказал, что лучше в бд делать

2024-10-01 18:21 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/project_V019_alter_google_auth_token.sql
> +DROP COLUMN token_type;
Токен обновления тут тоже обновляется, а токен доступа можно получить при помощи токена обновления, expiresIn - это время срока истечения токена, оно не постоянно, каждый раз разное, поэтому как уонстанту тоже нельзя сохранить, и эти даннеы нужны для получения и обновления токена, поэтому в структуре бд у меня только нужные данные. Лишние, как ты видел, я убрал(скоуп и тип токена), они тут действительно были не нужны. Поэтому тут ничего не нужно больше менять

2024-10-01 18:24 UTC, kripersh27 commented on src/main/java/faang/school/projectservice/model/EventMapping.java
> +    private Long eventId;
Да, тут только айдишник. Потому что у нас есть своя сущность Эвента, но она находится в юзер сервисе, и за ней я  через фейгн клиент хожу, а у гугл календаря своя сущность эвента, и нам нужно сопоставить нашу сущность и сущность гугловскую, поэтому это я делаю тут при помощи айдишников.

2024-10-01 18:25 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/model/GoogleAuthToken.java
> +public class GoogleAuthToken {
Влад сказал мне так сделать

2024-10-01 18:53 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/oauth/google_oauth/DatabaseCredentialDataStore.java
> +public class DatabaseCredentialDataStore implements DataStore<StoredCredential> {
Этот интерфейс из библиотеки Google OAuth Client Library, и его реализация служит для хранения учетных данных и позволяет библиотеке автомаьически обновлять токены доступа при их истечении, используя токен обновления, если его не использовать, то пришлось бы всё вручную прописывать и это в разы сложнее и больше, я считаю что не нужно изобретать велосипед, если можно пользоваться готовыми функциональностями. Тем более всё прекрасно работает)

2024-10-01 18:56 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/oauth/google_oauth/TokenService.java
> +public class TokenService {
Этот сервисный класс предоставляет для DatabaseCredentialDataStore методы для работы с токенами, можно было всё реализовать в методах DatabaseCredentialDataStore, но я вынес это в отдельный класс.

2024-10-01 19:06 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/config/google_calendar_config/GoogleCalendarConfig.java
> +    @Lazy
Если при запуске приложения сразу будет создаваться объект Calendar из гугловской библиотеки, то он сразу запросит токены доступа, а если мы впервые запускаем наш сервис, то токенов у нас пока нет, поэтому лениво тут загружаю, чтобы вначале при работе с гугл календарем пройти авторизацию и получить токен, после этого можно пользоваться календарем.

2024-10-01 19:18 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/oauth/google_oauth/OAuthService.java
> +
Да, я напишу по этому всему документацию и могу на дейли рассказать и показать что и как работает

Тут генерируется урл для авторизации, обрабатывается код авторизации, потом код авторизации меняется на токены и вот тут "googleAuthorizationCodeFlow.createAndStoreCredential(tokenResponse, USER_KEY)" как раз создается объект кредентиал, данные сохраняются в ДатаСтор и автоматически обновляются токены за счет public class DatabaseCredentialDataStore implements DataStore<StoredCredential>

2024-10-01 19:18 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/service/google_calendar/AclService.java
> +    @Autowired
Я про календарь выше описывал

2024-10-01 19:33 UTC, ilu23ilu23 commented on src/main/java/faang/school/projectservice/model/EventMapping.java
> +    private Long id;
Давай я UUID в следующий раз использую вместо сиквенса? Сейчас всё работает, не хочется шило на мыло менять, еще и ченджсеты добавлять, идею я понял, буду пользоваться, спасибо)

2024-10-01 20:22 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/project_V017_alter_event_mapping.sql
> +    ADD PRIMARY KEY (id);
Давай я UUID в следующий раз использую вместо сиквенса? Сейчас всё работает, не хочется шило на мыло менять, еще и ченджсеты добавлять, идею я понял, буду пользоваться, спасибо)

2024-10-03 15:57 UTC, 20cognosce requested changes

2024-10-03 15:57 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V015_create_event_mapping.sql
> +                               google_event_id VARCHAR(255) NOT NULL
event_id должен иметь констрейнт и ссылаться на таблицу

2024-10-03 15:57 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V016_alter_event_mapping.sql
> +    ADD PRIMARY KEY (id);
В смысле нельзя исправить в текущем чейнджсете? Ты никуда еще не вмерджил свои чейнджсеты даже

Переделать

2024-10-03 15:57 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V017_alter_event_mapping.sql
> +    ADD PRIMARY KEY (id);
Таблицы сразу сделай по-нормальному в этой задаче

Потом если каким-то потомкам придется это править, они зайдут в git blame и вспомнят этот кринж добрым словом

2024-10-03 15:57 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V019_alter_google_auth_token.sql
> +DROP COLUMN token_type;
Создай в одном чейнджсете, ОДНОМ, сразу ту структуру таблиц и связей, которая тебе нужна

2024-10-03 15:57 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/EventMapping.java
> +    private Long eventId;
На что ссылается event_id? Если это гугловский - то переименуй, чтобы понятно было. Если это внутренний - нужен констрейнт на primary key

event_id BIGINT NOT NULL UNIQUE,
google_event_id VARCHAR(255) NOT NULL

2024-10-03 15:58 UTC, 20cognosce commented
На дейли покажешь интеграцию с гуглом и функционал доработки

2024-10-04 19:03 UTC, 20cognosce approved these changes

2024-10-04 19:03 UTC, merged