Управление участниками команды
CorporationX/project_service pull request #674
Opened 2024-09-28 15:02 UTC by RuslanIovlev

тесты на сервис дорабатываю

2024-09-28 15:51 UTC, SharkB38 requested changes

2024-09-28 15:51 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        TeamMember user = teamMemberRepository.findById(userId);
У TeamMember два разных поля userId и Id, я не думаю, что здесь подходит этот метод

2024-09-28 15:51 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +            String message = String.format("This member %d is already a project participant." +
Не совсем понял момент с тем, что этот TeamMember уже есть в проекте, как это определяется?

2024-09-28 15:51 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +                .build();
А почему через билдер а не маппером в entity?

2024-09-28 15:51 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        if (!teamMemberRepository.findById(userId).getRoles().contains(TeamRole.TEAMLEAD)) {
Ну здесь тоже id, userId вот это вот все

2024-09-28 15:51 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +    public List<TeamMemberDto> getTeamMembersByFilter(TeamFilterDto filters) {
Вроде метод должен вернуть отфильтрованных участников конкретного проекта?

2024-09-28 17:02 UTC, ArstanSubanov approved these changes
Согласен с комментариями Валеры, в остальном всё класс👍

2024-09-28 18:41 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +            String message = String.format("This member %d is already a project participant." +
В условии просят проверить является ли юзер уже участником проекта, если у него же есть роль, то отправить на апдейт тогда

2024-09-28 18:42 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +                .build();
Как я понял можно и так и так,  делал через маппер, но показлось так симптичнее

2024-09-28 18:43 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        TeamMember user = teamMemberRepository.findById(userId);
Не совсем понял, что тогда использовать

2024-09-28 21:00 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        TeamMember user = teamMemberRepository.findById(userId);
Смотри, у тебя есть userId у TeamMember это идшник из таблицы users, а когда ты создаешь нового TeamMember ему присваивается свой идшник уже в team_members таблице. По идее тебе надо дописать метод в репозиторий findByUserId и использовать его, но можешь подождать, что Маша по этому поводу скажет, может я тут ошибаюсь. Просто когда сам с TeamMember работал так этот момент понял

2024-09-28 21:14 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +            String message = String.format("This member %d is already a project participant." +
Как-будто бы здесь сложнее проверки должны быть, если мы создаем нового TeamMember, надо для начала в дто передавать userId, чтобы найти всех TeamMember с этим userId, потом проверить, состоит ли кто то из найденных в команде которая принадлежит к определенному проекту, ид проекта как-будто бы тоже надо передавать в метод, и тогда можно сказать что этот юзер действительно уже является участником данного проекта и имеет какую то роль. По крайней мере я так это вижу. Но тут тоже лучше подождать, что Маша скажет

2024-09-28 21:22 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        TeamMember user = teamMemberRepository.findById(userId);
Пользователь может быть участником разных команд на разных проектах, поэтому у тебя может быть много TeamMember'ов с одним userId

2024-09-29 06:52 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +    @GetMapping("/teamMembers/filter")
Если в аргументе используешь RequestBody, делай PostMapping. Get используется с QueryParam
https://github.com/CorporationX/user_service/pull/1568#issuecomment-2365268042
Можешь почитать наши рассуждение по этому поводу и комментарий Маши)

2024-09-29 06:53 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +    @GetMapping("/teamMembers/all")
Тим мемберы существуют только в рамках проекта, как я думаю. Мне кажется, этот поиск нужно делать с учетом projectId.

2024-09-29 06:58 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +    private void validateUser(long userId) {
в чем заключается валидация? Или я не так понимаю смысл этого метода

2024-09-29 06:59 UTC, wmwmaks commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberRoleFilterTest.java
> +
лишняя пустая строка

2024-09-29 16:24 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +    @GetMapping("/teamMembers/filter")
Спасибо за ссылку, учту

2024-09-29 17:44 UTC, mysosnovskaya requested changes

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +    private final TeamMemberServiceImpl teamMemberService;
Внедрять лучше не TeamMemberServiceImpl, а TeamMemberService (через абстракцию). Чтобы разобраться, почему так принято, почитай про букву D в SOLID принципах)

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +    @GetMapping("/teamMembers/all")
Максим, я с тобой согласна, но в условии задачи написано действительно так, как будто нужно отдать вообще всех тим мемберов) Хотя вообще говоря идея странная - отдавать сразу все записи из какой-то одной таблицы. Но будем следовать условию задачи)
Руслан, если тебе интересно изучить дополнительную теорию (небольшую), то могу рекомендовать тебе добавить сюда пагинацию (pagination, разбиение на страницы). Но это необязательно)

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/team/TeamMemberDto.java
> +                            List<TeamRole> role) {
roles - множественное число

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +    private void validateUser(long userId) {
Если пользователя не существует, то 
` userServiceClient.getUser(userId);`
вернет ошибку, с этой точки зрения всё ок. Я бы только предложила переименовать метод в checkIfUserExists

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +    @PostMapping("/{id}/teamMembers")
Вместо teamMembers рекомендую использовать в урлах просто members, т.к. у тебя до этого есть /team, то будет очевидно, что /team/2/members - это участники второй команды)

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        TeamMember user = teamMemberRepository.findById(userId);
Согласна. У teamMemberJpaRepository есть метод findByUserIdAndProjectId, вот он тебе и нужен)

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +    public TeamMemberDto addTeamMember(long userId, TeamMemberDto teamMemberDto) {
Здесь первым параметром приходит teamId (id проекта/команды, куда добавлять нового участника) - это следует из того, как у тебя спроектирован урл в контроллере (/team/{id} - это кстати верно). А userId ты можешь получить из UserContext, метод getUserId - это в идеале, рекомендую сделать именно так. Но можешь также передать userId в эндпоинт либо через хэдер (предпочтительнее), либо через dto (вариант похуже)

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        if (!(user.getRoles().contains(TeamRole.TEAMLEAD) ||
Вот так будет проще восприниматься: 
`!user.getRoles().contains(TeamRole.TEAMLEAD) && !user.getRoles().contains(TeamRole.OWNER)`

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +            log.error(message);
логгировать здесь не нужно, это будет в глобальном обработчике ошибок (GlobalExceptionHandler) происходить

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +            String message = String.format("This member %d is already a project participant." +
Согласна с Валерой. На основе dto нельзя определить, является ли уже этот человек участником проекта или нет, в dto могут что угодно передать) Нужно сходить в базу

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +                .build();
Да, но лучше придерживаться единообразного подхода) Я бы через маппер везде делала, если только нет явного аргумента, почему через билдер в данной ситуации лучше

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        if (!teamMemberRepository.findById(userId).getRoles().contains(TeamRole.TEAMLEAD)) {
Согласна

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +    public List<TeamMemberDto> getTeamMembersByFilter(TeamFilterDto filters) {
Согласна. 
Рекомендую: в контроллере все `@PathVariable long id` переименовать в `@PathVariable long teamId` (тебе так самому будет проще не запутаться), также добавить teamId к get-эндпоинту с фильтрами. И про userId написала выше - он тоже нужен.

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        log.info("Getting team members by filter: {}", filters);
Для get-эндпоинтов уровень логирования лучше делать debug, т.к. get запросы делаются очень часто и если оставить info уровень, то будет много одинаковых логов, среди которых действительно важные логи (с модифицирующих методов) затеряются. Ну и логи будут очень много весить и занимать много места)

2024-09-29 17:44 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/teamfilter/TeamMemberRoleFilter.java
> +        return teamFilterDto != null;
И ещё поле внутри должно быть не null

2024-10-01 08:49 UTC, RuslanIovlev commented
я не понимаю, почему у меня не проходят тесты
практически везде падает nullpointerexception.
Я уже и так и сяк пытался мокать, уже зауптался

2024-10-01 08:51 UTC, RuslanIovlev commented
Либо в коде косяк

2024-10-01 10:21 UTC, wmwmaks commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberServiceTest.java
> +        teamMember = TeamMember.builder()
У тебя не все в setUp инициализируется, на мой взгляд. Я бы сделал так +-

team = new Team();
        project = new Project();
        team.setId(1L);
        project.setId(1L);

        teamMember = new TeamMember();
        teamMember.setId(2L);
        teamMember.setRoles(List.of(TeamRole.DEVELOPER));

        owner = new TeamMember();
        owner.setId(3L);
        owner.setRoles(List.of(TeamRole.OWNER));
        owner.setTeam(team);

        team.setTeamMembers(List.of(teamMember, owner));
        project.setTeams(List.of(team));
        
       И во всех when использовать эти сущности тестовые, например, when(....(tm.getId()).thanreturn(tm) и так далее.

2024-10-01 10:23 UTC, wmwmaks commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberServiceTest.java
> +        teamMember = TeamMember.builder()
Логика такая, что для того, чтобы работать с тиммембером, нужно его создать, а он не может существовать без команды, а команда не существует вне проекта. Так и получается, что собрать нужно все слои, а учитывая, что в том же deleteTeamMember ты должен передавать в метод findByUserIdAndProjectId у teamMemberJpaRepository projectId это становится еще актуальнее. Ты там ,кстати, пишешь в аргументе teamId, что может быть неверно. team и projectId разное. Так что я бы еще раз перепроверил логику методов сервиса. Не напутал ли чего вдруг

2024-10-01 10:31 UTC, wmwmaks commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberServiceTest.java
> +        teamMember = TeamMember.builder()
Не силен в тестах, могу быть не прав, но вдруг. Пища для размышлений так сказать)

2024-10-01 11:30 UTC, wmwmaks commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberServiceTest.java
> +        teamMember = TeamMember.builder()
Еще там в UserServiceClient, кажется, неверный url и название метода getUser, относительно user_service. Если я не ошибаюсь, Инна говорила в лекции, что должно быть точь в точь.

2024-10-01 16:58 UTC, mysosnovskaya requested changes
Нужно ещё раз разобраться с teamId/projectId, и отладить тесты (про них написала комментарий, если что - приходи в чат с конкретным вопросом). Жду скорее на следующее (и думаю уже финальное) ревью)
Ещё хочу отметить, что ты разобрался и добавил все мои необязательные предложения (пагинацию, user context) - молодец!) Отличный настрой!)

2024-10-01 16:58 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberServiceTest.java
> +        MockitoAnnotations.openMocks(this);
Эта строчка не нужна

2024-10-01 16:58 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberServiceTest.java
> +public class TeamMemberServiceTest {
Сейчас не все тесты проходят. Нужно с каждым отдельно разбираться. Не везде всё замокано (где-то не хватает мока на userContext, где мокается не тот метод, который на самом деле вызывается). Я не смогу вместо тебя продебажить, найти все ошибки и просто тебе о них сказать. Можешь попросить помощи у кого-то из команды или кидай скриншот теста и ошибки в чат, там вместе (со мной и/или с кем-то из команды) можно будет разобраться

2024-10-01 16:58 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberServiceTest.java
> +    private final static long USER_ID = 1L;
Константы лучше всегда писать в самом верху класса)

2024-10-01 16:58 UTC, mysosnovskaya commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberServiceTest.java
> +        teamMember = TeamMember.builder()
Да, Руслан, посмотри, пожалуйста, подходит ли то, что написал Максим, и если да, давай сделаем

2024-10-01 16:58 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        TeamMember user = teamMemberJpaRepository.findByUserIdAndProjectId(userId, teamId);
teamId и projectId это точно одно и то же? По смыслу они, конечно, связаны, но по-моему значения должны быть разными

2024-10-01 16:58 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +public interface TeamMemberService {
Молодец, что сервис выделил 👍

2024-10-01 16:58 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/TeamMember.java
> +    @Column(name = "roles")
Почему?

2024-10-01 16:58 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +                .id(teamMemberDto.teamMemberId())
Не поняла, почему в dto приходит id, если это создание?

2024-10-01 16:58 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +                                          @RequestBody TeamMemberDto teamMemberDto) {
Лучше разделить dto на создание, обновление и response

2024-10-01 16:58 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        Page<TeamMember> teamMembers = teamMemberJpaRepository.findAll(pageable);
Молодец, что разобрался и сделал пагинацию! 👍

2024-10-01 16:58 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +    private final UserContext userContext;
Отлично, что решил использовать контекст 👍 Это самое верное решение)

2024-10-01 16:58 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        TeamMember teamMember = TeamMember.builder()
Лучше всё-таки через маппер)

2024-10-01 16:58 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        log.info("Getting all team members");
Здесь и в этом методе ниже лучше log.debug (т.к. это get-методы)

2024-10-02 18:59 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +                                          @RequestBody TeamMemberDto teamMemberDto) {
не совсем понял что имеешь ввиду

2024-10-02 19:03 UTC, RuslanIovlev commented
Что я не могу понять, usercontext возвращает мой айдишник как пользователя
Так Влад говорит в одном из воркшопов
Его я использую для проверки что я являюсь тимлидом или создателем
Как я должен получить айди нового участника которого хочу добавить

2024-10-02 19:05 UTC, RuslanIovlev commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberServiceTest.java
> +        teamMember = TeamMember.builder()
Максим спасибо большое за наводку
Очень благодарен

2024-10-02 19:58 UTC, SharkB38 commented
> Что я не могу понять, usercontext возвращает мой айдишник как пользователя Так Влад говорит в одном из воркшопов Его я использую для проверки что я являюсь тимлидом или создателем Как я должен получить айди нового участника которого хочу добавить
Передать аргументом в метод, или создать CreateTeamMemberDto с полем userId

2024-10-02 19:58 UTC, SharkB38 approved these changes

2024-10-02 20:05 UTC, mysosnovskaya requested changes

2024-10-02 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +    @PutMapping("/members/{id}")
Почему-то в POST /{id}/members, а здесь - /members/{id}. Смысл разный: в первом случае id - это id команды (teamId), а во втором случае id - это id участника команды (team member). Везде ниже аналогично

2024-10-02 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +    public TeamMemberDto addTeamMember(@Positive @PathVariable long teamId,
В PostMapping называется id, а здесь - teamId. Это точно работает, ты проверял через постман?

2024-10-02 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +                                          @RequestBody TeamMemberDto teamMemberDto) {
Посмотри аналогию в StageController. Три отдельных dto класса: один на создание, другой на обновление и третий для возврата ответа (response)

2024-10-02 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/TeamMember.java
> +    @Column(name = "roles")
Комментарий помечен как разрешенный, но я так и не поняла, почему название колонки изменилось

2024-10-02 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +    TeamMemberDto addTeamMember(long id, TeamMemberDto teamMemberDto);
В названии лучше пояснить, что это за id. id команды? id участника команды? id проекта? везде ниже тоже

2024-10-02 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        Team team = teamRepository.findById(teamId).orElseThrow();
В orElseThrow нужно написать какое-то исключение.

2024-10-02 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        long projectId = team.getProject().getId();
Нашелся projectId, ура!)

2024-10-02 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        TeamMember user = teamMemberJpaRepository.findByUserIdAndProjectId(userId, projectId);
userId - это id того, кто делает запрос (например, менеджер команды). А что узнать, кого добавлять, нужно использовать поле teamMemberId из teamMemberDto. Только когда будешь разделять dto на три разных, то обрати внимание, что в dto на создание поле teamMemberId должно называться по-другому, т.к. когда ты только создаешь тим мембера, то у него ещё нет никакого id. У него есть id как у пользователя (user). Вот его мы должны присоединить к команде, сохранить через  `teamMemberJpaRepository.save(teamMember);` и тогда у этого пользователя появится teamMemberId

2024-10-02 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/TeamMemberServiceImpl.java
> +        teamMemberJpaRepository.delete(teamMemberRepository.findById(teamMemberId));
В teamMemberJpaRepository есть метод deleteById - вот лучше его использовать

2024-10-03 12:27 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/model/TeamMember.java
> +    @Column(name = "roles")
честно я не трогал
я только обновлял проект, возможно подтянулось

2024-10-04 20:06 UTC, mysosnovskaya requested changes
Ура! Теперь всё очень красиво вышло) Мне понравилось, что ты и UserContext используешь, а Pageable добавил, и с этими многочисленными id разобрался. Я думаю, что это очень крутая практика получилась) Молодец!
Остались три совсем мелких исправления и закроем задачу) Жду!

2024-10-04 20:06 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/TeamMember.java
> +    @Column(name = "roles")
Нужно вернуть обратно, т.к. это неверно. Я не знаю, откуда оно взялось, но в master это попасть не должно)

2024-10-04 20:06 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/team/TeamMemberCreateDto.java
> +        long userId,
Похоже, ты этим полем не пользуешься нигде (ты берешь userId из контекста), так что можно удалить

2024-10-04 20:06 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/TeamMemberMapper.java
> +    TeamMember toTeamMember(TeamMemberDto teamMemberDto);
А тебе этот метод точно где-то нужен?

2024-10-05 16:09 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/dto/team/TeamMemberCreateDto.java
> +        long userId,
почему, я же по этому полю добавляю нового участника
Из контекста я беру айдишник чтобы проверить кто делает запрос
Ты же мне сама так говорила

2024-10-05 16:30 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/team/TeamMemberCreateDto.java
> +        long userId,
А, извиняюсь. Да, всё верно тогда) Аппрув и мердж!

2024-10-05 16:31 UTC, mysosnovskaya approved these changes

2024-10-05 16:31 UTC, merged