Интеграция с Jira - BJS2-26687 - без тестов
CorporationX/project_service pull request #676
Opened 2024-09-28 19:05 UTC by fragmatik-top

Класс MyInfo я не пушал, там храниться мои данные для подключении к jira. Особо не обращайте внимание на это, я позже настрою с получением личных данных с user-service.

2024-09-29 10:18 UTC, ostermal7 reviewed
в большинстве случаев у эндпоинтов поубирай глаголы, они лишние

2024-09-29 10:18 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/exception/JiraErrorResponseException.java
> +    private final JiraDto errorResponse;
Не уверен хорошая ли это практика - в классе ошибке объявлять связь с дто классом. Почему бы сразу в эксепшн не прокидывать getErrors?

2024-09-29 10:18 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/dto/jira/JiraDto.java
> +    public static class InwardIssue {
Почему решил их всех статическими сделать?

2024-09-29 10:18 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/controller/jira/JiraController.java
> +    @PostMapping("/create")
зачем тут глагол? У тебя и так понятно, что /jira PostMapping будет создавать

2024-09-29 10:18 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/jira/JiraService.java
> +public class JiraService {
интерфейс и его имплементация

2024-09-29 10:18 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/controller/jira/JiraController.java
> +    @PutMapping("/update-task")
уверен, что тут и в остальных put, а не patch должен быть?

2024-09-29 10:18 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/controller/jira/JiraController.java
> +    @PutMapping("/update-link")
можно просто "/link". у тебя и так пут указывает, что апдейт. Пересмотри названия эндпоинтов

2024-09-29 10:18 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/jira/JiraService.java
> +                .onErrorResume(jiraResponse::handlerErrorConnection);
возможно чтоит рассмотреть отдельный метод, куда будешь в зависимости от желаемого передавать в аргументы путь. Потому что у тебя у методов на 90% один и тот же код, выходит дублирование

2024-09-29 10:18 UTC, ostermal7 commented on src/main/java/faang/school/projectservice/service/jira/response/JiraResponse.java
> +                                + errorBody)));
через switch с лямбдой тут не будет чище выглядеть?

2024-10-02 12:53 UTC, fragmatik-top commented on src/main/java/faang/school/projectservice/service/jira/JiraService.java
> +                .onErrorResume(jiraResponse::handlerErrorConnection);
Да проблема в том,что есть где методы put, get, post и разные ответы, где-то dto отправляю,а где то просто код отправляю, я думал над этим, но так и не получилось сделать

2024-10-02 12:55 UTC, fragmatik-top commented on src/main/java/faang/school/projectservice/service/jira/response/JiraResponse.java
> +                                + errorBody)));
Да было бы чище! я делал по началу, то там была одна проблема...

2024-10-07 16:35 UTC, mikhailov26 requested changes

2024-10-07 16:35 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/config/jira/WebClientConfig.java
> +@Component
меняем на @configuration

2024-10-07 16:35 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/dto/jira/JiraDto.java
> +    public static class InwardIssue {
Аналогичный вопрос

2024-10-07 16:35 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/service/jira/JiraService.java
Как писал Денис, интерфейс + имплементация, добавь в сервис пакет impl и туда его имплементацию

2024-10-07 16:35 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/service/jira/JiraServiceImpl.java
> +                .uri("/rest/api/3/issue/{issueKey}", issueKey)
для всех путей сделать пакет util, туда вставь публичные статические константы, так будет более правильно

2024-10-07 16:36 UTC, mikhailov26 commented
В целом хорошо, за исключением небольших НО

2024-10-17 17:10 UTC, mikhailov26 approved these changes

2024-10-17 17:10 UTC, merged