v1 task: Обработчик исключений в project_servic (feature-BJS2-26113)
CorporationX/project_service pull request #677
Opened 2024-09-29 12:28 UTC by Varrankin

2024-09-29 12:56 UTC, GusevVrn approved these changes
Вопрос у ErrorResponse к аннотации @Data - нужен ли он вообще, set - через билдер делаешь, toString вроде не выводишь, equals и hashCode тем более, мне кажется без этой аннотации будет работать, надо проверить.

так в целом хорошо

2024-09-29 18:25 UTC, mysosnovskaya requested changes

2024-09-29 18:25 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +    @ExceptionHandler(DataValidationException.class)
Оставить бы пустую строчку перед аннотацией. Так принято

2024-09-29 18:25 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +                .status(HttpStatus.BAD_REQUEST.value())
Зачем статус дублировать? И error тоже. Оно и так дойдет до пользователя благодаря аннотации ResponseStatus

2024-09-29 18:25 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +    public ErrorResponse handlerIllegalArgumentException(IllegalArgumentException e, HttpServletRequest request) {
Дублирование с предыдущим методом, давай объединим

2024-09-29 18:25 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +        log.error("Data validation exception occurred: {}", e.getMessage());
В лог лучше полностью всё исключение прокинуть, чтобы мы могли видеть стектрейс

2024-09-29 18:25 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +        Map<String, String> errors = e.getConstraintViolations().stream()
Молодец, что с этим исключением именно так поработал 👍

2024-09-29 18:25 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +    public ErrorResponse handlerException(Exception e, HttpServletRequest request) {
Дублирование с предыдущим методом

2024-09-29 18:25 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +                .status(HttpStatus.BAD_REQUEST.value())
Статус код не тот. И в следующем методе также.

2024-09-29 18:25 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/ErrorResponse.java
> +    private int status;
Уже писала в хэндлере, это поле не нужно, как и error

2024-09-29 18:25 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/ErrorResponse.java
> +    private Map<String,String> errorInFields;
Нужно стиль поправить.
А получается, что это поле нужно только для ошибок, связанных с валидацией? Тогда лучше сделать два разных dto, чтобы не смешивать всё в кучу.

2024-09-29 18:25 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/ErrorResponse.java
> +    public ErrorResponse(String url, int status, String error, String message){
А этот конструктор для чего? Ты везде билдером пользуешься.
И согласна с Пашей - тебе надо проверить, какие аннотации ты ставишь над классом, и оставить только нужные

2024-10-01 10:34 UTC, Varrankin commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +                .status(HttpStatus.BAD_REQUEST.value())
ты имеешь в виду, чтобы вообще убрать данные поля из ErrorResponse? просто как я понял, данные из ResponseStatus мы передаем в формате html, а в json таких данных не будет при ответе + я тестировал это через постман, поэтому решил оставить, а оставил потому что не совсем понимаю в каком формате мы ответ возвращаем клиенту? просто JSON или всегда HTML или то и другое? от чего это зависит?

2024-10-01 10:56 UTC, Varrankin commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +                .status(HttpStatus.BAD_REQUEST.value())
так же если мы используем аннотацию @RestController, Spring по умолчанию будет возвращать данные в формате JSON.

2024-10-01 11:01 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +                .status(HttpStatus.BAD_REQUEST.value())
Попробуй на другом сервисе, где еще не прикручен глобальный обработчик кинуть какой-нибудь запрос GET и посмотри что тебе придет в ответе, просто визуально в самом постмане.

Ты в тело ответа пихаешь код ответа и статус, а это дублирующая информация. 
Я на это обратил внимание при проверке, но не стал заострять, т.к. не был уверен как правильно.

Вот тут я кинул запрос и получил код 202 и статус accepted.
![photo_2024-10-01_13-57-37](https://github.com/user-attachments/assets/f1d64017-6460-468e-a265-d252af377981)

2024-10-01 11:12 UTC, Varrankin commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +                .status(HttpStatus.BAD_REQUEST.value())
а почему не тот? мы же тут обрабатываем все ошибки которые мы не смогли учесть и это наша проблема, т.е ошибка сервера, после мы должны локализировать ошибку и дописать обработчик более конкретным исключением

2024-10-01 11:22 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +                .status(HttpStatus.BAD_REQUEST.value())
@Varrankin обрати внимание на @ResponseStatus и  .status(...)
Ты в ответе отдаешь одну ошибку, а в теле хочешь показать другую. 

Я бы в @ResponseStatus кинул badRequest, но runtime эксепшен достаточно абстрактный, непонятно на каком этапе он упал. Поэтому послушаю @mysosnovskaya какой правильно указывать)

2024-10-01 11:25 UTC, Varrankin commented on src/main/java/faang/school/projectservice/exception/ErrorResponse.java
> +    public ErrorResponse(String url, int status, String error, String message){
согласен, просто не совсем понимал как работает билдер, сейчас разобрался)

2024-10-01 11:56 UTC, Varrankin commented on src/main/java/faang/school/projectservice/exception/ErrorResponse.java
> +    private Map<String,String> errorInFields;
исправил)

2024-10-01 18:46 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +                .status(HttpStatus.BAD_REQUEST.value())
REST - это всегда про json. Но статус код - это часть респонса, которая не относится к телу (теоретически тело может быть в любом формате). Вот у Паши на скрине выше виден статус код 202 в постмане. У тебя тоже будет виден статус код, который ты проставишь в аннотации ResponseStatus, поэтому ещё раз то же самое писать в json не нужно

2024-10-01 18:51 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +    public ErrorResponse handlerIllegalArgumentException(IllegalArgumentException e, HttpServletRequest request) {
Этот и предыдущий методы можно объединить в один метод. Посмотри, ExceptionHandler позволяет указать сразу несколько исключений

2024-10-01 18:51 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +    @ExceptionHandler(RuntimeException.class)
RuntimeException наследуется от Exception, поэтому этот метод можно удалить. В таком случае обработка RuntimeException будет сделана в методе handlerException (благодаря наследованию)

2024-10-01 18:51 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +                .status(HttpStatus.BAD_REQUEST.value())
RuntimeException это INTERNAL_SERVER_ERROR всегда. Это значит у нас на сервере что-то произошло (тот же Null Pointer Exception), что мы не предвидели. Пользователь как правило не виноват (мы должны его данные провалидировать и исключить некорректные данные от него). В таком случае все остальные ошибки - это наши с вами проблемы, внутренние (отсюда и internal)

2024-10-01 18:53 UTC, mysosnovskaya requested changes
Остались небольшие исправления, думаю, уже в следующий раз смержим) И ещё обрати внимание, я ещё выше ответила на некоторые вопросы к предыдущим комментариям

2024-10-01 18:53 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/ValidationErrorResponse.java
> +public class ValidationErrorResponse {
Вот, теперь отлично получилось с dto-классами 👍

2024-10-02 11:19 UTC, Varrankin commented on src/main/java/faang/school/projectservice/controller/GlobalExceptionHandler.java
> +                .status(HttpStatus.BAD_REQUEST.value())
понял) спасибо

2024-10-02 18:09 UTC, mysosnovskaya approved these changes

2024-10-02 18:09 UTC, merged