Google Calendar API integrated into project-service
CorporationX/project_service pull request #678
Opened 2024-09-29 12:53 UTC by MamadjonovKO

2024-10-02 08:03 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/controller/CalendarController.java
> +    }
Не понимаю зачем ты здесь возвращаешь String. Вроде бы в первом методе достаточно `return calendarService.auth(projectId, code);` и void. Во втором `return calendarService.createEvent(projectId, calendarId, eventDto);` и CalendarEventDto.

2024-10-03 09:47 UTC, MamadjonovKO commented on src/main/java/faang/school/projectservice/controller/CalendarController.java
> +    }
Я связал события из user-service с календарем. Теперь, когда в user-service создается новое событие, оно автоматически создается и в Google Календаре. После этого необходимо вернуть ID события из календаря и сохранить его в соответствующей сущности события в user-service. Для этого я добавил дополнительное поле в сущность для хранения ID из Google Календаря.

2024-10-03 10:00 UTC, MamadjonovKO commented on src/main/java/faang/school/projectservice/controller/CalendarController.java
> +    }
А первый момент, действительно, я забыл внести изменения. Когда тестировал, я захардкодил значение, исправил. Спасибо (:

2024-10-06 11:15 UTC, 20cognosce requested changes
В целом хорошо, но
1. Прошу добавить readme / help.md файл с сиквенс диаграммой по твоей фиче, чтобы другим разработчикам был понятен процесс интеграции с гуглом
2. На встрече необходимо провести лайв демо, как оно у тебя работает

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/CalendarController.java
> +@RequestMapping("projects")
/projects

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/CalendarController.java
> +    @GetMapping("calendars/auth")
/ в начале каждого эндпоинта

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/CalendarController.java
> +    @PostMapping("{projectId}/calendars/auth")
пробел

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/CalendarController.java
> +    @GetMapping("calendars/auth")
респонс статус 300

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/CalendarController.java
> +        eventDto.verifyEndIsAfterStartTime();
че за метод у ДТО? в валидаторе метод создай

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/repository/GoogleCalendarTokenRepository.java
> +            """)
зачем ты пишешь нативный квери на дефолтный метод

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/CalendarService.java
> +        }
Тебе не кажется, что это дублирование кода?

Сделай один метод, который принимает фукнцию
Оборачивает её в создание сервиса календаря, самого календаря и try catch
И в качестве функции передавай то, что внутри try блока

Код станет чище

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/CalendarService.java
> +        var newCalendar = calendarMapper.toModel(calendarDto);
var не используй
Calendar service - не понятное имя, что это

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/CalendarService.java
> +    @Transactional
Вопрос, что делает транзакция для всех эти методов? Они с базой не работают, они работают с сетевыми вызовами, причем тут транзакции тогда?

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/GoogleAuthorizationService.java
> +import com.google.api.client.auth.oauth2.*;
Не сворачивать

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/GoogleAuthorizationService.java
> +            http_transport = GoogleNetHttpTransport.newTrustedTransport();
camel case не по java specification

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/GoogleAuthorizationService.java
> +        if (credential.getExpiresInSeconds() < Long.parseLong(Objects.requireNonNull(env.getProperty("google.accessTokenExpiresInSeconds")))) {
а можно развернуть if else?

{
if (false) {
throw exception
}
main code;
}

2024-10-06 11:15 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/GoogleAuthorizationService.java
> +                    return calendarTokenRepository.save(calendarToken);
Что это...
Декомпозировать

2024-10-06 11:15 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    count_to_return: 10
Отступ 4 пробела
В настройках идеи

2024-10-15 20:51 UTC, 20cognosce requested changes
Конфликты

2024-10-15 20:51 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/calendar/readme/help.md
> +<div style="text-align: center;">
В корневой директории проекта, на одном уровне с build.gradle должен быть help.md и картинка, не в коде

2024-10-15 20:51 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/GoogleAuthorizationService.java
> +    }
Убери @PostConstruct, бины в конфигурации нужные создай

2024-10-15 20:51 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/GoogleAuthorizationService.java
> +    }
Почему public методы идут ниже приватных? Разложи методы по полочкам, какой от какого зависит
Может в другой класс вынеси что-то в зависимости от ответственности

2024-10-15 20:51 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    count_to_return: 10
Ты ничего не исправил, как было 2 пробела, так и осталось
Сделай 4 для табуляции в yaml

2024-10-15 20:51 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V017_create_google_calendar_token.sql
> +    project_id       BIGINT       NOT NULL,
Форматирование ctrl + L

2024-10-18 11:56 UTC, 20cognosce approved these changes
Исправь конфликты и можешь сделать мердж

2024-10-19 05:42 UTC, merged