BJS2-27436 : Добавление общих файлов
CorporationX/project_service pull request #679
Opened 2024-09-29 19:00 UTC by soulasphyxia

2024-09-29 21:13 UTC, SharkB38 approved these changes
Ну круто, нашел только пару спорных вещей

2024-09-29 21:13 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        BigInteger maxSizeInMBs = maxSize.divide(new BigInteger("1048576"));
Мб в конфиг или константу?

2024-09-29 21:13 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/s3/S3ServiceImpl.java
> +        }
Не знаю надо или нет, но может дальше ошибку прокидывать, чтобы потом хэндлер все это дело обрабатывал и кидал ответ клиенту?

2024-09-29 21:13 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/s3/S3ServiceImpl.java
> +            );
Я бы скобку на строку перенес

2024-09-30 03:54 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        Resource resource = findResourceById(resourceId);
Думаю тут нужна ещё проверка, что запрашивающий юзер является участником проекта, чтобы доступ к ресурсу был только у участников проекта, как тебе кажется?)

2024-09-30 04:00 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        resourceRepository.delete(resource);
Тут также думаю нужна проверка, что user это создатель ресурса или менеджер. И по условию, ресурс полностью не удаляется, а обнуляются параметры, ставится статус DELETED и обновляется storageSize у проекта)

2024-09-30 04:04 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        resource.setUpdatedAt(LocalDateTime.now());
Некритично, вроде над полем updatedAt стоит аннотация @UpdateTimestamp, поэтому вручную можно не обновлять)

2024-09-30 04:06 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        Resource updatedResource = resourceRepository.save(resource);
Думаю тут тоже нужно проверять и обновлять storage у проекта, так как могут большой файл передать при обновлении)

2024-09-30 04:19 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/s3/S3ServiceImpl.java
> +        resource.setUpdatedAt(LocalDateTime.now());
Также, можно вручную не обновлять эти поля) Я бы ещё этот ресурс создавал не здесь, а в классе ResourceServiceImpl, перед сохранением в базу, а здесь оставил бы только взаимодействие с s3)

2024-09-30 04:20 UTC, ArstanSubanov approved these changes
Отлично) Оставил свои рекомендации, можешь рассмотреть, если они покажутся логичными)

2024-09-30 12:51 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/s3/S3ServiceImpl.java
> +        }
да, добавлю исключения для работы с файлом

2024-09-30 12:53 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/s3/S3ServiceImpl.java
> +            );
если так переносить, то вроде как скобка ставится вот в таком стиле, как, например, фигурные скобки у классов или функций

2024-09-30 12:53 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        Resource resource = findResourceById(resourceId);
ты прав, сделаю!

2024-09-30 12:53 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        resourceRepository.delete(resource);
согласен, пропустил этот пункт, спасибо что заметил!!

2024-09-30 12:54 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        Resource updatedResource = resourceRepository.save(resource);
да, ты прав, что-то я совсем поторопился сдавать задачу в этот раз, столько всего упустил, хотя вроде как помнил :)

2024-09-30 15:13 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/s3/S3ServiceImpl.java
> +        resource.setUpdatedAt(LocalDateTime.now());
Арстан, спасибо тебе большое) я сделал очень глупо, просто скопировав код с воркшопа по minio. когда я по твоему вынес создание ресурса в методы ResourceService, у меня отвалилась надобность в методе updateFile и теперь я делаю обновление и загрузку через 1 метод

2024-09-30 17:14 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        BigInteger maxSizeInMBs = maxSize.divide(new BigInteger("1048576"));
сделал!

2024-10-01 09:17 UTC, mysosnovskaya requested changes

2024-10-01 09:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/config/context/AwsS3Config.java
> +@Configuration
Лучше сделать через ConfigurationProperties, она как раз для таких классов с параметрами

2024-10-01 09:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/config/context/AwsS3Config.java
> +    public AmazonS3 amazonClient() {
Я бы разделила на два класса: AwsS3Params (с параметрами из yaml) и AwsS3Config (с нужными бинами). Максим в своем ПР делал такое же, можешь посмотреть
https://github.com/CorporationX/user_service/pull/1602/files

2024-10-01 09:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/ResourceController.java
> +    public ResponseEntity<byte[]> getResource(@PathVariable @Positive Long resourceId){
Лучше вернуть `ResponseEntity<Resource>`, только это не тот ресурс, который в проекте, а спринговый класс. Его легко создать из InputStream 
https://genuinecoder.com/downloading-a-file-from-spring-controller-with-spring-boot/

2024-10-01 09:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/ResourceController.java
> +    @PostMapping("/{projectId}/add")
Зачем здесь /add? 
Вообще должно быть POST /resources, а в теле должна вся необходимая информация прийти. Но т.к. у тебя тело запроса - это файл, то можно сделать POST /resources/projects/{projectId}

2024-10-01 09:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(ResourceHandlingException.class)
Тут по-хорошему Throwable должен быть, чтобы вообще все исключения отловить и отправить красивый ответ со статусом 500

2024-10-01 09:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        if (teamMemberJpaRepository.existsByUserIdAndProjectId(userId, resource.getProject().getId())) {
А ещё нужно обратить внимание на allowedRoles у ресурса
https://github.com/CorporationX/project_service/blob/hydra-master-stream6/src/main/java/faang/school/projectservice/model/Resource.java#L49

2024-10-01 09:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        resource.getCreatedBy().getUserId().equals(userId)) {
Неверный стиль кода. И ещё ниже перед else пробела не хватает

2024-10-01 09:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        if (teamMember.getRoles().contains(TeamRole.MANAGER) ||
Лучше писать в стиле:
```
if (...) {
    throw new...
}
...
```
Это чтобы не писать значительную часть кода (весь блок if, практически всё тело метода) с повышенным уровнем вложенности

2024-10-01 09:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        resource.setName(file.getOriginalFilename());
С этой кучкой сеттеров нужно что-то делать) И в следующем методе тоже. Подумай, как это можно облагородить)

2024-10-01 09:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +            resourceRepository.save(resource);
Лучше сначала обновить информацию в базе данных, а потом удалить из s3. Да, по логике это странно, но тут нужно учесть тразнакционность:
- в текущей реализации может возникнуть такая ситуация: файл из s3 удалился успешно, а в базу данных по какой-либо причине изменения внести не удалось. Как следствие мы получаем не консистентное состояние. 
- если же поменять порядок местами, то: сначала идем в базу данных, а затем в s3. И если из s3 по какой-либо причине файл удалить не удалось, то мы получим исключение, а т.к. оно вылетит внутри транзакции, то все изменения, внесенные в базу данных, откатятся

2024-10-01 09:17 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/s3/S3ServiceImpl.java
> +            );
Да, тут со стилем всё ок

2024-10-05 08:06 UTC, soulasphyxia commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        if (teamMember.getRoles().contains(TeamRole.MANAGER) ||
да, согласен, но конкретно в этот раз у меня вспомнилось замечание Арстана, что лучше писать логику без отрицания, а тут получится, что без отрицания не обойтись. как тут поступать? мне кажется, что с отрицанием будет не критично, или, выносить все в отдельный метод, чтобы было без отрицания?

2024-10-05 15:57 UTC, mysosnovskaya requested changes

2024-10-05 15:57 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +    private boolean notCreatorOrManager(Resource resource, TeamMember teamMember) {
Вынести в отдельный метод определенно нужно, молодец, что подумал об этом и сделал) Над названием метода я бы ещё поработала (not в названиях методов не пишут). Может hasAccess (имеет доступ) или что-то такое

2024-10-05 15:57 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        Resource resource = Resource.builder()
Я бы создание ресурса вынесла в отдельный приватный метод. Здесь это очень мешает воспринимать логику метода

2024-10-05 15:57 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceServiceImpl.java
> +        boolean hasAllowedRole = teamMember.getRoles()
Всю это логику по определению роли можно вынести в отдельный приватный метод

2024-10-06 23:11 UTC, mysosnovskaya approved these changes

2024-10-06 23:11 UTC, merged