Feature bjs2 26120
CorporationX/project_service pull request #682
Opened 2024-09-29 19:47 UTC by Silencemess1ah

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/controller/resource/ResourceController.java
> +        return ResponseEntity.ok("File was successfully deleted!");
Убери responseEntity
и возвращай 204 ошибку, а не ok

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/dto/resource/ResourceResponseDto.java
> +@Data
тебе как минимум 3 аннотации не нужны из Data

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/dto/resource/ResourceUpdateDto.java
> +@Data
И тут тоже

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/model/Project.java
> +@EqualsAndHashCode
Я бы сгенерил EqualsAndHashCode руками раз появилась такая необходимость, т.к. он все еще включает в себя меняющиеся объекты и листы

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/model/Resource.java
> +@EqualsAndHashCode
аналогично

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/model/TeamMember.java
> +@EqualsAndHashCode
и туть

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public Project getProjectEntity(long id) {
посмотри на метод выше, они @Equals

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/validator/resource/ResourceValidator.java
> +
Отступ

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/validator/resource/ResourceValidator.java
> +    private static final BigInteger STORAGE_SIZE = new BigInteger(String.valueOf(Math.round(Math.pow(1000, 3))));
1000 и 3 как-нибудь вынести и указать что это

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/validator/resource/ResourceValidator.java
> +        if (!Objects.equals(fileOwner.getTeam().getProject().getId(), projectId)) {
раз уж такая пьянка то fileOwner.getTeam().getProject().getId() можно вынести в отдельную переменную и как-то ее красиво обозвать

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/validator/resource/ResourceValidator.java
> +        return Math.round(size / Math.pow(1000, 3));
вот опять какие-то 1000 и 3

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/validator/resource/ResourceValidator.java
> +        if ((BigInteger.valueOf(file.getSize())).compareTo(project.getStorageSize()) > 0) {
так, а если они равны?
еще момент, я не совсем понимаю, т.к. ты пускал должен понимать)
Если у меня файл 800мб, а project.getStorageSize() будет 1гб - в таком случае типо можно заливать?

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +        return amazonS3Client.getObject(request);
могут ли у тебя тут вылетить какие-нибудь ошибки при получении?
Проверял если пытаешься дернуть файл которого нету на облаке?

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +public class S3Service {
у тебя везде ключ или folder указаны с "/" - я в целом ок,
но если добавлять какую-то логику по добавлению чего-то из другого контроллера там тоже будет все через папки?

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +            PutObjectRequest request =
раздели логическими отступами

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +        amazonS3Client.deleteObject(request);
он что-нибудь может выбросить если файла в облаке не будет?

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    public void deleteObject(Resource resource) {
по логике получается что даже если вдруг файл не удалится сервис  который вызывает, об этом не узнает и пойдет дальше

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +            log.debug("Downloading file starts.");
у тебя же сверху загрузка, а ты только тут пишешь

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        if (!Objects.equals(resource.getCreatedBy().getId(), fileOwner.getId()) ||
resource.getCreatedBy().getId() и resource.getProject().getOwnerId() в отдельные переменные

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        resource.getProject().setStorageSize(resource.getProject().getStorageSize().add(resource.getSize()));
Это бы вынести в отдельный метод в Resource.java типо clearFile или что-то типо того

2024-09-30 19:43 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        List<TeamRole> updatedRoles = new ArrayList<>(resourceUpdateDto.getAllowedRoles());
а без new ArrayList<> не прокатит?

2024-09-30 19:54 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public Project getProjectEntity(long id) {
Да и самое смешное что я в тесте сижу и не понимаю почему приходит null Project вызываю один в тесте другой в сервисе два разных одинаковых метода )

2024-09-30 19:59 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        List<TeamRole> updatedRoles = new ArrayList<>(resourceUpdateDto.getAllowedRoles());
Не, в этом и прикол, там ошибка лезет из сущностей что мол ссылаюсь на одни и те же коллекции в базе

2024-09-30 20:02 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/validator/resource/ResourceValidator.java
> +        if ((BigInteger.valueOf(file.getSize())).compareTo(project.getStorageSize()) > 0) {
Если равны интересное наблюдение, к такому жизнь меня не готовила думаю шанс супер мал на такой исход надо подумать... если 800 а свободного места 1 гб лей не жалей

2024-09-30 20:04 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +        return amazonS3Client.getObject(request);
Целенаправленно мм нет, просто если создали файл то под него 100% есть ресурс, если ресурс не найден в базе оно сюда и не пойдет по идее...

2024-09-30 20:07 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +        amazonS3Client.deleteObject(request);
Ну тут тоже самое что и по получению, 2 проверки что есть в базе под него ресурс, ключ мне не откуда будет брать в этом случае и + еще проверки на человека что он либо манагер либо заливал этот файл, я могу конечно подумать как можно здесь тоже обезопаситься, но я даж не понимаю при каких условиях мы сюда попадем с другим ключом

2024-10-01 07:50 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/validator/resource/ResourceValidator.java
> +        if ((BigInteger.valueOf(file.getSize())).compareTo(project.getStorageSize()) > 0) {
@Silencemess1ah я пытаюсь сформулировать мысль, но не получатся.

project.getStorageSize() - это какой-то фикс же будет для одного проекта. Ты льешь туда файлы, тебе наверное надо не по фиксу смотреть, а по свободному месту на облаке и вот если свободного места больше чем file.getSize() то тогда все ок.
Могу ошибаться.

2024-10-01 07:56 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +        amazonS3Client.deleteObject(request);
@Silencemess1ah я тут больше про сами deleteObject и getObject - у тебя в бд может быть ключ, валидацию прям все проходит, а потом идешь в облако и такого файла нету.
Я посмотрел, у меня не было обработки этих ошибок, просто там каждый метод AmazonS3 может выбросить исключение, наверное проверить вот кейс сверху через дебагер, если все ок то ок. Для этого и проводится кросс) 
Если там может быть выброшена ошибка то делать эти методы через try-catch.

2024-10-01 08:11 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/validator/resource/ResourceValidator.java
> +        if ((BigInteger.valueOf(file.getSize())).compareTo(project.getStorageSize()) > 0) {
Тогда, наверное надо как то фиксировать при залитии первого для проекта файла размер места в облаке, типо устанавливать размер папки на 2гб  просто опять же зачем если он не даст залить больше чем указано в ресурсе проверку не пройдëтЬ, надо ж какой то наверное контракт заключать что мол мы расчитываем что возьмём 10 терабайт в облаке под свои нужды и из них выделять каждому проекту уже по 2гб , сложно)

2024-10-03 09:03 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    public void deleteObject(Resource resource) {
Добавил проверку на вылет ошибок во всех методах с3 сервиса

2024-10-03 09:28 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +public class S3Service {
Думал думал ничего путного не могу придумать насчет папок... да и вроде конкретно этот сервис отвечает за файлы проектов никого другого здесь и не будет, разве что отдельно бакеты создавать в общем на ревью кидаю с изначальной идеей там посмотрим...

2024-10-03 20:01 UTC, mysosnovskaya requested changes

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/config/context/s3Configuration/S3Configuration.java
> +    private String accessKey;
Будет круто вынести эти параметры в отдельный класс, над которым повесить аннотацию ConfigurationProperties

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/resource/ResourceController.java
> +    @PutMapping("/{projectId}/upload/{memberId}")
После /resources не может идти projectId, допустимо только resourceId. Лучше в request body передать всю необходимую информацию (projectId, memberId)

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/resource/ResourceController.java
> +    @PutMapping("/{projectId}/upload/{memberId}")
Это должен быть POST запрос (т.к. это создание)

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/resource/ResourceController.java
> +    @PostMapping("/update")
1. Это должен быть PUT запрос, т.к. обновление
2. /update писать не нужно, это уже выражается http-методом (PUT)
3. А вот {id} в урл добавить нужно - айди ресурса, который нужно обновить

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/resource/ResourceController.java
> +    @DeleteMapping("/{resourceId}/{teamMemberId}")
resourceId - да, а teamMemberId - нет, это должно быть в теле

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/resource/ResourceUpdateDto.java
> +    private Long id;
Это нужно вынести в урл (написала в контроллере об этом), а отсюда удалить

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/mapper/resource/ResourceMapper.java
> +    @Mapping(source = "createdBy.id", target = "createdById")
Пустую строчку бы оставить перед аннотацией)

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/Project.java
> +    public boolean equals(Object o) {
Ой, а это зачем?) То, что генерирует ломбок, не подойдет? Если тебе нужно какие-то поля исключить из этих методов, то у ломбока для этого есть механизмы, посмотри

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/Resource.java
> +    public boolean equals(Object o) {
Аналогично комментарию из Project

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/ResourceType.java
> -
Пустая строчка здесь нужна была, пусть остается)

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/TeamMember.java
> +    public boolean equals(Object o) {
Аналогично комментарию из Project

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        TeamMember fileOwner = teamMemberService.getTeamMemberById(memberId);
Как я понимаю, здесь должен быть id пользователя, который делает запрос. Если да, то его можно взять из UserContext метод getUserId. Так будет логичнее, чем верить тому, что передаст фронт) Там злоумышленник какой угодно id подставить может

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/validator/resource/ResourceValidator.java
> +            log.error("TeamMember with id {} , doesn't belongs to project {}!", fileOwner.getId(), projectId);
Логгировать не нужно, это будет в Global Exception Handler

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/validator/resource/ResourceValidator.java
> +            throw new DataValidationException("You cannot upload files because you don't belongs to the project!");
1. Здесь лучше сообщение из лога, т.к. в нем есть конкретика. 
2. Фронт как правило не показывает наши сообщения, мы их пишем для себя, чтобы потом разобраться, что произошло
3. Здесь лучше подойдет ForbiddenException (запрещено)

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/validator/resource/ResourceValidator.java
> +    public void setNewProjectStorageSize(Project project) {
Почему валидатор начал этим заниматься? Это абсолютно не его ответственность

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        Resource resource = Resource.builder()
Может вынесем это в отдельный приватный метод?

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        s3Service.saveObject(file, resource);
Молодец, что сначала сохранил в базу данных, а потом в s3 👍

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        TeamMember member = teamMemberService.getTeamMemberById(resourceUpdateDto.getUpdatedById());
Кажется, нужны какие-то проверки, что этот пользователь может файлы загружать

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        originalResource.setAllowedRoles(updatedRoles);
А так не сработает?
`originalResource.getAllowedRoles().addAll(new ArrayList<>(resourceUpdateDto.getAllowedRoles()));`
А то сложная схема какая-то)
И можешь прислать, какая ошибка вылетает без new ArrayList?

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        TeamMember member = teamMemberService.getTeamMemberById(resourceUpdateDto.getUpdatedById());
И тут такая же история, как и выше: нужно взять id пользователя, который делает запрос

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        s3Service.deleteObject(resource);
Это нужно сделать после того, как удалишь из базы, чтобы в случае ошибки изменения из базы данных откатились (+ ещё нужно Transactional повесить на метод)

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    private static final String SDK_ERROR_LOG_MESSAGE = "SdkClientException occurred: {}";
По-моему эти константы не нужны. Можно сделать` e.getClass().getName()` при логгировании, тогда получится обработку AmazonServiceException и SdkClientException объединить

2024-10-03 20:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/util/decoder/MultiPartFileDecoder.java
> +public class MultiPartFileDecoder implements MultipartFile {
Это ты интересно придумал) Правильно понимаю, что ты хотел возвращать не только содержимое, но и информацию о файле, поэтому понадобился этот класс?
А почему он Decoder? Он же ничего не декодирует

2024-10-07 08:24 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        originalResource.setAllowedRoles(updatedRoles);
Ошибка вылазит при создании когда я формирую ресурс для сохранения :
```
servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.orm.jpa.JpaSystemException: Found shared references to a collection: faang.school.projectservice.model.Resource.allowedRoles] with root cause
org.hibernate.HibernateException: Found shared references to a collection: faang.school.projectservice.model.Resource.allowedRoles 
```
 это когда меняю ``` .allowedRoles(new ArrayList<>(fileOwner.getRoles())) ``` на ``` .allowedRoles(new ArrayList<>(fileOwner.getRoles())) ```

2024-10-08 00:54 UTC, mysosnovskaya requested changes

2024-10-08 00:54 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/config/properties/PropertiesConfig.java
> +public class PropertiesConfig {
Лучше дать более конкретное название классу. Какие именно параметры это, для чего?

2024-10-08 00:54 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/resource/ResourceController.java
> +    private final UserContext userContext;
С UserContext хорошо получилось

2024-10-08 00:54 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/util/converter/GigabyteConverter.java
> +    public long byteToGigabyteConverter(long size) {
Пустая строчка нужна перед методом

2024-10-08 20:53 UTC, mysosnovskaya approved these changes

2024-10-08 20:53 UTC, merged