Валидация в сервисе Проектов (feature-BJS2-26110)
CorporationX/project_service pull request #684
Opened 2024-09-30 11:18 UTC by Varrankin

2024-09-30 19:06 UTC, GusevVrn reviewed
По библиотекам, я у Влада видел еще в каком-то одном из первом видео и сейчас мне Маша указала на это что такой импорт: 
import ...* - плохо т.к. по code check style потом может не пройти
https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcard-imports
называется Disable wildcard impors, посмотри там надо 999 в 2х окошках проставить. И как раз свои классы что ты сейчас правишь пройдись через ctrl + shift + O
p.s. в самих классах на это указывать не буду

2024-09-30 19:06 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    public InternshipDto getInternship(@PathVariable("id") @Positive Long id) {
Здесь, зачем указание ("id") - у тебя и так одна переменная в url.
Выше InternshipDto - внутри есть проверки на null, сюда бы тоже валидацию им прокинуть.

И смотри, раз ты этот контроллер правишь, у него почему-то нету версионирования в path - не знаю в рамках этой задачи лучше добавить или как. Тут лучше Машу дождаться.

2024-09-30 19:06 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public StageInvitationDtoResponse acceptInvitation(@PathVariable("id") @Positive long id) {
Айдишники аналогично предыдущему контроллеру.
И выше в Post эндпоинте StageInvitationDtoRequest - тоже обернуть бы в Valid

2024-09-30 19:06 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/dto/internship/InternshipDto.java
> +
лишний отступ
и в целом тут какие-то отступы появились

2024-09-30 19:06 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +        // нужна ли эта проверка если у нас есть @RequestBody?
не надо, т.к. этот метод дергается из контроллера где @RequiredBody(required = true) (true по дефолту)
Вот если бы @RequiredBody(required = false) тогда надо было, но тогда не было бы смысла писать false.

p.s. комментируй через - выделил текст - ctrl + shift + /

2024-09-30 19:06 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +//        if (filterDto == null) {
аналогчно, если что, это надо удалять не комментить

2024-09-30 19:06 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        existedProject.setDescription(projectDto.getDescription());
Вот тут посмотри внимательно по изначальной задаче или спроси у Варвары ( вроде она это делала).
Если там есть указание что описание и статус могут быть null тогда надо оставить то что было и удалить проверку в Dto

2024-09-30 19:06 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/validator/project/ProjectValidator.java
>              throw new DataValidationException("At least one updated field must not be empty");
At least one updated field must not be empty - хотя бы одно поле не должно быть null, а ты проверяешь только на один статус. 
Как я написал выше, посмотри по логике еще раз. Мне кажется тут гибкие условия были, а ты их молотком прибил.
+ лишние скобки у if + лишний отступ

2024-10-01 13:22 UTC, Varrankin commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    public InternshipDto getInternship(@PathVariable("id") @Positive Long id) {
я не стал версионирвоание исправлять и вообще вмешиваться в логику проекта, потому что это не требуется в рамках этой задачи, да и полностью логику и условия которые вкладывал автор не знаю и чтоб ошибок не наделать пока не трогаю. По поводу ("id") я указал потому что ставлю аннотацию @Positive, как я понял, так надо делать, потому что если не сделать то аннотация  @PathVariable применяется не к полю а к аннотации @Positive что не корректно. По поводу " сюда бы тоже валидацию им прокинуть.", не совсем понял о какой валидации ты говорил.

2024-10-01 13:29 UTC, Varrankin commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    public InternshipDto getInternship(@PathVariable("id") @Positive Long id) {
понял что ты имел в виду, добавить @Valid, чтобы отправлять объект в валидатор?

2024-10-01 13:29 UTC, Varrankin commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public StageInvitationDtoResponse acceptInvitation(@PathVariable("id") @Positive long id) {
написал выше, и да забыл добавить @Validated на класс

2024-10-04 15:16 UTC, Varrankin commented on src/main/java/faang/school/projectservice/validator/project/ProjectValidator.java
>              throw new DataValidationException("At least one updated field must not be empty");
так, что тут у нас написано,  что в условии если описание = null или описание пустое и статус = null. т.е у нас статус 100% не должен быть пустым, я на него аннотацию повесил, значит можно убрать из условия. Дальше, если у нас описание пустое или null тоже выкидываем исключение. т.е у нас описание не может быть пустым или null тоже аннотации повесил, можно убирать из условия

2024-10-04 16:14 UTC, mysosnovskaya requested changes

2024-10-04 16:14 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public StageInvitationDtoResponse acceptInvitation(@PathVariable("id") @Positive long id) {
И где validated?)

2024-10-04 16:14 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/internship/InternshipDto.java
> +    @NotNull(message = "Internship project field can't be null!")
Это не правда. Т.к. этот же dto используется на создание, то при создании id обязан быть null

2024-10-04 16:14 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/ProjectDto.java
> +    @NotNull(groups = Marker.getProject.class)
Вот тут всё верно)

2024-10-04 16:14 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    public InternshipDto getInternship(@PathVariable("id") @Positive Long id) {
Версионирование к этой задаче не относится, его здесь не нужно..
А вот про id, Дима, я тебя не поняла. `@PathVariable @Positive Long id` вроде бы должно работать)

2024-10-04 16:14 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/Marker.java
> +public interface Marker {
Мне очень понравился интерфейс Marker, объединяющий остальные 👍

2024-10-04 16:14 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/Marker.java
> +    interface getProject{}
С большой буквы

2024-10-06 09:22 UTC, Varrankin commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    public InternshipDto getInternship(@PathVariable("id") @Positive Long id) {
сейчас почитал, да будет работать, @PathVariable @Positive Long id, думал не будет, сейчас исправлю

2024-10-06 09:28 UTC, Varrankin commented on src/main/java/faang/school/projectservice/controller/stageInvitation/StageInvitationController.java
> +    public StageInvitationDtoResponse acceptInvitation(@PathVariable("id") @Positive long id) {
добавил

2024-10-06 22:39 UTC, mysosnovskaya approved these changes

2024-10-06 22:39 UTC, mysosnovskaya commented
Поправь конфликты и можешь мержить

2024-10-11 19:46 UTC, merged