create methods for upload files
CorporationX/project_service pull request #690
Opened 2024-09-30 17:24 UTC by DankeVilletti

2024-10-01 12:43 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public Project getProjectById(Long projectId) {
Как будто нет смысла создавать этот метод

2024-10-01 12:43 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +            throw new IllegalArgumentException("File size exceeds project limit");
Тут по смыслу лучше IllegalStateException

2024-10-01 12:43 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public TeamMember checkUserParticipationInProjectTeams(Long userId, Project project) {
Я бы сделал чуть по-другому
Объединил бы в один список все userId, которые относятся к этому проекту, и искал бы там уже нужного тебе пользователя

2024-10-01 12:43 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    ProjectService(ProjectRepository projectRepository,
тут не хватает модификатора доступа

2024-10-01 12:43 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/service/resource/ResourceManager.java
> +        project.setStorageSize(BigInteger.valueOf(project.getStorageSize().longValue() + resource.getSize().longValue()));
Нет сохранения обновленного project`a в репозитории

2024-10-07 20:06 UTC, 20cognosce requested changes

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +//////////////////////////////////////////////////////////////////////////////////////////////////
Что это

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +            @RequestBody MultipartFile file) {
перенос на новую строку со второго параметра
аргументы с содержимым метода сливаются

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +            @RequestBody MultipartFile file) {
Не документируй все так жестко, это треш
Код не читаем

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +            @Parameter(description = "File to upload", required = true, content = @Content(mediaType = "multipart/form-data", schema = @Schema(type = "string", format = "binary")))
Вот это особенно

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +import org.springframework.web.bind.annotation.*;
Не сворачивать

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +        Map<Resource, InputStream> resourceWithFileStream = projectService.getFileFromProject(projectId, userId, resourceId);
Из сервиса сразу достать ресурс
и в сервисе закрыть поток

никакой логики в контроллере

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/advice/UniversalControllerAdvice.java
> +        return new ResponseEntity<>(createErrorResponse(status, message, errors), status);
А можно switch case
case MethodArgumentNotValidException - ResponseEntity с errors
default - без

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/ResourceType.java
> -    OTHER;
А чего удалил?
if else выглядит диковато, но сам энам полезный ведь

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        Map<Boolean, TeamMember> isItTeamMember = teamService.checkParticipationUserInTeams(userId, project.getTeams());
Что это за мапа такая?
Почему не возвращать список команд, в которых участвует юзер и проверить его на пустоту?

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        Resource resource = resourceManager.uploadFileToProject(file, directoryPath, project, teamMember);
вынести это из транзакции IO операции не работают в транзакциях

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public void deleteFileFromProject(Long projectId, Long userId, Long resourceId) {
А тут вообще транзакции нет

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public Map<Resource,InputStream> getFileFromProject(Long projectId, Long userId, Long resourceId) {
Нет, только не так

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public Map<Resource,InputStream> getFileFromProject(Long projectId, Long userId, Long resourceId) {
Отдавай сразу файл

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public Map<Resource,InputStream> getFileFromProject(Long projectId, Long userId, Long resourceId) {
И не забудь закрыть поток

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ResourceManager.java
> +    @Transactional
Говорил уже

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/team/TeamMemberService.java
> +public class TeamMemberService {
?)

2024-10-07 20:06 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/team/TeamService.java
> +    }
Убирай мапы

2024-10-07 20:06 UTC, 20cognosce commented on src/test/java/faang/school/projectservice/controller/ProjectControllerTest.java
> +        MvcResult result = mockMvc.perform(multipart("/1/files")
Ну это интеграционный тест
Зачем в интеграционном тесте ты мокаешь сервис

Либо юнит делай, либо e2e по-нормальному

2024-10-07 20:06 UTC, 20cognosce commented on src/test/java/faang/school/projectservice/service/ProjectServiceTest.java
> +}
почему картинка не в тестовых ресурсах, а в тестовых сорсах

2024-10-08 06:23 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +        Map<Resource, InputStream> resourceWithFileStream = projectService.getFileFromProject(projectId, userId, resourceId);
У меня файлы могут быть большого веса и насколько я понял в таком случае их нужно передавать стримом, а когда я отправляю, спринг сам закрывает поток, после полной передачи файла
я добавлю класс, для удобства передачи в контроллер из сервиса

2024-10-08 07:11 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        Map<Boolean, TeamMember> isItTeamMember = teamService.checkParticipationUserInTeams(userId, project.getTeams());
Этот метод я использую в некоторых сценариях просто для того, чтобы убедиться, что пользователь является участником проекта (возвращая true если участник и ошибка если нет), а в некоторых случаях мне нужно именно получить TeamMember

2024-10-08 07:14 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        Map<Boolean, TeamMember> isItTeamMember = teamService.checkParticipationUserInTeams(userId, project.getTeams());
а если потребуется узнать в какой команде пользователь, то это можно узнать из самого TeamMember

2024-10-08 07:20 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        Map<Boolean, TeamMember> isItTeamMember = teamService.checkParticipationUserInTeams(userId, project.getTeams());
изначально здесь хотел тоже возвращать Map<Boolean, TeamMember>
потому что удобно пользоваться функцией если нужны ситуации c проверкой, где юзер не относится к проекту еще (убрав исключение из метода)

2024-10-08 07:52 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/controller/advice/UniversalControllerAdvice.java
> +        return new ResponseEntity<>(createErrorResponse(status, message, errors), status);
я так понял что не поддерживается jdk17, начиная с 21 только

2024-10-08 07:55 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/model/ResourceType.java
> -    OTHER;
нам мой взгляд бесполезная вещь, потому что тип файла можно записать при загрузке через getContentType, а здесь приведены не все типы

2024-10-08 14:53 UTC, 20cognosce requested changes

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +            @PathVariable("project-id") @Positive Long projectId,
Ну я ведь сказал переделать...
```
public ResourceDto uploadFileToProject(@PathVariable("project-id") @Positive Long projectId,
                                       @RequestParam("user-id") Long userId,
```

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +            @PathVariable("project-id") @Positive Long projectId,
Зачем писать доку на id???

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +            @PathVariable("project-id") @Positive Long projectId,
Это графомания

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +import faang.school.projectservice.model.Resource;
Resource спринговый

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +        InputStream fileStream = resourceWithFileStream.inputStream();
Пожалуйста, убери всю логику из контроллера
Убери потоки

Передавай объекты

2024-10-08 14:53 UTC, 20cognosce commented on src/test/java/faang/school/projectservice/service/ProjectServiceTest.java
> +}
папка resources в тестах такая же, как и в сорсах

2024-10-08 14:53 UTC, 20cognosce commented on src/test/java/faang/school/projectservice/service/ProjectServiceTest.java
> +}
.utils это who

2024-10-08 14:53 UTC, 20cognosce commented on src/test/java/faang/school/projectservice/service/ProjectServiceTest.java
> +import static org.mockito.Mockito.*;
Не сворачивать
Настрой идею

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/ResourceWithFileStream.java
> +public record ResourceWithFileStream(Resource resource, InputStream inputStream) {
no please
Не храни и не передавай потоки

Открыл - достал - закрыл
Всё

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +import faang.school.projectservice.model.Resource;
Другой ресурс

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    @Transactional
Я же сказал вынести IO операции из транзакции

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ResourceManager.java
> +import faang.school.projectservice.model.*;
Не сворачивать

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        Resource resource = uploadFileToS3(file, directoryPath, project, teamMember);
Это ок для БД, но API должен отдавать файл, а не json-объект

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        Resource resource = uploadFileToS3(file, directoryPath, project, teamMember);
Переименуй его по-другому, чтобы понимать, что это ресурс в нашей модели

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        Resource resource = uploadFileToS3(file, directoryPath, project, teamMember);
Имей в нем ссылку на хранилище в s3, либо в нем контент храни
и потом мапь это на спринговый Resource и его отдавай

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ResourceManager.java
> +        return resourceRepository.save(resource);
Нет, разделяй ответственность
Один класс отвечает за S3
Другой должен отвечать за бизнес-логику и БД

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/team/TeamService.java
> +public class TeamService {
Зачем ты сделал целый сервис для двух методов, который просто в стриме чет мапят
Говорю, сделай метод, который отдает список команд пользователя и не парься с мапингами этими боже

2024-10-08 14:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        TeamMember teamMember = checkUserParticipationInProjectTeams(userId, project);
Почему метод с именем check отдает объект
Поработай над семантикой того, что твои методы все делают и зачем

2024-10-08 15:50 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +import faang.school.projectservice.model.Resource;
не понял

2024-10-09 16:46 UTC, 20cognosce requested changes

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +            @RequestBody MultipartFile file) {
Давай в третий раз поправим
![image](https://github.com/user-attachments/assets/b31c4698-e69b-4bad-974f-90a89aab465b)

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/Moment.java
>  import jakarta.persistence.*;
Не сворачивать
Ctrl + Alt + L
Ctrl + Alt + O
На каждый класс, который ты правишь

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/ResourceDB.java
> +public class ResourceDB {
Не самое удачное название, назови его ProjectResource
На какую таблицу он ссылается?

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/ResourceInfo.java
> +public record ResourceInfo(Resource resource, ResourceDB resourceDB) {
Можно спринговый Pair возвращать, этот класс вводит в заблуждение и является лишним слоем абстракции

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +                .body(resourceInfo.resource());
Так уже лучше концептуально

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ResourceManager.java
> +import faang.school.projectservice.model.*;
?))))

2024-10-09 16:46 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V000__initial.sql
> +CREATE TABLE IF NOT EXISTS resourceDB
project_resource

2024-10-09 16:46 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/project_V014_resource.sql
> +ALTER TABLE resourceDB RENAME TO project_resource;
Не понял, если project_resource уже есть
Зачем тебе resourceDB

2024-10-09 16:46 UTC, 20cognosce commented on src/test/java/faang/school/projectservice/service/ProjectServiceTest.java
> +import static org.mockito.Mockito.*;
Где исправление

2024-10-09 16:46 UTC, 20cognosce commented on src/test/java/faang/school/projectservice/service/ProjectServiceTest.java
> +import faang.school.projectservice.model.*;
Где исправление

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/s3manager/S3Manager.java
> +            InputStream inputStream = s3Client.getObject(projectBucket, key).getObjectContent();
Ты не закрыл поток
Используй try with resources

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ResourceManager.java
> +    public ResourceDB createAndSaveProjectResource(ObjectMetadata metadata, Project project, TeamMember teamMember) {
@Transactional

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ResourceManager.java
> +
private методы внизу класса, public - вверху

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ResourceManager.java
> +    public ResourceDB createAndSaveProjectResource(ObjectMetadata metadata, Project project, TeamMember teamMember) {
Ну и опять-таки, с каким ресурсом работает этот класс
с S3 или с БДшным?

Если с  S3 - такого метода тут быть не должно, он должен быть в сервисе бизнес-логики

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ResourceManager.java
> +    }
В сервис

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ResourceManager.java
> +public class ResourceManager {
Назови его ProjectResourceManager
оставь тут только работу с S3
остальные методы вынеси в ProjectService
Может отдельный сервис создать - ProjectResourceService

И сервис уже должен вызывать s3 менеджера
Никакой зависимости на репозиторий тут быть не должно

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public ResourceInfo getFileFromProject(Long projectId, Long userId, Long resourceId) {
public методы вверху класса

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Resource in this project not found"));
Сделай sql запрос в репозитории который применяет условие where, на надо в рантайм приложения тянуть всю базу

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        ResourceInfo resourceInfo = resourceManager.uploadResource(file, directoryPath, project, teamMember);
Давай инвертируем зависимость, чтобы загрузка в S3 была вне транзакции.

1. Из контроллера запрос попадает в ProjectResourceService
=== Начало транзакции ===
2. ProjectResourceService валидирует юзера
3. ProjectResourceService собирает метаинфу по файлу и отдает её на валидацию в s3 manager
4. s3 manager валидирует метаинфу по файлу, в том числе на то, что такой файл уже есть в хранилище
5. Всё ок - ProjectResourceService создает сущность ресурса и сохраняет в БД с флагом PENDING
6. ProjectResourceService вызывает асинхронный метод uploadFileToStorage() у s3 manager
=== Конец транзакции ===

7. s3 manager выполняет upload ресурса
7.1 Fail - вызов метода ProjectService по обновлению статуса ресурса в БД на FAILED
Желательно также сохранять инфу в БД о причине такого инцидента с ресурсом
7.2 Success - вызов метода ProjectService по обновлению статуса ресурса в БД на ACTIVE

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        TeamMember teamMember = checkUserParticipationInProjectTeams(userId, project);
Переделать этот метод

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        String directoryPath = generateDirectoriesForUserFiles(projectId, userId);
Почему сервис бизнес-логики занимается созданием пути до ресурса, это ответственность S3 менеджера
Пусть он это посчитает и отдаст тебе, если тебе оно надо (а тебе в том-то и дело, что это вообще в данном сервисе не надо)

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +public class ProjectService {
ProjectResourceService

2024-10-09 16:46 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        ResourceInfo resourceInfo = resourceManager.uploadResource(file, directoryPath, project, teamMember);
Циклическую зависимость можешь либо разрешить в пропертях, либо добавить слой абстракции, отдельный сервис, который будет чисто CRUD для ресурса делать

2024-10-10 20:30 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +        return resourceMapper.toResourceDto(resource);
Тут что-то съехало)
Нужно автоформатирование

2024-10-10 20:30 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/service/resource/ProjectResourceService.java
> +    public TeamMember getTeamMemberFromProjectTeams(Long userId, Project project) {
Я думаю, что если ты же не обращаешься к нему из контроллера, или еще из какого-то класса, то он не должен быть публичным

2024-10-10 20:30 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/service/resource/ProjectResourceService.java
> +        projectRepository.save(project);
Тут лучше по аналогии с предыдущим методом сначала выполнить все действия с БД, а потом уже запускать асинхронную джобу, которая удалит файл из minio и обновит статус ресурса в бд

2024-10-11 15:28 UTC, 20cognosce approved these changes
На 95% хорошо
Пару правок внеси пожалуйста и можно мёрджить

2024-10-11 15:28 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/ProjectResource.java
> +public class ProjectResource {
Почему не Entity?

2024-10-11 15:28 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ProjectResourceDAO.java
> +public class ProjectResourceDAO {
Какой dao, почему не сервис...

2024-10-11 15:28 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/ProjectResource.java
> +public class ProjectResource {
Где связь с таблицей

2024-10-11 15:28 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ProjectResourceManager.java
> +        try (InputStream inputStream = s3Client.getObject(projectBucket, objectKey).getObjectContent()) {
Хорошо

2024-10-11 15:28 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ProjectResourceManager.java
> +    public ProjectResource createProjectResource(ObjectMetadata metadata, Project project, TeamMember teamMember) {
В маппер вынести

2024-10-11 15:46 UTC, DankeVilletti commented on src/main/java/faang/school/projectservice/model/ProjectResource.java
> +public class ProjectResource {
не понял про связь...
а насчет названия сама таблица с самого начала существования называлась project_resource
просто сущность также и назвал

2024-10-11 16:53 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/model/ProjectResource.java
> +public class ProjectResource {
Ладно, JPA будет в конце буткемпа

Нужны аннотации @Entity и @Table

2024-10-11 16:53 UTC, 20cognosce approved these changes

2024-10-11 16:53 UTC, merged