BJS2-26119 Добавление обложки к проекту
CorporationX/project_service pull request #691
Opened 2024-09-30 19:33 UTC by badasscoding

2024-10-03 11:44 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/controller/project/ProjectCoverController.java
> +@RequestMapping("/projects/{projectId}/cover")
версионирование потерял

2024-10-03 11:44 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/controller/project/ProjectCoverController.java
> +    public void deleteProjectImage(@PathVariable @Positive Long projectId) {
@ResponseStatus(HttpStatus.NOT_FOUND)

2024-10-03 11:44 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/controller/project/ProjectCoverController.java
> +    public ResponseEntity<byte[]> getProjectCover(@PathVariable @Positive Long projectId) {
нам в целом ResponseEntity и не нужен, почему бы не возвращать MultipartFile и реализовать его через какой-нибудь ByteArrayMultipartFile, ты его тогда сможешь в сервисе и полностью наполнить.
Из контроллера вынесешь все лишнее.

2024-10-03 11:44 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/dto/image/FileData.java
> +public class FileData {
ну я в контроллере написал, пока не особо вижу чтоб надо было что-то придумывать.
В методах можно будет интерфейс MultipartFile написать, а сейчас прям явный блок на работу через FileData висит

2024-10-03 11:44 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/project/ProjectCoverService.java
> +        return coverImageId != null ? s3Service.getObjectByKey(coverImageId) : null;
чисто в теории может быть тут Empty? например занулили руками

2024-10-03 11:44 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/project/ProjectCoverService.java
> +        if (coverImageId != null) {
тоже по empty вопрос

2024-10-03 11:44 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +    private static final Dimension MAX_SIZE = new Dimension(640, 1024);
размеры в yml куда-нибудь

2024-10-03 11:44 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/s3/ImageCloudService.java
> +public interface ImageCloudService {
ImageService а методы Object, по идее через эти методы можно будет с любыми файлами работать

2024-10-03 11:44 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/validator/image/ImageValidator.java
> +    public static final long MAX_IMAGE_SIZE = 41_451_520L; // 20 * 1024 * 2024
наверное тоже в yml

2024-10-03 11:44 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +            logError("fetching", key, e);
мож тут и ниже выбрасывать какую-нибудь кастомную ошибку S3, тогда и return null не нужен будет

2024-10-04 17:23 UTC, Silencemess1ah reviewed
![KYAAAgLc0eA-1920](https://github.com/user-attachments/assets/9d1da253-8840-401f-8c8e-492dfceddeb6)
Не понятно только с resourceId (описал ниже) ну и сомнения насчет малой обработки эксепшенов в S3

2024-10-04 17:23 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +            throw new IllegalArgumentException("Failed to resize image: " + e.getMessage(), e);
Могу ошибаться но причем здесь IllegalArgumentException? Ловим что в процессе конвертации отрубит свет, потеряем соединение, байты запутаются друг об друга, а выбрасываем что то то не так с аргументами, не много не логично как по мне Runtime да и все, ну или кастомное

2024-10-04 17:23 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +    }
Запутался, метод называется getResourceById(принимаем String resourceId (что уже странно)) вызываем findResourceByKey передаем resourceId (тоже дисонанс), может где то переименовать чтоб по смыслу походило?
И ошибку кидаем тоже с id шником хотя ищем по ключу вроде как, в общем с моей колокольни очень запутанно, я бы увидел о найти по айди, передал бы айди (лонг) и сидел бы понимал что не так)

2024-10-04 17:23 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/repository/ResourceRepository.java
> +    Optional<Resource> findResourceByKey(String key);
Пришел из сервиса сюда. а есть смысл по ключу их искать если там по id вроде пишешь? В Resource key не уникальное значение то есть гипотетически могут быть ошибки в поиске, просто найти по id и вытянуть ключ уже отдельно, + одна строка но гарантирует что конкретный ресурс вытянул из базы
![image](https://github.com/user-attachments/assets/6891f3ba-ff65-4d59-bf56-089b865926e6)

2024-10-04 17:23 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +            logError("fetching", key, e);
тут по факту 3 варианта ошибок IOException, (это с инпут стримом) 
sdkClientException, AmazonServiceException на методах getObject(), putObject(), deleteObject()
![image](https://github.com/user-attachments/assets/43a92158-56f8-46ea-a484-0d3b75ab8a0d)

2024-10-04 17:23 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +            logError("fetching", key, e);
Собственно мой коммент ко всем ниже где мы возвращаем просто null можно на каждый случай залогироваться и выбросить соответственное исключение

2024-10-04 17:23 UTC, Silencemess1ah commented on src/main/resources/application.yaml
> +    region: us-east-1
Не знаю насколько критично думаю Маша поправит если не прав, может ставить EU хотя бы, что поближе к нам?)

2024-10-04 18:53 UTC, badasscoding commented on src/main/java/faang/school/projectservice/controller/project/ProjectCoverController.java
> +    public ResponseEntity<byte[]> getProjectCover(@PathVariable @Positive Long projectId) {
Не понял почему ты против ResponseEntity

1. Сервисы для отдачи файлов обычно отправляют данные напрямую как byte[]. Это стандартный REST-подход. Клиенты, такие как браузеры, ожидают получить файл с правильными заголовками, а не объект MultipartFile, который используют для загрузки файлов.
2. Дока/Статьи по Spring тоже используют ResponseEntity<byte[]> для передачи файлов и бинарных данных в HTTP-ответе.

2024-10-04 19:04 UTC, badasscoding commented on src/main/java/faang/school/projectservice/dto/image/FileData.java
> +public class FileData {
MultipartFile это же интерфейс,  для него делать реализацию?

FileData - это просто DTO, которые хранит два необходимых поля. MultipartFile - это более сложная структура, плюс он предназначен больше для загрузки файлов 

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/multipart/MultipartFile.html

2024-10-04 19:06 UTC, badasscoding commented on src/main/java/faang/school/projectservice/service/project/ProjectCoverService.java
> +        return coverImageId != null ? s3Service.getObjectByKey(coverImageId) : null;
поле в таблице нуллабельное, поэтому может

cover_image_id   VARCHAR(255)

2024-10-04 19:06 UTC, badasscoding commented on src/main/java/faang/school/projectservice/service/project/ProjectCoverService.java
> +        if (coverImageId != null) {
поле в таблице нуллабельное, поэтому может

cover_image_id VARCHAR(255)

2024-10-04 19:18 UTC, badasscoding commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +            logError("fetching", key, e);
спасибо

2024-10-04 19:25 UTC, GusevVrn commented on src/main/java/faang/school/projectservice/dto/image/FileData.java
> +public class FileData {
я тут погнал, глянул что есть какой-то ByteArrayMultipartFile но не заметил что его нельзя использовать

2024-10-04 19:36 UTC, badasscoding commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +    }
я что-то с неймингом напутал, поправил

String там потому что поле key - String, не Long

2024-10-04 19:45 UTC, badasscoding commented on src/main/java/faang/school/projectservice/repository/ResourceRepository.java
> +    Optional<Resource> findResourceByKey(String key);
Сейчас такая логика:
1. Генерируем идентификатор для файла на S3
2. Отправляем файл на S3
3. Если успешно, то сохраняем Resource в БД (id у сущности автогенерируемое, а key мы указываем из пункта 1)

В этом случае если на S3 не загрузили, то и в БД ничего не положили

Можно сделать и как ты предлагаешь:

1. Сохранить Resource в БД
2. Взять id у сущности и с этим id отправить файл на S3

Но в случае ошибки, надо будет из БД объект удалить

С моей точки зрения первый вариант предпочтительнее, например, мы можем управлять какое название будут иметь файлы в бакете на S3

2024-10-05 15:49 UTC, mysosnovskaya requested changes

2024-10-05 15:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/config/s3/S3Config.java
> +    @Value("${services.s3.accessKey}")
Давай вынесем эти параметры в отдельный класс, помеченный аннотацией ConfigurationProperties. Почитай подробнее про эту аннотацию)

2024-10-05 15:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectCoverController.java
> +    public ResponseEntity<?> uploadProjectCover(@PathVariable @Positive Long projectId,
Почему у нас вылез ResponseEntity, ещё и без определенного типа?) Мы не используем ResponseEntity, всегда возвращаем просто dto

2024-10-05 15:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectCoverController.java
> +            return ResponseEntity.noContent().build();
В ResponseStatus уже стоит NO_CONTENT, этого достаточно. Здесь дублировать не нужно

2024-10-05 15:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectCoverController.java
> +            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
Это должно происходить в Global Exception Handler. К тому же response всегда должен быть в формате json, а у тебя сейчас просто строка. Так не пойдет =)

2024-10-05 15:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectCoverController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("Unexpected error occurred");
Аналогично. И кстати, здесь не BAD_REQUEST должен быть, а INTERNAL_SERVER_ERROR. Ты здесь не можешь утверждать, что это пользователь что-то не то передал. И скорее всего это не так

2024-10-05 15:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectCoverController.java
> +    private ResponseEntity<?> execute(Supplier<ResponseEntity<?>> operation) {
Здесь подойдет использование generic

2024-10-05 15:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectCoverController.java
> +@RequestMapping("/v1/projects/{projectId}/cover")
Правильно спроектировал api, молодец! Это не так-то просто, но у тебя получилось 👍

2024-10-05 15:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/repository/ResourceRepository.java
> +    Optional<Resource> findResourceByKey(String key);
Во втором случае если использовать транзакцию, то объект сам удалится из базы (если быть точной, то он туда вообще не попадет)

2024-10-05 15:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/repository/ResourceRepository.java
> +    Optional<Resource> findResourceByKey(String key);
1. Генерируем идентификатор для файла на S3
2. с key из первого шага
3. Отправляем файл на S3
Так не подойдет? И транзакцию обязательно

2024-10-05 15:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectCoverService.java
> +        return coverImageId != null ? s3Service.getFileByKey(coverImageId) : null;
Ошибку бы кинуть, если не нашли ничего

2024-10-05 15:49 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +    region: us-east-1
=) Не критично

2024-10-05 18:36 UTC, badasscoding commented on src/main/java/faang/school/projectservice/service/project/ProjectCoverService.java
> +        return coverImageId != null ? s3Service.getFileByKey(coverImageId) : null;
мне кажется странным кидать ошибку, если у проекта нет кавера
по-умолчанию его нет, поле в базе опциональное

я запрашиваю кавер и получаю ошибку? если на s3 будут проблемы, то ошибка будет

2024-10-06 03:05 UTC, mysosnovskaya requested changes
Давай ещё две крошечные правки и будем мержить)

2024-10-06 03:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectCoverService.java
> +        projectRepository.save(project);
Вчера предлагала, продублирую:
```
1. Генерируем идентификатор для файла на S3
2. Сохранить Resource в БД с key из первого шага
3. Отправляем файл на S3
Так не подойдет? И транзакцию обязательно
```
Рекомендую ознакомиться с этим комментарием:
https://github.com/CorporationX/post_service/pull/892#discussion_r1788632623
Там речь про удаление, но про загрузку аналогично. Лучше сначала в базу сохранить, а потом в s3, чтобы при ошибке с s3 из базы информация тоже откатилась бы)

2024-10-06 03:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectCoverService.java
> +        return coverImageId != null ? s3Service.getFileByKey(coverImageId) : null;
Это да, но у нас эндпоинт GET /{id}, такие эндпоинты всегда возвращают 404, если запрашиваемый ресурс найти не удалось. А вот уже стоит ли фронту эту ошибку показывать пользователю - это другой вопрос. Скорее всего нет, тогда фронт просто красиво нарисует что-то другое) Ему же всё равно, что null обработать, что 404, а с точки зрения корректного проектирования 404 будет правильнее

2024-10-08 20:51 UTC, mysosnovskaya approved these changes

2024-10-08 20:52 UTC, mysosnovskaya commented
У тебя какие-то тесты завалились, ci pipeline не прошел. Поправь и смержим

2024-10-13 14:32 UTC, merged