Добавление обложки к проекту BJS2-27061
CorporationX/project_service pull request #692
Opened 2024-09-30 22:46 UTC by sultan-inked

- Добавление новой обложки проекта
 - Получение обложки проекта
 - Удаление обложки проекта

2024-10-01 03:55 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/projectservice/validator/util/MultipartImage.java
> +    BufferedImage image;
Private поля?

2024-10-01 03:55 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        resourceRepository.save(projectCoverImageResource);
Я бы вызывал ресурсСервис.save. Вдруг перед сохранением ресурса есть какая-то валидация логическая. Сейчас ее нет, просто метод save, но потом может повиться. Чужие репозитории в сервисе некрасиво вызывать, как по мне

2024-10-01 03:55 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/projectservice/validator/ProjectCoverImageValidator.java
> +    public MultipartImage validate(MultipartFile file) {
Валидатор и валидирует, и делает ресайз. 2 логики в одном методе как будто. Я бы разделил, все манипуляции с имеджами куда-то в другой класс вынес. Тестировать потом проще и понятней будет

2024-10-01 15:29 UTC, sultan-inked commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        resourceRepository.save(projectCoverImageResource);
Я хотел так сделать, но циклическая зависимость появляется, потому что Семен использует updateStorageSize в ресурсе, как быть в таком случае?

2024-10-01 15:30 UTC, sultan-inked commented on src/main/java/faang/school/projectservice/validator/util/MultipartImage.java
> +    BufferedImage image;
Не заметил, спасибо

2024-10-01 15:39 UTC, sultan-inked commented on src/main/java/faang/school/projectservice/validator/ProjectCoverImageValidator.java
> +    public MultipartImage validate(MultipartFile file) {
Да, согласен, надо разделить, спасибо

2024-10-01 20:01 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        resourceRepository.save(projectCoverImageResource);
Я бы убрал RequiredArgsConstructor у РесурсСервиса и ПроджектСервиса. Прописал конструкторы у них руками и у этих бинов, которые в друг друга инжектятся, поставил в конструкторах аннотацию Lazy. Сам я так не делал еще ни тут, ни на работе (не сталкивался), но на собесах слышал, что такой ответ удовлетворял собеседующих

2024-10-02 16:15 UTC, sultan-inked commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        resourceRepository.save(projectCoverImageResource);
Спасибо, попробую

2024-10-02 19:43 UTC, sultan-inked commented on src/main/java/faang/school/projectservice/validator/ProjectCoverImageValidator.java
> +    public MultipartImage validate(MultipartFile file) {
Разделил, так лучше стало

2024-10-04 19:51 UTC, 20cognosce requested changes

2024-10-04 19:51 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +            return ImageIO.read(file.getInputStream());
ImageIO.read закрывает поток?

2024-10-04 19:51 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public ProjectService(S3Service s3Service, ProjectRepository projectRepository,
?)

2024-10-04 19:51 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        S3Object s3Object = s3Service.download(imageKey);
Вынести из транзакции, транзакция не управляет IO операциями

2024-10-04 19:51 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +                });
Можно попроще писать? Это не читаемо

2024-10-04 19:51 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +            projectRepository.save(project);
почему у тебя столько всего в блоке ifPresent 
Проще код сделай

2024-10-04 19:51 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public ProjectService(S3Service s3Service, ProjectRepository projectRepository,
@RequiredArgsConstructor??
@Lazy для чего?

2024-10-04 19:51 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/validator/util/image/MultipartImage.java
> +public class MultipartImage implements MultipartFile {
А готового класса нет?

2024-10-04 19:51 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/validator/ProjectServiceValidator.java
> +        long newFileSize = file.getSize();
Если ты достаешь только размер, почему передаешь весь файл?

2024-10-05 07:56 UTC, sultan-inked commented on src/main/java/faang/school/projectservice/service/image/ImageService.java
> +            return ImageIO.read(file.getInputStream());
Забыл что надо закрывать, спасибо, исправил

2024-10-05 08:00 UTC, sultan-inked commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public ProjectService(S3Service s3Service, ProjectRepository projectRepository,
Циклическая зависимость бинов произошла, ранее Семен уже инжектировал ProjectService в ResourceService, и я напрямую использовал ResourceRepository, на что указал Иван, и что лучше использовать сервис ресурса а не репозиторий, и пришлось вот так создать, это плохо?

2024-10-05 08:19 UTC, sultan-inked commented on src/main/java/faang/school/projectservice/validator/util/image/MultipartImage.java
> +public class MultipartImage implements MultipartFile {
Не нашел, мне пришлось создать свой, что бы передовать в S3 как файл, использую уже готовые методы, а не придумывать свой что бы передовать инпутСтрим

2024-10-05 08:29 UTC, sultan-inked commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public ProjectService(S3Service s3Service, ProjectRepository projectRepository,
https://github.com/CorporationX/project_service/pull/692#discussion_r1782071541

2024-10-06 07:34 UTC, sultan-inked commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    public ProjectService(S3Service s3Service, ProjectRepository projectRepository,
Вынес логику которая затрагивает РесурсСервис и раоботает с S3 в отдельный класс

2024-10-07 18:59 UTC, 20cognosce approved these changes

2024-10-07 18:59 UTC, merged