Feature bjs2 27252 google calendar integration
CorporationX/project_service pull request #694
Opened 2024-10-01 17:58 UTC by Rashit86

Сейчас задача сделана таким образом, что access_token и refresh_token сохраняются прямо в проекте. Т.е такой вариант подходит только если у каждого инстанса project-service один пользователь. По идее мне надо было сделать таблицу и хранить там эти токены с id пользователя. Но если я это буду делать, то у меня уйдет еще как минимум один день, думаю. Наверняка, там всплывут какие-нибудь сложности. Нужно будет делать чтобы хранилась дата истечения refresh-tokena и незадолго до истечения этой даты, нужно будет генерировать новый рефреш-токен. В общем, чтобы этот спринт не прошел мимо меня, решил отправить на PR в таком варианте

2024-10-07 15:34 UTC, mikhailov26 requested changes
В целом всё хорошо, молодец, что справился с такой тяжёлой таской, но я попрошу немного перетрясти иерархию пакетов: 1) в пакет model добавляем два пакета entity и dto и добавляем туда наши сущности и дто 2) Мне не нравится в корне директория google/calendar либо мы её убираем в сервис, либо в конфиг
3) Понимаю, что тебе это может показаться бесполезным, но по общепринятым правилам прошу в директории service сделать пакет impl. Сделать интерфейсы твоих сервисов в корне service, а в impl добавить твои имплементации

2024-10-07 15:34 UTC, mikhailov26 commented on src/main/java/faang/school/projectservice/mapper/calendar/CalendarMeetDtoEventDtoMapper.java
> +    }
Добавь проверку на null в switch

2024-10-10 09:49 UTC, Rashit86 commented on src/main/java/faang/school/projectservice/mapper/calendar/CalendarMeetDtoEventDtoMapper.java
> +    }
В этом методе до switch уже выполняется проверка на null, т.е в swich null не пройдёт

2024-10-10 09:51 UTC, Rashit86 commented
Я сделал рефакторинг. Интерфейсы сделал только для своих сервисов по этой задаче. Еще нашел что есть dto с одинаковыми названиями и сервисы с одинаковым функционалом. Так получилось как раз потому что много чего лежит по разным папочкам. Про dto и сервисы подсвечу их авторам

2024-10-13 11:53 UTC, mikhailov26 approved these changes

2024-10-13 11:53 UTC, merged