Управление задачами
CorporationX/project_service pull request #700
Opened 2024-10-03 07:55 UTC by lexus-74

2024-10-03 09:07 UTC, mrkorolev reviewed
Несколько моментов:
1. Мы в команде называем ветки feature-<номер задачи>, если тебе по твоему норм нащывать то ок, но лучше придерживаться одного соглашения
2. Методы фильтрации и получения tasks в один метод
3. Пересмотреть маппер, убрать ненужные default методы

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/controller/TaskController.java
> +    TaskDto createTask(@RequestBody @Validated TaskDto taskDto) {
1. Не используем глаголы в url относительно целевой коллекции (не первый раз пишу, обрати внимание)
2. Где модификатор доступа? Или я чего то не понимаю?

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/controller/TaskController.java
> +        Task originalTask = taskService.createTask(tempTask);
Почему такой нейминг? Это же новый созданный task, так и называй - created

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/controller/advice/AdviseController.java
> +}
Я в своей текущей задаче сейчас добавляю обновленный controller advice (после замечаний Димы), этот файл (и ResponseError) можешь удалить?

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/controller/TaskController.java
> +    @PutMapping()
1. Скобки без url - зачем?
2. Передавать taskId лучше в path variable (делает url понятным), вместо request param
3. Модификатор доступа
4. Нейминг - originalTask? Ты же обновляешь, значит он есть в системе

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/controller/TaskController.java
> +    @GetMapping("/id")
id -> taskId

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/controller/TaskController.java
> +        Task task = taskService.getTaskById(taskId, userId);
Нейминг - found, target, toFind (что угодно)

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/controller/TaskController.java
> +    public List<TaskDto> getFilteredTasks(@RequestParam @NotNull Long requestingUserId, @RequestBody TaskFilterDto filters) {
@20cognosce Не уверен, но думаю что ты должен брать requestingUserId из UserContext. Это информация текущего юзера (который залогинился в системе), поэтому эту инфу предпочтительно передавать не в requestParam.

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/controller/TaskController.java
> +    }
Этот метод и предыдущий (получение по фильтрам и получение всех tasks) можно вынести в отдельный метод. Если приходят фильтры, то фильтруешь - если нет, возвращаешь все tasks по projectId

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/controller/TaskController.java
> +    @GetMapping("/all")
Если сделаешь 1 метод для получения и фильтрации, url переделай

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/dto/task/TaskDto.java
> +    @NotNull
NotBlank уже делает проверку на null, зачем ты опять здесь проверяешь?

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/dto/task/TaskFilterDto.java
> +    private Long projectId;
Зачем тут это поле? Ты его в методе контроллера в path variable должен передавать

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +    }
У тебя и валидация, и сохранение в одном методе (нарушение SOLID - S)? Этот метод сделай валидационным, а сохранение делай прямо в публичном методе сервиса (createTask)

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +        return saveTask(task);
Два раза сохраняешь task? Вынеси сохранение в репозиторий как я написал ниже

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +        Task task = saveTask(tempTask);
Нейминг - toUpdate

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +    public List<Task> getFilteredTasks(Long requestingUserId, TaskFilterDto filters) {
Этот метод должен задачи ПРОЕКТА (!) с фильтрами, лучше в методе контроллера через Request Param передавать (тогда получение всех задач проекта и задач проекта с фильтрами можно в один метод запихнуть)

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +        List<Task> tasks = taskRepository.findAll();
taskRepository.findAllByProjectId - ты же для проекта ищешь tasks

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +    public List<Task> getAllTasksByProject(Long userId, Long projectId) {
Нет проверки на projectId - есть он в бд? В методе выше тоже сделай

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +    private void validateParameters(Task tempTask) {
Очень странное имя метода, придумай что-нибудь получше

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +    }
У тебя уже есть проверка в dto на null через jakarta аннотации, зачем ты ее опять делаешь? Также в методе проверки ты меняешь состояние task - нехорошо

2024-10-03 09:07 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/mapper/TaskMapper.java
> +public interface TaskMapper {
Очень много избыточности в этом маппере, даже не знаю где начать. Обратись к домкументации, постарайся убрать ненужные default методы

2024-10-03 09:12 UTC, Peregruzochka reviewed
тесты вроде гуд

2024-10-03 09:12 UTC, Peregruzochka commented on src/test/java/faang/school/projectservice/service/TaskServiceTest.java
> +        Assert.assertThrows(RuntimeException.class, () -> taskService.createTask(t));
Можно сделать статический импорт

2024-10-03 09:12 UTC, Peregruzochka commented on src/test/java/faang/school/projectservice/service/TaskServiceTest.java
> +        Task t = new Task();
Лучше переменные называть словами а не буквами

2024-10-03 09:12 UTC, Peregruzochka commented on src/test/java/faang/school/projectservice/service/TaskServiceTest.java
> +        t.setReporterUserId(1L);
можно повторяющиеся переменные вынести в `@BeforeEach`

2024-10-03 09:12 UTC, Peregruzochka commented on src/test/java/faang/school/projectservice/service/TaskServiceTest.java
> +                .usingRecursiveAssertion()
тут лучше подходит usingRecursiveComparison()

2024-10-06 10:41 UTC, 20cognosce requested changes

2024-10-06 10:41 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +    @Transactional
read only = true

2024-10-06 10:41 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +        if (filters != null) {
почему ты проверяешь на null
если можно 
private final List<TaskFilter> taskFilters = new ArrayList();

И тогда если фильтров нет, то список будет просто пустой.

2024-10-06 10:41 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +    @Transactional
readOnly = true

2024-10-06 10:41 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +        // Для прогона тестов
Не понял, для кого эти комментарии

Мокай userServiceClient, а не сервис

2024-10-06 10:41 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +        if (userId == 25) {
такого в коде быть не должно

2024-10-06 10:41 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +        // Для прогона тестов
А вообще что мешает поднять два сервиса одновременно и через FeignClient настроить запрос в юзер сервис?

2024-10-06 10:41 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +            taskRepository.findById(tempTask.getParentTask().getId()).ifPresentOrElse(
длинная цепочка вызовов, объяви опшинал

2024-10-06 10:41 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +        }
А попроще можно, декомпозировать?

2024-10-06 14:06 UTC, lexus-74 commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +        if (filters != null) {
Потому, что это dto c которым я вызываю данный метод из двух методов контроллера. В первом случае я передаю dto, во втором соответственно я его передаю как null

2024-10-06 15:38 UTC, 20cognosce approved these changes

2024-10-06 15:38 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/TaskController.java
> +import org.springframework.web.bind.annotation.*;
не сворачивать импорты

2024-10-06 15:38 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +            });
Ну проще можно же

2024-10-06 15:38 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/TaskService.java
> +                    });
.

2024-10-06 15:38 UTC, merged