Тесты еще не написал. До субботы напишу
CorporationX/project_service pull request #701
Opened 2024-10-03 12:40 UTC by aassylkhan

2024-10-03 13:15 UTC, SharkB38 requested changes
В целом круто, пару моментов прояснить бы

2024-10-03 13:15 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/config/S3Config.java
> +@Configuration
Сеттеры надо

2024-10-03 13:15 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/controller/project/ProjectController.java
> +    public ResponseEntity<String> uploadProjectCover(
Что то вроде было про ResponseEntity String у кого то, точно не помню

2024-10-03 13:15 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/impl/ProjectCoverServiceImpl.java
> +        if (file.getSize() > 5 * 1024 * 1024) {
Это бы в конфиг или константу

2024-10-03 13:15 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/impl/ProjectCoverServiceImpl.java
> +            throw new InvalidFileException("Размер файла превышает 5 Мб");
Сообщения на русском 🤔

2024-10-03 13:15 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/controller/project/ProjectController.java
> +        }
Вот тут не понял, почему здесь отлавливаешь ошибки у тебя же есть хэндлер?

2024-10-04 03:13 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/config/S3Config.java
> +    private String bucketName;
Параметры лучше в отдельный класс выделить, как Максим в своём ПР делал)

2024-10-04 03:13 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/ProjectCoverService.java
> +    String uploadProjectCover(Long projectId, MultipartFile file) throws Exception;
Думаю, стоит убрать что метод uploadProjectCover может выбрасывать исключение, и в самом методе их отправлять в GlobalExceptionHandler)

2024-10-04 03:13 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/impl/ProjectCoverServiceImpl.java
> +        PutObjectRequest putObjectRequest = new PutObjectRequest(bucketName, fileName,
Предложил бы ещё S3 в отдельный сервис вынести)

2024-10-04 13:30 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/controller/project/ProjectController.java
> +    public ResponseEntity<String> uploadProjectCover(
"Используем GET/POST + QueryParam/RequestBody."
Думаю, RequestParam +- равно QueryParam по логике работы, поэтому либо делать get запрос, либо менять RequestParam на RequestBody

2024-10-04 13:32 UTC, wmwmaks commented on src/main/java/faang/school/projectservice/service/impl/ProjectCoverServiceImpl.java
> +    private String bucketName;
у тебя в S3Config есть точно такое же поле)

2024-10-08 19:01 UTC, mysosnovskaya requested changes

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectController.java
> +    public ResponseEntity<String> uploadProjectCover(
String не преобразуется в json, а мы используем именно json для общения между бэком и фронтом. Поэтому просто String возвращать нельзя, его нужно оборачивать в dto. И я бы вернула просто coverImageId, без дополнительного текста. Иначе как фронт из этой строки с лишним текстом будет доставать id?

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/project/ProjectController.java
> +    public ResponseEntity<ProjectCoverDeleteResponse> deleteProjectCover(
Вот тут как раз правильно, что возвращаешь не String, а dto, но только ResponseEntity мы не используем, в нем нет смысла. Просто` public ProjectCoverDeleteResponse deleteProjectCover(`, ну или опять void, это тоже ок

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/ProjectCoverDeleteResponse.java
> +public record ProjectCoverDeleteResponse(
Можно делать более общее dto, например, SuccessResponse с полем message

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/project/ProjectCoverUploadRequest.java
> +public record ProjectCoverUploadRequest(
Где этот класс используется?

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(ex.getMessage());
Зачем это изменение? Благодаря аннотации ResponseStatus статус был корректен и с ней всё должно было работать корректно. Не понимаю, зачем потребовалось что-то менять. Тем более у нас выбран стиль именно с ResponseStatus, а вот ResponseEntity мы наоборот не используем без необходимости

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ex.getMessage());
Аналогично

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> -    public ErrorResponse handleInvitationAlreadyExistsException(InvitationAlreadyExistsException ex) {
А обработка InvitationAlreadyExistsException почему удалена?

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> -    public ErrorResponse handleInvalidInvitationStatusException(InvalidInvitationStatusException ex) {
А обработка InvalidInvitationStatusException почему удалена?

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/cover/ImageProcessor.java
> +    private int maxRectangleWidth;
У тебя есть класс ImageConfig с этими же параметрами. Вот здесь нужно использовать его

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/cover/ImageProcessor.java
> +        return switch (extension) {
Не понимаю смысл этого switch. Почему если у файла какое-то другое расширение (не png или gif), то мы говорим, что это jpg?

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/cover/impl/ProjectCoverServiceImpl.java
> +    private String getFileExtension(String filename) {
Дублирование с тем, что уже есть в ImageProcessor (там точно такой же метод)

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/cover/impl/ProjectCoverServiceImpl.java
> +            throw new InvalidFileException("File size exceeds " +
1024 * 1024 лучше вынести в константы

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/cover/impl/ProjectCoverServiceImpl.java
> +                contentType.equalsIgnoreCase("image/jpeg") ||
Было бы хорошо создать enum под эти варианты. Может быть уже готовый есть в одной из библиотек, надо посмотреть)

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/cover/impl/ProjectCoverServiceImpl.java
> +                contentType.equalsIgnoreCase("image/jpeg") ||
Можно создать константу `List<String>` с допустимыми форматами изображения и здесь проверять на contains в этом списке

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/cover/impl/ProjectCoverServiceImpl.java
> +        projectRepository.save(project);
Обрати внимание на этот мой коммент:
https://github.com/CorporationX/project_service/pull/679#discussion_r1782425067
Лучше сначала сохранить в базу, а потом в s3

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    void uploadFile(byte[] fileContent, String contentType, String key);
Уже есть метод uploadFile, и похоже, что ты в ProjectCoverServiceImpl пользуешься им) Поэтому этот метод нужно удалить

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/s3/S3ServiceImpl.java
> +    private final AmazonS3 amazonS3;
А зачем переименовывать?)

2024-10-08 19:01 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/resource/ResourceObjectResponse.java
> +public record ResourceObjectResponse (
В S3Service используется такой импорт:
`import faang.school.projectservice.dto.response.ResourceResponseObject;`
Похоже, этот класс не нужен

2024-10-13 08:43 UTC, aassylkhan commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    void uploadFile(byte[] fileContent, String contentType, String key);
@mysosnovskaya в главной ветке есть такой метод, но параметры не совпали с моим кодом.

2024-10-13 14:19 UTC, mysosnovskaya requested changes
Много моих комментариев остались неисправленными и неотвеченными. Отправляю на доработку.

2024-10-13 14:19 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> -    public ErrorResponse handleInvitationAlreadyExistsException(InvitationAlreadyExistsException ex) {
Ещё актуально

2024-10-13 14:19 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> -    public ErrorResponse handleInvalidInvitationStatusException(InvalidInvitationStatusException ex) {
Ещё актуально

2024-10-13 14:19 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(ex.getMessage());
Ещё актуально

2024-10-13 14:19 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/cover/ImageProcessor.java
> +    private int maxRectangleWidth;
Ещё актуально

2024-10-13 14:19 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/cover/ImageProcessor.java
> +        if (extension.equalsIgnoreCase("png") || extension.equalsIgnoreCase("gif")
Заведи константный список из форматов, которые поддерживаются (их даже можно из конфига подтянуть), а здесь просто сделай list.contains(extension), будет проще и красивее)

2024-10-13 14:19 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/cover/impl/ProjectCoverServiceImpl.java
> +                contentType.equalsIgnoreCase("image/jpeg") ||
Ещё актуально

2024-10-13 14:19 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    void uploadFile(byte[] fileContent, String contentType, String key);
Не поняла. Ты в сервисе вызываешь как
`s3Service.uploadFile(file, fileName);`
а это как раз верхний метод. Тем более из MultipartFile можно получить и fileContent, и contentType. Поэтому не вижу необходимости в этом методе

2024-10-13 14:19 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/resource/ResourceObjectResponse.java
> +public record ResourceObjectResponse (
Ещё актуально

2024-10-22 21:00 UTC, mysosnovskaya requested changes
Два моих комментария с прошлого раза продублировала ещё раз, а в остальном всё ок)

2024-10-22 21:00 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/resource/ResourceObjectResponse.java
> +public record ResourceObjectResponse (
Мой комментарий всё ещё актуален. Где используется этот класс? Я не нашла

2024-10-22 21:00 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/cover/impl/ProjectCoverServiceImpl.java
> +                contentType.equalsIgnoreCase("image/jpeg") ||
Дублирую свой предыдущий комментарий: 
Можно создать константу `List<String>` с допустимыми форматами изображения и здесь проверять на contains в этом списке

2024-10-24 17:51 UTC, mysosnovskaya approved these changes

2024-10-24 17:51 UTC, merged