BJS2-26879 -
CorporationX/project_service pull request #705
Opened 2024-10-05 16:34 UTC by mrkorolev

Implementation notes:
- Не везде добавил swagger документацию
- Не создаю x-user-id в header, сегодня вечером добавлю
- Тесты напишу позже, хотел проверить ход мыслей

https://faang-school.atlassian.net/browse/BJS2-26879

2024-10-06 13:45 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/service/team/TeamService.java
> +        return teamRepository.save(team);
Не совсем понятно, зачем сохранять команду 3 раза?
А может создать метод, который просто создает команду без MemberDto, а в бд добавить собственника, через user-context

2024-10-06 13:45 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/service/team/TeamService.java
> +import faang.school.projectservice.model.TeamMember;
ууу

2024-10-06 13:45 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/service/team/TeamMemberService.java
> +        TeamMemberUtil.validateOwnerOrTeamLead(teamProject, userContext.getUserId(), caller);
Почему валидатор не через @Bean? Я прост не понимаю как правильно

2024-10-06 13:45 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/service/team/TeamMemberService.java
> +    private TeamMember verifyMember(UserDto userData, Long projectId, Team target, TeamRole role) {
Мб назвать его createIfNotExist?

2024-10-06 13:45 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/dto/team/UpdateMemberDto.java
> +public class UpdateMemberDto {
зачем все это зачем?

2024-10-06 13:45 UTC, Peregruzochka commented on src/main/java/faang/school/projectservice/controller/advice/ControllerAdvice.java
> +import feign.FeignException;
хоба

2024-10-06 18:50 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/service/team/TeamMemberService.java
> +        TeamMemberUtil.validateOwnerOrTeamLead(teamProject, userContext.getUserId(), caller);
@20cognosce

2024-10-07 20:09 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/team/TeamMemberService.java
> +        TeamMemberUtil.validateOwnerOrTeamLead(teamProject, userContext.getUserId(), caller);
Util - класс со статическими методами
Можешь ли ты там всё провалидировать нормально без костылей в статике - хз
Лучше инстансы использовать

2024-10-07 20:10 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/team/TeamMemberService.java
> +        TeamMemberUtil.validateOwnerOrTeamLead(teamProject, userContext.getUserId(), caller);
Ну и по названию, валидация не входит в ответственность этого класса

2024-10-07 20:25 UTC, 20cognosce requested changes
причеши код немного и правь тесты

2024-10-07 20:25 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/ProjectServiceApplication.java
>  package faang.school.projectservice;
Билд фэйл

2024-10-07 20:25 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/controller/TeamController.java
> +    @PostMapping("/projects/{project-id}/members")
почему не гет

2024-10-07 20:25 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/repository/TeamMemberRepository.java
> +    }
Че за бред
зачем фасад над имеющимся репо

2024-10-07 20:25 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/repository/TeamMemberRepository.java
> +    }
убрать лишний

2024-10-07 20:25 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/team/TeamMemberService.java
> +        return stream.toList();
А если есть и роль, и ник?
Вот этот метод криво написан

2024-10-07 20:25 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/util/TeamMemberUtil.java
> +    }
Создай валидатор

2024-10-07 20:33 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/repository/TeamMemberRepository.java
> +    }
@20cognosce Кто то начал писать надстройку над обычным репозиторием, я просто продолжил

2024-10-07 20:59 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/service/team/TeamMemberService.java
> +        return stream.toList();
@20cognosce В описании задачи написано 'или', но я перепишу

2024-10-09 17:38 UTC, 20cognosce approved these changes

2024-10-09 17:38 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/repository/TeamMemberRepository.java
>      private final TeamMemberJpaRepository jpaRepository;
Ну это же бред, удалите лишниее

2024-10-09 17:38 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/validator/TeamMemberValidator.java
> +    }
private методы вниз, public - вверх

2024-10-09 17:38 UTC, merged

2024-10-09 17:42 UTC, mrkorolev commented on src/main/java/faang/school/projectservice/repository/TeamMemberRepository.java
>      private final TeamMemberJpaRepository jpaRepository;
@20cognosce Надеюсь ты видишь, что это не я написал. Иначе это не имело смысла.