Обновлен GlobalExceptionHandler для корректной обработки исключений и приведения ответов к требуемому формату
CorporationX/project_service pull request #718
Opened 2024-10-09 10:05 UTC by Suragany98

2024-10-10 05:46 UTC, SharkB38 requested changes

2024-10-10 05:46 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +    public ErrorResponse handleValidationExceptions(Exception ex) {
Тут бы название метода поменять

2024-10-10 05:46 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +        Map<String, String> errors = new HashMap<>();
Кажется там все таки нужен List, потому что у одного поля может быть несколько constraint'ов

2024-10-21 10:56 UTC, Suragany98 commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +        Map<String, String> errors = new HashMap<>();
в задаче было сказано чтоб было таким {
"description": "should not be blank"
}

2024-10-21 10:57 UTC, Suragany98 commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +    public ErrorResponse handleValidationExceptions(Exception ex) {
поменял на handleGeneralExceptions )

2024-10-21 12:45 UTC, SharkB38 approved these changes

2024-10-22 21:15 UTC, mysosnovskaya requested changes

2024-10-22 21:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +    public ErrorResponse handleGeneralExceptions(Exception ex) {
А мне нравилось предыдущее название =) Тут же как раз идея в том, что обрабатываются исключения, которые произошли из-за некорректных данных со стороны пользователя. Это можно обобщить словом валидация)

2024-10-22 21:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +    public Map<String, String> handleMethodArgumentNotValidException(MethodArgumentNotValidException ex) {
Новое название - хорошее, а вот зачем ты поменял `List<Violation>` на мапу не понимаю. Список смотрелся лучше, т.к. был понятным dto с понятными полями. К тому же в этот dto легко будет добавить новое поле при необходимости. Давай оставим список)

2024-10-22 21:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +        log.error(ex.getMessage(), ex);
Лог это хорошо

2024-10-22 21:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +        Map<String, String> errors = new HashMap<>();
Да, список лучше. 
В задаче это было как пример, говорящий о том, что должен использоваться dto (потому что в примере в json присутствует поле description, а у тебя в текущей реализации этого поля нет)

2024-10-22 21:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +    public ErrorResponse handleThrowable(Throwable ex) {
Новое название лучше 👍

2024-10-22 21:15 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +        return new ErrorResponse("An unexpected error occurred.");
getMessage из исключения лучше тоже всё-таки отправить в ответе, чтобы было понятно, из-за чего вообще это произошло

2024-10-31 10:05 UTC, Suragany98 commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +        return new ErrorResponse("An unexpected error occurred.");
исправил

2024-10-31 10:05 UTC, Suragany98 commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +    public Map<String, String> handleMethodArgumentNotValidException(MethodArgumentNotValidException ex) {
исправил

2024-10-31 10:05 UTC, Suragany98 commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +    public ErrorResponse handleGeneralExceptions(Exception ex) {
поменял )

2024-10-31 19:55 UTC, mysosnovskaya approved these changes

2024-10-31 19:55 UTC, merged