Добавление обложки к проекту
CorporationX/project_service pull request #719
Opened 2024-10-09 15:00 UTC by lexus-74

2024-10-09 19:27 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +        Project project = projectRepository.getProjectById(projectId);
Пишет что сборка со сбоем из-за этого метода (и из-за такого же на 46 строке). 
```
/home/runner/work/project_service/project_service/src/main/java/faang/school/projectservice/service/ProjectService.java:31: error: cannot find symbol

        Project project = projectRepository.getProjectById(projectId);
                                           ^
  symbol:   method getProjectById(Long)
  location: variable projectRepository of type ProjectRepository
/home/runner/work/project_service/project_service/src/main/java/faang/school/projectservice/service/ProjectService.java:46: error: cannot find symbol
        Project project = projectRepository.getProjectById(projectId);
                                           ^
  symbol:   method getProjectById(Long)
  location: variable projectRepository of type ProjectRepository
```

Попробуй напрямую имплементировать ProjectJpaRepository и использовать уже его метод findById.
```
private final ProjectJpaRepository projectJpaRepository;
Project project = projectJpaRepository.findById(projectId).orElseThrow();
```
Хотя, конечно, странно это все)

2024-10-09 19:27 UTC, Murzin34 commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +    private final long MAX_FILE_SIZE = 5 * 1024 * 1024;
Я бы, вместо константы, сразу в application.yaml добавил бы:
```
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
```
Там класс MultipartProperties должен сам все подцепить.

2024-10-11 17:03 UTC, 20cognosce requested changes
Обязательно ознакомься с моим ревью задачи Данила
Обратись к нему или к Владу, уже решали те же самые проблемы

2024-10-11 17:03 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/config/s3/S3Config.java
> +public class S3Config {
Кажется эта конфигурация уже устарела, создавали клиент уже

2024-10-11 17:03 UTC, 20cognosce commented on src/main/resources/application.yaml
>  services:
Сделай rebase

2024-10-11 17:03 UTC, 20cognosce commented on src/test/java/faang/school/projectservice/service/ProjectServiceTest.java
> +import static org.mockito.Mockito.*;
Не сворачивать импорты

2024-10-11 17:03 UTC, 20cognosce commented on src/test/java/faang/school/projectservice/service/ProjectServiceTest.java
> +import static org.mockito.Mockito.*;
Настрой идею

2024-10-11 17:03 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +        s3Service.uploadFile(file, key);
Нет, нет
Вынести это из транзакции, вот буквально Данилу то же самое писал, посмотри его ревью
https://github.com/CorporationX/project_service/pull/690

Давай инвертируем зависимость, чтобы загрузка в S3 была вне транзакции.

Из контроллера запрос попадает в ProjectResourceService
=== Начало транзакции ===

ProjectResourceService валидирует юзера

ProjectResourceService собирает метаинфу по файлу и отдает её на валидацию в s3 manager

s3 manager валидирует метаинфу по файлу, в том числе на то, что такой файл уже есть в хранилище

Всё ок - ProjectResourceService создает сущность ресурса и сохраняет в БД с флагом PENDING

ProjectResourceService вызывает асинхронный метод uploadFileToStorage() у s3 manager
=== Конец транзакции ===

s3 manager выполняет upload ресурса
7.1 Fail - вызов метода ProjectService по обновлению статуса ресурса в БД на FAILED
Желательно также сохранять инфу в БД о причине такого инцидента с ресурсом
7.2 Success - вызов метода ProjectService по обновлению статуса ресурса в БД на ACTIVE

Member
@[20cognosce](https://github.com/20cognosce) 20cognosce [2 days ago](https://github.com/CorporationX/project_service/pull/690#discussion_r1793847365)
Циклическую зависимость можешь либо разрешить в пропертях, либо добавить слой абстракции, отдельный сервис, который будет чисто CRUD для ресурса делать

2024-10-11 17:03 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +    private final ProjectJpaRepository projectJpaRepository;
Это же тот самый класс обертка? Можно удалить его и использовать обычный репозиторий?

2024-10-11 17:03 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +        if (coverImageId != null) {
А можно сделать так:

if (null) { exception }
func()
func()
func()
return;

2024-10-11 17:03 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +    @Transactional
Тебе транзакция нужна только на взаимодействие с БД
в одной транзакции должно идти вытаскивание проекта из базы по айди и его обновление
ты можешь ему присвоить null сразу же и закончить транзакцию

а из минио файл фактически удалить позднее, асинхронно

2024-10-11 17:03 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +            //  throw new FilerException(ErrorMessage.FILE_EXCEPTION)
Кому комментарии

2024-10-11 17:03 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +        return null;
В смысле null
Никогда не возвращай и не принимай null

2024-10-11 17:03 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    public InputStream downloadFile(String key) {
Нет, нет, нет
Не оперируй потоками
Поток надо открыть, достать что надо, и закрыть, всё

2024-10-11 17:03 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/ImageProcessor.java
> +            BufferedImage image = ImageIO.read(file.getInputStream());
ты закрыл поток чтения?

2024-10-11 17:03 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/ImageProcessor.java
> +import java.awt.*;
Опять

2024-10-21 20:30 UTC, 20cognosce approved these changes

2024-10-21 20:30 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/resource/ProjectResourceManager.java
> +
Почему два одинаковых метода?

2024-10-21 20:30 UTC, 20cognosce commented on src/main/java/faang/school/projectservice/service/ImageProcessor.java
> +import java.awt.*;
Почему не развернул импорт

2024-10-21 20:30 UTC, merged