BJS2-26125 (FEAT): Управление участниками команды
CorporationX/project_service pull request #726
Opened 2024-10-14 14:49 UTC by lowerKamaCase

2024-10-15 06:14 UTC, Silencemess1ah reviewed
Вопросы больше по стилю и не понятно сломалось ли с прошлого что-то из за одного метода удаленного пришлось много править, не думаю что это хороший подход лучше создать новый похожий или переиспользовать старый , ибо легко ошибиться, остальное в комментах ниже

2024-10-15 06:14 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        TeamMember userWirhAccessToAddTeamMember = teamMemberRepository.findById(addTeamMemberDto.getUserIdWithPermission())
with наверное ?

2024-10-15 06:14 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        }
Думаю разнести по приватным методам логику

2024-10-15 06:14 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +                .orElseThrow(() -> new IllegalArgumentException("User with id " + updaterUserId + " does not exist!"));
Дублируешься тоже в отдельный метод

2024-10-15 06:14 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        }
Тоже думаю можно в отдельный метод

2024-10-15 06:14 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Member " + memberId + " not found in the project"));
К комментам выше одни и те же вызовы в отдельный метод/ы

2024-10-15 06:14 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        }
можешь повесить аннотацию над filterDto своей обработчик подхватит если налл придет чтобы здесь не писать это

2024-10-15 06:14 UTC, Silencemess1ah commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberServiceTest.java
> +    private Long teamMemberId = 3L;
в константу

2024-10-15 06:14 UTC, Silencemess1ah commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> -                new EntityNotFoundException("Team member with id " + id + " does not exist!"));
Я так и не понял зачем ты удалил этот метод и везде пришлось править это в логике, в ресурсах, стажировках и т.д.

2024-10-15 11:58 UTC, imerku1ov commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +@RequestMapping("/api/v1/team")
Возможно я неправильно понял задание, но мне кажется тут неправильный дизайн API

1. Главное, что смутило - это то, что у TeamMember нет связи Team, хотя в классе TeamMember есть свойство private Team team, но ты его не используешь

2. @RequestBody не используется в GET запросе:
_"По RESTful принципам, GET-запросы предназначены для получения данных и должны быть идемпотентными и кэшируемыми. Передача тела запроса (как в случае с @RequestBody) не поддерживается стандартами HTTP для GET-запросов. Тело запроса может быть проигнорировано или даже привести к некорректной работе."_

3. Слов add, update, remove, find и т.д. не должно быть - почитай про RESTful соглашение: https://restfulapi.net/resource-naming/

4. Логику с разделением правам ("Добавлять участников в команду может только владелец проекта (owner), либо участник с ролью TEAMLEAD") тоже лучше переделать, при текущей реализации - это небезопасно, т.к. злоумышленник может украсть ID юзера с доступом и подменять данные. Используй `private final UserContext userContext;` и `userContext.getUserId(); ` - это текущий пользователь, под которым мы авторизованы/выполняем запрос - и у него проверяем role

5. В этом файле на мой взгляд должно быть примерно так:

```
@RestController
@RequestMapping("/api/v1/teams")
@RequiredArgsConstructor
public class TeamController {

    private final TeamMemberService teamMemberService;

    @PostMapping("/{teamId}/team-members")
    public TeamMemberDto addTeamMember(@PathVariable Long teamId, @RequestBody AddTeamMemberDto addTeamMemberDto) {
        return teamMemberService.addTeamMember(teamId, addTeamMemberDto);
    }

    @PutMapping("/{teamId}/team-members/{teamMemberId}")
    public TeamMemberDto updateTeamMember(@PathVariable Long teamId, @PathVariable Long teamMemberId, @RequestBody TeamMemberDto teamMemberDto) {
        return teamMemberService.updateTeamMember(teamId, teamMemberId, teamMemberDto);
    }

    @DeleteMapping("/{teamId}/team-members/{teamMemberId}")
    public void removeTeamMember(@PathVariable Long teamId, @PathVariable Long memberId) {
        teamMemberService.removeTeamMember(teamId, teamMemberId);
    }

    @GetMapping("/{teamId}/team-members/{teamMemberId}")
    public TeamMemberDto getTeamMemberById(@PathVariable Long teamId, @PathVariable Long teamMemberId) {
        return teamMemberService.getTeamMemberById(teamId, teamMemberId);
    }

    @GetMapping("/{teamId}/team-members")
    public List<TeamMemberDto> getTeamMembers(
            @PathVariable Long teamId, 
            @RequestParam(required = false) TeamMemberFilterDto filterDto) {
        if (filterDto == null) {
            return teamMemberService.getAllTeamMembers(teamId);
        } else {
            return teamMemberService.findTeamMembers(teamId, filterDto);
        }
    }
}
```

2024-10-15 12:11 UTC, imerku1ov commented on src/main/java/faang/school/projectservice/dto/teammember/AddTeamMemberDto.java
> +    private Long userIdWithPermission;
Это убрать и в TeamMemberService будет примерно так:

```
...
private final UserContext userContext;
private final TeamService teamService; // либо без него, но я бы добавил, чтобы инкапсулировать работу с teamRepository
private final TeamMemberValidator teamMemberValidator; // новый класс

public TeamMemberDto addTeamMember(Long teamId, AddTeamMemberDto addTeamMemberDto) {
        Long userId = userContext.getUserId();
        // тут надо провалидировать что такой user существует
        Team team = teamService.getById(teamId);
        Long projectId = team.getProject().getId();
        TeamMember teamMember = teamMemberRepository.findByUserIdAndProjectId(userId, projectId);
        // тут проверить что такой teamMember существует

       teamMemberValidator.validateUserRoleAccess(teamMember);
        ...
}
```

в validateUserRoleAccess будет
```
public void validateUserRoleAccess(TeamMember teamMember) {       
        if (!teamMember.getRoles().contains(TeamRole.TEAMLEAD) && !teamMember.getRoles().contains(TeamRole.OWNER)) {
            throw new DataValidationException(String.format
                    ("User with id %d doesn't have the right to add new participants", userId));
        }
}
```

2024-10-15 22:44 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        TeamMember userWirhAccessToAddTeamMember = teamMemberRepository.findById(addTeamMemberDto.getUserIdWithPermission())
поправил

2024-10-15 22:45 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        }
для чего это делать? код не повторяется, поэтому я не вижу смысла выносит это в отдельный метод

2024-10-15 22:57 UTC, lowerKamaCase commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +                .orElseThrow(() -> new IllegalArgumentException("User with id " + updaterUserId + " does not exist!"));
согласен. везде поправил где вызываю  teamMemberRepository.findById

2024-10-15 22:58 UTC, lowerKamaCase commented on src/test/java/faang/school/projectservice/service/teammember/TeamMemberServiceTest.java
> +    private Long teamMemberId = 3L;
done

2024-10-17 18:47 UTC, mysosnovskaya requested changes
У тебя сейчас никак не учитывается id проекта, куда добавляется участник. Из-за этого вылезают баги в логике. Это нужно поправить)

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +    @PutMapping
В пути должен быть id, т.к. мы обновляем конкретного тим мембера по идентификатору

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/filter/teammember/TeamMemberTeamNameFilter.java
> +        return entities.filter(member -> member.getTeam().getProject().getName().equalsIgnoreCase(filters.getTeamName()));
Поле называется teamName, а сравнивается с name из Project. Может быть тогда и в фильтрах сразу написать projectName?

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        List<TeamMember> existingMembers = teamMemberRepository.findAll();
Этот запрос потенциально вернет огромный объем данных. Тут лучше использовать более узкий метод, например, findByUserIdAndProjectId

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/dto/teammember/AddTeamMemberDto.java
> +public class AddTeamMemberDto {
А как мы узнаем, к какому проекту добавлять пользователя?

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +                member.setRoles(addTeamMemberDto.getRoles());
Обновление ролей может происходить только в update методе. Метод create занимается только созданием и ничем больше. Т.е. мы должны запретить такой сценарий, когда пытаются добавить уже существующего пользователя

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        TeamMember newMember = TeamMember.builder()
Почему не через маппер?

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +            if (member.getUserId().equals(addTeamMemberDto.getUserId())) {
И кстати, сейчас ты через findAll достал из базы данных вообще всех тим мемберов. А у нас один тим мембер может участвовать в нескольких проектах. И смотри, какая ситуация может получиться: ты хочешь добавить пользователя с id = 123 в какой-то проект. А вместо этого данный код найдет этого же пользователя как участника другого проекта и там обновит ему роли. Это совсем не то, что ожидается

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> -                new EntityNotFoundException("Team member with id " + id + " does not exist!"));
Метод просто переехал вниз) @lowerKamaCase пожалуйста, отвечай на комментарии

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        } else if (updater.getRoles().contains(TeamRole.TEAMLEAD)) {
А если в dto пришли и nickname, и roles? То тогда только из-за того, в каком порядке написан код, будет разное поведение. И тут возможна такая ситуация: к нам приходит dto с заданными nickname и roles. Ты обновляешь только никнейм и возвращаешь статус 200, как будто бы всё обновилось успешно. А на самом деле - роли не обновились. Получается обман)

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        if (!owner.getRoles().contains(TeamRole.OWNER)) {
Ещё бы проверить, в каком проекте он является владельцем. А то вдруг это другой проект? Ничто не запрещает одному человеку быть владельцем в одном проекте и просто исполнителем в другом. Но по твоей реализации получается, что если хотя бы в одном проекте пользователь является владельцем, то он может удалять людей в любом другом проекте, где он является просто участником. Так не должно быть)

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        }
Хорошее предложение)

2024-10-17 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/TeamMember.java
> +    @Column(name = "nickname")
Если добавляешь поля в модели, то значит должны и добавиться колонки в базе данных. У нас это делается через миграции, нужно познакомиться с ними и сделать через них) Если будут трудности - пиши в чат, разберемся вместе

2024-10-17 18:49 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/teammember/TeamMemberService.java
> +        }
Часть кода выносят в отдельный приватный метод не только в случае дублирования, но и в целях декомпозиции кода. Если метод слишком большой (больше 10-15 строк), то его принято разбивать на более мелкие методы, как раз вынося отдельные части в приватные методы. Поэтому с комментарием согласна

2024-10-17 18:50 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/controller/team/TeamController.java
> +@RequestMapping("/api/v1/team")
Класс, спасибо большое за такое подробное и вдумчивое ревью 👍

2024-10-21 18:44 UTC, mysosnovskaya approved these changes
Вот теперь красота)

2024-10-21 18:44 UTC, merged