BJS2-26158 - Created publisher for project view event
CorporationX/project_service pull request #727
Opened 2024-10-17 20:09 UTC by GusevVrn

2024-10-18 11:59 UTC, Varrankin commented
для меня все отлично сделано, замечаний нет

2024-10-19 14:43 UTC, mysosnovskaya requested changes

2024-10-19 14:43 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        return ProjectViewEvent.builder()
Почему не через маппер?)

2024-10-19 14:43 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +    private void notifyProjectViewEvent(Project project, long userId) {
А почему здесь notify в названии? Не лучше ли publish подойдет?

2024-10-20 19:16 UTC, mysosnovskaya approved these changes

2024-10-20 19:18 UTC, merged