Анализ посещаемости профиля проекта
CorporationX/project_service pull request #728
Opened 2024-10-19 10:04 UTC by RuslanIovlev

2024-10-19 10:21 UTC, SharkB38 requested changes
Четко, только нужно паблишер поправить

2024-10-19 10:21 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/publisher/ProjectViewEventPublisher.java
> +public class ProjectViewEventPublisher implements MessagePublisher<ProjectViewEvent> {
Здесь нужен конструктор, в котором ты по Qualifier будешь инжектить нужный тебе channelTopic. У нас же будет куча бинов с типо ChannelTopic а spring не знает какой конкретно нужен тебе

2024-10-19 11:52 UTC, ArstanSubanov approved these changes

2024-10-19 11:52 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/publisher/ProjectViewEventPublisher.java
> +    public void publish(ProjectViewEvent event) {
Думаю, стоит добавить retryable)

2024-10-19 11:52 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    private final ProjectViewEventPublisher projectViewEventPublisher;
Посоветовал бы инжектить MessagePublisher, а не конкретную реализацию)

2024-10-19 12:59 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/publisher/ProjectViewEventPublisher.java
> +    public void publish(ProjectViewEvent event) {
Спасибо, исправлю

2024-10-19 14:52 UTC, mysosnovskaya requested changes

2024-10-19 14:52 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/model/stage/StageRoles.java
> +    @Column(name = "roles", nullable = false)
Это точно так? По-моему я уже видела у тебя это изменение и настаивала на том, что это неверно) Посмотри в папке с миграциями, как создается эта таблица и как у нее называется колонка -  role или roles, а затем проверь по остальным миграциям, что эта колонка не переименовывалась.
В целом раз поле здесь не является коллекцией, то логичнее выглядит именно role

2024-10-20 11:32 UTC, wmwmaks commented on build.gradle.kts
> +    implementation("org.springframework.retry:spring-retry")
@mysosnovskaya кажется, ты говорила, что такие изменения нужно в отдельных задачах делать? Или если они полезные для таска, то можно и так?

2024-10-20 11:33 UTC, wmwmaks approved these changes
👍

2024-10-21 07:22 UTC, SharkB38 approved these changes

2024-10-21 19:21 UTC, mysosnovskaya approved these changes

2024-10-21 19:21 UTC, mysosnovskaya commented on build.gradle.kts
> +    implementation("org.springframework.retry:spring-retry")
Если эта зависимость нужна для выполнения текущей задачи, то конечно это в одном ПР должно быть. А вот если изменение какое-то косвенное и напрямую к задаче не относится (просто захотел версию обновить, хотя и со старой всё работало), то это в отдельном ПР

2024-10-24 17:54 UTC, merged