BJS2-27495 добавлено решение задачи
CorporationX/project_service pull request #732
Opened 2024-10-20 18:44 UTC by KarabbasBarabas

2024-10-21 10:49 UTC, RuslanIovlev commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    }
А почему решил RequiredArgsConstructor убрать?

2024-10-21 14:46 UTC, SharkB38 requested changes

2024-10-21 14:46 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/config/RedisConfig.java
> +    public RedisTemplate<String, String> projectEventPublisherRedisTemplate() {
А почему такой темплейт а не <String, ProjectEvent>?

2024-10-21 14:46 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/publisher/ProjectEventPublisher.java
> +@Service("ProjectEventPublisher")
Здесь бы больше @Component подошел

2024-10-21 14:46 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/publisher/AbstractMessagePublisher.java
> +public abstract class AbstractMessagePublisher<T> {
Какой то странноватый абстрактный класс если честно, теперь конечно понятно почему ты именно такой темплейт используешь. Но мы решили использовать для каждой сущности свой темплейт. Так что такой подход выбивается из стиля команды

2024-10-21 14:46 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +                .build();
Я бы наверное через маппер бы сделал, но это как тебе больше нравится

2024-10-21 14:46 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +        ProjectDto returnProjectDto = projectMapper.toProjectDto(projectRepository.save(project));
Мне кажется здесь бы вот так сделать:
```
projectRepository.save(project);
publisher.publish(projectMapper.toProjectEvent(project));
return projectMapper.toProjectDto(project);
```

2024-10-21 15:38 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/config/RedisConfig.java
> +    public RedisTemplate<String, String> projectEventPublisherRedisTemplate() {
а почему <String, ProjectEvent>?

2024-10-21 15:40 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/config/RedisConfig.java
> +    public RedisTemplate<String, String> projectEventPublisherRedisTemplate() {
Для единообразия конфига на проекте

2024-10-21 15:40 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +    }
чё то не помню, вернул

2024-10-21 15:42 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/publisher/ProjectEventPublisher.java
> +@Service("ProjectEventPublisher")
да, согласен

2024-10-21 15:48 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/publisher/AbstractMessagePublisher.java
> +public abstract class AbstractMessagePublisher<T> {
не вижу ничего странного, если честно.
То что вы решили, это конечно здорово. Но мне не по кайфу делать то, что решил кто-то и у меня не было возможности в этом поучаствовать, поэтому я делаю по-своему.
Темплейт сейчас итак один, когда добавиться ещё один типа RedisTemplate<String, String> на этот надо будет навесить Qualifaer("projectEventPublisherRedisTemplate")

2024-10-21 15:53 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +                .build();
ну да, когда другие методы сервиса будут отправлять проджект ивент, лучше один раз в маппере всё прописать. 
Но я бы так оставил

2024-10-21 15:55 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +        ProjectDto returnProjectDto = projectMapper.toProjectDto(projectRepository.save(project));
это к предыдущему твоему комментарию добавление?

2024-10-21 16:02 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +        ProjectDto returnProjectDto = projectMapper.toProjectDto(projectRepository.save(project));
Да

2024-10-21 16:45 UTC, ArstanSubanov commented on src/main/java/faang/school/projectservice/publisher/AbstractMessagePublisher.java
> +public abstract class AbstractMessagePublisher<T> {
Тут я с тобой не согласен, это решение было предложено Машей, чтобы убрать зависимость от objectMapper'а и мы все согласились, обсуждение происходило в её присутствии и все решения она одобрила. Создаётся такое чувство, что кросс-ревью тебе не нужен и ты не считаешь нас достаточно квалифицированными, чтобы предложить что-то правильное или стоящее. Представь, что тебя взяли на работу, ты придёшь на готовый проект и там будут свои правила оформления кода или ты не смог поучаствовать на митинге и всё обсудили без тебя, ты же там не скажешь - "я буду писать как я хочу, меня не было на митинге"? Если тебе не нужна работа в команде, ты хочешь получать ревью только от Маши и чтобы всё ты делал сам, то думаю стоит поговорить об этом с ней, обсудить, возможно найдется какое-либо решение, может ты сможешь делать задачи в ветке другой команды. Сегодня, Маша сказала что не будет делать ревью тем, кто не делает нормальное кросс-ревью, и боюсь твои задачи она вернёт обратно, также она возвращает задачи, которые не соответствуют общей договоренности.

2024-10-21 17:05 UTC, SharkB38 commented on src/main/java/faang/school/projectservice/publisher/AbstractMessagePublisher.java
> +public abstract class AbstractMessagePublisher<T> {
Все верно, это же командная работа, тут как бы два пути. Если тебе не нравится то к чему мы пришли, подними эту тему хотя бы в канале если на созвоны не попадаешь, предложи какое-то другое решение, аргументируй его, организуй обсуждение. Если не готов этим всем заниматься, тогда придется принять правила, даже если не по кайфу.

2024-10-21 18:55 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/publisher/AbstractMessagePublisher.java
> +public abstract class AbstractMessagePublisher<T> {
Валера опубликовал сообщение о договоренностях и у тебя была возможность принять в этом участие, написав комментарий и предложив продолжить обсуждение. Поэтому всё делаем в едином командном стиле. Отсутствие на созвонах не является причиной игнорировать командные решения. Если всегда ждать всех, то невозможно будет договориться вообще ни о чем. ПРы отправляю на доработку.

2024-10-21 18:58 UTC, mysosnovskaya requested changes

2024-10-21 18:58 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +                .build();
В чем преимущество в данный момент оставлять это через билдер? Нужна аргументация. Потому что в целом он всё делается через мапперы и я не понимаю, зачем здесь делать по-другому

2024-10-22 19:51 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/publisher/AbstractMessagePublisher.java
> +public abstract class AbstractMessagePublisher<T> {
@ArstanSubanov у тебя ошибочное чувство, ваши комментарии мне важны, которые аргументированные и понятно почему лучше сделать так как предлагается. Но только не те, которые в духе: "Мы так решили, поэтому надо делать так" - такие меня не интересуют. Сам не участвую в кросс-ревью потому что не хватает времени, не все лекции бывает могу посмотреть.
То что пишешь ты "чтобы убрать зависимость от objectMapper'а" - это я понимаю и согласен с этим.
То что написал Валерий - это мимо.
Про работу аргумент - просто ты куда-то не в ту сторону пишешь. 
На работе мне за работу платят деньги, у меня в договоре пункт, который означает примерно следущее "в рабочее время работать на интересы компании, на свои не работать"
Я его подписывал в здравом уме и светлой памяти и соблюдаю и я следую общекомандным договорённостям, ри разумеется среди них есть, в обсуждении которых я не принимал участие. А сейчас за обучение плачу деньги я.
Очень странно, что Маша написала, что она не будет делать ревью тем, кто не делает кросс-ревью.
Когда я оплачивал обучение не было условия, что я буду получать образовательные услуги, только если буду делать кросс-ревью

2024-10-22 19:52 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/publisher/AbstractMessagePublisher.java
> +public abstract class AbstractMessagePublisher<T> {
@SharkB38 
"Если не готов этим всем заниматься, тогда придется принять правила, даже если не по кайфу." - ты явно  ошибся адресом.
Я тебя не спрашивал что и как мне делать

2024-10-22 19:54 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +                .build();
аргументация в том, что сейчас есть более приоритетные задачи,  а это работает и ладно.
Но если могу поправить

2024-10-23 20:05 UTC, mysosnovskaya requested changes

2024-10-23 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/config/RedisConfig.java
> +    public RedisTemplate<String, String> projectEventPublisherRedisTemplate() {
Да, нужно изменить на `<String, ProjectEvent>`

2024-10-23 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +                .build();
Да, нужно поправить. 
Нельзя переоценить важность единообразного подхода. Когда на проекте десятки микросервисов, то намного проще ориентироваться в каждом из них, зная заранее как они устроены. Даже если открываешь новый микросервис для тебя, всё равно тебе там всё будет ясно, т.к. он сделан в едином стиле всей команды. Особенно это будет важно для будущих разработчиков, которые не писали этот проект с нуля. Поэтому мы всегда так трепетно относимся к единообразию) И привычку к этому нужно вырабатывать с мелочей, чтобы так было всегда и везде

2024-10-23 20:05 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/publisher/AbstractMessagePublisher.java
> +public abstract class AbstractMessagePublisher<T> {
Нужно переделать в соответствии с принятым подходом

2024-10-25 09:24 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +                .build();
Задача всё равно не будет мерджиться, я бы уже так оставил

2024-10-25 09:26 UTC, KarabbasBarabas commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +                .build();
задача всё равно не будет мерджиться, поэтому я бы так оставил

2024-10-25 20:54 UTC, mysosnovskaya commented on src/main/java/faang/school/projectservice/service/project/ProjectServiceImpl.java
> +                .build();
Если не будет, то ок)

2024-10-27 18:25 UTC, mysosnovskaya approved these changes

2024-10-27 18:26 UTC, closed without merging