BJS2-40669 Internship
CorporationX/project_service pull request #765
Opened 2024-11-07 14:51 UTC by mad1xx1dam

https://github.com/CorporationX/user_service/pull/1796 - restTemplate в userService

По созданию стажировки: принял, что ментор должен быть в какой-то из команд на указанном проекте + под стажеров создается полноценная команда на проекте + ментор не входит в эту команду, а его userId лишь указывается в качестве id ментора.

По обновлению стажировки: стажировка завершена - обновляю команду проекта в соотвествии с завершенностью их заданий (+ обновляю роли) + меняю статус стажировки на COMPLETED; стажировка не завершена - обновляю роли лишь тех, кто закончил выполнение своих заданий, статус стажировки меняю на IN_PROGRESS.

В валидаторе для updateDto сделал именно такую проверку на то, что началась/завершилась стажировка по той причине, что если смена статуса стажировки происходит именно через метод update, то если уже поставили COMPLETED однажды, то больше ничего делать не нужно. А если стоит статус NOT_STARTED, еще не факт, что стажировка еще не началась, просто могло быть такое, что не обновили статус на IN_PROGRESS => надо проверить именно по дате.

В методе getFilteredInternships фильтрацию по роли (которая указана в задании) сделал, проверяя наличие этой роли у ментора стажировки (я не особо понял, какую фильтрацию можно сделать по роли :<).

2024-11-07 15:20 UTC, Memoreks reviewed
Проделана большая работа. Код написан понятно.
Оставил небольшой комментарий

2024-11-07 15:20 UTC, Memoreks commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +public class InternshipService {
Я бы сразу добавил логирование
И не увидел тесты для InternshipService

2024-11-07 17:48 UTC, VovaBuzivskyi commented
Код написан хорошо. Оставил несколько комментариев.

2024-11-07 17:48 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/filter/internship/InternshipStatusFilter.java
> +        return internships.filter(internship -> internship.getStatus() == filterDto.getInternshipStatus());
Статус это объект не примитив, правильнее будет сравнить по equals. Так как дто будет приходить в теле запроса , то наверное маловероятно что это будет ссылка на один и тот же объект. Но я могу ошибаться.

2024-11-07 17:48 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +                        )
Можно через FlatMap сделать, чуть короче получится, но и так тоже хорошо)

2024-11-08 03:37 UTC, mad1xx1dam commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +                        )
Я так понимаю, что через flatMap если делать, то там логика фильтрации будет немного другая. С моим подходом пропускаются только те объекты, которые соответствуют прям всем пунктам фильтра. А если делать через flatMap, то там логика будет такая, что пропускаются те, которые соответствуют хотя бы одному пункту из фильтра

2024-11-08 03:37 UTC, mad1xx1dam commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +                        )
Я так понимаю, что через flatMap если делать, то там логика фильтрации будет немного другая. С моим подходом пропускаются только те объекты, которые соответствуют прям всем пунктам фильтра. А если делать через flatMap, то там логика будет такая, что пропускаются те, которые соответствуют хотя бы одному пункту из фильтра

2024-11-08 03:40 UTC, mad1xx1dam commented on src/main/java/faang/school/projectservice/filter/internship/InternshipStatusFilter.java
> +        return internships.filter(internship -> internship.getStatus() == filterDto.getInternshipStatus());
По идее в enum допускается сравнение по ==. Но лучше да - сделаю через equals, чтобы уже наверняка.
Спасибо!

2024-11-08 03:40 UTC, mad1xx1dam commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +public class InternshipService {
Забылся, спасибо!

2024-11-08 10:45 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +                        )
Согласен, через reduce будет правильнее логика фильтрации.

2024-11-08 15:36 UTC, VovaBuzivskyi commented
Стоит ли использовать константы и private методы. Получается что данные выносятся вне теста, а договаривались что контекст для тета пишем внутри самого теста(ну по крайней мере стараемся).

2024-11-12 02:27 UTC, abdddev requested changes
Много кода конечно) Молодец
Там не крит, но написал на всякий)
Если будут вопросы пиши

2024-11-12 02:27 UTC, abdddev commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +    private static final String USER_SERVICE_URL = "http://localhost:8080/api/v1/users";
Такие вещи лучше выносить в конфиг, а то понадобится поменять порт на 8082, придется все приложение пересобирать, а так можно просто поду перезапустить)

2024-11-12 02:27 UTC, abdddev commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +                        (s1, s2) -> s2
Насколько помню у пика непредсказуемое поведение, даже для log.debug я бы не стал его ставить, но это больше для информации))

2024-11-12 02:27 UTC, abdddev commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +        String url = String.format("%s/not-existing-ids", USER_SERVICE_URL);
ну и это место вынести))

2024-11-12 02:27 UTC, abdddev commented on src/main/java/faang/school/projectservice/service/team/TeamService.java
> +    public Team save(Team team) {
Transactional?

2024-11-12 02:33 UTC, abdddev commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +                .peek(internship -> log.debug("Filtered internship: ID={}, Status={}",
Насколько помню у пика непредсказуемое поведение, даже для log.debug я бы не стал его ставить, но это больше для информации))

2024-11-14 05:24 UTC, abdddev commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +        filteredInternships.forEach(internship ->
Я бы вообще снес, честно говоря)
Есть внизу лог общее количество и отфильтрованных

2024-11-14 05:30 UTC, abdddev approved these changes
Стало прям лучше в разы, круто

2024-11-14 07:38 UTC, mad1xx1dam commented
@Memoreks @VovaBuzivskyi @abdddev 
Огромное спасибо за ревью

2024-11-15 10:45 UTC, BobrAll reviewed
Мощный код получился, прям молодец. Немного комментариев тоже добавил

2024-11-15 10:45 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +@RequestMapping("/internship")
Для сущностей в rest принято использовать множественное число

2024-11-15 10:45 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    }
Методы Get/Post/Put/Delete/.. имеют говорящие названия. Т.е. все знают, что post для создания чего-либо, put для обновления, get для получения и т.д. Поэтому приставки по типу /create, /update избыточны

А для обновления лучше использовать put в данном случае (можно глянуть разницу между put и patch)

2024-11-15 10:45 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +public class InternshipController {
Все остальное отлично в плане эндпоинтов
Не помню, кидал или нет, но вот классная статья по именованию в рест https://habr.com/ru/articles/351890/

2024-11-15 10:45 UTC, BobrAll commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +    @Mapping(source = "interns", target = "internUserIds", qualifiedByName = "internsToIds")
Лайк

2024-11-15 10:45 UTC, BobrAll commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +import faang.school.projectservice.validator.internship.InternshipValidator;
Думаю можно смело написать import faang.school.projectservice.;
Или хотя бы по папкам:
import faang.school.projectservice.model. *;
import faang.school.projectservice.dto.*;
и т.д.

Это, конечно, ни на что не влияет, просто сократит простыню из 42 строчек)
P.S. Если что, после точек в конце импортов, которые я написал, стоит звездочка, но гит их интерпретирует как призыв к курсивному шрифту)

2024-11-15 10:45 UTC, BobrAll commented on src/main/java/faang/school/projectservice/service/internship/InternshipService.java
> +    @Value("${services.user-service.host}:${services.user-service.port}${spring.mvc.servlet.path}")
Круто!

2024-11-15 10:45 UTC, BobrAll commented on src/main/java/faang/school/projectservice/validator/internship/InternshipValidator.java
> +    private static final int MAX_INTERNSHIP_MONTHS_DURATION = 3;
Лайк

2024-11-15 12:15 UTC, mad1xx1dam commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +public class InternshipController {
Спасибо :))

2024-11-15 16:48 UTC, BobrAll commented
Отлично)

2024-11-15 16:48 UTC, merged