Feature/bjs2 40689
CorporationX/project_service pull request #766
Opened 2024-11-07 15:40 UTC by m1rroxxx

Проекты

2024-11-08 20:18 UTC, 24slavaK reviewed
так в целом все норм как будто , не знаю даже к чему придраться )

2024-11-08 20:18 UTC, 24slavaK commented on src/main/java/faang/school/projectservice/dto/ProjectDto.java
> +    private String visibility;
насколько я знаю enumы так и передаются они вроде по лучше в производительности чем стринги . По крайней мере такая дискуссия была в хелп канале

2024-11-08 20:18 UTC, 24slavaK commented on src/main/java/faang/school/projectservice/filter/project/StatusFilter.java
> +        return projects.filter(project -> project.getStatus().name().contains(projectFilterDto.getStatus()));
и тут как будто лучше полное совпадение юзать иначе Cancel и Cancelled могут вернуть к примеру, хотя эти перечисления могут нести разный смысл

2024-11-08 20:18 UTC, 24slavaK commented on src/main/java/faang/school/projectservice/mapper/ProjectMapper.java
> +    @Mapping(source = "status", target = "status", qualifiedByName = "stringToStatus")
ну и тут соответственно маппинг летит если будешь на enum менять

2024-11-11 20:58 UTC, MiraGlaceon requested changes

2024-11-11 20:58 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +        return projectService.getProjectById(id);
Оберни ответы в ResponseEntity и давай обрабатывать ошибки. У тебя есть валидация, но нет ExceptonHandler

2024-11-11 21:38 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +        return projectService.getProjectById(id);
по моему restController сам в ResponseEntity обернет, если только мне нужно какой то определённый код ответа вернуть, а по поводу exeptionHandler это же вроде 8 спринт, там есть задачи на это

2024-11-19 15:34 UTC, 24slavaK submitted a review, later dismissed

2024-11-20 16:50 UTC, MiraGlaceon approved these changes

2024-11-20 16:50 UTC, merged