Проекты
CorporationX/project_service pull request #784
Opened 2024-11-08 16:00 UTC by aplavina

https://faang-school.atlassian.net/browse/BJS2-40681

2024-11-09 13:16 UTC, frs717 commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +        logUpdate(project);
В логе выводится, что проект был обновлен.
Я бы разделил. Здесь все же создается проект.

2024-11-09 13:16 UTC, frs717 commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +            throw new NotOwnerException("The user is not the owner of this project");
Сейчас NotOwnerException выше ловиться в try catch. И там пробрасывается DataValidationException.

Может тогда сразу прокидывать DataValidationException ?

2024-11-09 13:16 UTC, frs717 commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +        return project == null || !filterPrivate(project) ? Optional.empty() : Optional.of(projectMapper.toDto(project));
project не может быть null

В методе getProjectById() есть логика на проверку
```
 public Project getProjectById(Long projectId) {
        return projectJpaRepository.findById(projectId).orElseThrow(
                () -> new EntityNotFoundException(String.format("Project not found by id: %s", projectId))
        );
    }
```

2024-11-09 13:16 UTC, frs717 commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +            Set<Long> memberIds = new HashSet<>();
Мне кажется этот фрагмент можно упростить.
Из members сразу получить set id

И в итоговой проверке: set.contains(userId) || userId.equals(project.getOwnerId())

2024-11-15 15:56 UTC, MiraGlaceon requested changes

2024-11-15 15:56 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/exception/handler/DataValidationHandler.java
> +public class DataValidationHandler {
За адвайсоры выражаю респект, но только у тебя по каждой ошибке есть адвайсор. Давай соберем типовые ошибки в адвайсор по валидации. Как ты считаешь?

2024-11-15 15:56 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/helpers/ProjectDfs.java
> +public class ProjectDfs {
Тут смущает имя класса, не совсем понятно что оно значит

2024-11-18 15:29 UTC, MiraGlaceon approved these changes

2024-11-18 17:35 UTC, merged