Вакансии
CorporationX/project_service pull request #785
Opened 2024-11-08 17:10 UTC by dimaevseenko

Реализация задачи + тесты

2024-11-10 16:16 UTC, 24slavaK commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    }
Методы валидации можно было бы вынести в отдельный класс

2024-11-10 16:16 UTC, 24slavaK commented on src/main/java/faang/school/projectservice/service/vacancy/VacancyServiceImpl.java
> +                .flatMap(filter -> filter.apply(vacancyStream, filters))
у тебя здесь ошибка будет выбрасываться "stream has already been operated upon or closed" в тестах не видно потому что у тебя в них у фильтров всегда только 1 параметр не null

2024-11-10 16:16 UTC, 24slavaK commented on src/main/java/faang/school/projectservice/validator/vacancy/VacancyServiceValidator.java
> +            if (!teamMember.get().getRoles().contains(TeamRole.OWNER) || teamMember.get().getRoles().contains(TeamRole.MANAGER)) {
Местами прям тяжело читать нудны \n

2024-11-10 16:17 UTC, 24slavaK commented
еще я не понял зачем столько интерфеисов которые как будто только 1 раз имплементировались , но может я просто логику программы не понимаю

2024-11-13 13:21 UTC, dimaevseenko commented on src/main/java/faang/school/projectservice/service/vacancy/VacancyServiceImpl.java
> +                .flatMap(filter -> filter.apply(vacancyStream, filters))
Поправил

2024-11-14 15:25 UTC, dimaevseenko commented
> еще я не понял зачем столько интерфеисов которые как будто только 1 раз имплементировались , но может я просто логику программы не понимаю

Для реализации принципа инверсии управления, чтобы в любой момент мы смогли подставить другую реализацию зависимости

2024-11-14 15:26 UTC, dimaevseenko commented
> > еще я не понял зачем столько интерфеисов которые как будто только 1 раз имплементировались , но может я просто логику программы не понимаю
> 
> Для реализации принципа инверсии управления, чтобы в любой момент мы смогли подставить другую реализацию зависимости

конкретно в данном случае - сервиса

2024-11-15 15:45 UTC, MiraGlaceon requested changes

2024-11-15 15:45 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +public class VacancyController {
Давай перепишем на RestController в рамках 7го спринта

2024-11-15 15:45 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    private void validateValidateVacancy(VacancyDto vacancyDto) {
Тут в целом методы валидации нужно заменить через аннотационный подход, через аннотацию Valid. Ты в dto можешь подвесить аннотации над полями типа NotNull или Positive на поле с айдишником и тогда спринг сам будет валидовать поля. Ты в целом так и делаешь в ДТОшках, но не валидируешь в контроллерах, например,  в методе getVacancies() можно добавить аннотацию Valid

2024-11-15 15:45 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/validator/vacancy/VacancyServiceValidator.java
> +            if (!teamMember.get().getRoles().contains(TeamRole.OWNER) || teamMember.get().getRoles().contains(TeamRole.MANAGER)) {
Согласен, будет полезно при большой цепочке методов каждый метод переводить на новую строку

2024-11-15 15:54 UTC, dimaevseenko commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    private void validateValidateVacancy(VacancyDto vacancyDto) {
В контроллере проверяются обьекты которые приходят в теле запроса, здесь валидация самих обьектов, не пустой ли Request Body. А дальше в сервисе я использую @Valid в параметре методов для проверки уже полей этого обьекта

2024-11-15 16:16 UTC, dimaevseenko commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +public class VacancyController {
Сделал

2024-11-15 16:24 UTC, dimaevseenko commented
Пишет, что не хватает тестов, но это в чужом сервисе только, на них я тесты не писал

2024-11-16 16:12 UTC, dimaevseenko commented
> Пишет, что не хватает тестов, но это в чужом сервисе только, на них я тесты не писал

Доделал тесты

2024-11-18 15:41 UTC, MiraGlaceon approved these changes

2024-11-18 15:42 UTC, merged