Solution for supProject
CorporationX/project_service pull request #799
Opened 2024-11-10 15:56 UTC by 24slavaK

2024-11-13 15:46 UTC, MiraGlaceon requested changes

2024-11-13 15:46 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/validator/Validator.java
> +public class Validator {
Укажи валидатор чего

2024-11-14 19:03 UTC, KandesQ approved these changes
классный код

2024-11-18 15:42 UTC, MiraGlaceon approved these changes

2024-11-18 16:22 UTC, merged