Подпроекты
CorporationX/project_service pull request #802
Opened 2024-11-11 08:28 UTC by allitov

2024-11-11 23:30 UTC, VovaBuzivskyi commented
Код написан хорошо ! Оставил несколько комментариев.

2024-11-11 23:30 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/filter/SubProjectNameFilter.java
> +        Objects.requireNonNull(filters, "Filters cannot be null");
А нужна ли эта валидация фильтра, выше ведь есть проверка фильтров на null. По идее если фильтр null то он не дойдет до apply.

2024-11-11 23:30 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/dto/subproject/SubProjectFilterDto.java
> +    private String name;
Может лучше назвать projectNamePattern или namePattern?

2024-11-11 23:30 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/dto/subproject/CreateSubProjectDto.java
> +public class CreateSubProjectDto {
Может лучше просто SubProjectDto?

2024-11-11 23:30 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/mapper/ProjectMapper.java
> +    Project toEntity(CreateSubProjectDto createSubProjectDto);
Нужно ли явно указывать как мапить если названия и типы полей одинаковые , по идее оно само должно мапить без проблем.

2024-11-11 23:30 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/mapper/ProjectMapper.java
> +    ProjectDto toDto(Project project);
Здесь должно тоже смаппится само, если я все правильно понимаю нужно явно указывать только те поля которые отличаются названием или типом данных.

2024-11-12 11:05 UTC, allitov reviewed
@VovaBuzivskyi, спасибо за ревью!

2024-11-12 11:05 UTC, allitov commented on src/main/java/faang/school/projectservice/dto/subproject/CreateSubProjectDto.java
> +public class CreateSubProjectDto {
Я бы тоже немного изменил название, но в тз используется такое :)

2024-11-12 11:05 UTC, allitov commented on src/main/java/faang/school/projectservice/dto/subproject/SubProjectFilterDto.java
> +    private String name;
Согласен, так будет лучше

2024-11-12 11:05 UTC, allitov commented on src/main/java/faang/school/projectservice/mapper/ProjectMapper.java
> +    Project toEntity(CreateSubProjectDto createSubProjectDto);
Это я баловался с BeanMapping аннотацией. Прочитал, что report policy ignore над классом не очень хорошая практика, но при этом приходится явно указывать маппинги

2024-11-12 11:05 UTC, allitov commented on src/main/java/faang/school/projectservice/mapper/ProjectMapper.java
> +    ProjectDto toDto(Project project);
Тут тоже использовал BeanMapping :)

2024-11-12 11:05 UTC, allitov commented on src/main/java/faang/school/projectservice/filter/SubProjectNameFilter.java
> +        Objects.requireNonNull(filters, "Filters cannot be null");
Сделал тут проверку, чтобы при передаче в метод apply null объектов как можно быстрее выбрасывалось исключение. Это на случай, если кто-то забудет вызвать isApplicable :)

2024-11-12 15:12 UTC, VovaBuzivskyi submitted a review, later dismissed

2024-11-12 15:13 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/filter/SubProjectNameFilter.java
> +        Objects.requireNonNull(filters, "Filters cannot be null");
Понял)

2024-11-14 06:47 UTC, abzalkhan00 reviewed
Хороший код, понравились детально написанные тесты

2024-11-14 06:47 UTC, abzalkhan00 commented on src/main/java/faang/school/projectservice/validator/subproject/SubProjectValidator.java
> +    @Value("${services.user-service.host}")
Там же, вроде, уже есть интерфейс UserServiceClient для работы с другими сервисами. Возможно, туда можно было добавить существующий метод из UserService, если я ничего не путаю

2024-11-14 06:47 UTC, abzalkhan00 commented on src/main/java/faang/school/projectservice/validator/subproject/SubProjectValidator.java
> +    @Value("${services.user-service.host}")
В этом случае не нужен будет RestTemplate

2024-11-16 13:39 UTC, allitov commented on src/main/java/faang/school/projectservice/validator/subproject/SubProjectValidator.java
> +    @Value("${services.user-service.host}")
Александр говорил, это пока что через RestTemplate сделать, вот его и прилепил :)
Спасибо за ревью!

2024-11-16 15:32 UTC, BobrAll requested changes
Код приятно читать - все понятно и хорошо написано. Пару комментариев оставил

2024-11-16 15:32 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +@RequestMapping("/projects/{projectId}/sub-projects")
Лайк)

2024-11-16 15:32 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +                                                 @Valid @RequestBody CreateSubProjectDto dto) {
Раз уж использовать x-user-id, то тогда везде)
А то где-то пользователь из хедера достается, а где-то в дто

2024-11-16 15:32 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    @PostMapping
Если вдруг UserService отвалится, то сервер вернет 500 и пользователю не будет понятно, в чем дело, было бы здорово добавить обработку

2024-11-16 15:32 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/SubProjectController.java
> +    @PostMapping
У тебя идет обращение к UserService без /api/v1/
Наверное не обновил из мастера 
Плюс сейчас 400 возвращает обращение к юзер сервису через эндпоинт создания подпроекта
400 : "{"timestamp":1731770756676,"status":400,"error":"Bad Request","path":"/api/v1/users/not-existing-ids"}"

2024-11-25 05:00 UTC, allitov reviewed
Еще добавил обработку EntityNotFoundException в user_service, иначе падали 500: https://github.com/CorporationX/user_service/pull/2025

2024-11-26 10:33 UTC, BobrAll approved these changes
Отлично, вливаю

2024-11-26 10:33 UTC, BobrAll commented on src/main/java/faang/school/projectservice/client/UserServiceClient.java
> +@FeignClient(name = "user-service", url = "${services.user-service.host}:${services.user-service.port}/api/v1")
В целом можно было бы и /users сюда)

2024-11-26 10:33 UTC, merged