https://faang-school.atlassian.net/browse/BJS2-40664
CorporationX/project_service pull request #811
Opened 2024-11-13 15:12 UTC by 0Miha0

Этапы проекта
1.
createStage(StageDto stageDto): Создает новый этап проекта.
 2.
getStageByFilter(StageFilterDto stageFilterDto): Получает список этапов, соответствующих заданным фильтрам. 
3.
deleteStage(Long stageId, ActionWithTask actionWithTask, Long transferStageId): Удаляет этап с возможностью каскадного удаления, закрытия или переноса задач. 
4.
updateStage(StageDto stageDto): Обновляет информацию об этапе, включая обеспечение необходимых ролей. 
5.
getAllProjectStages(Long projectId): Получает все этапы для указанного проекта. 
6.
getStageById(Long stageId): Получает информацию о конкретном этапе по его ID.
 7.
performCascadeDelete(Stage stage): Выполняет каскадное удаление этапа и связанных задач. 
8.
performCloseAction(Stage stage): Закрывает этап, отмечая все задачи как отмененные. 
9.
performTransferAction(Stage stage, Long transferStageId): Переносит задачи с одного этапа на другой. 
10.
ensureRequiredRoles(Stage stage, Map<TeamRole, Long> currentRoleCount, List<TeamMember> projectTeamMembers): Обеспечивает наличие необходимых ролей для этапа.

2024-11-13 16:14 UTC, Memoreks reviewed
Отличное решение. Особенно круто смотрится подробное логирование, лайк за это:)
Оставил небольшие комментарии

2024-11-13 16:14 UTC, Memoreks commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +public class StageController {
Я бы сразу добавил @RequestMapping

2024-11-13 16:14 UTC, Memoreks commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +    public StageDto createStage(StageDto stageDto){
И аннотации для эндпоинтов, в данном случае PostMapping

2024-11-13 16:14 UTC, Memoreks commented on src/main/java/faang/school/projectservice/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
Круто!

2024-11-13 16:14 UTC, Memoreks commented on src/main/java/faang/school/projectservice/filter/stage/StageRolesFilter.java
> +public class StageRolesFilter implements StageFilter {
Почему аннотация контроллер?

2024-11-13 16:14 UTC, Memoreks commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    private final StageInvitationRepository stageInvitationRepository;
Договорились, что напрямую в другие репозитории не обращаемся. Лучше переписать методы обращаться через сервисы, которые уже будут обращаться к репозиториям.

2024-11-13 16:14 UTC, Memoreks commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +        }
Для красоты можно попробовать переделать switch из java 12

2024-11-13 16:14 UTC, Memoreks commented on src/test/java/faang/school/projectservice/service/stage/StageServiceTest.java
> +        );
Это все можно не писать если применить аннотации @Mock и @InjectMocks

2024-11-14 17:49 UTC, VovaBuzivskyi commented
Код написан хорошо. Оставил несколько комментариев.

2024-11-14 17:51 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/dto/stage/StageDto.java
> +public class StageDto {
Здесь еще нужны конструкторы NoArgs AllArgs

2024-11-14 17:51 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/dto/stage/StageFilterDto.java
> +    private List<StageRoles> stageRoles;
Здесь тоже нужны конструкторы.  И я не думаю что это хорошая идея передавать внутри Дто фильтра ,сущности. Так как говорили передавать и возвращать с эндпоинтов только Дто а не сущности. 
Я думаю тебе стоит поменять фильтр , как я понял по заданию тебе нужно фильтровать по этим параметрам 
![Снимок экрана 2024-11-15 000435](https://github.com/user-attachments/assets/99f555a5-7a5f-47d9-8948-a0b442c0f739)
![Снимок экрана 2024-11-15 000311](https://github.com/user-attachments/assets/2e512b22-638d-4cb2-96eb-e2a60a6fe904)
 а не по списку сущностей StageRole.
T.e тебе нужно два фильтра типа String : teamRolePattern & taskStatusPattern

2024-11-14 17:51 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/filter/stage/StageRolesFilter.java
> +        return stageFilterDto.getStageRoles() != null;
Если stageFilterDto будет null , получится NullPointerException . И не получится дойти до метода getStageRoles(). Нужна проверка самого фильтра на null

2024-11-14 17:51 UTC, VovaBuzivskyi commented on src/main/java/faang/school/projectservice/filter/stage/StageRolesFilter.java
> +    public Stream<Stage> apply(Stream<Stage> stage, StageFilterDto stageFilterDto) {
В стриме по идее может быть много stages , а переменная называется stage (мелочь но лучше поменять)

2024-11-14 17:51 UTC, VovaBuzivskyi commented on src/test/java/faang/school/projectservice/service/stage/StageServiceTest.java
> +                .thenReturn(stage);
Нету verify() вызова этого метода

2024-11-14 17:51 UTC, VovaBuzivskyi commented on src/test/java/faang/school/projectservice/service/stage/StageServiceTest.java
> +                .thenReturn(stageDto);
Маппер Spy ,ему не нужно писать что возвращать, он сам вернет смапленный обьект.

2024-11-14 17:51 UTC, VovaBuzivskyi commented on src/test/java/faang/school/projectservice/service/stage/StageServiceTest.java
> +                .thenReturn(stream);
Нету вызова verify() для методов: isApplicable и apply

2024-11-14 17:51 UTC, VovaBuzivskyi commented on src/test/java/faang/school/projectservice/validtor/stage/StageValidatorTest.java
> +@ExtendWith(MockitoExtension.class)
Эта аннотация здесь не нужна , так как в этом классе нет Моков.

2024-11-16 15:01 UTC, BobrAll reviewed
Хороший код. Немного правок написал, потом самое главное - протестировать с postman все запросы, когда напишешь эндпоинты в контроллере

2024-11-16 15:01 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +public class StageController {
на 7 спринте уже есть материалы по аннтациям RestController, RequestMapping, GetMapping, PostMapping, RequestBody и др., их бы сюда добавить сразу

2024-11-16 15:01 UTC, BobrAll commented on src/main/java/faang/school/projectservice/filter/stage/StageTaskStatusFilter.java
> +    @Override
У нас по код-стайлу принято вставлять пустые строки перед связкой ("аннотации + метод/поле"), можно глянуть в инфо дс

В остальных местах тоже поправить бы

2024-11-16 15:01 UTC, BobrAll commented on src/main/java/faang/school/projectservice/filter/stage/StageTaskStatusFilter.java
> +    }
Круто

2024-11-16 15:01 UTC, BobrAll commented on src/main/java/faang/school/projectservice/validator/stage/StageValidator.java
> +    }
Сильно!

2024-11-16 15:01 UTC, BobrAll commented on src/test/java/faang/school/projectservice/service/stage/StageServiceTest.java
> +    public void setUp() {
Большеватый сетап, постарайся вынести из него по-максимуму все в методы (в таком случае контекст теста сразу будет виден)

2024-11-16 15:36 UTC, BobrAll commented
@0Miha0 Скажи пожалуйста, почему ты не исправил (либо не прокомментировал, если мнения расходятся) замечания, которые тебе ребята на ревью написали?

2024-11-16 15:37 UTC, BobrAll commented
Также конфликт нужно поправить
<img width="959" alt="image" src="https://github.com/user-attachments/assets/68e0b671-f5b6-42a2-ac30-cbdbe7432824">

2024-11-16 15:44 UTC, BobrAll commented
> @0Miha0 Скажи пожалуйста, почему ты не исправил (либо не прокомментировал, если мнения расходятся) замечания, которые тебе ребята на ревью написали?

В дискорде видел обсуждение, если что - это круто, что ты там об этом спросил. Но изменений-то нет, а по остальным комментариям обсуждений нет

2024-11-16 15:58 UTC, BobrAll commented
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/e465d109-b98c-49eb-90fa-09c66601e70a">
Ага, я кажется понял. На ревью мне нужно отправлять уже со всеми исправлениями после код-ревью. Иначе получается, что мы делаем двойную работу - проверяем одно и то же

2024-11-17 15:35 UTC, BobrAll reviewed
Объемная задача, но у тебя хорошо получилось с ней справиться. Еще пару комментариев оставил, потом можно вливать в мастер.

2024-11-17 15:35 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +    public List<StageDto> getStageWithFilter(@RequestBody StageFilterDto stageFilterDto) {
В спецификации не допускается тело в гет-запросе. Это единственное место, где для получения можно использовать метод post.
Все остальные эндпоинты - супер

2024-11-17 15:35 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +@RequestMapping("/api/v1/stages")
В мастер-ветке уже есть приставка /api/v1, поэтому тут ее можно не делать (двойная тогда будет)
<img width="788" alt="image" src="https://github.com/user-attachments/assets/b19f77e0-9733-4bf3-9804-bd6e7e6158c6">

2024-11-17 15:35 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +    @GetMapping("/project/{projectId}")
Тут бы во множественном числе сделать projects (так принято в рест для сущностей)

2024-11-17 15:35 UTC, BobrAll commented on src/main/java/faang/school/projectservice/service/stage/StageService.java
> +    private final StageInvitationRepository stageInvitationRepository;
Тут исправлений так и нет (по крайней мере к project-репозиторию обращение должно идти через сервис)

2024-11-20 12:32 UTC, BobrAll requested changes
Тесты все еще падают 
<img width="948" alt="image" src="https://github.com/user-attachments/assets/86538ff9-10c2-490a-8b83-142c4c5d5a2f">

2024-11-20 12:32 UTC, BobrAll commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +@RequestMapping("stages")
stages в RequestMapping должно начинаться с / 
Тестировал запросы?

2024-11-24 06:48 UTC, 0Miha0 commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +@RequestMapping("stages")
Да, все работает, теперь точно работает

2024-11-24 11:45 UTC, BobrAll approved these changes
Отлично, вливаю

2024-11-24 11:45 UTC, merged