- Реализована логика создания стажировки с валидацией.
CorporationX/project_service pull request #836
Opened 2024-11-18 09:05 UTC by Pizdja

- Реализована логика обновления стажировки.
- Добавлена логика получения всех стажировок.
- Добавлена логика получения стажировок с фильтрацией.
- Реализована логика получения стажировки по её ID.
- Реализована логика завершения стажировки и увольнения стажера.

2024-11-20 14:57 UTC, SergeyZhitenev commented
Нет тестов, соответственно код не проверялся, сейчас он не рабочий. Делай тесты сразу, все равно без них никто ничего не заапрувит + не нужно было бы ждать ревью, чтобы получить больше половины комментов. Так же надо тестить через постман, через него хотя бы можно убедиться, работает что-то или нет. Логика обновления, как мне показалось, реализована не так, как просится в задании. 
Мой совет - посмотри задачи других ребят, и те, что на ревью висят, и те, что уже выполнены и смержены ( даже открывать ничего не надо, все уже в проекте ). Это нормальная практика делать по образу и подобию, при этом разбирая то, что сделано) Делаем-с)

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/dto/InternshipDto.java
> +        InternshipStatus status,
@NotNull

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/dto/InternshipDto.java
> +        @NotNull Long projectId,
Везде, где указывается id, добавь @Positive сейчас у тебя можно передать отрицательный id

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +        return TeamMember.builder().id(teamMemberId).build();
TeamMember нужно не создавать, а получать из БД

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +    @Mapping(source = "mentorId", target = "mentorId", qualifiedByName = "mapTeamMemberToLong")
Можно заменить на @Mapping(source = "team_member.id", target = "mentorId") и попробовать, должно работать

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +public interface InternshipMapper {
Ниже есть замечание по teamMember, но так же ты забыл про маппинг project, который так же должен вытаскиваться из бд, комментарии относительно него такие же. Скорее всего эти поля нужно заигнорить при маппинге и в сервис добавить метод инициализации, который будет ходить в бд и сетить эти поля вручную, а потом уже возвращать полный entity объект

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +    public void createInternship(InternshipDto internshipDto) {
Замечание ко всем методам, каждый из них должен возвращать InternshipDto

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        internshipRepository.save(internshipMapper.toEntity(internshipDto));
Не смаппится, почему описал в маппере. + нет проверок на существование проекта, переданного в дто, нет проверки на существование пользователей, переданных в дто. Когда добавишь отдельный метод для маппинга, у тебя эти проверки реализуются сами собой, потому что будешь обращаться в бд

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/dto/InternshipDto.java
> +        @Past LocalDateTime startDate,
Начало стажировки в прошлом?

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        internshipRepository.save(internshipMapper.toEntity(internshipDto));
+ проверка, что юзер, переданный в качестве ментора, находится в команде в указанном проекте и обладает ролью ментор

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    public void earlyCompletionInternship(@RequestParam long internshipId, @RequestParam long teamMemberId) {
Можно передать отрицательное значение, @Positive выручит

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +public class InternshipController {
Все методы должны возвращать дто, сейчас пустое тело ответа

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +        return projectRepository.getProjectById(id).getStatus();
Если честно, выглядит как какие-то костыли, сделай отдельный метод получения project, а уже все статусы это валидация - ее можно вынести в валидатор

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +    public void setTeamMembersRoleNonIntern(List<Long> teamMemberIds) {
ты в 1 методе и идешь в бд за мемберами и меняешь им статусы, может кто-то скажет иное, но для меня выглядит странно + вынос 1 строки в метод ниже, читаемость прям падает

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        if (projectService.isProjectComplete(internshipDto.projectId())) {
В методе обновления, ты проверяешь, завершена ли стажировка или нет. Но у тебя нет метода, который позволяет статус стажировки менять (у тебя нет метода обновления стажировки)

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        removeTeamMembersFromInternship(internshipId, teamMemberId);
зачем здесь разбивка на 2 метода? У тебя все что делает dismissTeamMember, это вызывает другой метод, все

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        Internship internship = internshipRepository.findById(internshipId).orElse(null);
Зачем делать orElse(null), что само по себе bad practice, затем внизу делать if на проверку этого самого null и выкидывание исключения. Если можно просто указать orElseThrow()?

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +    public List<InternshipDto> getFilteredInternships(InternshipStatus internshipStatus) {
![image](https://github.com/user-attachments/assets/4850bbc6-c45b-4d1a-aec2-5711009c355a)
а фильтр по роли где?

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    public List<InternshipDto> getFilteredInternships(@RequestParam InternshipStatus internshipStatus) {
А как ты этот параметр получишь, если не ожидаешь его в строке запроса? + в задаче есть еще 1 фильтр, что, если передадут его? Да и объект из запроса как будто получить не получится

2024-11-20 14:59 UTC, SergeyZhitenev commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +    public void completeInternship(long internshipId, long teamMemberId) {
наверное нужно еще и саму стажировку завершить 
![image](https://github.com/user-attachments/assets/658744eb-8706-4253-9672-f187681086f7)

2024-11-28 08:53 UTC, YaKokin requested changes

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PutMapping("/{internshipId/change/{status}")
здесь скобочку забыл в мапинге. из-за этого код не компилится. большая просьба перед отправкой кода на ревью хотя бы запустить свой код и убедиться в том, что он компилируется.

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +@RequestMapping("/api/v1/internship")
давай ресурс назовем во множественном числе /api/v1/internships
чтобы соответствовать общему код стайлу принятому в команде

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +public class InternshipController {
Если делаешь версионирование, в название контроллер добавляй название версии. например InternshipV1Controller

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    public ResponseEntity<Long> createInternship(@Valid @RequestBody InternshipDto internshipDto) {
при создании ресурса мы обычно возвращаем клиенту только что созданный ресурс (а точнее информацию о нем)
Возвращать просто лонг такая себе идея. Если клиенту захочется получить какую-то доп информацию о ресурсе, который ты создал, ему придется делать повторный запрос на бэк и попросту гонять трафик. давай лучше создалим специальную дто для респонса InternshipResponseDto и положим туда поля, который будут полезны клиенту при получении ответа?

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    public ResponseEntity<Void> updateInternship(@Valid @RequestBody InternshipDto internshipDto) {
такое же замечание. здесь я хочу видеть дто респонса, которое несет в себе информацию об обновленной сущности

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    public ResponseEntity<Long> createInternship(@Valid @RequestBody InternshipDto internshipDto) {
давай не будем явно заворачивать в ResponseEntity и просто вернем значение напрямую. спринг сам автоматически завернет возвращаемое значение в ResponseEntity

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PutMapping
операцию обновлении существущего ресурса мы всегда применяем к конкретному ресурсу с конкретным id. исходя из твоего ендпоинта мне совсем не понятно, какой ресурс мы обновляем

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PostMapping("/{internshipId}/dismissal/{teamMemberId}")
хорошо спроектировал, молодец

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PostMapping("/{internshipId}/complete/{teamMemberId}")
и здесь, красавчик

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PostMapping("/{internshipId}/complete/{teamMemberId}")
хотя я бы поставил метод DELETE чтобы явно указать, что мы удаляем участника из ресурса intership

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PostMapping("/filter/{internshipFilterDto}")
зачем здесь PostMapping?
давай лучше GetMapping
мы все таки получаем ресурс.

зачем ты указываешь дто в пути ура? при этом в самом методе ты ожидаешь дто из тела. давай будем из тела получать дто.

и "filter" убери из ендпоинта. он избыточен

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @GetMapping
молодец

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @GetMapping("/{internshipId}")
отлично

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +    InternshipDto toDto(Internship entity);
указывай пожалуйста в нейминге в какое конкретное дто ты мапишь. если у тебя будет несколько Internship Dto
то не понятно будет в какую конкретно ты мапишь.
предлагаю пока написать toInternshipDto

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +    List<InternshipDto> toDtos(List<Internship> entities);
тут тоже поправь название

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        if (ChronoUnit.MONTHS.between(internshipDto.startDate(), internshipDto.endDate()) > 3) {
давай в отдельный метод вынесем валидацию, чтобы не городить

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +        return teamMemberService.getTeamMemberById(dto.mentorId());
маппер лучше делать тупым. зависимость от сервиса делает маппер менее гибким. его тяжелее использовать повторно. также ты нарушаешь принцип единой ответственности, потому что твой маппер помимо преобразования объектов еще и сервисом умеет работать.
тестировать такой код будет тяжелее, потому что нужно будет думать об инжекции сервиса.

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +        return projectService.getProjectById(dto.projectId());
аналогичное замечание

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +        return teamMemberService.getTeamMemberById(dto.mentorId());
лучше убрать получение сущностей по id в сервис

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +        return teamMemberService.getAllTeamMembersByIds(dto.internIds());
аналогично

2024-11-28 08:53 UTC, YaKokin commented on src/main/java/faang/school/projectservice/dto/InternshipDto.java
> +        @NotBlank String name,
я бы еще поле description добавил

2024-12-06 10:49 UTC, ipasynkov-epam commented on src/main/java/faang/school/projectservice/mapper/InternshipMapper.java
> +                                @Context TeamMemberService teamMemberService,
поясни, пожалуйста, зачем ты используешь здесь сервисы и аннотацию Context? Не уверен, что в маппинге нужны ссылки на сервисы

2024-12-06 10:49 UTC, ipasynkov-epam commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        Internship internship = internshipMapper.toEntity(internshipDto);
возможно стоит переименовать метод toEntity в маппере, чтобы понимать куда идет маппинг. Например, назвать его toInternship. Как думаешь?

2024-12-06 10:49 UTC, ipasynkov-epam commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        internship.setInterns(teamMemberService.getAllTeamMembersByIds(internshipDto.internIds()));
не нужно делать в вызове метода вызовы других методов - это трудно для дебага, для отслеживания ошибок и пр. 
это к строкам: 32, 33, 35

2024-12-06 10:49 UTC, ipasynkov-epam commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        return internshipMapper.toInternshipDtos(internshipRepository.findAll());
тут снова вложенные вызовы. Репозиторий на findAll всегда возвращает валидные для маппера значения?

2024-12-06 10:49 UTC, ipasynkov-epam commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        return internshipMapper.toInternshipDto(getInternshipById(internshipId));
переход в метод getInternshipById скорее всего лишний. Мы здесь точно так же можем сходить в репозиторий за Internship и потом сделать маппинг

2024-12-06 10:50 UTC, ipasynkov-epam commented
Есть вопросы по маппингу. +нужно решить мерж-конфликты

2024-12-09 13:18 UTC, ipasynkov-epam approved these changes

2024-12-09 13:18 UTC, ipasynkov-epam commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +        return internshipMapper.toInternshipDto(getInternshipById(internshipId));
Увидел, что он у тебя и в других методах тоже используется).

2024-12-09 13:20 UTC, ipasynkov-epam commented
Сейчас ПР идет в ветку, у которой в названии есть слово master. Такие мержи блокируются правилами. Поэтому, сделай, пожалуйста, ПР в другую ветку и я его смержу

2024-12-09 14:42 UTC, YaKokin approved these changes

2024-12-09 14:42 UTC, merged