Управление участниками команды
CorporationX/project_service pull request #839
Opened 2024-11-18 20:27 UTC by Macacin

Первый коммит по фиче с управлением участниками команды, контроллер, сервис и основная необходимая логика. Пока без тестов.

2024-11-19 10:31 UTC, YaKokin requested changes
Еще не досмотрел весь код. Скорее всего позже будут еще правки. Постараюсь в течение дня досмотреть. Пока что можешь исправлять то, что уже просмотрено.

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @PostMapping("/{creatorId}/members")
на мой взгляд не самое удачное проектирование ендпоинтов, потому что оно не очевидно идентифицирует ресурс. у тебя контроллер предоставляет ендпоинты для управления командой, в частности для добавления, удаления, получения участников (для этого мы инжектим TeamMemberService).

если я хочу добавить участника в проект, я хочу выбрать команду, в которую я хочу добавить участника. то есть фактически обратиться к ресурсу (в нашем случае это команда) и вызывать операцию добавления. это и должен отображать твой REST API.
api/v1/teams/{creatorId}/members здесь мне мало понятно, причем тут creatorId, если я обращаюсь к teams

гораздо очевиднее будет спроектировать ендпоинт вот так:
POST api/v1/teams/{teamId}/members
так сразу понятно, что я хочу обратиться к команде с id teamId, далее обратиться к участникам команды (members) и выполнить добавление/создание нового участника команды (POST)

а чтобы отслеживать юзера, который хочет выполнить это действие, мы можем хэдэрах класть его id и оттуда же вытаскивать его, чтобы проверить, имеет ли данный юзер право на выполнение конкретного действия.

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @PostMapping("/{updaterId}/members/{memberId}")
почему PoatMapping, а не PutMapping?
мы же обновляем. старайся продумывать, какой метод лучше использовать, чтобы клиенты твоего апи сходу понимали, что делает твой ендпоинт.

такое же замечание к проектированию структуры ендпоиндта, как и выше.

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @DeleteMapping("/{deleterId}/members/{memberId}")
здесь тоже. глядя на твой ендпоинт, я не понимаю, в какой команде я хочу удалить пользователя

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    public List<CreateTeamMemberDto> getFilteredTeamMembers(@RequestParam(required = false) String name,
молодец, что включил  фильтров в параметры запроса. так из урла сразу понятно, какие параметры фильтрации применяются к запросу

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @GetMapping("/{projectId}/members")
данный ендпоинт больше относится не к команде, а к проекту. видеть его в этом контроллере странно. давай вместо того, чтобы прямо следовать условию, подумаем, как бы это сделать грамотно?

мне в голову пришло два варианта:
1. можем сделать отдельный контроллер ProjectController и там сделаем ендпоинт, котоый будет отдавать всех участников проекта id которого мы передадим в урл с учетом параметров фильтров
будет выглядеть как-то так GET api/v1/projects/members?name = something&rolle=anything
так намного логичнее, тебе так не кажется?
2. более мудренный вариант. можем сделать ендпоинт в этом же контроллере, который в параметрах фильтрации будет получать еще и id проекта, участники которого нам нужны:
 /api/v1/members/?projectId=1&name="Nikola"&role="bossOfThisGym"
 
 мне больше нравится первый вариант.

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @GetMapping("/members")
этот ендпоинт не имеет отношения к командам. здесь мы просто хотим получить всех участников всех проектов всех команд (зачем правда).
я считаю, что он бесполезный. предлагаю осознанно подходить к решению задач, как разработчики.
поэтому давай просто его выпилим. он нам не пригодится. а если и понадобится в будущем, то вынесем его в контроллер TeamMembersController

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @GetMapping("/{teamId}/members")
отично, то, о чем я и говорил.

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    public UpdateTeamMemberDto updateTeamMember(@RequestBody @Valid UpdateTeamMemberDto teamMemberDto,
давай создадим ResponseTeamMemberDto, чтобы разграничивать логику ответа и обновления

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    public List<CreateTeamMemberDto> getAllTeamMembers() {
такое же замечание с ResponseDto. очень сильно режет глаз, когда ендпоинт для чтения данных возвращает дто для создания (это я уже не говорю, про потенциальную переиспользуемость и централизацию набора данных для ответа в одной дтошке, удобно же)

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/TeamMemberMapper.java
> +    TeamMember toCreateEntity(CreateTeamMemberDto createTeamMemberDto);
toCreateEntity? у нас их разве несколько? давай лучше просто toEntity

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/TeamMemberMapper.java
> +    TeamMember toUpdateEntity(UpdateTeamMemberDto updateTeamMemberDto);
аналогично

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/TeamMemberMapper.java
> +    List<TeamMember> toCreateEntityList(List<CreateTeamMemberDto> createTeamMemberDtos);
toEntityList

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/TeamMemberMapper.java
> +    List<TeamMember> toUpdateEntityList(List<UpdateTeamMemberDto> updateTeamMemberDtos);
toEntityList

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/TeamMemberMapper.java
> +    default List<Long> mapStageIds(List<Stage> stages) {
mapStageToIds тогда

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/TeamMemberMapper.java
> +    CreateTeamMemberDto toCreateDto(TeamMember teamMember);
давай тут отступ добавим, чтобы не сливалось

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/TeamMemberMapper.java
> +    UpdateTeamMemberDto toUpdateDto(TeamMember teamMember);
и тут отступ

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +        ensureHasAccess(creatorId, List.of(TeamRole.OWNER, TeamRole.TEAMLEAD), "add team member");
давай не будем хардкодить "add team member"
предлагаю создать enum с действиями, которые ты можешь производить над участниками проекта и передавать их в параметры метода сервиса. (там же для каждого enum укажешь строковое представление

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +            return teamMemberMapper.toCreateDto(teamMember);
если юзер уже есть в проекте, то ты достаешь его из базы и сетишь ему нужную роль, а потом хочешь вернуть его.
но возвращаешь ты не уже существующего участника, которого только что из базы вытащил, а участника, которого недавно из дто смапил. а ты его даже до конца не заполнил еще. это я уже не говорю про то, что у него даже id нет.

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +        teamMember.setTeam(team);
давай всю лоигку с 42 по 48 логику вынесем в отдельный метод createOrUpdateTeamMember
в нем ты будешь как раз таки проверять, если такой участник в проекте и если есть, то будешь менять ему роль и возвращать.
а если такого участника еще нет в проекте, то будешь формировать объект TeamMember также, как делаешь это сейчас и возвращать его.

так мы сделаем основной метод создания чистым и более читабельным. + тебе это тестировать проще будет (так как код будет модульным)

в основном же методе все что тебе нужно будет сделать - это получить TeamMember и сохранить его в базу и вернуть дто.

2024-11-19 10:31 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +        ensureHasAccess(creatorId, List.of(TeamRole.OWNER, TeamRole.TEAMLEAD), "add team member");
задумка хорошая так еще и читается легко, молодец

2024-11-19 11:58 UTC, Macacin commented on src/main/java/faang/school/projectservice/mapper/TeamMemberMapper.java
> +    List<TeamMember> toUpdateEntityList(List<UpdateTeamMemberDto> updateTeamMemberDtos);
короче если сделать такое же название toEntityList то идея подсвечивает что код не скомпилится из-за стирания типов, поэтому я оставил у одного метода старое название. Хз просто как это обходится, не смог нагуглить, если знаешь подсвети

2024-11-19 12:12 UTC, Macacin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @PostMapping("/{creatorId}/members")
вообще у меня в дтошке которая передается в метод есть поле teamId, и в сервисе оттуда берется инфа о том в какую команду положить мембера

2024-11-19 12:13 UTC, Macacin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @PostMapping("/{creatorId}/members")
как лучше поступить, все равно в эндпоинт передавать айдишник команды?

2024-11-19 18:43 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @PostMapping("/{creatorId}/members")
ты можешь просто не убрать teamId из ДТОшки, и передавать его чисто в урле

2024-11-19 18:47 UTC, YaKokin commented on src/main/java/faang/school/projectservice/mapper/TeamMemberMapper.java
> +    List<TeamMember> toUpdateEntityList(List<UpdateTeamMemberDto> updateTeamMemberDtos);
давай тогда назовем createDtosToEntities и updateDtosToEntities

2024-11-19 20:29 UTC, YaKokin requested changes

2024-11-19 20:29 UTC, YaKokin commented on src/main/java/faang/school/projectservice/exceptions/GlobalExceptionHandler.java
> +@ControllerAdvice
тут можем написать RestControllerAdvice, тогда не нужно будет каждый раз заворачивать ErrorResponse в ResponseEntity

2024-11-19 20:29 UTC, YaKokin commented on src/main/java/faang/school/projectservice/exceptions/GlobalExceptionHandler.java
> +    public ResponseEntity<ErrorResponse> handleResourceNotFoundException(ResourceNotFoundException ex) {
А тут тогда просто буем возвращать ErrorResponse и с помощью аннотации ResponseStatus будет указывать нужный код ответа

2024-11-21 08:05 UTC, YaKokin requested changes

2024-11-21 08:05 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @PostMapping("/{teamId}/members/add")
для чего add? Post и так говорит нам, что мы создаем ресурс. давай уберем add.

2024-11-21 08:05 UTC, YaKokin commented on src/main/java/faang/school/projectservice/dto/CreateTeamMemberDto.java
> +        Long id,
во время создания нового участника у нас точно не будет id на руках, так как он генерится на уровне БД. тогда нет смысла передавать id в дто для создания.

2024-11-21 08:07 UTC, YaKokin commented on src/main/java/faang/school/projectservice/dto/ResponseTeamMemberDto.java
> +        @NotBlank List<TeamRole> roles,
TeamRole это внутренняя сущность. внутренние сущности мы не передаем наружу. Давай создадим TeamRoleDto или же будем передавать строковое или целочисленное значение TeamRole

2024-11-21 08:08 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @PutMapping("/{teamId}/members/update")
такое же замечание. update в урле здесь не нужен. метод Put показывает, какое действие происходит

2024-11-21 08:16 UTC, YaKokin requested changes

2024-11-21 08:16 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    public ResponseTeamMemberDto updateTeamMember(@RequestBody @Valid UpdateTeamMemberDto teamMemberDto,
при обновлении ты хочешь обновить конкретный ресурс. по урлу, который ты предлагаешь, не понятно какой конкретный ресурс обновляется. давай после members добавим memberId чтобы было понятно, кого мы обновляем. а из UpdateTeamMemberDto тогда уберем id, потому что и так передаем его в урле.

2024-11-21 08:25 UTC, Macacin commented on src/main/java/faang/school/projectservice/dto/ResponseTeamMemberDto.java
> +        @NotBlank List<TeamRole> roles,
Это не сущность а enum класс в котором перечисляются роли

2024-11-21 09:31 UTC, Macacin commented on src/main/java/faang/school/projectservice/dto/ResponseTeamMemberDto.java
> +        @NotBlank List<TeamRole> roles,
<img width="705" alt="Снимок экрана 2024-11-21 в 12 31 11" src="https://github.com/user-attachments/assets/6c4dca00-0441-4a49-95de-f244d4f4536e">

2024-11-21 09:46 UTC, YaKokin requested changes
Остальное досмотрю чуть позже

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    @DeleteMapping("/{teamId}/members/delete/{memberId}")
Аналогично, delete убираем. вот здесь как раз таки хорош продумал с тем, чтобы передавать memberId в урле

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/dto/UpdateTeamMemberDto.java
> +        @Positive @NotNull Long userId,
зачем здесь передавать userId. В таске говорится, что мы хотим уметь обновлять никнейм участника, роли и позицию в команде. про связь между id участника и id юзера, который является этим участником речи никакой не шло. и если подумать логически, то обновлять эту связь довольно странно.

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/dto/UpdateTeamMemberDto.java
> +        List<TeamRole> roles,
Тут аналогично. TeamRole внешняя сущность. в дто не передаем

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/model/Team.java
> +    public void addTeamMember(TeamMember teamMember) {
молодец, что подумал об инкапсуляции!

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/model/TeamMemberActions.java
> +    ADD("adding a team member"),
я бы назвал ADD_MEMBER. просто ADD довольно абстрактно. не понятно, что конкретно участник может добавлять. а если я завтра добавлю такой enum только для действий над проектом? тогда у тебя ADD будут пересекаться и это будет тяжело читать.

 старайся давать такие названия, чтобы не человеку, который будет это читать не нужно было прыгать в файл, чтобы понять, что делает тот или иной метод или что обозначает конкретная константа перечисления. тогда твой код будет читаться намного проще

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/model/TeamMemberActions.java
> +    UPDATE("updating a team member"),
тут и в ремув аналогично

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/StageService.java
> +                .map(stageRepository::getById)
это не эффективный способ доставать Stage из репозитория. здесь для каждого id отдельно ходишь в базу. а если у тебя таких id будет много? также будешь бомбить базу запросами для каждого id?
эффективнее будет сделать один запрос к базе, в который ты передашь список адйишников, которые тебя интересуют и база одним ответом вернет тебе их.
для этого в репозитории можно создать метод findAllByIdIn, как-то так (потыкаешься если что, там выпадашка тебе подскажет). в него просто передашь список айди и в ответ получишь свои stageы

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +        TeamMember teamMember = teamMemberMapper.toEntity(teamMemberDto);
на мой взгляд этот мапинг лучше также вынести в метод createTeamMember. идея была в том, чтобы полностью скрыть то, как решается кейсы когда юзер уже есть в команде или когда его добавляют в первый раз. это делается для улучшения читабельности и прозрачности кода. мапинг в данном случае - это тоже часть создания юзера, поэтому его лучше вынести.

и если мы мапинг будем выносить в отдельный метод, то тогда в него стоит передавать дтошку, а не сущность.

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +    private TeamMember createTeamMember(TeamMember teamMember, Team team, Project project) {
сам метод я бы назвал createOrChangeRolesTeamMember или createOrUpdateRolesTeamMember
такое название лучше описывает действие твоего метода + человеку, который будет читать твой код сразу понятно, что ты учел этот кейс.

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +        team.addTeamMember(teamMember);
молодец, что подумал об этой связи

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +        teamService.saveTeam(team);
зачем здесь вызывать saveTeam. у тебя навешана аннотация @Transactional. если ты вытягиваешь сущность из базы, то она отслеживается сессией Hibernate и находится в состоянии persistance. если ты производишь над такой сущностью какие-либо изменения а затем закрываешь транзакцию, Hibernate автоматически учитывает все изменения, произведенные с persistance сущностями и вносит эти изменения в базу без явного сохранения.

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +        long updaterId = userContext.getUserId();
отлично

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +            return requiredRoles.stream().anyMatch(role -> teamMember.getRoles().contains(role));
teamMember.getRoles().contains(role) вот это очень тяжело читается, особенно, с цепочкой стримов в одну строку.
лучше сделай отдельный метод, котоый будет проверять содержится ли определенная роль и конкретного участника. можешь этот метод вынести прямо в сущность TeamMember у нее дергать его (логично, что каждый участник знает, какие у него роли есть, а каких нет)
так будет куда читабельнее, плюс мы соблюдаем инкапсуляцию

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +        return teamMemberRepository.findByUserIdAndProjectId(userId, projectId) != null;
если метод потенциально может вернуть null, то лучше завернуть его результат в Optional. так ты дашь понять пользователям своего метода, что может быть null и они должны этот кейс обработать.

если возвращать optional то тебе достаточно будет вызвать у результата метод isPresent()

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +                    String.format("Team member with user ID %d does not exist", userId)
молодец, учел замечания с конкатенацией. правда можно сделать читабельнее. в ResourceNotFoundException есть специальный конструктор, который принимает имя ресурса, имя поля, и значение поля по которому не был найден ресурс. давай его заюзаем и не будем городить с String.format

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +                        .anyMatch(teamMember -> teamMember.getId().equals(memberId))
не читабельно. создай лучше в классе сущности метод isSameTeamMember и в нем уже проверяй равны ли айдишники

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +        if (updater.getRoles().contains(TeamRole.TEAMLEAD)) {
здесь ты проверяешь есть у юзера требуемая роль, для того, чтобы выполнить обновление ролей и позиции. метод для этого у тебя уже есть. давай просто переделаем его так, чтобы можно было его переиспользовать для этой ситуации

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +            if (teamMemberDto.roles() != null) {
давай вынесем вот этот if в метод updateRolseIfPresent

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +            if (teamMemberDto.stageIds() != null) {
аналогично - updateStagesIfPresent

2024-11-21 09:46 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +            UserDto user = userServiceClient.getUser(updaterId);
updateMemberSelf - здесь мы обновляем все поля, которые юзер может обновить самостоятельно, если они ему принадлежат (имя, фото аватара, био и тд)

2024-11-21 09:49 UTC, YaKokin commented on src/main/java/faang/school/projectservice/dto/ResponseTeamMemberDto.java
> +        @NotBlank List<TeamRole> roles,
ок, тогда оставляем

2024-11-21 09:52 UTC, Macacin commented on src/main/java/faang/school/projectservice/model/Team.java
> +    public void addTeamMember(TeamMember teamMember) {
ну вот я пока тестил оказалось что зря подумал, там список в сущности неизменяемый, пришлось лезть в репу добавлять методы

2024-11-21 09:57 UTC, Macacin commented on src/main/java/faang/school/projectservice/dto/UpdateTeamMemberDto.java
> +        @Positive @NotNull Long userId,
так там в таске написано, что никнейм может менять только юзер сам себе (тот который сделал запрос), мне иначе никак не проверить, в сервисе что запрос делается от этого же пользователя

2024-11-21 10:42 UTC, Macacin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +                    String.format("Team member with user ID %d does not exist", userId)
я там пока ты проверял поменял в коде на EntityNotFoundException, мне показалось это тут уместнее

2024-11-21 12:17 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +        if (updaterId == teamMember.getUserId()) {
вот эту проверку я бы вынес в обычный if на 62 строчке

2024-11-21 12:28 UTC, YaKokin commented on src/main/java/faang/school/projectservice/controller/TeamV1Controller.java
> +    public ResponseTeamMemberDto updateTeamMember(@RequestBody @Valid UpdateTeamMemberDto teamMemberDto,
поправить дто для обновления

2024-11-21 12:33 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +        List<Long> userIds = teams.stream()
подумай, как можно вынести в отдельный метод

2024-11-21 12:34 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +                            .filter(u -> u.getId().equals(member.getId()))
проверку вынеси в отдельный метод сущности

2024-11-21 12:35 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +                .filter(member -> {
весь фильтр тоже лучше вынести в отдельный метод с понятным названием, которое будет говорить о том, что мы проверяем в фильтре

2024-11-21 12:36 UTC, YaKokin commented on src/main/java/faang/school/projectservice/service/TeamMemberService.java
> +                    return user.getUsername().contains(name) && member.getRoles().contains(role);
подумай, как можно упростить это выражение для чтения

2024-11-21 18:52 UTC, YaKokin approved these changes

2024-11-21 18:52 UTC, merged