BJS2-40659
CorporationX/project_service pull request #844
Opened 2024-11-19 18:57 UTC by davidx5x5

2024-11-22 18:51 UTC, evgen-backend-rostov commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    @PostMapping("/update")
Если делать по концепции REST, то лучше использовать @PutMapping

Чтобы обновить вакансию, тебе в эндпоинте нужно получить id и передать его в сервис через @PathVariable

2024-11-22 18:56 UTC, davidx5x5 commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    @PostMapping("/update")
Спасибо, действительно нужно исправить;)

2024-11-22 21:10 UTC, jibulani requested changes
в целом ок, но есть несколько замечаний для исправления

2024-11-22 21:10 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    @PostMapping("/create")
/create, /update и /delete можно не писать, за это отвечают сами типы методов (POST, PUT, DELETE)

2024-11-22 21:10 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    @PostMapping("/filter")
тут и ниже должны быть `@GetMapping`, потому что для получения данных используются GET-запросы

2024-11-22 21:10 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    public VacancyDto getVacancyForId(@RequestBody VacancyDto vacancyDto) {
логичнее назвать getVacancyById и передать id через `@PathVariable`, а не передавать весь VacancyDto в тело запроса

2024-11-22 21:10 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/impl/vacancy/VacancyServiceImpl.java
> +    private void validationCreatedcontainedInTeam(Project project, VacancyDto vacancyDto) {
методы должны называться как действие, лучше используй слово validate
и почему-то не все слова в camelCase написаны тут и в следующем методе

2024-11-22 21:10 UTC, jibulani commented on src/test/java/faang/school/projectservice/service/impl/vacancy/VacancyServiceImplTest.java
> +        verify(vacancyRepository, times(1)).deleteById(2L);
в остальных тестах тоже можно добавить подобные проверки

2024-11-22 21:10 UTC, jibulani commented on src/test/java/faang/school/projectservice/service/impl/vacancy/VacancyServiceImplTest.java
> +public class VacancyServiceImplTest {
еще не помешают тесты на негативные сценарии

2024-11-23 11:14 UTC, davidx5x5 commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    @PostMapping("/filter")
спасибо исправил

2024-11-24 20:53 UTC, jibulani requested changes
все хорошо, есть только пара небольших замечаний и вопрос

2024-11-24 20:53 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    public VacancyDto create(@RequestBody VacancyDto vacancyDto) {
чтобы валидация полей дто сработала, нужна еще аннотация `@Validated`

2024-11-24 20:53 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/impl/vacancy/VacancyServiceImpl.java
> +        if (!vacancyRepository.existsById(vacancyDto.getId())) {
зачем нужен этот if? ты же выше удаляешь всегда вакансию по этому id, то есть тут внутри if всегда будет true
или может какая-то другая логика подразумевалась и я что-то не понял?

2024-11-24 20:53 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/impl/vacancy/VacancyServiceImpl.java
> +        if (!isCreatedcontainedInTeam) {
не все слова в camelCase

2024-11-25 18:22 UTC, davidx5x5 commented on src/main/java/faang/school/projectservice/service/impl/vacancy/VacancyServiceImpl.java
> +        if (!vacancyRepository.existsById(vacancyDto.getId())) {
это действительно было излишне)))

2024-11-25 18:22 UTC, davidx5x5 commented on src/main/java/faang/school/projectservice/service/impl/vacancy/VacancyServiceImpl.java
> +        if (!isCreatedcontainedInTeam) {
ок переделал

2024-11-25 18:23 UTC, davidx5x5 commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    public VacancyDto create(@RequestBody VacancyDto vacancyDto) {
ок

2024-11-25 21:16 UTC, jibulani requested changes
еще чуть-чуть и смержим!

2024-11-25 21:16 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +@RestController
`@Component` и `@RestController` не надо одновременно использовать

2024-11-25 21:16 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    public VacancyDto updateVacancy(@RequestBody VacancyDto vacancyDto) {
тут и в остальных местах, где есть `@RequestBody` тоже должна быть аннотация `@Validated`

2024-11-25 21:16 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/filter/Filter.java
> +@Component
здесь не нужна аннотация, это же просто интерфейс

2024-11-25 21:19 UTC, davidx5x5 commented on src/main/java/faang/school/projectservice/service/filter/Filter.java
> +@Component
))) исправил

2024-11-25 21:20 UTC, davidx5x5 commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +@RestController
спасибо учту, думал нужно вместе

2024-11-25 21:21 UTC, davidx5x5 commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    public VacancyDto updateVacancy(@RequestBody VacancyDto vacancyDto) {
ок

2024-11-26 16:08 UTC, jibulani approved these changes
супер, в прод!

2024-11-26 16:09 UTC, merged