Feature/bjs2 40676 Этапы проекта
CorporationX/project_service pull request #848
Opened 2024-11-20 11:07 UTC by bozhedar

2024-11-20 13:01 UTC, aplavina requested changes

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +            log.error("Пустое название");
Вместо этого, в StageDto можно также как и в StageInvitationDto навесить аннотаций для валидации

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +        validate(stage);
Если указать правила первичной валидации с помощью аннотации в дтошке, то можно не вызывать этот метод, просто добавить аннотацию @Valid:
public StageDto create(@RequestBody @Valid StageDto stage){
    ...
}

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/dto/invitation/StageInvitationDto.java
> +    private StageInvitationStatus status; // получаем только на возврате
Комментариев в коде лучше чтобы не было

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +        return stageService.getAllStages(stage);
Если здесь передается тело запроса, то лучше поменять метод на post, не смотря на то, что тут идет получение данных

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/dto/stage/StageDto.java
> +    private Long projectId;
Можно message добавить как это сделано в StageInvitationDto

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        validateExisting(projectId);
Почему тут public?

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        List<Long> IdsTasksToDelete = stage.getTasks().stream().map(Task::getId).toList();
Название переменной с большой буквы

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/service/StageService.java
> +                .stream().filter(t -> !IdsTasksToDelete.contains(t.getId())).toList();
Лучше t поменять на task

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/service/StageService.java
> +                .filter(s -> !s.getStageId().equals(stageDto.getStageId())).toList();
Тут тоже s можно переименовать

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        return stageDto;
Не надо еще удалить сам stage?

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        return stageMapper.toDto(stageRepository.save(postponeStage));
У Task есть поле stage, видимо нужно переносимым такскам поставить в это поле новый stage куда их переносим
https://github.com/CorporationX/project_service/blob/Medusa-master-stream7/src/main/java/faang/school/projectservice/model/Task.java

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        deleteCascade(stageDto);
deleteCascade у тебя удаляет такси каскадно и из проекта тоже, но ведь мы их не удаляем из проекта, мы их просто в другой stage переносим

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +        return stageService.getAllStages(stage);
В задании написано получить все этапы проекта, думаю имеется ввиду что этот метод получает этапы по id проекта, а не по этапу

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        if (!projectService.existsById(projectId)){
Вроде эти методы нигде больше не используются, надо бы сделать private и вообще эта логика относится к самим проектам, а не к стадиям, но ты делаешь эти публичные методы для работы с проектами в StageService

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        Project project = projectService.getById(stageDto.getProjectId());
Если этот метод будет искать этапы по id проекта, то тут не придется его вытаскивать из stageDto, он будет параметром метода

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        Map<TeamRole, Integer> neededRolesMap = getNeededRolesMap(dtoRoles, dtoRolesOrig);
Тоже public

2024-11-20 13:01 UTC, flornana commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        Map<TeamRole, Integer> rolesMap = dtoRoles.stream()
И тут public

2024-11-20 13:01 UTC, aplavina commented on src/main/java/faang/school/projectservice/service/project/ProjectService.java
> +        projectRepository.save(project);
В ProjectService есть метод create для создания проекта, если нужно делать какие-то обновления в проекте, лучше добавить метод update с правильной логикой обновления, а так получается что это просто обертка над методом save у ProjectRepository

2024-11-21 08:19 UTC, bozhedar commented on src/main/java/faang/school/projectservice/dto/stage/StageDto.java
> +    private Long projectId;
не уверен что по смыслу подходит

2024-11-21 08:26 UTC, bozhedar commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        return stageDto;
решил прям из базы его не удалять, потому что обсуждали что в базе обычно ничего не затирается, по этому просто устанавливаю проекту этапы без ненужного этапа

2024-11-21 08:36 UTC, bozhedar commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +        return stageService.getAllStages(stage);
почему лучше менять на Post?
Ну да проще просто id передать, поправлю

2024-11-21 08:40 UTC, bozhedar commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        if (!projectService.existsById(projectId)){
в задаче сказано что этап строго привязан к проекту, по этому решил сделать валидацию для проекта

2024-11-21 08:42 UTC, bozhedar commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +            log.error("Пустое название");
над  StageInvitationDto работал Данияр, я просто скопировал

2024-11-21 09:28 UTC, bozhedar commented on src/main/java/faang/school/projectservice/service/StageService.java
> +        validateExisting(projectId);
сделал их паблик чтобы было проще тестировать, думаю ничего страшного не произойдет если оставлю их такими потому что придется заново тесты переделывать с учетом аннотаций валидации и прочего при том что и так слишком много времени на эту задачу потратил и хочется уже наконец-то перейти к другим задачам, попробую в другой задаче использовать @Validate

2024-11-21 14:49 UTC, aplavina commented on src/main/java/faang/school/projectservice/controller/StageController.java
> +        return stageService.getAllStages(stage);
> почему лучше менять на Post? Ну да проще просто id передать, поправлю

Просто хорошая практика

2024-11-21 14:57 UTC, aplavina approved these changes

2024-11-25 15:41 UTC, MiraGlaceon approved these changes

2024-11-26 06:22 UTC, merged