feat: функционал задачи управление календарем
CorporationX/project_service pull request #852
Opened 2024-11-20 13:01 UTC by SergeyZhitenev

2024-11-20 15:59 UTC, The-Naku requested changes

2024-11-20 15:59 UTC, The-Naku commented on src/main/java/faang/school/projectservice/filter/meetFilters/DateFilter.java
> +        return requests.filter(meet -> meet.getCreatedAt().toLocalDate().equals(ld));
meet.getCreatedAt().toLocalDate().equals(ld)  нарушает инкапсуляцию.
куда элегантнее будет добавить в Meet  метод isSameCreated и передавать ему дату

2024-11-20 15:59 UTC, The-Naku commented on src/main/java/faang/school/projectservice/filter/meetFilters/MeetFilter.java
> +
реализации этого интерфейса лучше выносить в пакет impl

2024-11-20 15:59 UTC, The-Naku commented on src/main/java/faang/school/projectservice/dto/meet/UpdateMeetDto.java
> +public record UpdateMeetDto(
а если при обновлении пользователь не хочет изменить какие то поля, а например только название или только описание? Мы получается его ограничиваем заставляя прописывать изменения для каждого поля, а если он не хочет меня поля, которые уже сущетсвуют и не изменяет их, то зачем нам передавать их в запросе и обьемом данных уменьшать трафик

2024-11-20 15:59 UTC, The-Naku commented on src/main/java/faang/school/projectservice/service/MeetService.java
> +        meet.setTitle(updateMeetDto.title());
к комменту из updateDto о том, что пользователь не обязан изменять каждое поле. 
Также в библиотеке mapStruct есть удобный метод update, чтобы не городить сеттеры , который поддерживает частичное обновление

2024-11-20 15:59 UTC, The-Naku commented on src/main/java/faang/school/projectservice/validator/MeetValidator.java
> +        long requesterId = Long.parseLong(request.getHeader("x-user-id"));
в лекции про feign client на  платформе есть про userContext, у которого есть метод getUserId, который позволяет нам получить id пользователя из хедера запроса и не нужно будет передавать в контроллер обьект с данными самого запроса и самому вытаскивать значение хедера, ибо эта функция у нас уже реализована в проекте. Ты молодец, что разобрался как это делать, однако думаю не стоит расширять кодовую база кодом с одинаковой функциональностью  

и твоя валидация относится к бизнес логике скорее  и логичнее ее все же оставить в сервисе, мне кажется 
это относится и к методам ниже

2024-11-20 15:59 UTC, The-Naku commented on src/main/java/faang/school/projectservice/service/MeetService.java
> +        meet.getUserIds().remove(userId);
также тут нарушается инкапсуляция , было бы элегантнее создать метод с говорящим названием  в сущности по удалению участника из списка участников и вызывать его

2024-11-20 15:59 UTC, The-Naku commented on src/main/java/faang/school/projectservice/service/MeetService.java
> +    public List<MeetDto> getMeets(HttpServletRequest request) {
как будто возможно лучше было бы создать дто с полями всех фильтров и получать эти фильтры из тела запроса от клиента, было бы нагляднее какие и сколько фильтров у нас вообще есть
Также есть вероятность, что кол-во фильтров может сильно увеличится и их клиент  захочет применить все одновременно и тогда URL может очень сильно разрастись 

Это мои мысли на этот счет, и возможно твой вариант тоже хорош
Интересно уточнить у Ильи на этот счет

2024-11-21 12:30 UTC, The-Naku commented on src/main/java/faang/school/projectservice/controller/MeetController.java
> +    public MeetDto create(@Validated @RequestBody MeetDto meetDto) {
почитай о том как правильно проектировать ендпоинты  по ресту. слов действий (за редким исключением) не должно быть в URI. когда у тебя приходит запрос с post или delete не нужно указывать, что это происходит в URI так как у нас запрос приходит с конкретным типом действия. 
путь должен обозначать ресурс, а не действие. действие должно быть выражено через http методы

2024-11-27 13:23 UTC, ipasynkov-epam approved these changes

2024-11-27 13:26 UTC, ipasynkov-epam commented
![image](https://github.com/user-attachments/assets/f147f4af-6148-4d18-94ca-338d854b7431)
Сейчас нужно создать ПР в другую ветку, в мастер мержить не получится)

2024-11-28 16:10 UTC, ipasynkov-epam approved these changes

2024-11-28 16:10 UTC, merged