Этапы проекта BJS2 40686
CorporationX/project_service pull request #857
Opened 2024-11-21 09:07 UTC by lomuserg

2024-11-24 18:58 UTC, lomuserg commented
Вроде все методы протестировал, но 0.5 покрытия пишет.

2024-11-26 19:09 UTC, MiraGlaceon requested changes

2024-11-26 19:09 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/stage/StageController.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
Давай вынесем хэндлер в RestControllerAdvice класс

2024-11-29 17:02 UTC, MiraGlaceon approved these changes

2024-11-29 17:13 UTC, merged