Feature bjs2 41017
CorporationX/project_service pull request #860
Opened 2024-11-21 15:26 UTC by Memoreks

2024-11-22 00:38 UTC, abdddev submitted a review, later dismissed
Все гуд и четко

2024-11-22 00:48 UTC, abdddev commented
MethodArgumentNotValidException кстати его не нашел из задания)

2024-11-22 03:48 UTC, Memoreks commented
> MethodArgumentNotValidException

@abdddev я взял все исключения из проекта, которые на данный момент созданы
Думал MethodArgumentNotValidException дан просто для примера)
Добавлю его)

2024-11-22 18:42 UTC, VovaBuzivskyi commented
Много поправил и GlobalExceptionHendler хорошо сделан, молодец!

2024-11-22 18:43 UTC, VovaBuzivskyi submitted a review, later dismissed

2024-11-24 11:41 UTC, BobrAll requested changes
В классах хорошо, что поубирал _, но в пакетах их бы наоборот оставить

2024-11-27 16:09 UTC, BobrAll approved these changes
Отлично)

2024-11-27 16:09 UTC, merged