BJS2-40649 реализация работы со стажировками
CorporationX/project_service pull request #864
Opened 2024-11-22 18:09 UTC by evgen-backend-rostov

2024-11-24 11:11 UTC, AlexLogino reviewed
Осилил только контроллер и немного сервисов

2024-11-24 11:11 UTC, AlexLogino commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +                internshipDto.status() != InternshipStatusDto.COMPLETED
internshipDto.status() 3 раза используется в методе.
думаю, имеет смысл вынести в переменную его

тоже самое с методами выше (внутри validateInternshipDtoBasic()),
ну или у Жени спросить этот момент

2024-11-24 11:11 UTC, AlexLogino commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +        return internshipService.getInternshipById(Long.valueOf(id)).orElse(null);
чтобы убрать Long.valueOf() можно в параметре метода тип Long поставить

2024-11-24 11:11 UTC, AlexLogino commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    }
базовой валидации нет здесь и в getInternshipById()

2024-11-24 11:11 UTC, AlexLogino commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +public interface InternshipService {
зачем для каждого сервиса свой интерфейс? не помню, чтоб такое в лекциях где-то было

2024-11-24 11:11 UTC, AlexLogino commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +    @PostMapping("/get")
мжт назвать просто "/filter"

2024-11-24 11:39 UTC, evgen-backend-rostov commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +                internshipDto.status() != InternshipStatusDto.COMPLETED
Сама конструкция "internshipDto.status()" не очень длинная, решил не выносить.

@jibulani, подскажи пожалуйста этот момент)

2024-11-24 11:46 UTC, evgen-backend-rostov commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +        return internshipService.getInternshipById(Long.valueOf(id)).orElse(null);
На проекте были косяки со слишком большими числами: javaScript стандартными средствами не умеет обрабатывать значения типа Long и при больших значениях он их округлял, тем самым передавая на бэк несуществующий айдишник. В итоге решили, что фронт передаёт все значения в String, а бэк уже самостоятельно приводит их к нужному формату

2024-11-24 12:28 UTC, evgen-backend-rostov commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +public interface InternshipService {
Да, в наших лекциях я тоже такого не помню. Увидел такую реализацию у Стаса в коде и вспомнил, что на предыдущем обучении эту тему затрагивали.

Если я правильно понимаю, суть такая: есть класс, который работает с базой данных postgresql. И каждый сервис, который использует этот класс жёстко связан с этим классом и с его реализацией. Т.е, если нам нужно будет заменить в проекте базу данных, то нам не просто нужно будет создать новый класс, но и сменить по всему коду старый класс на новый.

А если использовать интерфейс, то такой жёсткой привязки нет, и нам нужно только заменить реализацию с одной на другую, не трогая при этом классы, которые этот интерфейс используют. 

Может не очень корректно объяснил, но на ближайшем созвоне можно будет обсудить

2024-11-24 20:12 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/InternshipController.java
> +                internshipDto.status() != InternshipStatusDto.COMPLETED
согласен, что лучше вынести в переменную и уже ее везде использовать

2024-11-24 20:44 UTC, jibulani requested changes
есть несколько замечаний, а в целом хорошо

2024-11-24 20:44 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/InternshipService.java
> +public interface InternshipService {
есть несколько причин выделять отдельно сервис, например:
1) соблюдаем D из SOLID - dependency inversion - с наличием интерфейса можем делать зависимости от абстракции, а не от реализации
2) если вдруг все-таки понадобится иметь несколько реализаций, то с готовым интерфейсом это проще сделать
3) при наличии интерфейса спринг скорее всего будет использовать dynamic proxy для работы всяких штук типа @Transactional, а это немного производительнее, чем cglib

2024-11-24 20:44 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceImpl.java
> +    private void doCompleteLogic(InternshipDto internshipDto) {
по названию метода непонятно, что именно он делает

2024-11-24 20:44 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceImpl.java
> +                    // корректно ли такое сравнение энама?
enum можно просто через == сравнивать, обычно так и делают

2024-11-24 20:44 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceImpl.java
> +                TeamRole role = TeamRole.valueOf(internshipDto.role().name());
лучше внутри RoleDto определить метод, позволяющий из RoleDto получить TeamRole

2024-11-24 20:44 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceImpl.java
> +                // пришлось костылить и создавать в тестах мутабельные листы, чтобы можно было добавить в него значение
лучше отрефакторить код, чтобы отдельно создать список ролей и уже один раз его засетить и сохранить, а тут у тебя куча перезаписей получится, это неоптимально, так как будет увеличена нагрузка на БД

2024-11-24 20:44 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceImpl.java
> +                // как-то в принципе мои манипуляции с сущностями кажутся мне сомнительными, нужен взгляд со стороны
ну да, такая же история, как и в if, надо подумать над рефакторингом

2024-11-24 20:44 UTC, jibulani commented on src/main/java/faang/school/projectservice/validator/InternshipServiceValidator.java
> +            throw new DataValidationException("Duration of internship more than 3 month");
лучше не хардкодить жестко 3 month, а брать значение из переменной maxInternshipDuration, вдруг оно изменится, соответственно и срок другой будет проверяться, а в ошибке по прежнему останутся 3 месяца

2024-11-24 20:44 UTC, jibulani commented on src/main/java/faang/school/projectservice/validator/InternshipServiceValidator.java
> +                // насколько корректна такая конструкция?
если хотел проверить, что список состоит только из уникальных элементов, можно было сравнить, что размер сета и исходного списка совпадают

2024-11-24 20:44 UTC, jibulani commented on src/test/java/faang/school/projectservice/service/internship/InternshipServiceImplTest.java
> +
нужны тесты еще на другие методы сервиса и на негативные сценарии

2024-11-25 20:25 UTC, evgen-backend-rostov commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceImpl.java
> +                // пришлось костылить и создавать в тестах мутабельные листы, чтобы можно было добавить в него значение
Оставил код практически без изменений. Ещё раз перепроверил, всё правильно работает:
* я беру сущность пользователя
* достаю из неё список ролей
* внутри программы добавляю к этому списку новую роль
* в сущности пользователя заменяю старый список на новый 
* и только теперь обновляю в базе пользователя с новым списком ролей

В плане оптимизации можно было бы сначала создать список из уже изменённых пользователей, и одним общим списком сохранить их в базу, но в репозитории метода типа saveAll нету

2024-11-25 21:05 UTC, evgen-backend-rostov commented on src/main/java/faang/school/projectservice/service/internship/InternshipServiceImpl.java
> +                // как-то в принципе мои манипуляции с сущностями кажутся мне сомнительными, нужен взгляд со стороны
Подумал, но может не совсем в нужную сторону. Раньше я доставал из сужности поля и пытался менять их. Теперь я делаю копию этого поля, работаю с ней без проблем, обновляю данные этого поля в сущности и обновлённую сущность сохраняю в базу данных.

Если я правильно понимаю, из-за того, что в базе нет отдельных методов для обновления конкретных полей одной сущности, приходится выполнять кучу манипуляций с обновлением сущности в самом сервисе и только потом сетить сущность в базу.

Надеюсь не сильно замудрённо написал, потому что уже рубит спать и пишу на последнем запасе сознания 😵

2024-11-26 21:06 UTC, evgen-backend-rostov commented on src/main/java/faang/school/projectservice/validator/InternshipServiceValidator.java
> +            throw new DataValidationException("Duration of internship more than 3 month");
Эти даты кучу времени сожрали: я и в Period пытался их конвертить, искал подходящий метов в Duration. В итоге с делал в тупую. Если так тоже не подходит, облегчи мою судьбу пожалуйста, просто напиши, как это должно быть)

2024-11-26 21:09 UTC, evgen-backend-rostov commented on src/main/java/faang/school/projectservice/validator/InternshipServiceValidator.java
> +                // насколько корректна такая конструкция?
Это же метод update. По идее, туда можно запихнуть юзеров, которых нет в стажировке. Мне нужно проверить, что айдишники именно по значениям совпадают

2024-11-26 21:15 UTC, evgen-backend-rostov commented on src/test/java/faang/school/projectservice/service/internship/InternshipServiceImplTest.java
> +
Жень, уточни пожалуйста, насколько это критично? Времени катастрофически не хватает, хочется успеть как можно больше разнообразных тем на практике попробовать. С тестами на базовом уровне понимание есть, остаётся только механическая работа по их написанию.

Буду благодарен, если на данных момент можно их пропустить, и дописать, если в этом будет необходимость

2024-11-26 21:42 UTC, jibulani commented on src/test/java/faang/school/projectservice/service/internship/InternshipServiceImplTest.java
> +
понял, хорошо, главное, чтобы было понимание, как и какие сценарии можно протестировать

2024-11-26 21:48 UTC, jibulani commented on src/main/java/faang/school/projectservice/validator/InternshipServiceValidator.java
> +            throw new DataValidationException("Duration of internship more than 3 month");
имел в виду кидать ошибку не с захардкоженным текстом "Duration of internship more than 3 month"
а с текстом вида "Duration of internship more than " + maxInternshipDuration.toDays() + " days"
вижу, что ты что-то подобное и сделал :)

2024-11-26 21:51 UTC, jibulani approved these changes
отлично!

2024-11-26 21:52 UTC, merged

2024-11-27 13:49 UTC, evgen-backend-rostov commented on src/test/java/faang/school/projectservice/service/internship/InternshipServiceImplTest.java
> +
Благодарю за понимание)