Валидация в сервисе Проектов BJS2-40980
CorporationX/project_service pull request #881
Opened 2024-11-25 09:11 UTC by lomuserg

2024-11-25 19:58 UTC, m1rroxxx reviewed
на мой взгляд min(0) вообще бесполезная штука в нашем случает, потому что мы всегда проверяем в базе на сущесвование
остальное написал в комментах

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
>          return projectService.updateProject(projectDto);
вроде как так не будет валидироваться

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/dto/ProjectDto.java
> +    @Min(value = 0, message = "Id must be non-negative")
на id не надо ставить notnull, у нас не зайдёт в контроллер dto при создании (когда создаем id еще не сущесвует)

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/dto/ProjectDto.java
> +    @NotBlank(message = "Description must not be blank")
не ошибка, но возможно проект можно сделать и без описания, как будто оно не обязательно

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/dto/ProjectDto.java
> +    @Min(value = 0, message = "ParentProjectId must be non-negative")
в целом тоже не ошибка, но эти айдишки и так проверятся на существование в базе, а там они не могут быть меньше нуля

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/dto/ProjectDto.java
>      private String coverImageId;
а тут немного не понял зачем, это же строка, она выглядит примерно вот так
http://localhost:9000/projectbucket/25FE675DCF0C8E50C011A95A08EBDB0E84EA0134A7CF6B5890D39D3910F0C00A

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/dto/ProjectFilterDto.java
>  }
в фильтрах поля могут быть null, если пользователь не захочет ничего фильтровать

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/dto/ProjectFilterDto.java
>  }
или захочет отфильтровать только по одному, валидацию не пройдёт и он получит ошибку

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/dto/UserDto.java
> +    @Min(value = 0, message = "Id must be non-negative")
опять на id notNull не нужен

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/dto/VacancyFilterDto.java
>      private Long projectId;
опять фильтры могут быть null

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/dto/VacancyDto.java
> +    @Min(value = 0, message = "Id must be non-negative")
id можт быть null

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/controller/ProjectController.java
> +    public ProjectDto getProjectById(@NotNull @Min(0) @PathVariable long id) {
не уверен что сюда надо ставитмь nutNull, по умолчанию параметр обязателен, если его не будет конроллер выбросит исключение

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/controller/sub_project/SubProjectController.java
> +                                           @RequestBody ProjectFilterDto projectFilterDto) {
тоже не уверен что надо сатвить notNull

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/controller/sub_project/SubProjectController.java
> +                                           @RequestBody ProjectFilterDto projectFilterDto) {
ещё не уверен что @Min(0) вообще нужно, каждое значение и так провериться в базе на существование, + ты это лублируешь в dto и в контроллере

2024-11-25 19:58 UTC, m1rroxxx commented on src/main/java/faang/school/projectservice/controller/vacancy/VacancyController.java
> +    public VacancyDto getVacancy(@NotNull @Min(0) @PathVariable Long vacancyId) {
тоже не уверен что нужно @NotNull @Min(0)

2024-11-28 10:41 UTC, lomuserg commented on src/main/java/faang/school/projectservice/dto/ProjectDto.java
>      private String coverImageId;
увидел Id не увидел тип данных)

2024-11-29 17:06 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/dto/ProjectDto.java
> +    @Min(value = 0, message = "Id must be non-negative")
Надо уточнить, что именно на dto не нужно вешать над id аннотацию NotNull. В целом в dto не всегда нужен id. Но вот в сущностях аннотацию обязательно надо почти всегда

2024-11-29 17:08 UTC, MiraGlaceon requested changes

2024-11-29 17:08 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +        //projectValidator.validate(projectDto, this::existsByOwnerUserIdAndName, userContext.getUserId());
Это бы подтереть сразу, если не нужно больше в коде

2024-11-29 17:08 UTC, MiraGlaceon submitted a review, later dismissed

2024-11-29 17:20 UTC, lomuserg commented on src/main/java/faang/school/projectservice/service/ProjectService.java
> +        //projectValidator.validate(projectDto, this::existsByOwnerUserIdAndName, userContext.getUserId());
Забыл вернуть, там Никита свою валидацию делал. Я закомментил, чтобы не мешала тестировать.

2024-11-30 20:04 UTC, 24slavaK approved these changes

2024-11-30 21:01 UTC, merged