Prject Service -BJS2-40695 (sprint 6)
CorporationX/project_service pull request #893
Opened 2024-11-28 02:28 UTC by Amanyaz

Это задача BJS2-40695 (БЕЗ ТЕСТА) из спринта 6. Требования не такие ч…еткие, как в спринте 5. Поэтому я сделал, как понял.

2024-11-28 20:39 UTC, RuslanGabd reviewed
все ок, но есть пару замечаний. Dto надо переделывать.

2024-11-28 20:39 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        Moment moment = momentMapper.toEntity(momentDto);
я бы добавил проверку что бы убедиться что такого Момента еще нету в базе и по идеи мы не должны id в Dto передавать, id БД выдает в процессе записи сущности. Фронтенд точно не формиурет id сущности

2024-11-28 20:39 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +    }
в следующей можно попробовать подключить логи, что бы если была ошибка она еще и в логи писалась.
Как пример: 
![image](https://github.com/user-attachments/assets/21c84cb5-3f8f-4eec-b8f5-2b49064fa901)

2024-11-28 20:39 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/dto/moment/MomentDto.java
> +    private List<Project> projects;
не должно дто содержать другие сущности темболее списки. Максимум id других сущностей/ списки id 
Иначе представляешь какой трафик будет если между беком и фронтом будет передаваться обьект со списсками других обьектов

2024-11-28 20:39 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/controller/moment/MomentController.java
> +            throw new ValidationException("The project was completed");
исходя из комментария в MomentDto эти проверки здесь не должны быть, из Дто мы получаем айдишников проджектов через репозатирии проджекта вытаскиваем этот проджект и проверяем, такая проверка должна делаться в сервисе.

2024-11-29 00:07 UTC, Amanyaz commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        Moment moment = momentMapper.toEntity(momentDto);
Я удалил поле id из класса MomentDto. Но я не совсем понял, как проверить, создан ли такой момент в базе данных или нет. Насколько я знаю, если момент уже существует, база данных просто обновит его, а если момента нет, то создаст его. Если у вас есть другая идея, пожалуйста, исправьте меня и буду признателен, если вы предоставите необходимый код.

2024-11-29 00:48 UTC, Amanyaz commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        Moment moment = momentMapper.toEntity(momentDto);
Я удалил поле id из класса MomentDto.  я создал метод для проверки, существует ли момент. Если существует, он выбрасывает исключение, если не существует — создаёт его.

2024-11-29 13:27 UTC, Amanyaz commented on src/main/java/faang/school/projectservice/dto/moment/MomentDto.java
> +    private List<Project> projects;
Да, вы правы, Влад тоже говорил об этом во время своего видеоурока, но я забыл. Поэтому я изменил код так, как Влад показывал на уроке: удалил List<Resource> resource, потому что она мне вообще не нужна в классе MomentDto, и заменил List<Project> projects на List<ProjectDto> projects. Я сам создал класс ProjectDto, и в нем только два поля: long id и ProjectStatus status. ProjectStatus — это не сущность, она не имеет представления в базе данных, это просто перечисление (Enumeration).

2024-11-29 13:36 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        Moment moment = momentMapper.toEntity(momentDto);
здесь все правильно

2024-11-29 13:36 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/dto/moment/MomentDto.java
> +    private List<Project> projects;
я не вижу изменений кода

2024-11-29 14:34 UTC, Amanyaz commented on src/main/java/faang/school/projectservice/controller/moment/MomentController.java
> +            throw new ValidationException("The project was completed");
Сделано!

2024-11-29 14:50 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/controller/moment/MomentController.java
> +            throw new ValidationException("The project was completed");
> Сделано!

Где?

2024-11-29 21:19 UTC, RuslanGabd submitted a review, later dismissed

2024-11-30 22:06 UTC, jibulani requested changes
хорошо, но есть несколько мест для исправления

2024-11-30 22:06 UTC, jibulani commented on src/main/java/faang/school/projectservice/dto/moment/MomentFilterDto.java
> +    Project project;
дто не должен использовать сущности из базы

2024-11-30 22:06 UTC, jibulani commented on src/main/java/faang/school/projectservice/dto/moment/filters/MomentFilter.java
> +
проблемы с отступами

2024-11-30 22:06 UTC, jibulani commented on src/main/java/faang/school/projectservice/dto/project/ProjectDto.java
> +long id;
и тут отступы уехали

2024-11-30 22:06 UTC, jibulani commented on src/test/java/faang/school/projectservice/service/project/MomentServiceTest.java
> +
договаривались писать названия тестов в формате, при котором в названии будет бизнес-условие и успешность теста, т.е. testCreateWithExistingMoment можно переписать в виде createWithExistingMomentFailTest, а testCreate - createMomentSuccessTest
лучше так именуй, чтобы в проекте все тесты в одинаковом формате назывались

2024-11-30 22:06 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        Moment moment = momentMapper.toEntity(momentDto);
как достигается выполнение требования?

> Если добавляется новый партнёр, то должен обновиться список участников и наоборот: если добавляется участник из другого проекта, то проект автоматически добавляется в партнеры по моменту.

2024-12-03 16:25 UTC, Amanyaz commented on src/main/java/faang/school/projectservice/dto/moment/MomentFilterDto.java
> +    Project project;
Заменил на ProjectDto

2024-12-03 16:56 UTC, Amanyaz commented on src/main/java/faang/school/projectservice/dto/moment/filters/MomentFilter.java
> +
поправил

2024-12-03 16:56 UTC, Amanyaz commented on src/main/java/faang/school/projectservice/dto/project/ProjectDto.java
> +long id;
Поправил

2024-12-03 16:56 UTC, Amanyaz commented on src/test/java/faang/school/projectservice/service/project/MomentServiceTest.java
> +
изменил

2024-12-03 16:57 UTC, Amanyaz commented on src/main/java/faang/school/projectservice/service/MomentService.java
> +        Moment moment = momentMapper.toEntity(momentDto);
сделал

2024-12-03 20:03 UTC, jibulani approved these changes
принято, молодец!

2024-12-03 20:03 UTC, merged