Feature/bjs2 41121 - Google Calendar Integration
CorporationX/project_service pull request #912
Opened 2024-12-02 11:26 UTC by aplavina

2024-12-04 20:18 UTC, Shakhaev submitted a review, later dismissed

2024-12-06 15:12 UTC, MiraGlaceon requested changes

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/client/UserServiceClient.java
> +    @GetMapping("api/v1/event/{eventId}")
1) api/v1 вынеси в конфигурацию проекта. И этот путь нужно использовать во всех эндпоинтах. Вынеси в аннотацию общего маппинга FRequesMapping
2) Ресурсы указывай во множественном числе. Типа users, events и тд

Подправь сразу в UserService, пожалуйста

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/client/calendar/GoogleCalendarClient.java
> +            log.error("Exception when requesting token", e);
Не критично, но уточни именно что это гугл токен, а не какой-то иной

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/client/calendar/GoogleCalendarClient.java
> +            log.error("Exception when refreshing token", ex);
Так же в логах

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/client/calendar/GoogleCalendarClient.java
> +                            "Basic " + Base64.getEncoder().encodeToString(
Тяжело прочитать, давай вынесем получение авторизации в метод или получение HttpExecuteInterceptor

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/client/calendar/GoogleCalendarClient.java
> +                    .insert(calendar).execute();
В целом давай цепочку вызова методов писать с новой строки, так читабельнее

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/config/calendar/GoogleClientSecretsConfig.java
> +            return new GoogleClientSecrets();
В таком случае вернется заглушка? Тогда как она себя поведет? Это не обвалит приложение, если у нас доступов нет, но в таком случае во всех сервисах нужно предусмотреть, что имеем доступ в календарь, иначе штатно обработать

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/calendar/GoogleAuthController.java
> +    private final GoogleClientSecrets clientSecrets;
Порядок переменных желательно вести осмысленно. Например, сначала констаны, потом инжекция бинов, потом final переменны, далее объекты и примитивы. Как вариант, но будет лаконичнее, сразу знаешь что где, когда будет куча переменных

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/calendar/GoogleAuthController.java
> +    @GetMapping("/oauth2/google")
Общий путь давай вынесем в RequestMapping

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/calendar/GoogleAuthController.java
> +        String authUrl = clientSecrets.getDetails().getAuthUri()
Такого рода логику тоже следует вынести в сервис, если нужен редирект

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/calendar/GoogleCalendarController.java
> +    @PostMapping("/event/{projectId}")
Events

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/calendar/GoogleCalendarController.java
> +    @PostMapping("/{projectId}")
Тут нужно указать ресурс projects, иначе ссылка будет выглядеть так: /calendar/5. Подумают что 5й календарь, но на самом деле это проект.  /calendar/projects/5

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/calendar/GoogleCalendarController.java
> +    @PostMapping("/acl/{projectId}")
Не совсем понимаю что такое acl, явно из логики гугла. Может стоит вынести GoogleAuthController или тут все у тебя окей? Расскажи что делает эндпоинт

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/dto/event/EventDto.java
> +    private Long id;
Тоже NotNull на айдишники

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/service/calendar/GoogleCalendarApiService.java
> +    private static final String TIMEZONE = "UTC";
Вот тут, к примеру, все аккуратненько у тебя в списке переменных

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/service/calendar/GoogleCalendarApiService.java
> +        log.info("Refreshed token {}", token);
Так же конкретику в логгах, чей токен был обновлен

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/service/calendar/GoogleCalendarService.java
> +        if (teamMember.getRoles() == null || !teamMember.getRoles().contains(TeamRole.OWNER)) {
Этот if можно вынести в отдельный метод, типа checkTeamMemberROles и там бросать эксепшен, тут сократить до одной строки

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/service/calendar/GoogleCalendarService.java
> +            if (teamMember.getRoles() == null || (!teamMember.getRoles().contains(TeamRole.MANAGER)
Так же вынести можно

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/service/calendar/GoogleCalendarService.java
> +            if (project.getCalendarId() == null) {
Тут

2024-12-06 15:12 UTC, MiraGlaceon commented on src/main/resources/logback.xml
> +    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
Это вроде как раз обсуждали с командой, что вам удобнее будет. Одобряю настройку

2024-12-06 15:13 UTC, MiraGlaceon commented
Давай добавим обработчики ошибок для контроллера календаря и клиента, если нет еще в проекте

2024-12-10 08:52 UTC, aplavina commented on src/main/java/faang/school/projectservice/controller/calendar/GoogleCalendarController.java
> +    @PostMapping("/acl/{projectId}")
ACL - создание/получение/удаление прав доступа к мероприятию/списку мероприятий.

2024-12-10 08:54 UTC, aplavina commented on src/main/java/faang/school/projectservice/controller/calendar/GoogleCalendarController.java
> +    @PostMapping("/acl/{projectId}")
https://en.wikipedia.org/wiki/Access-control_list

2024-12-28 11:19 UTC, aplavina commented on src/main/java/faang/school/projectservice/config/calendar/GoogleClientSecretsConfig.java
> +            return new GoogleClientSecrets();
проверила, все ок, проект работает без файла с credentials, 500 ошибка только в методах связанных с календарем, так и должно быть

2024-12-28 11:22 UTC, aplavina commented on src/main/java/faang/school/projectservice/controller/calendar/GoogleCalendarController.java
> +    @PostMapping("/acl/{projectId}")
acl не специфичен для гугл календаря, как я понимаю это вообще такая штука которая нужна чтобы присылать ссылку доступа с определенными правами на ресурс, то есть календарь, в нашем случае на почту приходит вот такое письмо
<img width="623" alt="image" src="https://github.com/user-attachments/assets/adf6bb9f-bca9-4b9c-9fe5-9afdea2809bb" />

2025-01-08 15:22 UTC, MiraGlaceon approved these changes

2025-01-08 16:15 UTC, merged