Murloc7 b alex vacations bjs2 40691
CorporationX/project_service pull request #913
Opened 2024-12-03 13:55 UTC by alexFromAC143937

2024-12-03 20:20 UTC, alexFromAC143937 commented
![image](https://github.com/user-attachments/assets/7c39ab73-7f5d-4c00-8c24-b7b35f8b3970)

2024-12-03 20:24 UTC, alexFromAC143937 commented
![image](https://github.com/user-attachments/assets/4bb4ef7f-2520-4910-8d12-175229f34257)

2024-12-03 20:26 UTC, alexFromAC143937 commented
![image](https://github.com/user-attachments/assets/bb5b08c8-f112-43eb-ac8e-da596cb67ad9)

2024-12-03 20:27 UTC, alexFromAC143937 commented
![image](https://github.com/user-attachments/assets/12294e7f-b37a-4d2c-9b11-ba43b0870245)

2024-12-03 20:29 UTC, alexFromAC143937 commented
![image](https://github.com/user-attachments/assets/59a014d7-ab9f-453f-9d13-22abe3df4750)

2024-12-03 20:32 UTC, alexFromAC143937 commented
![image](https://github.com/user-attachments/assets/fffae966-a372-496a-bb05-e02a8027f485)

2024-12-05 19:20 UTC, RuslanGabd reviewed
Интересно сделано, мне пару моментов не понятно, оставил комментарии.

2024-12-05 19:20 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    private final ValidationVacancies validationVacancies;
VacationService - ОтпускСервис ?

2024-12-05 19:20 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +
Либо я что-то упускаю, либо я не понимаю зачем так сложно проверять на null. Почему нельзя в Dto над полем Добавить аннотацию @NotNull

2024-12-05 19:20 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +        validationVacancies.isVacancyExist(vacancyDto.id());
зачем нам с фронта получать целое  Dto когда нужен только id? Можно из RequestParam получать только id, а еще лучше из PathVariable:

@DeleteMapping("/{id}")
public ResponseEntity<Void> delete(@PathVariable  @Min(1)  Long id) {

2024-12-05 19:20 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    }
Зачем Dto возвращаешь? то есть удалили вакансию и возвращаем Dto на сущности которой уже нет, как по мне не логично.
Здесь лучше вернуть id удаленной сущности.

2024-12-05 19:20 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/repository/VacancyExtraRepository.java
> +
не совсем понял за чем этот класс. Почему нельзя  VacancyRepository использовать сразу в сервисе.

2024-12-05 19:20 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/service/CandidateService.java
> +                candidateRepository.deleteById(idCandidate);
а если одно из условии не выполниться то кандидат не удалиться и мы никак об этом не узнаем. ведь ошибка не выброситься

2024-12-05 19:20 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/service/CandidateService.java
> +        if (candidate == null) {
Я бы выбрасывал ошибку вместо null тогда одна проверка отпадает, а две другие в отдельный приватный метод вынести.

2024-12-05 19:20 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/service/VacationService.java
> +    }
такой return сложно читаем.

Снова вопрос почему нельзя VacancyRepository использвать сразу.
У нас на входе уже есть Dto можно и его возвращать

2024-12-17 23:26 UTC, alexFromAC143937 commented on src/main/java/faang/school/projectservice/repository/VacancyExtraRepository.java
> +
Видится, что обработка должна использоваться в реализации репазирория, так как может переиспользоваться и другими классами

2024-12-17 23:31 UTC, alexFromAC143937 commented on src/main/java/faang/school/projectservice/service/CandidateService.java
> +        if (candidate == null) {
Суть в том, что в рамках бизнес логики, удалить нужно, если значения есть, если нет, то продолжиь работу далее.

2024-12-17 23:32 UTC, alexFromAC143937 commented on src/main/java/faang/school/projectservice/service/CandidateService.java
> +                candidateRepository.deleteById(idCandidate);
В данной ситуации такая бизнес логика

2024-12-17 23:35 UTC, alexFromAC143937 commented on src/main/java/faang/school/projectservice/service/VacationService.java
> +    }
Проблема в том, что если использовать сразу, то нужно еще обрабатывать ислючения каждый раз, если не найден,  а так а) переиспользование б) кода наоборот меньше)

2024-12-18 00:46 UTC, RuslanGabd submitted a review, later dismissed

2024-12-18 21:32 UTC, jibulani requested changes
хорошее покрытие тестами, молодец!

есть комментарии от меня и Руслана, нужно поправить

2024-12-18 21:32 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    private final ValidationVacancies validationVacancies;
почему зарезолвил? не исправлено же

2024-12-18 21:32 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +
тоже не исправлено

2024-12-18 21:32 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    public VacancyDto getVacancyById(@NotNull @RequestBody VacancyDto vacancyDto) {
почему для получения вакансии по id используешь Post-запрос и передаешь VacancyDto?
достаточно передать только id в аргументы и использовать Get-запрос
и вместо VACANCY_ID нужно использовать просто ID

2024-12-18 21:32 UTC, jibulani commented on src/main/java/faang/school/projectservice/repository/VacancyExtraRepository.java
> +
другие классы по-хорошему должны работать с вакансиями через VacancyService, так что действительно избыточно выглядит

2024-12-18 21:32 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/VacationService.java
> +public class VacationService {
VacancyService

2024-12-18 21:32 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/VacationService.java
> +        validationVacancies.isProjectExist(vacancyDto.projectId());
обычно такие методы не в отдельный класс выносят, а просто в приватные методы текущего класса

2024-12-18 21:32 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +        validationVacancies.isVacancyExist(vacancyDto.id());
согласен

2024-12-18 21:32 UTC, jibulani commented on src/main/java/faang/school/projectservice/validation/ValidationVacancies.java
> +public class ValidationVacancies {
если выносить в отдельный класс, то я бы назвал его ValidationVacanciesUtil

2024-12-18 21:32 UTC, jibulani commented on src/main/java/faang/school/projectservice/validation/ValidationVacancies.java
> +    public void hasToBeNotNull(String parameterValue, String nameFieldForMessage) {
я бы переименовал checkNotNull

2024-12-18 21:32 UTC, jibulani commented on src/main/java/faang/school/projectservice/validation/ValidationVacancies.java
> +    public void isProjectExist(Long idProject) {
isProjectExist намекает, что метод должен вернуть boolean (есть или нет)
в данном случае тоже назвал бы в духе checkProjectExist

2024-12-18 21:32 UTC, jibulani commented on src/main/java/faang/school/projectservice/validation/ValidationVacancies.java
> +    public void isProjectExist(Long idProject) {
в остальных местах по аналогии

2024-12-18 21:32 UTC, jibulani commented on src/main/resources/data-project-init.sql
> +/*
зачем закомменченный код?

2024-12-18 21:32 UTC, jibulani commented on src/test/java/faang/school/projectservice/controller/VacancyControllerTest.java
> +    private MockMvc mockMvc;
круто, что написал тесты с mockMvc!

2024-12-18 21:32 UTC, jibulani commented on src/test/java/utils/VacationDataCreatorTest.java
> +public class VacationDataCreatorTest {
это же не класс с тестами, лучше назвать просто VacancyDataCreator

2024-12-19 01:24 UTC, alexFromAC143937 commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    public VacancyDto getVacancyById(@NotNull @RequestBody VacancyDto vacancyDto) {
Задание: Контроллер принимает и возвращает только объекты VacancyDto или коллекции этих объектов. Нужно создать класс VacancyDto с минимальным необходимым набором полей для обеспечения работы функционала.

2024-12-19 01:29 UTC, alexFromAC143937 commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    public VacancyDto getVacancyById(@NotNull @RequestBody VacancyDto vacancyDto) {
ID - это "/{id}"; VACANCY_ID = "/id";. А так как указано, что "принимает и возвращает только объекты VacancyDto", поэтому введена отдельная переменная

2024-12-19 01:46 UTC, alexFromAC143937 commented on src/main/java/faang/school/projectservice/service/VacationService.java
> +public class VacationService {
Done

2024-12-19 01:50 UTC, alexFromAC143937 commented on src/main/java/faang/school/projectservice/service/VacationService.java
> +        validationVacancies.isProjectExist(vacancyDto.projectId());
Думал над этим, но так как валидация может проводится как в контролере так и сервисе и исходя из нетипичности работы с ДТО, пришел к выводу, что лучше вынести валидацию в один класс, откуда брать  и использовать, где нужно

2024-12-19 01:53 UTC, alexFromAC143937 commented on src/main/java/faang/school/projectservice/validation/ValidationVacancies.java
> +public class ValidationVacancies {
Думал вынести в папку утилит, но так как может понадобится валидацию и для другиг сервисов, то создал папку faang.school.projectservice.validation, поэтому не целесообразно добавлять к названию Utils

2024-12-19 02:07 UTC, alexFromAC143937 commented on src/main/java/faang/school/projectservice/validation/ValidationVacancies.java
> +    public void hasToBeNotNull(String parameterValue, String nameFieldForMessage) {
Done

2024-12-19 09:14 UTC, alexFromAC143937 commented on src/test/java/utils/VacationDataCreatorTest.java
> +public class VacationDataCreatorTest {
Done

2024-12-19 21:48 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/VacancyController.java
> +    public VacancyDto getVacancyById(@NotNull @RequestBody VacancyDto vacancyDto) {
тут скорее неточность формулировки, обычно делают так, как я написал
ок, как сделал, так и сделал

2024-12-19 21:50 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/VacationService.java
> +        validationVacancies.isProjectExist(vacancyDto.projectId());
для проверки дто достаточно аннотациями нужные поля пометить (`@NotNull`, `@NotBlank` и тд)

2024-12-19 21:52 UTC, jibulani approved these changes
принято!

2024-12-19 21:52 UTC, merged