[BJS2-41077] - resources adding
CorporationX/project_service pull request #917
Opened 2024-12-05 21:09 UTC by Alexey-Zimin

Выкладываю пока без тестов
![addresource](https://github.com/user-attachments/assets/0566ee57-105a-4047-9a11-72779de79e2d)
![resource_added_minio](https://github.com/user-attachments/assets/bdf33981-d62c-4d24-896c-be7b362ac3d1)
![getresource](https://github.com/user-attachments/assets/0ab4d0fd-6811-4861-bd58-6b6dc2756c9d)
![updateresource](https://github.com/user-attachments/assets/4a0674de-d23a-40b5-899b-04aeadc4bce1)
![updateresource_minio](https://github.com/user-attachments/assets/796d4f72-a239-4313-a25c-1c91dd479d3d)
![deleteresource](https://github.com/user-attachments/assets/b9476f41-7c3d-4dfc-bdb3-5adf9fb069b4)
![deleteresource_minio](https://github.com/user-attachments/assets/805734d5-839a-4bfb-a880-fe79d290b9a4)

2024-12-11 17:23 UTC, RuslanGabd reviewed
оставил пару комментов

2024-12-11 17:23 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/service/ResourceService.java
> +    public InputStream downloadResource(Long resourceId) {
уверен что здесь нужен Transactional?

2024-12-11 17:23 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/controller/ResourceController.java
> +    }
возможна ли ситуация когда userContext вернет null?
я бы далее по коду добавил проверку на null например в validateUserId

2024-12-11 17:23 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/controller/ResourceController.java
> +
не совсем понимаю почему MediaType.IMAGE_PNG если в задаче речь шла про PDF, XLS, DOCX, видео и аудио файлы.

2024-12-11 17:23 UTC, RuslanGabd commented on src/main/java/faang/school/projectservice/service/ResourceService.java
> +    private final static long TWO_GB_IN_BYTES = 2_147_483_648L;
не критично но я бы вынес в yaml. все так это значение которое иногда надо менять.

2025-01-03 16:50 UTC, Alexey-Zimin commented on src/main/java/faang/school/projectservice/service/ResourceService.java
> +    public InputStream downloadResource(Long resourceId) {
Убрал

2025-01-03 16:51 UTC, Alexey-Zimin commented on src/main/java/faang/school/projectservice/controller/ResourceController.java
> +
Исправил на хранение всех описанных ресурсов

2025-01-03 16:53 UTC, Alexey-Zimin commented on src/main/java/faang/school/projectservice/controller/ResourceController.java
> +    }
при запросе пользователя будет вылетать ексепшен, если такого пользователя нет

2025-01-03 16:53 UTC, Alexey-Zimin commented on src/main/java/faang/school/projectservice/service/ResourceService.java
> +    private final static long TWO_GB_IN_BYTES = 2_147_483_648L;
оставил

2025-01-09 21:14 UTC, jibulani requested changes
есть несколько небольших комментариев

мощно поработал над тестами, молодец!

2025-01-09 21:14 UTC, jibulani commented on src/main/java/faang/school/projectservice/controller/resource/ResourceController.java
> +//    @GetMapping(path = UrlUtils.ID, produces = "application/octet-stream")
забыл удалить/раскомментировать?

2025-01-09 21:14 UTC, jibulani commented on src/main/java/faang/school/projectservice/dto/resource/ResourceDtoStored.java
> +public class ResourceDtoStored {
можно было бы отнаследоваться от ResourceDto и добавить только одно поле byte[] fileBytes;

2025-01-09 21:14 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        resource.setKey(key);
дважды повторяется блок кода с сеттерами для ресурса, я бы вынес в отдельный приватный метод

2025-01-09 21:14 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    void toS3File(MultipartFile file, String bucketName, String key) throws IOException;
чтобы меньше путаницы в методах с одинаковыми названиями было, лучше сделать тот же порядок у одинаковых аргументов: String bucketName, String key, MultipartFile file

2025-01-09 21:14 UTC, jibulani commented on src/test/java/faang/school/projectservice/service/resource/ResourceServiceTest.java
> +        bucketName = "resourceBucket";
зачем каждый раз инициализировать? недостаточно просто константами сделать?

2025-01-09 22:25 UTC, Alexey-Zimin commented on src/main/java/faang/school/projectservice/controller/resource/ResourceController.java
> +//    @GetMapping(path = UrlUtils.ID, produces = "application/octet-stream")
Исправил

2025-01-09 22:25 UTC, Alexey-Zimin commented on src/test/java/faang/school/projectservice/service/resource/ResourceServiceTest.java
> +        bucketName = "resourceBucket";
Исправил

2025-01-09 22:25 UTC, Alexey-Zimin commented on src/main/java/faang/school/projectservice/service/s3/S3Service.java
> +    void toS3File(MultipartFile file, String bucketName, String key) throws IOException;
Исправил

2025-01-09 22:31 UTC, Alexey-Zimin commented on src/main/java/faang/school/projectservice/dto/resource/ResourceDtoStored.java
> +public class ResourceDtoStored {
Я пытался реализовать наследование, но у меня возникли проблемы с мапперами.
    @Mapping(source = "createdBy.id", target = "createdById") - в этих строках перестает собираться, так как поле createdById становится недоступным. Я попытался найти решение, но сразу так не нашел. Оставил себе на потом разобраться с этой проблемой. Если это критично, то буду разбираться.

2025-01-09 22:41 UTC, Alexey-Zimin commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        resource.setKey(key);
Я выносил метод для того, чтобы убрать дублирование сетторов для ресурсов, но получается не совсем красиво. По коду повторяются вызовы только четырех сетторов. Далее, в одном месте кода дополнительно вызывается еще 2 сеттера, а в другом - один сеттер. И если сделать доп. метод для инициализации, то нужно будет передавать еще три параметра в новый метод и вызывать сеттеры для ресурса, даже если их не нужно вызывать, то есть передавать в качестве параметров значения уже имеющиеся в полях и ими же инициализировать еще раз. Это мне не понравилось + еще входных параметров 7 шт уже будет, а это много. Если делать метод только для общих сеттеров , то тоже фигня какая-то получается. Поэтому решил оставить так как сейчас в коде.

2025-01-10 20:20 UTC, jibulani approved these changes
принято!

2025-01-10 20:20 UTC, jibulani commented on src/main/java/faang/school/projectservice/service/resource/ResourceService.java
> +        resource.setUpdatedAt(now);
не обратил внимание при первом ревью - тут можно было не обновлять вручную поле updatedAt, поскольку над ним стоит аннотация `@UpdateTimestamp`, которая это автоматически сделает
некритично

2025-01-10 20:20 UTC, merged