BJS2-40673 - Стажировка (рефакторинг)
CorporationX/project_service pull request #918
Opened 2024-12-06 17:19 UTC by Shakhaev

- Мелкие исправления в InternshipController и в тестовом классе контроллера.
- Исправление логики TaskStatusValidator (рефакторинг, улучшение читаемости и чистоты кода).
- Распределение классов по соответствующим пакетам в main и в test директориях.

2024-12-07 14:58 UTC, MiraGlaceon requested changes

2024-12-07 14:58 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +@RequestMapping("/api/v1")
Давай сделаем как подсвечено было на одном из последних созвонов. Вынесем путь "/api/v1" и сделаем для всех контроллеров. Для этого вынеси путь в конфигурацию, а потом настрой бин RequestMappingHandlerMapping, чтобы путь применялся ко всем эндпоинтам.
 А в аннотации RequestMapping выноси общий путь для контроллера, например, "/internships"

2024-12-07 14:58 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
>      public ResponseEntity<InternshipDto> createInternship(@RequestBody InternshipDto internshipDto) {
Не относится к твоим доработкам, но я подсвечу момент:
Давай избавляться от ResponseEntity. Спринг сам умеет оборачивать объекты в эту оболочку в контроллерах, из метода достаточно вернуть только объект. Есть ситуации, когда пригодится ResponseEntity, но их нужно найти

2024-12-07 14:58 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +        URI location = URI.create("/api/v1/internships/" + responseDto.getId());
Вот здесь расскажи что у тебя происходит и скажи гибко будет это, что если изменится путь к ресурсу?

2024-12-07 14:58 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    @GetMapping("/filters/internships")
Вот здесь из пути надо исключать filters, подумать как его использовать в качестве параметров или тела запроса.  У тебя контроллер по стажировкам, следовательно путь до стажировок должен быть в приоритете, типа /internships/<уже все остальное>

2024-12-07 14:58 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    @GetMapping("/{internshipId}/internships")
Тоже самое, сначала ресурс, потом его айди /internships/<уже все остальное>

2024-12-07 14:58 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/validator/internship/TaskStatusValidator.java
> +        if (internship.getStatus().equals(InternshipStatus.COMPLETED)) {
Тут возможно у тебя internship.getStatus() не будет null по логике никогда, но лайфхак менять проверку equals в приоритет у констант, типа: InternshipStatus.COMPLETED.equals(internship.getStatus())
Так ты будешь убивать двух зайцев сразу: и проверка на null и на соответствие

2024-12-07 14:58 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/validator/internship/TaskStatusValidator.java
> +                    boolean hasUncompletedTasks = member.getStages().stream()
Внутренний фильтр, я бы вынес в метод, который говорил бы сам за себя что он делает. Тогда у тебя была бы лаконичная цепочка вызовов методом через точку, которую легко прочитать, а сами методы с логикой отдельно

2024-12-07 14:58 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/validator/internship/TaskStatusValidator.java
> +                .filter(member -> {
Тут так же фильтр бы вынести и читаемость тем самым облегчить

2024-12-08 12:18 UTC, Shakhaev commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +        URI location = URI.create("/api/v1/internships/" + responseDto.getId());
Здесь происходит формирование и возвращение в ответе ResponseEntity того пути, по которому созданная новая стажировка будет доступна пользователю сразу после ее создания. Что касается пути в URI location, то да, согласен. Вынес общий путь в конфиг, а /internships оставил.

2024-12-08 12:31 UTC, Shakhaev commented on src/main/java/faang/school/projectservice/controller/internship/InternshipController.java
> +    @GetMapping("/filters/internships")
Решил использовать параметры запроса с аннотацией @RequestParam, а в @GetMapping юзать путь "/filters". 
Общий путь может быть таким: GET /internships/filters?statusPattern=ACTIVE&rolePattern=DEVELOPER

2024-12-11 16:01 UTC, MiraGlaceon approved these changes

2024-12-11 16:02 UTC, merged