BJS2-41581 - Получение достижения "Менеджер"
CorporationX/project_service pull request #922
Opened 2024-12-12 10:55 UTC by Shakhaev

2024-12-15 09:59 UTC, frs717 submitted a review, later dismissed

2024-12-15 09:59 UTC, frs717 commented on src/main/java/faang/school/projectservice/validator/teammember/TeamMemberValidator.java
> +                UserDto user = userServiceClient.getUser(userId);
Здесь для оптимизации можно сделать метод getUsers(List<Integer> ids)
Чтобы не делать несколько запросов к user_service, а получить все за один запрос
Это как предложение для улучшения

2024-12-20 18:43 UTC, MiraGlaceon requested changes

2024-12-20 18:43 UTC, MiraGlaceon commented on build.gradle.kts
> +    "**/controller/**"
👍

2024-12-20 18:43 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/client/UserServiceClient.java
> +    @GetMapping("/users/{userId}")
Главное так же, чтобы на стороне user был такой эндпоинт

2024-12-20 18:43 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/dto/client/UserDto.java
> +
Тут лишняя пустая строчка или так git показывает?

2024-12-20 18:43 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/model/Team.java
> +    @OneToMany(mappedBy = "team", fetch = FetchType.EAGER)
Жадную подгрузку нужно использовать разумно. Членов команды не должно быть много, расскажи почему решил использовать жадную загрузку, а не загрузку графа сущности при необходимости ?

2024-12-20 18:43 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/service/team/TeamService.java
> +        teamEventPublisher.publish(new TeamEvent(
Этап публикации тоже можно вынести в отдельный метод и после транзакции, если не сохранилась сущность, то ты дальше и не пройдешь, а если не удалась публикация, то тебе не нужно откатывать сохранение команд в бд. Одно другому не мешает, так сказать

2024-12-20 18:43 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/validator/team/TeamValidator.java
> +            throw new IllegalArgumentException("User with given ID does not exist.");
Таких ошибок такого типа может быть много. Может стоит создать тип ошибки UserNotFoundException. Глянь, может пригодиться еще где. Поиск пользователя много где происходить должен

2024-12-20 18:43 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/validator/teammember/TeamMemberValidator.java
> +            throw new DataValidationException("User with given ID does not exist.");
А тут ты используешь DataValidationException. Два разных типа. Лучше завести один тип ошибки

2024-12-21 09:31 UTC, Shakhaev commented on src/main/java/faang/school/projectservice/dto/client/UserDto.java
> +
Да, действительно пустая строка, исправил!

2024-12-21 09:31 UTC, Shakhaev commented on src/main/java/faang/school/projectservice/client/UserServiceClient.java
> +    @GetMapping("/users/{userId}")
Да, такой эндпоинт есть

2024-12-21 09:38 UTC, Shakhaev commented on src/main/java/faang/school/projectservice/model/Team.java
> +    @OneToMany(mappedBy = "team", fetch = FetchType.EAGER)
У меня была проблема при написании логики создания команд, при которой TeamMember не подсохранялись в сущности Team, и при вызове эндопоинта getTeams не отображались члены команды, потому что они не сохранялись должным образом. Для проверки правильного сохранения членов команд в сущности команды я внес жадную загрузку, чтобы подтягивать эти сущности при получении всех команд. Я почитал про этот тип выборки, понял, что он оказывается на производительность влияет. Полагаю, что нужно оставить тип загрузки по умолчанию - ленивый.

2024-12-25 14:38 UTC, MiraGlaceon commented on src/main/java/faang/school/projectservice/model/Team.java
> +    @OneToMany(mappedBy = "team", fetch = FetchType.EAGER)
Можно использовать жадную загрузку, но осторожно. Лучше обработать сценарий иначе

2024-12-25 14:40 UTC, MiraGlaceon approved these changes

2024-12-25 14:44 UTC, merged